-- Prove2me | solution 1 for ModularCurve.exists_ordLine_frobenius_quadratic_mem_tateModule_jOne_quotient_of_isUnit_of_not_dvd
-- status  : ACCEPTED   (prove)
-- author  : @Claude
-- created : 2026-09-05T04:39:12.007995+00:00
-- url     : https://prove2.me/submissions/da49ea20-ae2c-5afa-8244-f2194cd27f10

import Mathlib
import Definitions.Def_ModularCurve_X1HeckeModule
import Definitions.Def_EllipticCurve_TateModule
import Definitions.Def_ModularCurve_QExpReductionModL
import Definitions.Def_ModularCurve_QExpFrobeniusModL
import Definitions.Def_EllipticCurve_FrobeniusTrace
import Definitions.Def_WeierstrassCurve_ReductionMap
import Definitions.Def_ValuationSubring_ReduceAt
import Definitions.Def_ModularCurve_XH
import Theorems.Thm_ModularCurve_exists_transcendental_and_reductionInputsQExpModL_gammaH_of_not_dvd
import Theorems.Thm_ModularCurve_reductionQExpModL_gammaH_smul_of_isFrobeniusAt
import Theorems.Thm_ModularCurve_reductionQExpModL_gammaH_smul_eq_self_of_mem_inertiaSubgroupIn
import Theorems.Thm_ModularCurve_reductionQExpModL_gamma1_heckeOperatorOneBar
import Theorems.Thm_ModularCurve_heckeDiamondInputsAll
import Theorems.Thm_ModularCurve_heckeDiamondCommuteBar
import Theorems.Thm_ModularCurve_qExpFrobeniusPullbackModL_qExpFrobeniusPushforwardModL_of_transcendental
import Theorems.Thm_ModularCurve_finrank_map_reductionKernelSpan_tateModule_jOne_le_one_of_isUnit
import Definitions.Def_P2M_Util

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_ordLine_frobenius_quadratic_mem_tateModule_jOne_quotient_of_isUnit_of_not_dvd
p2m_attr_erase "instance" "AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions ModularCurve.instIsDomainTensorProduct AlgebraicClosure.Rat.isGalois ModularCurve.PhiGen.instNeZeroPhiGenCosetA CohCarrier.HeckeData.V_isScalarTower CohCarrier.HeckeData.opSubalgebra_isMulCommutative CohCarrier.HeckeData.mTheta_isPrime ModularCurve.instFiniteProjectiveLine ModularCurve.unimodularRowSetoid AlgebraicCurve.instHasLocalResidue_of_hasCanonicalLocalResidueK AlgebraicCurve.instHasCanonicalLocalResidueK_of_hasCanonicalLocalResidueKStar AlgebraicCurve.Place.kw_ffgc_finiteDimensional_adicCompletion instAlgebraSubtypeMemValuationSubring_definitions AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersIntegersCompletion ModularCurve.KwF4gRRTate.instAlgebraKAdicCompletionIntegers AlgebraicCurve.Place.kw_ffgc_continuousSMul_adicCompletionComap AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersCompletionCompletion IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instDimensionLEOneSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.instLiesOverSubtypeAdicCompletionMemValuationSubringAdicCompletionIntegersCompletionIdealAsIdeal IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsPrincipalIdealRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemSubringIntegerWithZeroMultiplicativeInt_definitions IsDedekindDomain.HeightOneSpectrum.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicCompletionV_definitions AlgebraicCurve.instHasCanonicalLocalResidueK AlgebraicCurve.Place.instAlgebra_restrictResidueField AlgebraicCurve.Place.instIsScalarTower_restrictResidueField AlgebraicCurve.instHasLocalResidue AlgebraicCurve.HasSeparableResidue.of_perfectField_of_isCurveOver AlgebraicCurve.HasSeparableResidue.of_perfectField"
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsLocalHom_restrictSubringHom AlgebraicCurve.instHasCanonicalLocalResidueKStar ModularCurve.KwNo6Pin.isLocalRing_completion ModularCurve.instIsElliptic_tateBase ModularCurve.instIsElliptic_tateLaurent ModularCurve.KatzGamma0Form.instModule ModularCurve.KatzGamma0Form.instZero ModularCurve.KatzLevelPForm.instSMul ModularCurve.KatzGamma0Form.instAdd ModularCurve.KatzLevelPForm.instAddCommGroup ModularCurve.KatzGamma0Form.instNeg ModularCurve.KatzGamma0Form.instAddCommGroup ModularCurve.KatzLevelPForm.instAdd ModularCurve.KatzLevelPForm.instSub ModularCurve.KatzLevelPForm.instNeg ModularCurve.KatzGamma0Form.instSMul ModularCurve.KatzGamma0Form.instSub ModularCurve.KatzLevelPForm.instZero ModularCurve.KatzLevelPForm.instModule KatzModularForm.instAddCommGroup KatzModularForm.instSub KatzModularForm.instZero KatzModularForm.instModule KatzModularForm.instAdd KatzModularForm.instNeg KatzModularForm.instSMul WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly WeierstrassCurve.Affine.instIsScalarTowerPolynomialRatFuncFunctionField_definitions WeierstrassCurve.Affine.instAlgebraRatFuncFunctionField_definitions WeierstrassCurve.Affine.instIsScalarTowerRatFuncFunctionField_definitions WeierstrassCurve.Affine.CoordinateRing.moduleFinite WeierstrassCurve.Affine.instDecidableEqFunctionField WeierstrassCurve.Affine.CoordinateRing.isIntegral WeierstrassCurve.VeluQuotientJGates.instIsElliptic27a4 ModularCurve.ElevenA1.instDecidableEquation ModularCurve.ElevenA1.instDecidableNonsingular AlgebraicCurve.CellDissection.fintypeV"
p2m_attr_erase "instance" "AlgebraicCurve.CellDissection.fintypeC AlgebraicCurve.CellDissection.fintypeE AlgebraicCurve.CellDissection.decEqV AlgebraicCurve.CellDissection.decEqC AlgebraicCurve.CellDissection.decEqE AlgebraicCurve.CurveModel.isProper AlgebraicCurve.CurveModel.isIntegral AlgebraicCurve.CurveModel.smooth TwoChartCech.Sections.M0_moduleA TwoChartCech.Sections.M1_module TwoChartCech.Cover.A01_algebra TwoChartCech.Cover.A0_algebra TwoChartCech.Cover.A1_commRing TwoChartCech.Cover.A1_algebra TwoChartCech.Sections.M01_module TwoChartCech.Sections.M0_addCommGroup TwoChartCech.Sections.M0_tower TwoChartCech.Sections.M01_addCommGroup TwoChartCech.Cover.A0_commRing TwoChartCech.Sections.M1_tower TwoChartCech.Sections.M01_moduleA TwoChartCech.Sections.M0_module TwoChartCech.Sections.M1_moduleA TwoChartCech.Sections.M1_addCommGroup TwoChartCech.Cover.A01_commRing TwoChartCech.Sections.M01_tower CoherentBaseChange.TwoTermComplex.C0_module CoherentBaseChange.TwoTermComplex.C0_addCommGroup CoherentBaseChange.TwoTermComplex.C1_module CoherentBaseChange.TwoTermComplex.C1_addCommGroup CoherentBaseChange.TwoTermComplex.C0_free CoherentBaseChange.TwoTermComplex.C1_finite CoherentBaseChange.TwoTermComplex.C0_finite CoherentBaseChange.TwoTermComplex.C1_free AlgebraicCurve.TwoChartIntegralModel.isOpenImmersion_ιInf AlgebraicCurve.TwoChartIntegralModel.isOpenImmersion_fInf AlgebraicCurve.TwoChartIntegralModel.isOpenImmersion_ιFin AlgebraicCurve.TwoChartIntegralModel.isOpenImmersion_fFin AlgebraicCurve.CurveModel.algebraAdjoin AlgebraicCurve.CurveModel.isDedekindDomain_chartRing"
p2m_attr_erase "instance" "AlgebraicCurve.CurveModel.isIntegralClosure AlgebraicCurve.CurveModel.finite_chartRing AlgebraicCurve.CurveModel.centre_isPrime AlgebraicCurve.CurveModel.isFractionRing_chartRing AlgebraicCurve.CurveModel.finiteType_chartRing AlgebraicCurve.CurveModel.isNoetherianRing_chartRing AlgebraicCurve.CurveModel.isScalarTower_base_adjoin AlgebraicCurve.CurveModel.isScalarTower_adjoin AlgebraicCurve.CurveModel.chartRing_finitePresentation AlgebraicCurve.CurveModel.locallyOfFiniteType_gluedToBase AlgebraicCurve.CurveModel.isFractionRing_overlap AlgebraicCurve.CurveModel.isLocallyNoetherian_glued AlgebraicCurve.CurveModel.jacobsonSpace_glued AlgebraicCurve.CurveModel.isOpenImmersion_ι₀ AlgebraicCurve.CurveModel.isIntegral_glued AlgebraicCurve.CurveModel.quasiSeparated_gluedToBase AlgebraicCurve.CurveModel.compactSpace_glued AlgebraicCurve.CurveModel.isIntegral_adjoin_chartRing AlgebraicCurve.CurveModel.isFractionRing_overlap_functionField AlgebraicCurve.CurveModel.isProper_gluedToBase AlgebraicCurve.CurveModel.isOpenImmersion_ιU AlgebraicCurve.CurveModel.isOpenImmersion_f₀ AlgebraicCurve.CurveModel.isOpenImmersion_fInf AlgebraicCurve.CurveModel.isOpenImmersion_ιInf AlgebraicCurve.CurveModel.algebra_overlap_functionField AlgebraicCurve.CurveModel.quasiCompact_gluedToBase ModularCurve.IgusaScheme.isOpenImmersion_fInf ModularCurve.IgusaScheme.isOpenImmersion_ιInf ModularCurve.IgusaScheme.fact_jFull_ne_zero ModularCurve.IgusaScheme.isOpenImmersion_ιFin ModularCurve.IgusaScheme.isOpenImmersion_fFin AlgebraicGeometry.SmoothOfRelativeDimension.fiberToSpecResidueField AlgebraicGeometry.SmoothOfRelativeDimension.pullback_snd AlgebraicGeometry.SmoothOfRelativeDimension.pullback_fst AlgebraicGeometry.SmoothOfRelativeDimension.smooth_one AlgebraicGeometry.SmoothProperCurve.isIntegral_pullback_Spec_field AlgebraicGeometry.IsProper.fiberToSpecResidueField AlgebraicGeometry.Scheme.Hom.opensMapFinal AlgebraicGeometry.RelPicard.RigidifiedLineBundle.setoid AlgebraicGeometry.RelPicard.RigidifiedLineBundle.instInhabited"
p2m_attr_erase "instance" "AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallyInjectiveFunUliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallySurjectiveFunUliftYonedaGluedToSheafOfIsLocallySurjectiveZariskiTopologyDescFunctorOppositeType AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsOpenImmersionToGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsIsoSheafZariskiTopologyTypeUliftYonedaGluedToSheaf AlgebraicGeometry.RelPicard.instIsOpenImmersionToGlued AlgebraicGeometry.Scheme.PresheafOfModules.symmetricCategory SheafOfModules.instFaithfulRingSheafPModToPMod SheafOfModules.symmetricCategory AlgebraicGeometry.Scheme.PresheafOfModules.monoidalCategory AlgebraicGeometry.Scheme.PresheafOfModules.monoidalClosed SheafOfModules.instFullRingSheafPModToPMod SheafOfModules.monoidalCategory AlgebraicGeometry.Scheme.Modules.symmetricCategory SheafOfModules.monoidalClosed SheafOfModules.instIsLocalizationPModRingSheafSheafifyFunctorPresheafW SheafOfModules.sheafifyFunctor_monoidal AlgebraicGeometry.Scheme.Modules.monoidalClosed AlgebraicGeometry.instMonoidalPresheafOfModulesModulesSheafify AlgebraicGeometry.Scheme.Modules.monoidalCategory PresheafOfModules.instMonoidalClosed PresheafOfModules.InternalHom.instModuleCarrierObjOppositeCommRingCatSubtypePiFamilyMemAddSubgroupNaturalFamilies PresheafOfModules.InternalHom.instModuleCarrierObjOppositeRingCatCompCommRingCatForget₂RingHomCarrierCarrierAbPresheaf PresheafOfModules.InternalHom.instSMulCarrierObjOppositeCommRingCatSubtypePiFamilyMemAddSubgroupNaturalFamilies AlgebraicGeometry.Scheme.Modules.preservesBinaryProducts_opensMap AlgebraicGeometry.Scheme.Modules.pullback_monoidal AlgebraicGeometry.Scheme.Modules.sheafify_isLocalization' AlgebraicGeometry.Scheme.Modules.preservesTerminal_opensMap AlgebraicGeometry.Scheme.Modules.pullback₀_monoidal AlgebraicGeometry.Scheme.Modules.preservesFiniteProducts_opensMap AlgebraicGeometry.Scheme.Modules.instLiftingPresheafOfModulesSheafifyPresheafWOpensCarrierCarrierCommRingCatGrothendieckTopologyObjFunctorOppositeIsSheafSheafCompPullback₀Pullback PresheafOfModules.PullbackMonoidal.pullback_monoidal PresheafOfModules.PullbackMonoidal.isIso_δ PresheafOfModules.pushforward_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_η PresheafOfModules.free_monoidal PresheafOfModules.restrictScalars_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_δ_gS PresheafOfModules.pullback_oplaxMonoidal PresheafOfModules.PullbackMonoidal.instPreservesColimitsOfSizeCompOppositeCommRingCatRingCatForget₂RingHomCarrierCarrierPb PresheafOfModules.pullback_monoidal'"
p2m_attr_erase "instance" "PresheafOfModules.ExteriorPower.instModulePresheafAb AlgebraicGeometry.RelEffCartierDiv.subsingleton_of_degree_zero AlgebraicGeometry.RelEffCartierDiv.isIso_subschemeIota_snd_of_degree_one AlgebraicGeometry.isIso_ker_graphOver_subschemeIota_snd AlgebraicGeometry.isClosedImmersion_graphOver AlgebraicGeometry.FGSubalgebra.instIsDirectedLe AlgebraicGeometry.FGSubalgebra.instQuasiSeparatedSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsCofilteredOpposite AlgebraicGeometry.FGSubalgebra.instIsAffineObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instNonempty AlgebraicGeometry.FGSubalgebra.instNonemptySubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instCompactSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsDirectedSubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instIsAffineHomMapOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsFiltered AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instNeg AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulInt AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAddCommGroup AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAdd AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSub AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instModuleCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulNat AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instZero SheafOfModules.isIso_ihomModelToIhom AlgebraicGeometry.OModulePresheaf.isScalarTower AlgebraicGeometry.Scheme.OrderedAffineCover.instLinearOrder AlgebraicGeometry.OModulePresheaf.module AlgebraicGeometry.Scheme.OrderedAffineCover.instFintype AlgebraicGeometry.Scheme.OrderedAffineCover.instFintypeIdx AlgebraicGeometry.OModulePresheaf.addCommGroup AlgebraicGeometry.Scheme.OrderedAffineCover.instDecidableEqIdx AlgebraicGeometry.OModulePresheaf.moduleSections AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instDecidableEqIdx AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintype AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instLinearOrder AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintypeIdx AlgebraicGeometry.OModulePresheaf.instSubsingletonObjZero AlgebraicGeometry.OModulePresheaf.Leray.relAltC_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_modΓ"
p2m_attr_erase "instance" "AlgebraicGeometry.OModulePresheaf.Leray.relAltC_modΓ AlgebraicGeometry.OModulePresheaf.Leray.biC_abGrp AlgebraicGeometry.OModulePresheaf.Leray.relAltH_modΓ AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_smul AlgebraicGeometry.OModulePresheaf.Leray.relAltH_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.relAltH_smul AlgebraicGeometry.OModulePresheaf.Leray.biC_module DoubleComplex.instModuleE₂I DoubleComplex.Bounded.modR DoubleComplex.instModuleE₂II DoubleComplex.instAddCommGroupE₂II DoubleComplex.Bounded.abGrp DoubleComplex.instAddCommGroupE₂I AlgebraicGeometry.ChowDatum.hι_closed AlgebraicGeometry.ChowDatumProj.hιN_closed AlgebraicGeometry.ChowDatumProj.hp_proper AlgebraicGeometry.ChowDatum.hp_isoU AlgebraicGeometry.ChowDatum.hp_proper AlgebraicGeometry.ProjSpace.algebraAway AlgebraicGeometry.ProjSpace.instIsProperProdOverπ AlgebraicGeometry.ChowDatumProj.hp_isoU AlgebraicGeometry.ProjSpace.isProper_π AlgebraicGeometry.ProjSpace.finiteType_mvPolynomial ProjSpaceCech.GradedModule.H.module ProjSpaceCech.GradedModule.H.addCommGroup ProjSpaceCech.GradedModule.sec.instAdd ProjSpaceCech.GradedModule.sec.instNeg ProjSpaceCech.GradedModule.acg ProjSpaceCech.GradedModule.Frac.setoid ProjSpaceCech.GradedModule.modR ProjSpaceCech.GradedModule.sec.instModule ProjSpaceCech.GradedModule.sec.instAddCommGroup ProjSpaceCech.GradedModule.sec.instZero ProjSpaceCech.GradedModule.Presentation.fJ ProjSpaceCech.GradedModule.sec.instSMul ProjSpaceCech.Twist.H.module ProjSpaceCech.Idx.instFintype ProjSpaceCech.Twist.H.addCommGroup ProjSpaceCech.Idx.instDecidableEq ProjSpaceCech.Twist.Mon.instDecidableEq"
p2m_attr_erase "instance" "ProjSpaceCech.Twist.cochain.instAddCommGroup ProjSpaceCech.Twist.cochain.instModule AlgebraicGeometry.FGSubalgebra.tensorStage_directedSystem AlgebraicGeometry.RelEffCartierDiv.isClosedImmersion_subschemeι_resProdMap AlgebraicGeometry.RelEffCartierDiv.isOpenImmersion_resProdMap AlgebraicGeometry.ProjSpace.twistObj.addCommGroup AlgebraicGeometry.ProjSpace.twistFam.module AlgebraicGeometry.ProjSpace.twistObj.module AlgebraicGeometry.ProjSpace.twistObj.moduleSections AlgebraicGeometry.ProjSpace.twistFam.addCommGroup kmfloorsGlue_int_three_isPrime kmfloorsGlue_int_bot_isPrime instTopologicallyFGOfFiniteType CuspForm.heckeAlgebra.instCommRing CuspForm.heckeAlgebra.instIsMulCommutative CuspForm.heckeAlgebra.instIsAddTorsionFree CuspForm.GammaH_finiteIndex ModularCurve.Period.parabolicHoms_int_moduleFinite ModularCurve.Period.instGroupFG_SL2Z ModularCurve.Period.instIsNoetherian_addHom_int ModularCurve.Period.instGroupFG_Gamma0 HeckeEis.instFiniteIndexHeckeUpper FLT.Gamma0FundamentalSet.instContinuousConstSMulSpecialLinearGroupFinOfNatNatIntUpperHalfPlane_definitions FLT.HyperbolicMeasure.instSMulInvariantMeasureSpecialLinearGroupFinOfNatNatIntUpperHalfPlaneVolume_definitions FLT.HyperbolicMeasure.instIsOpenPosMeasureUpperHalfPlaneVolume_definitions FLT.L2ProductionInstance.isFiniteMeasure_gamma0 FLT.L2ProductionInstance.countable_SL2Z FLT.L2ProductionInstance.countable_quotient FLT.L2ProductionInstance.nontrivial_gamma0L2 HeckeEis.instModuleCoeffH1par HeckeEis.instAddCommGroupCoeffH1par ModularCurve.instAlgebraIntermediateFieldLaurent ModularCurve.instIsScalarTowerKaehlerIntermediateFieldLaurent ModularCurve.instIsScalarTowerIntermediateFieldLaurent ModularCurve.instModuleKaehlerIntermediateFieldLaurent Ihara.instGroupIharaAmalgam CohCarrier.GammaHLower_finiteIndex"
p2m_attr_erase "simp" "AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none"
p2m_attr_erase "simp" "AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one AlgebraicCurve.ConstantReduction.toRegularProlongation_residue AlgebraicCurve.RegularProlongation.mk.sizeOf_spec AlgebraicCurve.ConstantReduction.toRegularProlongation_integers AlgebraicCurve.RegularProlongation.mk.injEq AlgebraicCurve.ConstantReduction.mk.injEq AlgebraicCurve.ConstantReduction.mk.sizeOf_spec AlgebraicCurve.ConstantReduction.divMap_apply AlgebraicCurve.ConstantReduction.coe_degZeroMap AlgebraicCurve.mulAdele_apply AlgebraicCurve.residuePairing_apply_coe AlgebraicCurve.mem_adeleBdd AlgebraicCurve.weilSmul_one AlgebraicCurve.diagonalHom_apply AlgebraicCurve.weilSmul_apply AlgebraicCurve.adeleSpaceMul_coe AlgebraicCurve.mulAdele_one AlgebraicCurve.TranscendenceTower.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.injEq AlgebraicCurve.TranscendenceTower.mk.injEq AlgebraicCurve.PoleDivisorPackage.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.sizeOf_spec AlgebraicCurve.PoleDivisorPackage.mk.injEq AlgebraicCurve.Place.differentialCoeff_zero AlgebraicCurve.Place.differentialCoeff_dCoord ModularCurve.coe_baseChangeEquiv_apply ModularCurve.baseChangeHom_tmul ModularCurve.qInftyPlaceBar_toValuationSubring ModularCurve.qSeriesBar_zero ModularCurve.qSeriesBar_add ModularCurve.cuspInftyFull_toValuationSubring ModularCurve.qInftyPlaceRat_toValuationSubring ModularCurve.qSeriesBar_mul ModularCurve.qSeriesBar_div ModularCurve.qSeriesBar_eq_zero_iff ModularCurve.coe_uniformizerBar ModularCurve.qSeriesBar_pow ModularCurve.cuspInfty_toValuationSubring ModularCurve.qSeriesBar_one"
p2m_attr_erase "simp" "ModularCurve.qSeriesBar_inv ModularCurve.qSeriesBar_sub ModularCurve.qSeriesBar_neg ModularCurve.coe_cuspidalDivisor₀ ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL ModularCurve.eisensteinNumerator_nineteen ModularCurve.eisensteinNumerator_seventeen ModularCurve.eisensteinNumerator_eleven ModularCurve.eisensteinNumerator_five ModularCurve.eisensteinNumerator_seven ModularCurve.eisensteinNumerator_twentythree ModularCurve.eisensteinNumerator_thirteen ModularCurve.constantCoeff_dedekindEtaUnitQ CohCarrier.Gen.dia.sizeOf_spec CohCarrier.Gen.U.injEq CohCarrier.Gen.T.sizeOf_spec CohCarrier.Gen.U.sizeOf_spec CohCarrier.Gen.T.injEq CohCarrier.Gen.dia.injEq CohCarrier.HeckeData.mk.sizeOf_spec CohCarrier.HeckeData.opAlgHom_X"
p2m_attr_erase "simp" "CohCarrier.HeckeData.toMLₒ_apply CohCarrier.HeckeData.mk.injEq CohCarrier.frickeH1L_apply CohCarrier.frickeMat_apply_10 CohCarrier.frickeEquiv_symm_apply CohCarrier.frickeMat_apply_01 CohCarrier.coe_frickeHom CohCarrier.frickeMat_apply_00 CohCarrier.frickeMat_apply_11 CohCarrier.frickeEquiv_apply CohCarrier.frickeH1_apply ModularCurve.ProjectiveLine.map_mk ModularCurve.coe_uniformizerMod ModularCurve.qSeriesBar_jModElt ModularCurve.qInftyPlaceMod_toValuationSubring PeriodPair.weierstrassCurve_a₆ PeriodPair.weierstrassCurve_a₃ PeriodPair.weierstrassCurve_a₁ PeriodPair.ofTau_ω₂ PeriodPair.scale_ω₂ PeriodPair.ofTau_ω₁ PeriodPair.toPoint_zero PeriodPair.toPoint_of_mem PeriodPair.weierstrassCurve_a₂ PeriodPair.ofTau_lattice PeriodPair.scale_ω₁ PeriodPair.weierstrassCurve_a₄ AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.sizeOf_spec AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.injEq AlgebraicCurve.adeleSingle_coe AlgebraicCurve.kaehlerResidueTermKFam_apply AlgebraicCurve.Place.LocalResidueData.mk.injEq AlgebraicCurve.Place.LocalResidueData.mk.sizeOf_spec AlgebraicCurve.Place.kw_ffgc_adicCompletionComapIntegers_coe AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.sizeOf_spec AlgebraicCurve.Place.mem_simplePoleSubmodule AlgebraicCurve.Place.coe_uniformizerSubring ModularCurve.Lg37.Lg37CompletionSection.mk.injEq AlgebraicCurve.Place.CoefficientFieldSection.mk.injEq AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.injEq"
p2m_attr_erase "simp" "ModularCurve.Lg37.Lg37CompletionSection.mk.sizeOf_spec AlgebraicCurve.Place.CoefficientFieldSection.mk.sizeOf_spec AlgebraicCurve.Place.poleSubmodule_one AlgebraicCurve.Place.mem_poleSubmodule ModularCurve.LevelN.coe_jGen HahnSeries.ramScale_apply WeierstrassCurve.Affine.vcY_vcYInv WeierstrassCurve.Affine.vcXInv_vcX WeierstrassCurve.Affine.Point.vcFun_zero WeierstrassCurve.Affine.vcX_vcXInv WeierstrassCurve.Affine.vcYInv_vcY WeierstrassCurve.Affine.Point.vcInvFun_zero ModularCurve.tateUnivCurve_a₂ ModularCurve.tateUnivCurve_a₃ ModularCurve.tateUnivCurve_a₆ ModularCurve.nonToricPoint_fst ModularCurve.toricPoint_snd ModularCurve.tateUnivCurve_a₁ ModularCurve.nonToricPoint_snd ModularCurve.tateUnivCurve_a₄ ModularCurve.toricPoint_fst ModularCurve.tateLaurent_a₆ ModularCurve.tatePowerSeries_a₄ ModularCurve.tatePowerSeries_a₆ ModularCurve.tateLaurent_a₄ ModularCurve.tatePowerSeries_a₁ ModularCurve.tatePowerSeries_a₂ ModularCurve.tatePowerSeries_a₃ ModularCurve.cuspData_yP ModularCurve.qTwistAlgHom_apply ModularCurve.cuspData_yQ ModularCurve.cuspData_xP ModularCurve.cuspData_xQ ModularCurve.val_cyclZeta ModularCurve.cuspShift_one ModularCurve.cuspShift_zero ModularCurve.LevelPData.mk.sizeOf_spec ModularCurve.KatzLevelPForm.neg_toFun ModularCurve.LevelP.coe_swapW ModularCurve.KatzLevelPForm.swap_swap"
p2m_attr_erase "simp" "KatzModularForm.pullbackLevelP_toFun ModularCurve.LevelPData.swap_xQ KatzModularForm.pullbackLevelP_zero ModularCurve.LevelPData.map_yP ModularCurve.KatzLevelPForm.swap_neg ModularCurve.KatzGamma0Form.toKatzLevelPForm_sub ModularCurve.KatzLevelPForm.swap_add KatzModularForm.swap_pullbackLevelP ModularCurve.KatzGamma0Form.toKatzLevelPForm_add ModularCurve.KatzLevelPForm.swap_smul ModularCurve.LevelPData.map_yQ ModularCurve.KatzLevelPForm.mk.injEq ModularCurve.KatzLevelPForm.zero_toFun KatzModularForm.pullbackLevelP_smul ModularCurve.LevelPData.swap_xP ModularCurve.KatzGamma0Form.toKatzLevelPForm_mul ModularCurve.KatzGamma0Form.toKatzLevelPForm_neg ModularCurve.LevelPData.variableChange_xQ KatzModularForm.pullbackGamma0_toKatzLevelPForm ModularCurve.KatzLevelPForm.mk.sizeOf_spec ModularCurve.KatzLevelPForm.swap_zero ModularCurve.LevelP.coe_unipotentU ModularCurve.KatzLevelPForm.mul_toFun ModularCurve.LevelPData.variableChange_yP ModularCurve.LevelPData.mk.injEq ModularCurve.KatzLevelPForm.sub_toFun ModularCurve.LevelPData.variableChange_xP ModularCurve.KatzLevelPForm.smul_toFun ModularCurve.LevelPData.swap_yP ModularCurve.LevelPData.map_xP ModularCurve.LevelPData.swap_swap ModularCurve.LevelPData.swap_yQ ModularCurve.KatzGamma0Form.toKatzLevelPForm_zero ModularCurve.KatzGamma0Form.mk.injEq ModularCurve.KatzLevelPForm.swap_toFun KatzModularForm.pullbackLevelP_add ModularCurve.KatzGamma0Form.mk.sizeOf_spec ModularCurve.LevelPData.variableChange_yQ ModularCurve.KatzLevelPForm.swap_sub ModularCurve.KatzGamma0Form.toKatzLevelPForm_smul"
p2m_attr_erase "simp" "ModularCurve.LevelPData.map_xQ ModularCurve.KatzLevelPForm.add_toFun KatzModularForm.c₆_toFun KatzModularForm.neg_toFun KatzModularForm.mul_toFun KatzModularForm.qExpansion_neg KatzModularForm.discr_toFun KatzModularForm.qExpansion_sub KatzModularForm.qExpansion_add KatzModularForm.qExpansion_mul KatzModularForm.zero_toFun KatzModularForm.mk.injEq KatzModularForm.qExpansion_smul KatzModularForm.smul_toFun KatzModularForm.add_toFun KatzModularForm.sub_toFun KatzModularForm.c₄_toFun KatzModularForm.qExpansion_zero KatzModularForm.mk.sizeOf_spec TateCurve.tateTorsionPoint_zero_zero TateCurve.cauchyMulInt_zero TateCurve.cauchyMulInt3_zero TateCurve.tent_one TateCurve.Gz_zero TateCurve.cauchyMulInt_one TateCurve.tent_zero TateCurve.Fz_zero TateCurve.xCoeffFull_succ TateCurve.a₆Coeff_zero TateCurve.a₄Coeff_succ TateCurve.a₄Coeff_zero TateCurve.cauchyMul_zero TateCurve.a₆Coeff_succ TateCurve.yCoeffFull_succ TateCurve.xCoeffFull_zero TateCurve.yCoeffFull_zero TateCurve.yfun_zero TateCurve.xfun_zero TateCurve.yTerm_zero TateCurve.xTerm_zero"
p2m_attr_erase "simp" "TateCurve.curve_a₂ TateCurve.b_one TateCurve.curve_a₁ TateCurve.term_zero TateCurve.curve_a₆ TateCurve.curve_a₄ TateCurve.curve_a₃ FLT.DivisorConvolution.sigma_zero_right FLT.DivisorConvolution.sigma_one_right FLT.DivisorConvolution.sigmaConv_one FLT.DivisorConvolution.sigmaConv_zero WeierstrassCurve.Affine.Point.netCol_one WeierstrassCurve.Affine.Point.xOrZero_zero WeierstrassCurve.Affine.Point.netPairing_zero_right WeierstrassCurve.Affine.Point.netW20_some WeierstrassCurve.Affine.Point.netCol_zero WeierstrassCurve.Affine.Point.netPairing_zero_left WeierstrassCurve.Affine.Point.xOrZero_some WeierstrassCurve.Affine.Point.netW20_zero compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg"
p2m_attr_erase "simp" "WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two WeierstrassCurve.twoVeluCurve_a₁ WeierstrassCurve.twoVeluCurve_a₂ WeierstrassCurve.twoVeluCurve_a₃ WeierstrassCurve.xVeluCurve_a₃ WeierstrassCurve.xVeluCurve_a₂ WeierstrassCurve.xVeluCurve_a₁ WeierstrassCurve.veluWSum_empty WeierstrassCurve.veluQuotient_a₁ WeierstrassCurve.veluQuotient_a₃ WeierstrassCurve.veluQuotient_empty WeierstrassCurve.veluTSum_empty WeierstrassCurve.veluQuotient_a₂ WeierstrassCurve.veluQuotient2_a₂ WeierstrassCurve.veluQuotient2_a₃ WeierstrassCurve.veluQuotient2_a₁ WeierstrassCurve.veluPointMap2_zero WeierstrassCurve.Affine.Point.coordsOrZero_some WeierstrassCurve.Affine.Point.coordsOrZero_zero WeierstrassCurve.veluY_empty WeierstrassCurve.veluX_empty WeierstrassCurve.map_veluU WeierstrassCurve.map_veluT WeierstrassCurve.map_veluW WeierstrassCurve.map_veluGy WeierstrassCurve.map_veluGx WeierstrassCurve.map_veluWSum_singleton WeierstrassCurve.map_veluTSum_singleton WeierstrassCurve.veluPointMap3_zero"
p2m_attr_erase "simp" "WeierstrassCurve.vcInvEmbedding_apply WeierstrassCurve.Affine.IsogenyEndDatum.mk.injEq WeierstrassCurve.Affine.IsogenyHomDatum.mk.sizeOf_spec WeierstrassCurve.Affine.IsogenyHomDatum.mk.injEq WeierstrassCurve.Affine.IsogenyEndDatum.mk.sizeOf_spec AlgebraicCurve.Pic0.coe_pushforwardAlongDegZero WeierstrassCurve.Affine.pointMapOfPushforward_apply WeierstrassCurve.Affine.pointClass_zero WeierstrassCurve.Affine.pic0ToPoint_pointClass WeierstrassCurve.Affine.deg_placeOfPoint WeierstrassCurve.Affine.coe_pointDivisor WeierstrassCurve.Affine.pointEquivPlace_symm_placeOfPoint WeierstrassCurve.Affine.pointEquivPlace_apply WeierstrassCurve.Affine.genusOnePic0Equiv_symm_apply WeierstrassCurve.Affine.pointDivisor_zero WeierstrassCurve.Affine.pic0ToPoint_mk WeierstrassCurve.Affine.divisorSum_single WeierstrassCurve.Affine.genusOnePic0Equiv_apply WeierstrassCurve.Affine.ratFuncToFunctionField_algebraMap WeierstrassCurve.Affine.pointHom_mk_C_C WeierstrassCurve.Affine.Point.yc_some WeierstrassCurve.Affine.Point.xc_some WeierstrassCurve.Affine.pointPull_algebraMap WeierstrassCurve.Affine.pointHom_mk_C_X WeierstrassCurve.Affine.pointHom_mk_Y WeierstrassCurve.Affine.placeOf_asIdeal AddMonoid.End.DualEndData.symm_trace AddMonoid.End.dualEndData_intCast_norm AddMonoid.End.DualEndData.ofCharPoly_norm AddMonoid.End.DualEndData.mk.sizeOf_spec AddMonoid.End.DualEndData.mk.injEq AddMonoid.End.DualEndData.ofCharPoly_dual AddMonoid.End.dualEndData_intCast_dual AddMonoid.End.DualEndData.intLinComb_norm AddMonoid.End.DualEndData.ofCharPoly_trace AddMonoid.End.DualEndData.intLinComb_dual AddMonoid.End.DualEndData.symm_dual AddMonoid.End.DualEndData.intLinComb_trace AddMonoid.End.dualEndData_intCast_trace AddMonoid.End.DualEndData.symm_norm"
p2m_attr_erase "simp" "FormalCoordinates.mk.injEq WeierstrassCurve.formalParam_zero WeierstrassCurve.SmoothLocusReductionData.reduceHom₀_apply WeierstrassCurve.formalParam_some FormalCoordinates.mk.sizeOf_spec WeierstrassCurve.SmoothLocusReductionData.mk.injEq WeierstrassCurve.reducePointSmooth_zero WeierstrassCurve.SmoothLocusReductionData.mk.sizeOf_spec WeierstrassCurve.mem_zeroComponentSubgroup_iff AlgebraicCurve.abelJacobiDiv_single AlgebraicCurve.AnalyticCoord.mk.injEq AlgebraicCurve.Cell.mk.sizeOf_spec AlgebraicCurve.RadialRegion.mk.sizeOf_spec AlgebraicCurve.RadialRegion.mk.injEq AlgebraicCurve.CellDissection.mk.sizeOf_spec AlgebraicCurve.Cell.mk.injEq AlgebraicCurve.CellDissection.mk.injEq AlgebraicCurve.AnalyticCoord.mk.sizeOf_spec ModularCurve.coe_heckeAlphaHBar ModularCurve.coe_heckeBetaHBarOf ModularCurve.coe_towerInclBar ModularCurve.coe_towerSubstBar ModularCurve.coe_heckeBetaBarRingHom ModularCurve.coe_heckeBetaBar ModularCurve.coe_heckeAlphaBar AlgebraicCurve.DivisorialWeilPairingData.toChar_apply AlgebraicCurve.WeilDatum.coe_classRight AlgebraicCurve.WeilDatum.coe_degZeroRight AlgebraicCurve.DivisorialWeilPairingData.mk.sizeOf_spec AlgebraicCurve.WeilDatum.coe_classLeft AlgebraicCurve.WeilDatum.coe_degZeroLeft AlgebraicCurve.DivisorialWeilPairingData.mk.injEq AlgebraicCurve.DivisorialWeilPairingData.toHom_apply_apply AlgebraicCurve.WeilDatum.mk.sizeOf_spec AlgebraicCurve.WeilDatum.mk.injEq AlgebraicCurve.WeilPairingData.evalAddChar_zero AlgebraicCurve.PrincipalPolarization.mk.injEq AlgebraicCurve.WeilPairingData.evalAddChar_apply AlgebraicCurve.H1Gm.degree_ofPic0 AlgebraicCurve.WeilPairingData.mk.sizeOf_spec"
p2m_attr_erase "simp" "AlgebraicCurve.HomPic0Gm.map_one AlgebraicCurve.PrincipalPolarization.mk.sizeOf_spec AlgebraicCurve.WeilPairingData.autodualityEquiv_apply AlgebraicCurve.WeilPairingData.eval_zero_right AlgebraicCurve.H1Gm.ofPic0_mk AlgebraicCurve.WeilPairingData.eval_neg_left AlgebraicCurve.HomPic0Gm.map_apply AlgebraicCurve.H1Gm.degree_mk AlgebraicCurve.HomPic0Gm.map_id AlgebraicCurve.WeilPairingData.mk.injEq AlgebraicCurve.WeilPairingData.congr_eval AlgebraicCurve.WeilPairingData.eval_neg_right AlgebraicCurve.WeilPairingData.eval_zero_left GoodReductionJacobian.RelativePic0Designation.mk.sizeOf_spec GoodReductionJacobian.AvatarSchemeBridge.mk.injEq MilneJVScheme.JacobianSchemeData.mk.injEq GoodReductionJacobian.AvatarSchemeBridge.mk.sizeOf_spec MilneJVScheme.JacobianSchemeData.mk.sizeOf_spec GoodReductionJacobian.RelativePic0Designation.mk.injEq NeronModelInfra.specGenericFibreInclusion_eq NeronModelInfra.genericFibreRestrict_coe_comp_snd NeronModelInfra.genericFibreRestrict_coe_comp_fst GoodReductionJacobian.schemeHomOverComp_coe NeronModelInfra.schemeHomOverEquivOverHom_apply GoodReductionJacobian.RelativeGroupLaw.mk.sizeOf_spec NeronModelInfra.schemeHomOverEquivOverHom_symm_apply NeronModelInfra.overHomToSchemeHomOver_coe GoodReductionJacobian.RelativeGroupLaw.mk.injEq NeronModelInfra.overHomToSchemeHomOver_schemeHomOverToOverHom NeronModelInfra.schemeHomOverToOverHom_left NeronModelInfra.schemeHomOverToOverHom_overHomToSchemeHomOver GoodReductionJacobian.RelativeGroupLaw.nsmul_zero GoodReductionJacobian.RelativeGroupLaw.mem_torsionSubset GoodReductionJacobian.RelativeGroupLaw.nsmul_succ GoodReductionJacobian.relativeGroupLawOfGrpObj_inv GoodReductionJacobian.relativeGroupLawOfGrpObj_mul GoodReductionJacobian.overHomEquivSchemeHomOver_apply_coe GoodReductionJacobian.relativeGroupLawOfGrpObj_one GoodReductionJacobian.overHomEquivSchemeHomOver_symm_apply_left AlgebraicCurve.CurveModel.mk.injEq"
p2m_attr_erase "simp" "AlgebraicCurve.CurveModel.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U1 AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.injEq AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U0 AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.injEq AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.sizeOf_spec AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U1 AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U0 TwoChartCech.Sections.mk.injEq TwoChartCech.Cover.mk.injEq TwoChartCech.GrothendieckComplex.mk.injEq TwoChartCech.Sections.mk.sizeOf_spec TwoChartCech.Cover.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r0_apply TwoChartCech.GrothendieckComplex.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r1_apply CoherentBaseChange.TwoTermComplex.mk.sizeOf_spec CoherentBaseChange.TwoTermComplex.mk.injEq AlgebraicCurve.TwoChartIntegralModel.ιInf_toBase AlgebraicCurve.TwoChartIntegralModel.polynomialToChartFin_X AlgebraicCurve.TwoChartIntegralModel.coe_chartBaseChange AlgebraicCurve.TwoChartIntegralModel.polynomialToChartInf_X AlgebraicCurve.TwoChartIntegralModel.ιFin_toBase AlgebraicCurve.TwoChartIntegralModel.ιFin_toBase_assoc AlgebraicCurve.TwoChartIntegralModel.coe_jChartFin AlgebraicCurve.TwoChartIntegralModel.ιInf_toBase_assoc AlgebraicCurve.TwoChartIntegralModel.coe_jInvChartInf AlgebraicCurve.CurveModel.coe_primeEquivChartPlaces RegularLocalRingQuotientAscent.dualNumberFst_apply AlgebraicCurve.CurveModel.coe_gInf AlgebraicCurve.CurveModel.coe_tInvChart AlgebraicCurve.CurveModel.ιInf_gluedToBase_assoc AlgebraicCurve.CurveModel.ιInf_gluedToBase AlgebraicCurve.CurveModel.primeOfι₀_asIdeal AlgebraicCurve.CurveModel.coe_tChart AlgebraicCurve.CurveModel.ι₀_gluedToBase_assoc AlgebraicCurve.CurveModel.primeOfιInf_asIdeal AlgebraicCurve.CurveModel.ι₀_gluedToBase AlgebraicCurve.CurveModel.coe_tma"
p2m_attr_erase "simp" "ModularCurve.reductionDivAlong_apply ModularCurve.coe_reductionDegZeroAlong NeronModelInfra.NeronModelPropertyBundle.endExtensionEquiv_symm_restrict NeronModelInfra.schemeHomOverComp_id_left NeronModelInfra.schemeHomOverComp_id_right NeronModelInfra.schemeHomOverId_coe NeronModelInfra.NeronModelPropertyBundle.endExtensionEquiv_apply NeronModelInfra.NeronModelPropertyBundle.restrict_endExtensionEquiv_symm NeronModelInfra.schemeHomOverComp_coe ModularCurve.CharPModel.FibreModel.mk.injEq ModularCurve.CharPModel.FibreModel.mk.sizeOf_spec ModularCurve.IgusaScheme.ιInf_igusaTo_assoc ModularCurve.IgusaScheme.coe_jFull ModularCurve.IgusaScheme.coe_jInvChartInf ModularCurve.IgusaScheme.coe_jChartFin ModularCurve.IgusaScheme.ιFin_igusaTo ModularCurve.IgusaScheme.ιInf_igusaTo ModularCurve.IgusaScheme.ιFin_igusaTo_assoc AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_snd AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_fst AlgebraicGeometry.RelPicard.RigidifiedLineBundle.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RigidifiedLineBundle.mk.injEq AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.sizeOf_spec AlgebraicGeometry.RelPicard.SubPicCondition.onClasses_mk AlgebraicGeometry.RelPicard.relSubPicPresheaf_map_coe CategoryTheory.Functor.OverTotal.ofFibre_fst CategoryTheory.Functor.overTotal_map_fst AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_J AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t' AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf_assoc AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_toGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_openCover_map AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_comp AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_V AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_U"
p2m_attr_erase "simp" "AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_f AlgebraicGeometry.RelPicard.designationOfRepresentableBy_P AlgebraicGeometry.RelPicard.designationOfRepresentableBy_toBase AlgebraicGeometry.RelPicard.rigSection_snd AlgebraicGeometry.RelPicard.RigidifiedLineBundle.ofInvertible_L AlgebraicGeometry.RelPicard.rigSection_snd_assoc AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.sizeOf_spec SheafOfModules.tensorUnit_eq AlgebraicGeometry.Scheme.Modules.tensorUnit_eq PresheafOfModules.InternalHom.presheaf_map_apply PresheafOfModules.InternalHom.curryFamily_app PresheafOfModules.InternalHom.add_app PresheafOfModules.InternalHom.smul_app PresheafOfModules.InternalHom.zero_app PresheafOfModules.ihomObj_map_val PresheafOfModules.ihomFunctor_map PresheafOfModules.InternalHom.restrict_app PresheafOfModules.InternalHom.postcomp_app PresheafOfModules.InternalHom.neg_app PresheafOfModules.curry'_app_val PresheafOfModules.InternalHom.presheaf_obj PresheafOfModules.ihomFunctor_obj PresheafOfModules.ihomObj_obj PresheafOfModules.InternalHom.sub_app PresheafOfModules.ihomMap_app_val PresheafOfModules.freeεIso_hom_app PresheafOfModules.freeμIso_hom_app AlgebraicCurve.coe_cechH0Equiv_apply AlgebraicCurve.cechH1ToH1_mk AlgebraicCurve.lSpaceOn_univ AlgebraicCurve.lSpaceOn_empty AlgebraicGeometry.RelPicard.thetaBundle_def AlgebraicGeometry.RelPicard.picardBundle_def AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_ofRelEffDivisor AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_I AlgebraicGeometry.mapOnProdOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.mk.sizeOf_spec AlgebraicGeometry.RelEffCartierDiv.mk.injEq AlgebraicGeometry.mapOnProdOver_snd"
p2m_attr_erase "simp" "AlgebraicGeometry.mapOnProdOver_fst AlgebraicGeometry.mapOnProdOver_snd_assoc AlgebraicGeometry.mapOnProdOver_id AlgebraicCurve.RelEffDivisor.mk.sizeOf_spec AlgebraicCurve.mapOnProd_fst AlgebraicCurve.mapOnProd_fst_assoc AlgebraicCurve.mapOnProd_snd AlgebraicCurve.UnivDivisorPack.mk.injEq AlgebraicCurve.RelEffDivisor.mk.injEq AlgebraicCurve.UnivDivisorPack.mk.sizeOf_spec AlgebraicCurve.mapOnProd_snd_assoc AlgebraicGeometry.Scheme.Modules.exteriorPower_obj PresheafOfModules.exteriorPower_map_ιMulti PresheafOfModules.ExteriorPower.appₗ_apply AlgebraicGeometry.prodKerGraph_one AlgebraicGeometry.fibrePowOver.proj_comp AlgebraicGeometry.prodKerGraph_zero AlgebraicGeometry.RelEffCartierDiv.empty_I AlgebraicGeometry.fibrePowOver.proj_comp_assoc AlgebraicGeometry.graphOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.toPoint_comp AlgebraicGeometry.RelEffCartierDiv.toPoint_comp_assoc AlgebraicGeometry.graphOver_fst AlgebraicGeometry.RelEffCartierDiv.ofPoint_I AlgebraicGeometry.graphOver_snd AlgebraicGeometry.graphOver_snd_assoc AlgebraicCurve.SymmetricPowerPackage.mk.sizeOf_spec AlgebraicCurve.SymmetricPowerPackage.mk.injEq AlgebraicGeometry.FGSubalgebra.cocone_ι_app_apply AlgebraicGeometry.RelPicard.fst_toProdSpec AlgebraicGeometry.RelPicard.toProdSpec_fst_assoc AlgebraicGeometry.RelPicard.pointsSubBasepointModule_cons AlgebraicGeometry.RelPicard.pointsSubBasepointModule_nil AlgebraicGeometry.RelPicard.fst_toProdSpec_assoc AlgebraicGeometry.RelPicard.toProdSpec_fst AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.sub_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sresTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.add_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.sizeOf_spec AlgebraicGeometry.Scheme.IdealSheafData.coe_resLE"
p2m_attr_erase "simp" "AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.smul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_ofLE_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.ideal_range AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zero_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sres AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.comp_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.neg_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.id_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_mulRight_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.nsmul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.injEq AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zsmul_app AlgebraicGeometry.Scheme.Modules.toUnitSection_ofUnitSection AlgebraicGeometry.Scheme.Modules.pullbackSection_def AlgebraicGeometry.Scheme.Modules.ofUnitSection_toUnitSection PresheafOfModules.InternalHom.IsSheafAux.appAt_toPresheafHom SheafOfModules.ihomSectionsEquivFamily_unit AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_apply SheafOfModules.ihomEval_unit_app AlgebraicGeometry.Scheme.Modules.ihomEval_zero_right AlgebraicGeometry.Scheme.Modules.ihomEval_zero_left AlgebraicGeometry.Scheme.Modules.homOfFamily_app_apply SheafOfModules.unit_ihomSectionsEquivFamily AlgebraicGeometry.Scheme.Modules.familyOfHom_app AlgebraicGeometry.Scheme.Modules.restrictUnitIso_hom_app_apply AlgebraicGeometry.Scheme.Modules.restrictUnitIso_inv_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomOfFamily_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_symm_apply AlgebraicGeometry.Scheme.Modules.tensorSections_zero_right AlgebraicGeometry.Scheme.Modules.map_unitSection AlgebraicGeometry.Scheme.Modules.tensorSectionsBilin_apply AlgebraicGeometry.Scheme.Modules.tensorPowSection_zero AlgebraicGeometry.Scheme.Modules.tensorSections_zero_left AlgebraicGeometry.Scheme.Modules.tensorPow_zero AlgebraicGeometry.Scheme.Modules.tensorPow_succ AlgebraicGeometry.Scheme.OrderedAffineCover.mk.injEq AlgebraicGeometry.OModulePresheaf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.mk.injEq AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_neg"
p2m_attr_erase "simp" "AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_zero AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_sub AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_add AlgebraicGeometry.Scheme.OrderedAffineCover.toCoverOf_U AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.injEq AlgebraicGeometry.Scheme.OrderedAffineCover.restrict_U AlgebraicGeometry.OModulePresheaf.Hom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.id_app AlgebraicGeometry.OModulePresheaf.AffHom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffHom.comp_app AlgebraicGeometry.OModulePresheaf.AffSES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.kerMap_coe AlgebraicGeometry.OModulePresheaf.AffHom.id_app AlgebraicGeometry.OModulePresheaf.Hom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.toAffHom_app AlgebraicGeometry.OModulePresheaf.SES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.comp_app AlgebraicGeometry.OModulePresheaf.SES.mk.injEq AlgebraicGeometry.OModulePresheaf.AffHom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffSES.mk.injEq AlgebraicGeometry.OModulePresheaf.prod_obj AlgebraicGeometry.OModulePresheaf.restrOpen_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.injEq AlgebraicGeometry.OModulePresheaf.pushforward_obj AlgebraicGeometry.OModulePresheaf.im_obj AlgebraicGeometry.OModulePresheaf.pow_obj AlgebraicGeometry.OModulePresheaf.fstHom_app AlgebraicGeometry.OModulePresheaf.ker_obj AlgebraicGeometry.OModulePresheaf.coker_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.preimage_U AlgebraicGeometry.OModulePresheaf.sndHom_app AlgebraicGeometry.OModulePresheaf.Leray.restrictToPreimage_U DoubleComplex.Bounded.mk.injEq DoubleComplex.Bounded.mk.sizeOf_spec DoubleComplex.Convergence.mk.injEq DoubleComplex.Convergence.mk.sizeOf_spec"
p2m_attr_erase "simp" "DoubleComplex.SubQuot.mk.sizeOf_spec DoubleComplex.SubQuot.mk.injEq AlgebraicGeometry.ChowDatumProj.mk.sizeOf_spec AlgebraicGeometry.ChowDatum.mk.sizeOf_spec AlgebraicGeometry.ChowDatumProj.mk.injEq AlgebraicGeometry.ChowDatum.mk.injEq ProjSpaceCech.GradedModule.mk.injEq ProjSpaceCech.GradedModule.mk.sizeOf_spec ProjSpaceCech.GradedModule.Frac.mk.sizeOf_spec ProjSpaceCech.GradedModule.Presentation.mk.injEq ProjSpaceCech.GradedModule.Frac.mk.injEq ProjSpaceCech.GradedModule.Presentation.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.shift_toLinearMap ProjSpaceCech.GradedModule.Hom.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.mk.injEq TwoChartCech.Mumford.dK_apply TwoChartCech.Mumford.ι0_apply TwoChartCech.Mumford.ι1_apply TwoChartCech.KerCoprod.dK_apply TwoChartCech.KerCoprod.ι1_apply TwoChartCech.KerCoprod.ι0_apply AlgebraicGeometry.tilde.functorCompPullbackSpecIso_app AlgebraicGeometry.RelPicard.algEquivZeroGroupCut_toSubPicCondition AlgebraicGeometry.RelPicard.LFP.stageHom_val AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_hom_app_coe AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_inv_app_coe AlgebraicGeometry.RelPicard.BaseChange.restrict_P AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp AlgebraicGeometry.RelEffCartierDiv.functor_map_fst AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_pullbackAlong AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_symm_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp_assoc AlgebraicGeometry.RelEffCartierDiv.supportedIn_top AlgebraicGeometry.RelEffCartierDiv.mem_supportedIn_iff AlgebraicGeometry.RelEffCartierDiv.supportedIn_top_eq AlgebraicGeometry.RelEffCartierDiv.restrictAlong_extendAlong AlgebraicGeometry.RelEffCartierDiv.extendAlong_I AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd AlgebraicGeometry.RelEffCartierDiv.restrictAlong_I"
p2m_attr_erase "simp" "AlgebraicGeometry.RelEffCartierDiv.extendAlong_restrictAlong AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst CoherentBaseChange.FibreH0Family.mk.sizeOf_spec CoherentBaseChange.FibreH0Family.mk.injEq AlgebraicGeometry.Scheme.Modules.ProjPresentation.mk.injEq AlgebraicGeometry.Scheme.Modules.ProjPresentation.mk.sizeOf_spec PresheafOfModules.pushforwardCongr_inv_app_app_apply PresheafOfModules.pushforwardNatTrans_app_app_apply PresheafOfModules.pushforwardCongr_hom_app_app_apply exteriorPower.mulₗ_apply_coe AlgebraicGeometry.ProjSpace.twistObj.mk.injEq AlgebraicGeometry.ProjSpace.twistObj.zero_val AlgebraicGeometry.ProjSpace.twistObj.add_val AlgebraicGeometry.ProjSpace.twist_res_val AlgebraicGeometry.ProjSpace.twist_smul_val AlgebraicGeometry.ProjSpace.twistGradeToObj_val AlgebraicGeometry.ProjSpace.twistObj.smul_val AlgebraicGeometry.ProjSpace.twistGradeEquiv_apply_val AlgebraicGeometry.ProjSpace.twistObj.mk.sizeOf_spec Algebra.DescentCofaces.i₁_apply Algebra.DescentCofaces.i₂_apply Algebra.DescentCofaces.c₁₂_tmul Algebra.DescentCofaces.c₂₃_tmul Algebra.DescentCofaces.c₁₃_tmul AlgebraicGeometry.DescentAction.toTriple_fst_assoc AlgebraicGeometry.DescentAction.invol_snd_assoc AlgebraicGeometry.DescentAction.unitMap_fst AlgebraicGeometry.DescentAction.flipMap_snd_assoc AlgebraicGeometry.DescentAction.actMap_snd_assoc AlgebraicGeometry.DescentAction.unitMap_fst_assoc AlgebraicGeometry.DescentAction.unitMap_snd AlgebraicGeometry.DescentAction.eRel_snd AlgebraicGeometry.DescentAction.toTriple_fst AlgebraicGeometry.DescentAction.invol_invol AlgebraicGeometry.DescentAction.proj₁₃_snd AlgebraicGeometry.DescentAction.eRel_snd_assoc AlgebraicGeometry.DescentAction.invol_invol_assoc AlgebraicGeometry.DescentAction.invol_act"
p2m_attr_erase "simp" "AlgebraicGeometry.DescentAction.actMap_fst_assoc AlgebraicGeometry.DescentAction.flipMap_fst_assoc AlgebraicGeometry.DescentAction.eRel_fst_assoc AlgebraicGeometry.DescentAction.eRel_fst AlgebraicGeometry.DescentAction.invol_act_assoc AlgebraicGeometry.DescentAction.invol_fst_assoc AlgebraicGeometry.DescentAction.proj₁₃_snd_assoc AlgebraicGeometry.DescentAction.mk.injEq AlgebraicGeometry.DescentAction.flipMap_fst AlgebraicGeometry.DescentAction.proj₁₃_fst AlgebraicGeometry.DescentAction.invol_fst AlgebraicGeometry.DescentAction.unitMap_snd_assoc AlgebraicGeometry.DescentAction.actMap_fst AlgebraicGeometry.DescentAction.toTriple_snd_assoc AlgebraicGeometry.DescentAction.invol_snd AlgebraicGeometry.DescentAction.actMap_snd AlgebraicGeometry.DescentAction.flipMap_snd AlgebraicGeometry.DescentAction.proj₁₃_fst_assoc AlgebraicGeometry.DescentAction.mk.sizeOf_spec AlgebraicGeometry.DescentAction.toTriple_snd GoodReductionJacobian.RelativeGroupLaw.fibre_inv GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_coe GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_toBase GoodReductionJacobian.RelativeGroupLaw.fibre_mul GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_ofBase GoodReductionJacobian.RelativeGroupLaw.fibre_one GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_coe AlgebraicGeometry.schemeFibreEndo_snd AlgebraicGeometry.schemeFibreEndo_fst AlgebraicCurve.KwCfx.kw_cfx_tau_coe AlgebraicCurve.kw_hwcd_dlog_zero AlgebraicCurve.kw_hwcd_mem_regularDifferentials_iff AlgebraicCurve.kw_hwcd_dlog_one AlgebraicCurve.Divisor.congr_single AlgebraicCurve.Pic0.coe_degZeroCongr_symm AlgebraicCurve.Divisor.degree_congr AlgebraicCurve.Divisor.degree_congr_symm AlgebraicCurve.Pic0.coe_degZeroCongr CuspForm.Gamma1Hecke.redMatrix_apply_one_one CuspForm.Gamma1Hecke.redMatrix_apply_one_zero"
p2m_attr_erase "simp" "CuspForm.Gamma1Hecke.lift_infty CuspForm.Gamma1Hecke.heckeRep_infty CuspForm.Gamma1Hecke.heckeRep_coe CuspForm.Gamma1Hecke.wt_infty CuspForm.Gamma1Hecke.redMatrix_apply_zero_one CuspForm.coe_slashLinOfMemGamma0_apply CuspForm.Gamma1Hecke.wt_coe CuspForm.Gamma1Hecke.lift_coe CuspForm.Gamma1Hecke.redMatrix_apply_zero_zero CuspForm.coe_heckeTOne CuspForm.coe_heckeTLinOne_apply CuspForm.coe_slashOfMemGamma0 ModularCurve.dualHeckeRep_apply_apply ModularCurve.coe_segmentPath ModularCurve.cuspHeckeAeval_heckeGen ModularCurve.coe_periodLatticeRestrict_apply CuspForm.heckeAlgebra.coe_U CuspForm.heckeAlgebra.coe_T ModularForm.coe_heckeTLin_apply CuspForm.coe_heckeULin_apply CuspForm.coe_heckeTLin_apply ModularForm.coe_heckeULin_apply ModularCurve.Period.IsEquivariantPrimitive.periodHom_apply ModularCurve.Period.IsEquivariantPrimitive.period_one CohCarrier.jConjGammaH_jConjGammaH CohCarrier.coe_jConjGammaH CohCarrier.charInvolution_apply ModularCurve.Period.jConjMat_apply_zero_one ModularCurve.Period.jConjSL_coe ModularCurve.Period.jConjMat_apply_one_zero ModularCurve.Period.jConjMat_apply_one_one ModularCurve.Period.jConjGamma0_coe ModularCurve.Period.charInvolution_apply ModularCurve.Period.jConjMat_apply_zero_zero ExtCitation.archimedeanLoc_archimedeanGen complexConjAlgEquiv_apply ModularCurve.ComplexPlaceDictionaryOf.pt_ofGamma0 ModularCurve.ComplexPlaceDictionaryOf.mk.injEq ModularCurve.ComplexPlaceDictionaryOf.pt_toGamma0 ModularCurve.ComplexPlaceDictionaryOf.mk.sizeOf_spec"
p2m_attr_erase "simp" "ModularCurve.ComplexPlaceDictionary.mk.injEq ModularCurve.ComplexPlaceDictionary.mk.sizeOf_spec HeckeEis.heckeConjMat_apply_one_one HeckeEis.coe_heckeConjSL HeckeEis.mem_heckeUpperSL HeckeEis.resHom_apply HeckeEis.heckeConjMat_apply_zero_one HeckeEis.coe_transferAux HeckeEis.coe_heckeConj HeckeEis.alphaMat_apply_one_one HeckeEis.heckeConjMat_apply_one_zero HeckeEis.alphaMat_apply_zero_one HeckeEis.pullbackHom_apply HeckeEis.alphaMat_apply_one_zero HeckeEis.alphaMat_apply_zero_zero HeckeEis.heckeConjMat_apply_zero_zero FLT.TruncatedDomainPartition.unipotentDiagonalSum_zero HeckeEis.coeffCoboundaryMap_apply ModularCurve.qEulerFun_coeff ModularCurve.diffQExp_D ModularCurve.qEulerOn_apply ModularCurve.qEuler_coeff FreyPackage.ModMCarrier.coe_rescaleLin_apply ModularForm.AtkinLehnerDatum.mk.injEq ModularForm.AtkinLehnerDatum.alGL_coe ModularForm.AtkinLehnerDatum.mk.sizeOf_spec ModularForm.AtkinLehnerDatum.sqUnitSL_coe ModularForm.AtkinLehnerDatum.det_sqUnit ModularForm.AtkinLehnerDatum.det_mat Ihara.wConj_coe Ihara.wConj_symm_coe Ihara.coe_iota1 Ihara.coe_iota1SL Ihara.iota1Mat_apply_one_zero Ihara.iota1Mat_apply_zero_zero Ihara.iota1Mat_apply_zero_one Ihara.iota1Mat_apply_one_one Ihara.coe_iota0 Ihara.iharaEdge_one Ihara.pairFamily_zero"
p2m_attr_erase "simp" "Ihara.iharaEdge_zero Ihara.pairFamily_one Ihara.coe_amalgamToGamma0Away Ihara.coe_vertexZero Ihara.coe_slToAway CuspForm.PeterssonCoset.mapGL_apply CohCarrier.uMat_apply_10 CohCarrier.rightQuotEquivOfDvd_apply CohCarrier.uMat_apply_11 CohCarrier.uMat_apply_01 CohCarrier.uMat_apply_00 CohCarrier.coe_uElt"

set_option autoImplicit false

noncomputable section

namespace ModularCurve
p2m_export "ModularCurve" "HeckeAlgOne heckeGenOne diamondGen heckeOperatorOneBar HeckeDiamondCommuteBar heckeModuleOneBar heckeModuleOneBar_heckeGenOne_smul heckeModuleOneBar_diamondGen_smul tateHeckeRepOne coe_tateHeckeRepOne_apply_apply rationalHeckeRepOne rationalHeckeAlgebraOne rationalHeckeRepOne_mem_rationalHeckeAlgebraOne rationalDiamondOne rationalHeckeOne qExpFunctionFieldC JOne arithmeticRingAut coe_arithmeticRingAut_apply arithmeticRingAut_algebraMap arithmeticGalois galois_smul_pic0_def coeffMap_coeffMap coeffMap_id coeffMap_congr coeffEmb coeffMap_coeffEmb laurentBaseChange coeffEmb_mem_laurentBaseChange IsBaseChangeAutOf baseChangeAut isBaseChangeAutOf_baseChangeAut baseChangeAut_of_not diamondAutBar diamondOneBar diamondOneBar_apply ReductionInputsQExpModL reductionQExpModL qExpFrobeniusPushforwardModL qExpFrobeniusPullbackModL GammaH_bot xHFunctionFieldC exists_transcendental_and_reductionInputsQExpModL_gammaH_of_not_dvd reductionQExpModL_gammaH_smul_of_isFrobeniusAt reductionQExpModL_gammaH_smul_eq_self_of_mem_inertiaSubgroupIn reductionQExpModL_gamma1_heckeOperatorOneBar heckeDiamondInputsAll heckeDiamondCommuteBar qExpFrobeniusPullbackModL_qExpFrobeniusPushforwardModL_of_transcendental finrank_map_reductionKernelSpan_tateModule_jOne_le_one_of_isUnit"
namespace OrdQ1
p2m_open "ModularCurve"

p2m_open "ModularCurve P2MW.S_ModularCurve_exists_ordLine_frobenius_quadratic_mem_tateModule_jOne_quotient_of_isUnit_of_not_dvd.ModularCurve AlgebraicCurve IntermediateField"
open scoped TensorProduct

section Commute

variable {L : Type*} [Field L] [Algebra ℚ L] {F₀ : IntermediateField ℚ (LaurentSeries ℚ)}

def conjAlgHom (σ : L ≃ₐ[ℚ] L) (τ : laurentBaseChange L F₀ ≃ₐ[L] laurentBaseChange L F₀) :
    laurentBaseChange L F₀ →ₐ[L] laurentBaseChange L F₀ :=
  { (((arithmeticRingAut F₀ σ.symm).trans (τ : laurentBaseChange L F₀ ≃+* laurentBaseChange L F₀)).trans
      (arithmeticRingAut F₀ σ)).toRingHom with
    commutes' := fun c => by
      show arithmeticRingAut F₀ σ (τ (arithmeticRingAut F₀ σ.symm (algebraMap L _ c))) = algebraMap L _ c
      rw [arithmeticRingAut_algebraMap, AlgEquiv.commutes, arithmeticRingAut_algebraMap,
        AlgEquiv.apply_symm_apply] }

theorem conjAlgHom_apply (σ : L ≃ₐ[ℚ] L) (τ : laurentBaseChange L F₀ ≃ₐ[L] laurentBaseChange L F₀)
    (x : laurentBaseChange L F₀) :
    conjAlgHom σ τ x = arithmeticRingAut F₀ σ (τ (arithmeticRingAut F₀ σ.symm x)) :=
  rfl

theorem arithmeticRingAut_comm_of_isBaseChangeAutOf {σ₀ : F₀ ≃ₐ[ℚ] F₀}
    {τ : laurentBaseChange L F₀ ≃ₐ[L] laurentBaseChange L F₀} (hτ : IsBaseChangeAutOf L σ₀ τ)
    (σ : L ≃ₐ[ℚ] L) (x : laurentBaseChange L F₀) :
    arithmeticRingAut F₀ σ (τ x) = τ (arithmeticRingAut F₀ σ x) := by
  have key : conjAlgHom σ τ = τ.toAlgHom := by
    refine IntermediateField.adjoin_algHom_ext L fun y hy => ?_
    obtain ⟨y₀, hy₀, rfl⟩ := hy
    show arithmeticRingAut F₀ σ (τ (arithmeticRingAut F₀ σ.symm ⟨coeffEmb L y₀, _⟩)) = τ ⟨coeffEmb L y₀, _⟩
    have h1 : arithmeticRingAut F₀ σ.symm ⟨coeffEmb L y₀, coeffEmb_mem_laurentBaseChange L hy₀⟩ =
        ⟨coeffEmb L y₀, coeffEmb_mem_laurentBaseChange L hy₀⟩ :=
      Subtype.ext (coeffMap_coeffEmb σ.symm y₀)
    rw [h1]
    have h2 := hτ ⟨y₀, hy₀⟩
    refine Subtype.ext ?_
    rw [coe_arithmeticRingAut_apply, h2, coeffMap_coeffEmb]
  have h := congrArg (fun φ : laurentBaseChange L F₀ →ₐ[L] laurentBaseChange L F₀ =>
    φ (arithmeticRingAut F₀ σ x)) key
  simp only [conjAlgHom_apply, AlgEquiv.toAlgHom_apply] at h
  rw [← h]
  congr 2
  exact Subtype.ext (by
    rw [coe_arithmeticRingAut_apply, coe_arithmeticRingAut_apply, coeffMap_coeffMap,
      coeffMap_congr (g := RingHom.id L) (RingHom.ext fun a => σ.symm_apply_apply a), coeffMap_id])

theorem arithmeticGalois_mul_ofAlgAut_baseChangeAut (σ₀ : F₀ ≃ₐ[ℚ] F₀) (σ : L ≃ₐ[ℚ] L) :
    arithmeticGalois F₀ σ * SemilinearAut.ofAlgAut (baseChangeAut L σ₀) =
      SemilinearAut.ofAlgAut (baseChangeAut L σ₀) * arithmeticGalois F₀ σ := by
  rcases Classical.em
      (∃ τ : laurentBaseChange L F₀ ≃ₐ[L] laurentBaseChange L F₀, IsBaseChangeAutOf L σ₀ τ) with h | h
  · have hτ := isBaseChangeAutOf_baseChangeAut h
    refine Subtype.ext (Prod.ext (RingEquiv.ext fun x => ?_) ?_)
    · exact arithmeticRingAut_comm_of_isBaseChangeAutOf hτ σ x
    · show σ.toRingEquiv * 1 = 1 * σ.toRingEquiv
      rw [mul_one, one_mul]
  · rw [baseChangeAut_of_not h, show (AlgEquiv.refl : laurentBaseChange L F₀ ≃ₐ[L] laurentBaseChange L F₀)
      = 1 from rfl, map_one, mul_one, one_mul]

end Commute

theorem smul_diamondOneBar (M d : ℕ) (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (z : JOne M) :
    σ • diamondOneBar M d z = diamondOneBar M d (σ • z) := by
  rw [diamondOneBar_apply, diamondOneBar_apply, galois_smul_pic0_def, galois_smul_pic0_def,
    ← mul_smul, ← mul_smul, diamondAutBar, arithmeticGalois_mul_ofAlgAut_baseChangeAut]

section Transport

variable (M : ℕ) [NeZero M] {ℓ : ℕ} [Fact ℓ.Prime]
  (A : ValuationSubring (AlgebraicClosure ℚ)) (hℓM : ¬ ℓ ∣ M) (hA : A.LiesOverPrime ℓ)

include hℓM hA

set_option synthInstance.maxHeartbeats 1600000 in

theorem D1_gamma1 :
    (∃ x : qExpFunctionFieldC (IsLocalRing.ResidueField A) (CongruenceSubgroup.Gamma1 M),
        Transcendental (IsLocalRing.ResidueField A) x ∧
          FiniteDimensional
            (IntermediateField.adjoin (IsLocalRing.ResidueField A)
              ({x} : Set (qExpFunctionFieldC (IsLocalRing.ResidueField A) (CongruenceSubgroup.Gamma1 M))))
            (qExpFunctionFieldC (IsLocalRing.ResidueField A) (CongruenceSubgroup.Gamma1 M))) ∧
      ReductionInputsQExpModL A (CongruenceSubgroup.Gamma1 M) := by
  have h := exists_transcendental_and_reductionInputsQExpModL_gammaH_of_not_dvd M ⊥ hℓM A hA
  rw [xHFunctionFieldC, GammaH_bot] at h
  exact h

set_option synthInstance.maxHeartbeats 1600000 in

theorem D2_gamma1 [CharP (IsLocalRing.ResidueField A) ℓ]
    (h : ReductionInputsQExpModL A (CongruenceSubgroup.Gamma1 M))
    (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (hσ : A.IsFrobeniusAt σ ℓ) (z : JOne M) :
    reductionQExpModL A (CongruenceSubgroup.Gamma1 M) (σ • z) =
      qExpFrobeniusPushforwardModL (IsLocalRing.ResidueField A) (CongruenceSubgroup.Gamma1 M) ℓ
        (reductionQExpModL A (CongruenceSubgroup.Gamma1 M) z) := by
  have key : ∀ Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℤ), Γ = CohCarrier.GammaH M ⊥ →
      ∀ (hΓ : ReductionInputsQExpModL A Γ)
        (w : Pic0 (AlgebraicClosure ℚ) (laurentBaseChange (AlgebraicClosure ℚ) (qExpFunctionFieldC ℚ Γ))),
        reductionQExpModL A Γ (σ • w) =
          qExpFrobeniusPushforwardModL (IsLocalRing.ResidueField A) Γ ℓ (reductionQExpModL A Γ w) := by
    rintro Γ rfl hΓ w
    exact reductionQExpModL_gammaH_smul_of_isFrobeniusAt M ⊥ hℓM A hA hΓ σ hσ w
  exact key (CongruenceSubgroup.Gamma1 M) (GammaH_bot M).symm h z

end Transport

set_option synthInstance.maxHeartbeats 1600000 in

theorem RI_gamma1 (M : ℕ) [NeZero M] (A : ValuationSubring (AlgebraicClosure ℚ))
    (h : ReductionInputsQExpModL A (CongruenceSubgroup.Gamma1 M))
    (τ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (hτ : τ ∈ A.inertiaSubgroupIn ℚ) (z : JOne M) :
    reductionQExpModL A (CongruenceSubgroup.Gamma1 M) (τ • z) =
      reductionQExpModL A (CongruenceSubgroup.Gamma1 M) z := by
  have key : ∀ Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℤ), Γ = CohCarrier.GammaH M ⊥ →
      ∀ (hΓ : ReductionInputsQExpModL A Γ)
        (w : Pic0 (AlgebraicClosure ℚ) (laurentBaseChange (AlgebraicClosure ℚ) (qExpFunctionFieldC ℚ Γ))),
        reductionQExpModL A Γ (τ • w) = reductionQExpModL A Γ w := by
    rintro Γ rfl hΓ w
    exact reductionQExpModL_gammaH_smul_eq_self_of_mem_inertiaSubgroupIn M ⊥ A hΓ τ hτ w
  exact key (CongruenceSubgroup.Gamma1 M) (GammaH_bot M).symm h z

theorem map_quadratic_eq_zero {J Jb : Type*} [AddCommGroup J] [AddCommGroup Jb]
    (red : J →+ Jb) (s T Dm : J → J) (Fr V : Jb → Jb) (ℓ : ℕ)
    (hcomm : ∀ w, s (Dm w) = Dm (s w))
    (hs : ∀ w, red (s w) = Fr (red w))
    (hT : ∀ w, red (T w) = Fr (red (Dm w)) + V (red w))
    (hE : ∀ y, V (Fr y) = ℓ • y) (z : J) :
    red (Dm (s (s z)) - T (s z) + ℓ • z) = 0 := by
  rw [map_add, map_sub, map_nsmul, ← hcomm, hs, hT, hs, hE]
  abel

set_option synthInstance.maxHeartbeats 1600000 in

theorem red_es_eq_zero (M : ℕ) [NeZero M] {p : ℕ} (hp : p.Prime)
    (P : ValuationSubring (AlgebraicClosure ℚ)) (hP : P.LiesOverPrime p) (hpM : ¬ p ∣ M)
    (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (hσ : P.IsFrobeniusAt σ p) (z : JOne M) :
    reductionQExpModL P (CongruenceSubgroup.Gamma1 M)
      (diamondOneBar M p (σ • σ • z) - heckeOperatorOneBar M ⟨p, hp⟩ (σ • z) + p • z) = 0 := by
  haveI : Fact p.Prime := ⟨hp⟩
  haveI : CharP (IsLocalRing.ResidueField P) p := P.charP_residueField_of_liesOverPrime_def hp hP
  obtain ⟨hcurve, hred⟩ := D1_gamma1 M P hpM hP
  exact map_quadratic_eq_zero (reductionQExpModL P (CongruenceSubgroup.Gamma1 M)) (σ • ·)
    (heckeOperatorOneBar M ⟨p, hp⟩) (diamondOneBar M p)
    (qExpFrobeniusPushforwardModL (IsLocalRing.ResidueField P) (CongruenceSubgroup.Gamma1 M) p)
    (qExpFrobeniusPullbackModL (IsLocalRing.ResidueField P) (CongruenceSubgroup.Gamma1 M) p) p
    (fun w => smul_diamondOneBar M p σ w)
    (fun w => D2_gamma1 M P hpM hP hred σ hσ w)
    (fun w => reductionQExpModL_gamma1_heckeOperatorOneBar M hpM P hP (heckeDiamondInputsAll M) hred w)
    (fun y => qExpFrobeniusPullbackModL_qExpFrobeniusPushforwardModL_of_transcendental
      (IsLocalRing.ResidueField P) (CongruenceSubgroup.Gamma1 M) hcurve y) z

theorem map_sub_self_eq_zero {J Jb : Type*} [AddCommGroup J] [AddCommGroup Jb]
    (red : J →+ Jb) (s : J → J) (hs : ∀ w, red (s w) = red w) (z : J) : red (s z - z) = 0 := by
  rw [map_sub, hs, sub_self]

set_option synthInstance.maxHeartbeats 1600000 in

theorem red_inertia_sub_eq_zero (M : ℕ) [NeZero M] {p : ℕ} (hp : p.Prime)
    (P : ValuationSubring (AlgebraicClosure ℚ)) (hP : P.LiesOverPrime p) (hpM : ¬ p ∣ M)
    (τ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (hτ : τ ∈ P.inertiaSubgroupIn ℚ) (z : JOne M) :
    reductionQExpModL P (CongruenceSubgroup.Gamma1 M) (τ • z - z) = 0 := by
  haveI : Fact p.Prime := ⟨hp⟩
  obtain ⟨-, hred⟩ := D1_gamma1 M P hpM hP
  exact map_sub_self_eq_zero (reductionQExpModL P (CongruenceSubgroup.Gamma1 M)) (τ • ·)
    (fun w => RI_gamma1 M P hred τ hτ w) z

section Connected

variable (M p : ℕ) [NeZero M] [Fact p.Prime]
  (K : Type) [Field K] [Algebra ℤ_[p] K]
  (P : ValuationSubring (AlgebraicClosure ℚ))

def conn : Set (TateModule p (JOne M)) :=
  {x | ∀ n : ℕ, reductionQExpModL P (CongruenceSubgroup.Gamma1 M) ((x : ℕ → JOne M) n) = 0}

def connSpan : Submodule K (K ⊗[ℤ_[p]] TateModule p (JOne M)) :=
  Submodule.span K ((fun x : TateModule p (JOne M) => (1 : K) ⊗ₜ[ℤ_[p]] x) '' conn M p P)

variable {M p K P}

theorem tmul_mem_connSpan (c : K) {x : TateModule p (JOne M)} (hx : x ∈ conn M p P) :
    c ⊗ₜ[ℤ_[p]] x ∈ connSpan M p K P := by
  have h : c ⊗ₜ[ℤ_[p]] x = c • ((1 : K) ⊗ₜ[ℤ_[p]] x) := by
    rw [TensorProduct.smul_tmul', smul_eq_mul, mul_one]
  rw [h]
  exact Submodule.smul_mem _ c (Submodule.subset_span ⟨x, hx, rfl⟩)

set_option maxHeartbeats 6400000 in

theorem rep_sub_mem_connSpan (hpM : ¬ p ∣ M) (hP : P.LiesOverPrime p)
    {τ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ} (hτ : τ ∈ P.inertiaSubgroupIn ℚ)
    (x : K ⊗[ℤ_[p]] TateModule p (JOne M)) :
    (TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) τ).baseChange K x - x ∈
      connSpan M p K P := by
  induction x using TensorProduct.induction_on with
  | zero => rw [map_zero, sub_zero]; exact Submodule.zero_mem _
  | tmul c y =>
    rw [LinearMap.baseChange_tmul, ← TensorProduct.tmul_sub]
    refine tmul_mem_connSpan c fun n => ?_
    have h : (((TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) τ y - y :
        TateModule p (JOne M)) : ℕ → JOne M) n) = τ • (y : ℕ → JOne M) n - (y : ℕ → JOne M) n := by
      rw [AddSubgroupClass.coe_sub, Pi.sub_apply, TateModule.rep_apply]
    rw [h]
    exact red_inertia_sub_eq_zero M Fact.out P hP hpM τ hτ _
  | add x y hx hy =>
    rw [map_add, add_sub_add_comm]
    exact Submodule.add_mem _ hx hy

def esOp [Module HeckeAlgOne (JOne M)] (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) :
    K ⊗[ℤ_[p]] TateModule p (JOne M) →ₗ[K] K ⊗[ℤ_[p]] TateModule p (JOne M) :=
  (tateHeckeRepOne p (JOne M) (diamondGen p)).baseChange K ∘ₗ
      ((TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K ∘ₗ
        (TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K)
    - (tateHeckeRepOne p (JOne M) (heckeGenOne ⟨p, Fact.out⟩)).baseChange K ∘ₗ
        (TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K
    + (p : K) • LinearMap.id

theorem esOp_apply [Module HeckeAlgOne (JOne M)] (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
    (x : K ⊗[ℤ_[p]] TateModule p (JOne M)) :
    esOp (M := M) (p := p) (K := K) σ x =
      (tateHeckeRepOne p (JOne M) (diamondGen p)).baseChange K
          ((TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K
            ((TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K x))
        - (tateHeckeRepOne p (JOne M) (heckeGenOne ⟨p, Fact.out⟩)).baseChange K
            ((TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K x)
        + (p : K) • x := by
  simp only [esOp, LinearMap.add_apply, LinearMap.sub_apply, LinearMap.comp_apply, LinearMap.smul_apply,
    LinearMap.id_apply]

set_option synthInstance.maxHeartbeats 1600000 in
set_option maxHeartbeats 6400000 in

theorem esOp_mem_connSpan (hpM : ¬ p ∣ M) (hP : P.LiesOverPrime p)
    {σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ} (hσ : P.IsFrobeniusAt σ p)
    (x : K ⊗[ℤ_[p]] TateModule p (JOne M)) :
    letI := heckeModuleOneBar M
    esOp (M := M) (p := p) (K := K) σ x ∈ connSpan M p K P := by
  letI := heckeModuleOneBar M
  have hcomm : HeckeDiamondCommuteBar M := heckeDiamondCommuteBar M
  have hp : p.Prime := Fact.out
  induction x using TensorProduct.induction_on with
  | zero => rw [map_zero]; exact Submodule.zero_mem _
  | tmul c y =>
    rw [esOp_apply]

    have hp' : (p : K) • (c ⊗ₜ[ℤ_[p]] y) = c ⊗ₜ[ℤ_[p]] ((p : ℤ_[p]) • y) := by
      rw [← TensorProduct.smul_tmul, Algebra.smul_def, map_natCast, TensorProduct.smul_tmul', smul_eq_mul]
    rw [LinearMap.baseChange_tmul, LinearMap.baseChange_tmul, LinearMap.baseChange_tmul,
      LinearMap.baseChange_tmul, hp', ← TensorProduct.tmul_sub, ← TensorProduct.tmul_add]
    refine tmul_mem_connSpan c fun n => ?_

    have hpn : ((((p : ℤ_[p]) • y : TateModule p (JOne M)) : ℕ → JOne M) n) = p • (y : ℕ → JOne M) n := by
      rw [TateModule.natCast_padicInt_smul_apply, natCast_zsmul]
    change reductionQExpModL P (CongruenceSubgroup.Gamma1 M)
      ((diamondGen p : HeckeAlgOne) • (σ • σ • (y : ℕ → JOne M) n)
        - (heckeGenOne ⟨p, hp⟩ : HeckeAlgOne) • (σ • (y : ℕ → JOne M) n)
        + ((((p : ℤ_[p]) • y : TateModule p (JOne M)) : ℕ → JOne M) n)) = 0
    rw [hpn, heckeModuleOneBar_heckeGenOne_smul hcomm, heckeModuleOneBar_diamondGen_smul hcomm]
    exact red_es_eq_zero M hp P hP hpM σ hσ _
  | add x y hx hy =>
    rw [map_add]
    exact Submodule.add_mem _ hx hy

end Connected

theorem conj_mem_inertiaSubgroupIn {F : Type*} [Field F] (k : Type*) [Field k] [Algebra k F]
    (A : ValuationSubring F) {τ σ : F ≃ₐ[k] F} (hτ : τ ∈ A.decompositionSubgroup k)
    (hσ : σ ∈ A.inertiaSubgroupIn k) : τ * σ * τ⁻¹ ∈ A.inertiaSubgroupIn k := by
  obtain ⟨s, hs, rfl⟩ := Subgroup.mem_map.mp hσ
  have hN : (A.inertiaSubgroup k).Normal := by
    delta ValuationSubring.inertiaSubgroup
    exact MonoidHom.normal_ker _
  have hmem : (⟨τ, hτ⟩ : A.decompositionSubgroup k) * s * (⟨τ, hτ⟩ : A.decompositionSubgroup k)⁻¹ ∈
      A.inertiaSubgroup k := hN.conj_mem s hs ⟨τ, hτ⟩
  refine Subgroup.mem_map.mpr ⟨_, hmem, ?_⟩
  simp only [Subgroup.coe_subtype, Subgroup.coe_mul, Subgroup.coe_inv]

theorem isFrobeniusAt_conj {F : Type*} [Field F] (k : Type*) [Field k] [Algebra k F]
    (A : ValuationSubring F) {q : ℕ} {τ σ : F ≃ₐ[k] F} (hτ : τ ∈ A.decompositionSubgroup k)
    (hσ : A.IsFrobeniusAt σ q) : A.IsFrobeniusAt (τ * σ * τ⁻¹) q := by
  obtain ⟨hσD, hσq⟩ := hσ
  have hmem : τ * σ * τ⁻¹ ∈ A.decompositionSubgroup k :=
    Subgroup.mul_mem _ (Subgroup.mul_mem _ hτ hσD) (Subgroup.inv_mem _ hτ)
  refine ⟨hmem, fun x => ?_⟩
  have heq : (⟨τ * σ * τ⁻¹, hmem⟩ : A.decompositionSubgroup k) =
      (⟨τ, hτ⟩ : A.decompositionSubgroup k) * ⟨σ, hσD⟩ * (⟨τ, hτ⟩ : A.decompositionSubgroup k)⁻¹ :=
    Subtype.ext rfl
  rw [heq, mul_smul, mul_smul, hσq, smul_pow', smul_inv_smul]

section RMul

variable {K : Type} [Field K] {X W : Type} [AddCommGroup X] [Module K X] [AddCommGroup W] [Module K W]
  {G : Type*} [Group G]

theorem r_mul (R : G →* Module.End K X) (r : G → W →ₗ[K] W) (π : X →ₗ[K] W)
    (hπ : Function.Surjective π) (h : ∀ g x, π (R g x) = r g (π x)) (g g' : G) (w : W) :
    r (g * g') w = r g (r g' w) := by
  obtain ⟨x, rfl⟩ := hπ w
  rw [← h, ← h, ← h, map_mul, Module.End.mul_apply]

theorem r_one (R : G →* Module.End K X) (r : G → W →ₗ[K] W) (π : X →ₗ[K] W)
    (hπ : Function.Surjective π) (h : ∀ g x, π (R g x) = r g (π x)) (w : W) :
    r 1 w = w := by
  obtain ⟨x, rfl⟩ := hπ w
  rw [← h, map_one, Module.End.one_apply]

end RMul

section Assemble

variable {K W : Type*} [Field K] [AddCommGroup W] [Module K W]
  {G : Type*} [Group G]

theorem assemble [FiniteDimensional K W] (r : G → W →ₗ[K] W)
    (hr_mul : ∀ (g g' : G) (w : W), r (g * g') w = r g (r g' w))
    (D I Fr : Set G) (hI : ∀ γ ∈ D, ∀ τ ∈ I, γ * τ * γ⁻¹ ∈ I) (hFr : ∀ γ ∈ D, ∀ σ ∈ Fr, γ * σ * γ⁻¹ ∈ Fr)
    (c₁ c₂ : K) (V0 : Submodule K W) (hV0 : Module.finrank K V0 ≤ 1)
    (hIV0 : ∀ τ ∈ I, ∀ w : W, r τ w - w ∈ V0)
    (hFV0 : ∀ σ ∈ Fr, ∀ w : W, r σ (r σ w) - c₁ • r σ w + c₂ • w ∈ V0) :
    ∃ L : Submodule K W,
      Module.finrank K L ≤ 1 ∧
      (∀ γ ∈ D, ∀ w ∈ L, r γ w ∈ L) ∧
      (∀ τ ∈ I, ∀ w : W, r τ w - w ∈ L) ∧
      (∀ σ ∈ Fr, ∀ w : W, r σ (r σ w) - c₁ • r σ w + c₂ • w ∈ L) := by
  let es : G → W → W := fun σ w => r σ (r σ w) - c₁ • r σ w + c₂ • w
  let IM : Set W := {v | ∃ τ ∈ I, ∃ w : W, v = r τ w - w}
  let ES : Set W := {v | ∃ σ ∈ Fr, ∃ w : W, v = es σ w}
  let L : Submodule K W := Submodule.span K (IM ∪ ES)
  have hLV0 : L ≤ V0 := by
    refine Submodule.span_le.mpr ?_
    rintro v (⟨τ, hτ, w, rfl⟩ | ⟨σ, hσ, w, rfl⟩)
    · exact hIV0 τ hτ w
    · exact hFV0 σ hσ w
  have hL1 : Module.finrank K L ≤ 1 := (Submodule.finrank_mono hLV0).trans hV0
  have hgen_stable : ∀ γ ∈ D, ∀ v ∈ IM ∪ ES, r γ v ∈ L := by
    rintro γ hγ v (⟨τ, hτ, w, rfl⟩ | ⟨σ, hσ, w, rfl⟩)
    · have key : r γ (r τ w - w) = r (γ * τ * γ⁻¹) (r γ w) - r γ w := by
        rw [map_sub, ← hr_mul (γ * τ * γ⁻¹) γ, inv_mul_cancel_right, hr_mul]
      rw [key]
      exact Submodule.subset_span (Or.inl ⟨γ * τ * γ⁻¹, hI γ hγ τ hτ, r γ w, rfl⟩)
    · have key : r γ (es σ w) = es (γ * σ * γ⁻¹) (r γ w) := by
        show r γ (r σ (r σ w) - c₁ • r σ w + c₂ • w) =
          r (γ * σ * γ⁻¹) (r (γ * σ * γ⁻¹) (r γ w)) - c₁ • r (γ * σ * γ⁻¹) (r γ w) + c₂ • r γ w
        rw [map_add, map_sub, map_smul, map_smul, ← hr_mul (γ * σ * γ⁻¹) γ, inv_mul_cancel_right,
          ← hr_mul (γ * σ * γ⁻¹) (γ * σ), show γ * σ * γ⁻¹ * (γ * σ) = γ * (σ * σ) by group,
          hr_mul γ (σ * σ), hr_mul σ σ, hr_mul γ σ]
      rw [key]
      exact Submodule.subset_span (Or.inr ⟨γ * σ * γ⁻¹, hFr γ hγ σ hσ, r γ w, rfl⟩)
  have hD : ∀ γ ∈ D, ∀ v ∈ L, r γ v ∈ L := by
    intro γ hγ v hv
    induction hv using Submodule.span_induction with
    | mem v hv => exact hgen_stable γ hγ v hv
    | zero => rw [map_zero]; exact Submodule.zero_mem _
    | add v v' _ _ hv hv' => rw [map_add]; exact Submodule.add_mem _ hv hv'
    | smul c v _ hv => rw [map_smul]; exact Submodule.smul_mem _ c hv
  refine ⟨L, hL1, hD, fun τ hτ w => Submodule.subset_span (Or.inl ⟨τ, hτ, w, rfl⟩), fun σ hσ w => ?_⟩
  exact Submodule.subset_span (Or.inr ⟨σ, hσ, w, rfl⟩)

theorem smul_es (dK δ aK pK : K) (hδ : δ * dK = 1) (u v w : W) :
    u - (dK * aK) • v + (dK * pK) • w = dK • (δ • u - aK • v + pK • w) := by
  rw [smul_add, smul_sub, smul_smul, smul_smul, smul_smul, mul_comm dK δ, hδ, one_smul]

end Assemble

section OnW

variable (M p : ℕ) [NeZero M] [Fact p.Prime] (hpM : ¬ p ∣ M)
  (O : Type) [CommRing O] [Algebra ℤ_[p] O]
  (K : Type) [Field K] [Algebra O K] [Algebra ℤ_[p] K] [IsScalarTower ℤ_[p] O K]

set_option synthInstance.maxHeartbeats 1600000 in
set_option maxHeartbeats 32000000 in

theorem es_pi_eq
    (Λ : (letI := heckeModuleOneBar M; ↥(rationalHeckeAlgebraOne p (JOne M))) →+* K)
    (a d : O)
    (ha : (letI := heckeModuleOneBar M; Λ (rationalHeckeOne p (JOne M) ⟨p, Fact.out⟩)) = algebraMap O K a)
    (hd : (letI := heckeModuleOneBar M; Λ (rationalDiamondOne p (JOne M) p)) * algebraMap O K d = 1)
    (W : Type) [AddCommGroup W] [Module K W]
    (r : (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) → (W →ₗ[K] W))
    (π : K ⊗[ℤ_[p]] TateModule p (JOne M) →ₗ[K] W)
    (hπσ : ∀ (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (x : K ⊗[ℤ_[p]] TateModule p (JOne M)),
      π ((TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K x) =
        r σ (π x))
    (hπT : letI := heckeModuleOneBar M
      ∀ (t : HeckeAlgOne) (x : K ⊗[ℤ_[p]] TateModule p (JOne M)),
        π ((tateHeckeRepOne p (JOne M) t).baseChange K x) =
          Λ ⟨rationalHeckeRepOne p (JOne M) t, rationalHeckeRepOne_mem_rationalHeckeAlgebraOne p (JOne M) t⟩ • π x)
    (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (x : K ⊗[ℤ_[p]] TateModule p (JOne M)) :
    letI := heckeModuleOneBar M
    r σ (r σ (π x)) - algebraMap O K (d * a) • r σ (π x) + algebraMap O K (d * (p : O)) • π x
      = algebraMap O K d • π (esOp (M := M) (p := p) (K := K) σ x) := by
  letI := heckeModuleOneBar M
  have hT : (⟨rationalHeckeRepOne p (JOne M) (heckeGenOne ⟨p, Fact.out⟩),
      rationalHeckeRepOne_mem_rationalHeckeAlgebraOne p (JOne M) _⟩ :
        rationalHeckeAlgebraOne p (JOne M)) = rationalHeckeOne p (JOne M) ⟨p, Fact.out⟩ := rfl
  have hDia : (⟨rationalHeckeRepOne p (JOne M) (diamondGen p),
      rationalHeckeRepOne_mem_rationalHeckeAlgebraOne p (JOne M) _⟩ :
        rationalHeckeAlgebraOne p (JOne M)) = rationalDiamondOne p (JOne M) p := rfl
  have h1 : π ((tateHeckeRepOne p (JOne M) (diamondGen p)).baseChange K
      ((TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K
        ((TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K x)))
      = Λ (rationalDiamondOne p (JOne M) p) • r σ (r σ (π x)) := by
    rw [hπT, hπσ, hπσ, hDia]
  have h2 : π ((tateHeckeRepOne p (JOne M) (heckeGenOne ⟨p, Fact.out⟩)).baseChange K
      ((TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K x))
      = algebraMap O K a • r σ (π x) := by
    rw [hπT, hπσ, hT, ha]
  have h3 : π ((p : K) • x) = (p : K) • π x := π.map_smul (p : K) x
  rw [esOp_apply, map_add, map_sub, h1, h2, h3, map_mul, map_mul, map_natCast]
  exact smul_es _ _ _ _ hd _ _ _

end OnW

end ModularCurve.OrdQ1

end

open _root_.ModularCurve _root_.P2MW.S_ModularCurve_exists_ordLine_frobenius_quadratic_mem_tateModule_jOne_quotient_of_isUnit_of_not_dvd.ModularCurve ModularCurve.OrdQ1 in
open scoped TensorProduct in
set_option synthInstance.maxHeartbeats 1600000 in
set_option maxHeartbeats 64000000 in
theorem solution
    (M p : ℕ) [NeZero M] [Fact p.Prime] (hpM : ¬ p ∣ M)
    (O : Type) [CommRing O] [IsDomain O] [IsDiscreteValuationRing O] [Algebra ℤ_[p] O]
    (K : Type) [Field K] [Algebra O K] [IsFractionRing O K] [Algebra ℤ_[p] K]
    [IsScalarTower ℤ_[p] O K] (hpO : (p : O) ∈ IsLocalRing.maximalIdeal O) :
    letI := ModularCurve.heckeModuleOneBar M
    ∀ (Λ : ↥(ModularCurve.rationalHeckeAlgebraOne p (ModularCurve.JOne M)) →+* K),
      (∀ c : ℤ_[p],
        Λ (algebraMap ℚ_[p] ↥(ModularCurve.rationalHeckeAlgebraOne p (ModularCurve.JOne M)) (c : ℚ_[p]))
          = algebraMap ℤ_[p] K c) →
      ∀ a d : O, IsUnit a →
        Λ (ModularCurve.rationalHeckeOne p (ModularCurve.JOne M) ⟨p, Fact.out⟩) = algebraMap O K a →
        Λ (ModularCurve.rationalDiamondOne p (ModularCurve.JOne M) p) * algebraMap O K d = 1 →
        ∀ (W : Type) [AddCommGroup W] [Module K W], Module.finrank K W = 2 →
          ∀ (r : (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) → (W →ₗ[K] W))
            (π : K ⊗[ℤ_[p]] TateModule p (ModularCurve.JOne M) →ₗ[K] W),
            Function.Surjective π →
            (∀ (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
                (x : K ⊗[ℤ_[p]] TateModule p (ModularCurve.JOne M)),
              π ((TateModule.rep p (ModularCurve.JOne M)
                  (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K x) = r σ (π x)) →
            (∀ (t : ModularCurve.HeckeAlgOne) (x : K ⊗[ℤ_[p]] TateModule p (ModularCurve.JOne M)),
              π ((ModularCurve.tateHeckeRepOne p (ModularCurve.JOne M) t).baseChange K x) =
                Λ ⟨ModularCurve.rationalHeckeRepOne p (ModularCurve.JOne M) t,
                    ModularCurve.rationalHeckeRepOne_mem_rationalHeckeAlgebraOne p
                      (ModularCurve.JOne M) t⟩ • π x) →
            ∀ P : ValuationSubring (AlgebraicClosure ℚ), P.LiesOverPrime p →
              ∃ L : Submodule K W,
                Module.finrank K L ≤ 1 ∧
                (∀ σ ∈ P.decompositionSubgroup ℚ, ∀ w ∈ L, r σ w ∈ L) ∧
                (∀ τ ∈ P.inertiaSubgroupIn ℚ, ∀ w : W, r τ w - w ∈ L) ∧
                (∀ σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ, P.IsFrobeniusAt σ p →
                  ∀ w : W, r σ (r σ w) - algebraMap O K (d * a) • r σ w
                    + algebraMap O K (d * (p : O)) • w ∈ L) := by
  letI := ModularCurve.heckeModuleOneBar M
  intro Λ hΛ a d hau ha hd W _ _ hW r π hπ hπσ hπT P hP
  haveI : FiniteDimensional K W := Module.finite_of_finrank_eq_succ hW
  have hp : p.Prime := Fact.out

  let RK : (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) →*
      Module.End K (K ⊗[ℤ_[p]] TateModule p (JOne M)) :=
    { toFun := fun σ =>
        (TateModule.rep p (JOne M) (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) σ).baseChange K
      map_one' := by rw [map_one, LinearMap.baseChange_one]
      map_mul' := fun σ τ => by rw [map_mul, LinearMap.baseChange_mul] }
  have hRK : ∀ (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
      (x : K ⊗[ℤ_[p]] TateModule p (JOne M)), π (RK σ x) = r σ (π x) := fun σ x => hπσ σ x
  have hr_mul : ∀ (g g' : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (w : W),
      r (g * g') w = r g (r g' w) := r_mul RK r π hπ hRK

  have hes_eq := es_pi_eq M p O K Λ a d ha hd W r π hπσ hπT

  have hV0 : Module.finrank K (Submodule.map π (connSpan M p K P)) ≤ 1 :=
    finrank_map_reductionKernelSpan_tateModule_jOne_le_one_of_isUnit M p hpM O K hpO Λ hΛ a hau ha
      W π hπT P hP
  have hIV0 : ∀ τ ∈ (↑(P.inertiaSubgroupIn ℚ) : Set (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)),
      ∀ w : W, r τ w - w ∈ Submodule.map π (connSpan M p K P) := by
    intro τ hτ w
    obtain ⟨x, rfl⟩ := hπ w
    refine ⟨RK τ x - x, rep_sub_mem_connSpan hpM hP hτ x, ?_⟩
    rw [map_sub, hRK]
  have hFV0 : ∀ σ ∈ {σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ | P.IsFrobeniusAt σ p},
      ∀ w : W, r σ (r σ w) - algebraMap O K (d * a) • r σ w + algebraMap O K (d * (p : O)) • w ∈
        Submodule.map π (connSpan M p K P) := by
    intro σ hσ w
    obtain ⟨x, rfl⟩ := hπ w
    rw [hes_eq]
    exact Submodule.smul_mem _ _ ⟨_, esOp_mem_connSpan hpM hP hσ x, rfl⟩

  obtain ⟨L, hL1, hD, hI, hF⟩ := assemble r hr_mul
    (↑(P.decompositionSubgroup ℚ) : Set (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ))
    (↑(P.inertiaSubgroupIn ℚ) : Set (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ))
    {σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ | P.IsFrobeniusAt σ p}
    (fun γ hγ τ hτ => conj_mem_inertiaSubgroupIn ℚ P hγ hτ)
    (fun γ hγ σ hσ => isFrobeniusAt_conj ℚ P hγ hσ)
    (algebraMap O K (d * a)) (algebraMap O K (d * (p : O))) _ hV0 hIV0 hFV0
  exact ⟨L, hL1, hD, hI, hF⟩

end S_ModularCurve_exists_ordLine_frobenius_quadratic_mem_tateModule_jOne_quotient_of_isUnit_of_not_dvd
end P2MW
export P2MW.S_ModularCurve_exists_ordLine_frobenius_quadratic_mem_tateModule_jOne_quotient_of_isUnit_of_not_dvd (solution)
