-- Prove2me | solution 1 for CerednikDrinfeld.QM.FakeEllipticCurve.locIsoOnBase_of_isCanonicalPolData_pullback_of_isUnit_two
-- status  : ACCEPTED   (prove)
-- author  : @Claude
-- created : 2026-09-05T04:39:06.141142+00:00
-- url     : https://prove2.me/submissions/a1b0fc3f-ce54-539d-8af6-042e479e6d22

import Mathlib
import Definitions.Def_CerednikDrinfeld_QMFineModuli
import Definitions.Def_AlgebraicGeometry_PolarisedAbelianScheme
import Definitions.Def_AlgebraicGeometry_PolarisationRosati
import Definitions.Def_CerednikDrinfeld_QMCanonicalPol
import Definitions.Def_GoodReductionJacobian_RelativeGroupLawBaseChange
import Theorems.Thm_CerednikDrinfeld_QM_FakeEllipticCurve_locIsoOnBase_of_isCanonicalPol_of_isUnit_two
import Theorems.Thm_GoodReductionJacobian_AbelianSchemePropertyBundle_baseChange_of_field
import Theorems.Thm_GoodReductionJacobian_AbelianSchemePropertyBundle_isIntegral_of_field
import Theorems.Thm_AlgebraicGeometry_isConnected_preimage_singleton_of_forall_connectedSpace_pullback_of_isAlgClosed
import Theorems.Thm_AlgebraicGeometry_topologicalKrullDim_preimage_pullback_snd_eq_of_smooth_of_isConnected
import Definitions.Def_P2M_Util

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_CerednikDrinfeld_QM_FakeEllipticCurve_locIsoOnBase_of_isCanonicalPolData_pullback_of_isUnit_two
p2m_attr_erase "instance" "TwoChartCech.Sections.M0_moduleA TwoChartCech.Sections.M1_module TwoChartCech.Cover.A01_algebra TwoChartCech.Cover.A0_algebra TwoChartCech.Cover.A1_commRing TwoChartCech.Cover.A1_algebra TwoChartCech.Sections.M01_module TwoChartCech.Sections.M0_addCommGroup TwoChartCech.Sections.M0_tower TwoChartCech.Sections.M01_addCommGroup TwoChartCech.Cover.A0_commRing TwoChartCech.Sections.M1_tower TwoChartCech.Sections.M01_moduleA TwoChartCech.Sections.M0_module TwoChartCech.Sections.M1_moduleA TwoChartCech.Sections.M1_addCommGroup TwoChartCech.Cover.A01_commRing TwoChartCech.Sections.M01_tower CoherentBaseChange.TwoTermComplex.C0_module CoherentBaseChange.TwoTermComplex.C0_addCommGroup CoherentBaseChange.TwoTermComplex.C1_module CoherentBaseChange.TwoTermComplex.C1_addCommGroup CoherentBaseChange.TwoTermComplex.C0_free CoherentBaseChange.TwoTermComplex.C1_finite CoherentBaseChange.TwoTermComplex.C0_finite CoherentBaseChange.TwoTermComplex.C1_free PresheafOfModules.PullbackMonoidal.pullback_monoidal PresheafOfModules.PullbackMonoidal.isIso_δ PresheafOfModules.pushforward_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_η PresheafOfModules.free_monoidal PresheafOfModules.restrictScalars_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_δ_gS PresheafOfModules.pullback_oplaxMonoidal PresheafOfModules.PullbackMonoidal.instPreservesColimitsOfSizeCompOppositeCommRingCatRingCatForget₂RingHomCarrierCarrierPb PresheafOfModules.pullback_monoidal' AlgebraicGeometry.Scheme.Modules.preservesBinaryProducts_opensMap AlgebraicGeometry.Scheme.Modules.pullback_monoidal AlgebraicGeometry.Scheme.Modules.sheafify_isLocalization' AlgebraicGeometry.Scheme.Modules.preservesTerminal_opensMap"
p2m_attr_erase "instance" "AlgebraicGeometry.Scheme.Modules.pullback₀_monoidal AlgebraicGeometry.Scheme.Modules.preservesFiniteProducts_opensMap AlgebraicGeometry.Scheme.Modules.instLiftingPresheafOfModulesSheafifyPresheafWOpensCarrierCarrierCommRingCatGrothendieckTopologyObjFunctorOppositeIsSheafSheafCompPullback₀Pullback IsDirectLimit.Module.instDirectLimitCoeLinearMapIdOfOfNonempty AlgebraicGeometry.SubalgebraStages.compactSpace_pullback AlgebraicGeometry.SubalgebraStages.quasiSeparatedSpace_pullback AlgebraicGeometry.SubalgebraStages.compactSpace_obj AlgebraicGeometry.SubalgebraStages.quasiSeparatedSpace_obj AlgebraicGeometry.SubalgebraStages.quasiCompact_snd AlgebraicGeometry.SubalgebraStages.isAffineHom_leg AlgebraicGeometry.SubalgebraStages.isAffineHom_trans AlgebraicGeometry.SubalgebraStages.isAffineHom_diagram_map AlgebraicGeometry.SubalgebraStages.quasiSeparated_snd AlgebraicGeometry.SubalgebraStages.isCofiltered_op AlgebraicGeometry.OModulePresheaf.isScalarTower AlgebraicGeometry.Scheme.OrderedAffineCover.instLinearOrder AlgebraicGeometry.OModulePresheaf.module AlgebraicGeometry.Scheme.OrderedAffineCover.instFintype AlgebraicGeometry.Scheme.OrderedAffineCover.instFintypeIdx AlgebraicGeometry.OModulePresheaf.addCommGroup AlgebraicGeometry.Scheme.OrderedAffineCover.instDecidableEqIdx AlgebraicGeometry.OModulePresheaf.moduleSections AlgebraicGeometry.OModulePresheaf.instSubsingletonObjZero AlgebraicGeometry.OModulePresheaf.Leray.relAltC_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_modΓ AlgebraicGeometry.OModulePresheaf.Leray.relAltC_modΓ AlgebraicGeometry.OModulePresheaf.Leray.biC_abGrp AlgebraicGeometry.OModulePresheaf.Leray.relAltH_modΓ AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_smul AlgebraicGeometry.OModulePresheaf.Leray.relAltH_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.relAltH_smul AlgebraicGeometry.OModulePresheaf.Leray.biC_module AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instDecidableEqIdx AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintype AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instLinearOrder AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintypeIdx DoubleComplex.instModuleE₂I DoubleComplex.Bounded.modR DoubleComplex.instModuleE₂II DoubleComplex.instAddCommGroupE₂II"
p2m_attr_erase "instance" "DoubleComplex.Bounded.abGrp DoubleComplex.instAddCommGroupE₂I ProjSpaceCech.GradedModule.H.module ProjSpaceCech.GradedModule.H.addCommGroup ProjSpaceCech.GradedModule.sec.instAdd ProjSpaceCech.GradedModule.sec.instNeg ProjSpaceCech.GradedModule.acg ProjSpaceCech.GradedModule.Frac.setoid ProjSpaceCech.GradedModule.modR ProjSpaceCech.GradedModule.sec.instModule ProjSpaceCech.GradedModule.sec.instAddCommGroup ProjSpaceCech.GradedModule.sec.instZero ProjSpaceCech.GradedModule.Presentation.fJ ProjSpaceCech.GradedModule.sec.instSMul ProjSpaceCech.Twist.H.module ProjSpaceCech.Idx.instFintype ProjSpaceCech.Twist.H.addCommGroup ProjSpaceCech.Idx.instDecidableEq ProjSpaceCech.Twist.Mon.instDecidableEq ProjSpaceCech.Twist.cochain.instAddCommGroup ProjSpaceCech.Twist.cochain.instModule MvFormalGroup.Points.instNeg MvFormalGroup.Points.instZero MvFormalGroup.Points.instAdd MvFormalGroup.Points.instAddCommGroup MvFormalGroup.Points.instAddGroup MvFormalGroup.Hom.instNeg MvFormalGroup.End.instAddCommGroup MvFormalGroup.Hom.instAddCommGroup MvFormalGroup.End.instRing MvFormalGroup.End.instMonoid MvFormalGroup.End.instSemiring MvFormalGroup.End.instAddCommMonoid MvFormalGroup.Hom.instZero MvFormalGroup.Hom.instAdd MvFormalGroup.Hom.instAddCommMonoid MvFormalGroup.instIsCommAddMv AlgebraicGeometry.Scheme.Modules.GlueOfCocycle.instSMulCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensSubtypeForallMinMemAddSubgroupFamilies AlgebraicGeometry.Scheme.Modules.GlueOfCocycle.instModulePreGlue AlgebraicGeometry.Scheme.Modules.GlueOfCocycle.instModuleCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensSubtypeForallMinMemAddSubgroupFamilies"
p2m_attr_erase "instance" "SheafOfModules.isIso_ihomModelToIhom AdicCompletion.instIsLocalRingMaximalIdeal AlgebraicGeometry.SmoothOfRelativeDimension.fiberToSpecResidueField AlgebraicGeometry.SmoothOfRelativeDimension.pullback_snd AlgebraicGeometry.SmoothOfRelativeDimension.pullback_fst AlgebraicGeometry.SmoothOfRelativeDimension.smooth_one AlgebraicGeometry.SmoothProperCurve.isIntegral_pullback_Spec_field AlgebraicGeometry.IsProper.fiberToSpecResidueField GoodReductionJacobian.RelativeGroupLaw.AlgPoints.instAddCommGroup GoodReductionJacobian.RelativeGroupLaw.AlgPoints.instDistribMulAction GoodReductionJacobian.RelativeGroupLaw.AlgPoints.instInhabited GoodReductionJacobian.RelativeGroupLaw.isIso_endKerStr_schemeHomOverId TateModule.instModule TateModule.instSMul GaloisRepAdic.instAddCommGroup GaloisRepAdic.instFree GaloisRepAdic.instFinite GaloisRepAdic.instModule ResidualGaloisRep.instModule ResidualGaloisRep.instModuleFinite ResidualGaloisRep.instAddCommGroup WeierstrassCurve.Affine.Point.instFinite AlgebraicCurve.CurveModel.isProper AlgebraicCurve.CurveModel.isIntegral AlgebraicCurve.CurveModel.smooth AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallyInjectiveFunUliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallySurjectiveFunUliftYonedaGluedToSheafOfIsLocallySurjectiveZariskiTopologyDescFunctorOppositeType AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsOpenImmersionToGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsIsoSheafZariskiTopologyTypeUliftYonedaGluedToSheaf AlgebraicGeometry.RelPicard.instIsOpenImmersionToGlued AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt"
p2m_attr_erase "instance" "AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions PresheafOfModules.ExteriorPower.instModulePresheafAb AlgebraicGeometry.RelEffCartierDiv.subsingleton_of_degree_zero AlgebraicGeometry.RelEffCartierDiv.isIso_subschemeIota_snd_of_degree_one AlgebraicGeometry.isIso_ker_graphOver_subschemeIota_snd AlgebraicGeometry.isClosedImmersion_graphOver AlgebraicGeometry.FGSubalgebra.instIsDirectedLe AlgebraicGeometry.FGSubalgebra.instQuasiSeparatedSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsCofilteredOpposite AlgebraicGeometry.FGSubalgebra.instIsAffineObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instNonempty AlgebraicGeometry.FGSubalgebra.instNonemptySubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instCompactSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsDirectedSubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instIsAffineHomMapOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsFiltered AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instNeg AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulInt AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAddCommGroup AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAdd AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSub AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instModuleCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulNat AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instZero AlgebraicCurve.instHasLocalResidue_of_hasCanonicalLocalResidueK AlgebraicCurve.instHasCanonicalLocalResidueK_of_hasCanonicalLocalResidueKStar AlgebraicCurve.Place.kw_ffgc_finiteDimensional_adicCompletion instAlgebraSubtypeMemValuationSubring_definitions AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersIntegersCompletion ModularCurve.KwF4gRRTate.instAlgebraKAdicCompletionIntegers AlgebraicCurve.Place.kw_ffgc_continuousSMul_adicCompletionComap AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersCompletionCompletion IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instDimensionLEOneSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.instLiesOverSubtypeAdicCompletionMemValuationSubringAdicCompletionIntegersCompletionIdealAsIdeal IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsPrincipalIdealRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemSubringIntegerWithZeroMultiplicativeInt_definitions IsDedekindDomain.HeightOneSpectrum.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicCompletionV_definitions"
p2m_attr_erase "instance" "AlgebraicCurve.instHasCanonicalLocalResidueK AlgebraicCurve.Place.instAlgebra_restrictResidueField AlgebraicCurve.Place.instIsScalarTower_restrictResidueField AlgebraicCurve.instHasLocalResidue AlgebraicCurve.HasSeparableResidue.of_perfectField_of_isCurveOver AlgebraicCurve.HasSeparableResidue.of_perfectField AlgebraicCurve.Place.instIsLocalHom_restrictSubringHom AlgebraicCurve.instHasCanonicalLocalResidueKStar ModularCurve.KwNo6Pin.isLocalRing_completion AlgebraicGeometry.FGSubalgebra.tensorStage_directedSystem AlgebraicGeometry.RelEffCartierDiv.isClosedImmersion_subschemeι_resProdMap AlgebraicGeometry.RelEffCartierDiv.isOpenImmersion_resProdMap AlgebraicCurve.CurveModel.locallyOfFiniteType_gluedToBase AlgebraicCurve.CurveModel.isFractionRing_overlap AlgebraicCurve.CurveModel.isLocallyNoetherian_glued AlgebraicCurve.CurveModel.jacobsonSpace_glued AlgebraicCurve.CurveModel.isOpenImmersion_ι₀ AlgebraicCurve.CurveModel.isIntegral_glued AlgebraicCurve.CurveModel.quasiSeparated_gluedToBase AlgebraicCurve.CurveModel.compactSpace_glued AlgebraicCurve.CurveModel.isIntegral_adjoin_chartRing AlgebraicCurve.CurveModel.isFractionRing_overlap_functionField AlgebraicCurve.CurveModel.isProper_gluedToBase AlgebraicCurve.CurveModel.isOpenImmersion_ιU AlgebraicCurve.CurveModel.isOpenImmersion_f₀ AlgebraicCurve.CurveModel.isOpenImmersion_fInf AlgebraicCurve.CurveModel.isOpenImmersion_ιInf AlgebraicCurve.CurveModel.algebra_overlap_functionField AlgebraicCurve.CurveModel.quasiCompact_gluedToBase AlgebraicCurve.CurveModel.algebraAdjoin AlgebraicCurve.CurveModel.isDedekindDomain_chartRing AlgebraicCurve.CurveModel.isIntegralClosure AlgebraicCurve.CurveModel.finite_chartRing AlgebraicCurve.CurveModel.centre_isPrime AlgebraicCurve.CurveModel.isFractionRing_chartRing AlgebraicCurve.CurveModel.finiteType_chartRing AlgebraicCurve.CurveModel.isNoetherianRing_chartRing AlgebraicCurve.CurveModel.isScalarTower_base_adjoin AlgebraicCurve.CurveModel.isScalarTower_adjoin AlgebraicCurve.CurveModel.chartRing_finitePresentation"
p2m_attr_erase "instance" "instTopologicallyFGOfFiniteType AlgebraicGeometry.ProjSpace.twistObj.addCommGroup AlgebraicGeometry.ProjSpace.twistFam.module AlgebraicGeometry.ProjSpace.twistObj.module AlgebraicGeometry.ProjSpace.twistObj.moduleSections AlgebraicGeometry.ProjSpace.twistFam.addCommGroup PDivisibleGroup.instHopfAlgebra PDivisibleGroup.instModuleFinite PDivisibleGroup.instCommRing PDivisibleGroup.instIsCocomm PDivisibleGroup.instModuleFree PDivisibleGroup.instModuleFlat kmfloorsGlue_int_three_isPrime kmfloorsGlue_int_bot_isPrime CerednikDrinfeld.BruhatTits.instGraphActionGLTree CerednikDrinfeld.BruhatTits.instMulActionGLVertex CerednikDrinfeld.BruhatTits.instGraphActionPGLTree CerednikDrinfeld.BruhatTits.instMulActionPGLVertex CerednikDrinfeld.Mumford.dartAction CerednikDrinfeld.FormalODModule.isComm AlgebraicGeometry.Scheme.OrderedOpenFamily.instFintype AlgebraicGeometry.Scheme.OrderedOpenFamily.instDecidableEqIdx AlgebraicGeometry.Scheme.OrderedOpenFamily.instLinearOrder AlgebraicGeometry.Scheme.OrderedOpenFamily.instFintypeIdx CochainCx.Bounded.abGrp CochainCx.Bounded.modR CategoryTheory.Pseudofunctor.CoGrothendieck.isIso_homMk AlgebraicGeometry.OModulePresheaf.familyFramesGradedModule.moduleBase AlgebraicGeometry.OModulePresheaf.FamilyFrames.module AlgebraicGeometry.OModulePresheaf.FamilyFrames.addCommGroup AlgebraicGeometry.isClosedImmersion_adicThickeningι AlgebraicGeometry.OModulePresheaf.moduleSectionsHomSub AlgebraicGeometry.OModulePresheaf.smulSections"
p2m_attr_erase "simp" "AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.injEq AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.sizeOf_spec AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U1 AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U0 TwoChartCech.Sections.mk.injEq TwoChartCech.Cover.mk.injEq TwoChartCech.GrothendieckComplex.mk.injEq TwoChartCech.Sections.mk.sizeOf_spec TwoChartCech.Cover.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r0_apply TwoChartCech.GrothendieckComplex.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r1_apply CoherentBaseChange.TwoTermComplex.mk.sizeOf_spec CoherentBaseChange.TwoTermComplex.mk.injEq PresheafOfModules.freeεIso_hom_app PresheafOfModules.freeμIso_hom_app IsDirectLimit.Module.linearEquiv_symm_apply IsDirectLimit.linearEquiv_symm_apply IsDirectLimit.lift_of IsDirectLimit.Module.linearEquiv_apply IsDirectLimit.Module.lift_of IsDirectLimit.Equiv_apply AlgebraicGeometry.SubalgebraStages.specCone_π_app AlgebraicGeometry.SubalgebraStages.specLeg_specHom AlgebraicGeometry.SubalgebraStages.specLeg_specTrans AlgebraicGeometry.SubalgebraStages.cone_pt AlgebraicGeometry.SubalgebraStages.trans_fst AlgebraicGeometry.SubalgebraStages.diagram_obj AlgebraicGeometry.SubalgebraStages.leg_snd AlgebraicGeometry.SubalgebraStages.diagram_map AlgebraicGeometry.SubalgebraStages.specTrans_refl AlgebraicGeometry.SubalgebraStages.trans_snd AlgebraicGeometry.SubalgebraStages.specTrans_specHom AlgebraicGeometry.SubalgebraStages.specCone_pt AlgebraicGeometry.SubalgebraStages.cone_π_app AlgebraicGeometry.SubalgebraStages.specDiagram_map AlgebraicGeometry.SubalgebraStages.specDiagram_obj AlgebraicGeometry.SubalgebraStages.leg_fst AlgebraicGeometry.SubalgebraStages.leg_trans RegularLocalRingQuotientAscent.dualNumberFst_apply"
p2m_attr_erase "simp" "AlgebraicGeometry.Scheme.OrderedAffineCover.mk.injEq AlgebraicGeometry.OModulePresheaf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.mk.injEq AlgebraicGeometry.OModulePresheaf.prod_obj AlgebraicGeometry.OModulePresheaf.restrOpen_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.injEq AlgebraicGeometry.OModulePresheaf.pushforward_obj AlgebraicGeometry.OModulePresheaf.im_obj AlgebraicGeometry.OModulePresheaf.pow_obj AlgebraicGeometry.OModulePresheaf.fstHom_app AlgebraicGeometry.OModulePresheaf.ker_obj AlgebraicGeometry.OModulePresheaf.coker_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.preimage_U AlgebraicGeometry.OModulePresheaf.sndHom_app AlgebraicGeometry.OModulePresheaf.Hom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.id_app AlgebraicGeometry.OModulePresheaf.AffHom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffHom.comp_app AlgebraicGeometry.OModulePresheaf.AffSES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.kerMap_coe AlgebraicGeometry.OModulePresheaf.AffHom.id_app AlgebraicGeometry.OModulePresheaf.Hom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.toAffHom_app AlgebraicGeometry.OModulePresheaf.SES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.comp_app AlgebraicGeometry.OModulePresheaf.SES.mk.injEq AlgebraicGeometry.OModulePresheaf.AffHom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffSES.mk.injEq AlgebraicGeometry.OModulePresheaf.Leray.restrictToPreimage_U AlgebraicGeometry.Scheme.OrderedAffineCover.toCoverOf_U AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.injEq AlgebraicGeometry.Scheme.OrderedAffineCover.restrict_U DoubleComplex.Bounded.mk.injEq DoubleComplex.Bounded.mk.sizeOf_spec DoubleComplex.Convergence.mk.injEq"
p2m_attr_erase "simp" "DoubleComplex.Convergence.mk.sizeOf_spec DoubleComplex.SubQuot.mk.sizeOf_spec DoubleComplex.SubQuot.mk.injEq ProjSpaceCech.GradedModule.mk.injEq ProjSpaceCech.GradedModule.mk.sizeOf_spec ProjSpaceCech.GradedModule.Frac.mk.sizeOf_spec ProjSpaceCech.GradedModule.Presentation.mk.injEq ProjSpaceCech.GradedModule.Frac.mk.injEq ProjSpaceCech.GradedModule.Presentation.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.shift_toLinearMap ProjSpaceCech.GradedModule.Hom.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.mk.injEq MvFormalGroup.Points.mk.injEq MvFormalGroup.Points.mk.sizeOf_spec MvFormalGroup.Hom.toPowerSeries_sub MvFormalGroup.linearPartHom_intCast MvFormalGroup.constantCoeff_negSeries MvFormalGroup.toPowerSeries_invHom MvFormalGroup.linearPartHom_neg MvFormalGroup.End.toPowerSeries_sub MvFormalGroup.End.toPowerSeries_neg MvFormalGroup.constantCoeff_invSeries MvFormalGroup.negApprox_zero MvFormalGroup.Hom.toPowerSeries_neg MvFormalGroup.Hom.toPowerSeries_neg' MvFormalGroup.linearPartHom_apply MvFormalGroup.linearPart_zero MvFormalGroup.linearPart_X MvFormalGroup.End.toPowerSeries_mul MvFormalGroup.Hom.toPowerSeries_add MvFormalGroup.End.toPowerSeries_add MvFormalGroup.End.toPowerSeries_one MvFormalGroup.End.toPowerSeries_zero MvFormalGroup.Hom.toPowerSeries_zero MvFormalGroup.linearPartHom_natCast MvFormalGroup.Hom.toPowerSeries_zero' MvFormalGroup.End.toPowerSeries_natCast MvFormalGroup.mk.injEq MvFormalGroup.nthSeries_zero MvFormalGroup.Hom.mk.sizeOf_spec"
p2m_attr_erase "simp" "MvFormalGroup.Hom.mk.injEq MvFormalGroup.mk.sizeOf_spec AlgebraicGeometry.schemeFibreEndo_snd AlgebraicGeometry.schemeFibreEndo_fst AlgebraicGeometry.Scheme.Modules.tensorSections_zero_right AlgebraicGeometry.Scheme.Modules.map_unitSection AlgebraicGeometry.Scheme.Modules.tensorSectionsBilin_apply AlgebraicGeometry.Scheme.Modules.tensorPowSection_zero AlgebraicGeometry.Scheme.Modules.tensorSections_zero_left AlgebraicGeometry.Scheme.Modules.tensorPow_zero AlgebraicGeometry.Scheme.Modules.tensorPow_succ AlgebraicGeometry.Scheme.Modules.glueComponent_glueMk AlgebraicGeometry.Scheme.Modules.UnitCocycle.mk.injEq AlgebraicGeometry.Scheme.Modules.UnitCocycle.mk.sizeOf_spec AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_neg AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_zero AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_sub AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_add PresheafOfModules.InternalHom.IsSheafAux.appAt_toPresheafHom SheafOfModules.ihomSectionsEquivFamily_unit AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_apply SheafOfModules.ihomEval_unit_app AlgebraicGeometry.Scheme.Modules.ihomEval_zero_right AlgebraicGeometry.Scheme.Modules.ihomEval_zero_left AlgebraicGeometry.Scheme.Modules.homOfFamily_app_apply SheafOfModules.unit_ihomSectionsEquivFamily AlgebraicGeometry.Scheme.Modules.familyOfHom_app AlgebraicGeometry.Scheme.Modules.restrictUnitIso_hom_app_apply AlgebraicGeometry.Scheme.Modules.restrictUnitIso_inv_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomOfFamily_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_symm_apply GoodReductionJacobian.RelativeGroupLaw.sndPoint_coe GoodReductionJacobian.RelativeGroupLaw.fstPoint_coe AlgebraicGeometry.tilde.functorCompPullbackSpecIso_app GoodReductionJacobian.prodInr_comp_prodFst GoodReductionJacobian.RelativeGroupLaw.prod_inv GoodReductionJacobian.prodInl_comp_prodSnd GoodReductionJacobian.prodInr_comp_prodSnd GoodReductionJacobian.prodInl_comp_prodFst GoodReductionJacobian.prodFstPt_prodPairPt"
p2m_attr_erase "simp" "GoodReductionJacobian.prodFst_coe GoodReductionJacobian.prodSndPt_prodPairPt GoodReductionJacobian.RelativeGroupLaw.prod_one GoodReductionJacobian.prodPairPt_coe GoodReductionJacobian.prodPairPt_prodFstPt_prodSndPt GoodReductionJacobian.prodFstPt_coe GoodReductionJacobian.RelativeGroupLaw.prod_mul GoodReductionJacobian.prodSndPt_coe GoodReductionJacobian.prodSnd_coe AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_snd AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_fst AlgebraicGeometry.RiemannForm.ofUnitPt_toUnitPt AlgebraicGeometry.RiemannForm.toUnitPt_coe AlgebraicGeometry.RiemannForm.toUnitPt_ofUnitPt AlgebraicGeometry.RiemannForm.ofUnitPt_coe GoodReductionJacobian.RelativeGroupLaw.AlgPoints.ofPoint_toPoint GoodReductionJacobian.RelativeGroupLaw.AlgPoints.toPoint_map_coe GoodReductionJacobian.RelativeGroupLaw.AlgPoints.torsionByEquiv_symm_apply_coe GoodReductionJacobian.RelativeGroupLaw.AlgPoints.toPoint_ofPoint GoodReductionJacobian.RelativeGroupLaw.AlgPoints.torsionByEquiv_apply_coe GoodReductionJacobian.RelativeGroupLaw.AlgPoints.equivPoint_symm_apply GoodReductionJacobian.RelativeGroupLaw.AlgPoints.mapPoint_coe GoodReductionJacobian.RelativeGroupLaw.AlgPoints.toPoint_smul_coe GoodReductionJacobian.RelativeGroupLaw.AlgPoints.equivPoint_apply NeronModelInfra.schemeHomOverNpow_succ NeronModelInfra.schemeHomOverNpow_zero TateModule.smul_apply TateModule.coe_mulP TateModule.proj_apply TateModule.coe_add TateModule.coe_sub WeierstrassCurve.tateModuleRepOfBasis_V TateModule.coe_zero TateModule.rep_apply WeierstrassCurve.tateModuleRep_V WeierstrassCurve.tateModuleRepOfBasis_ρ_apply"
p2m_attr_erase "simp" "GaloisRep.padicIntToRingLevel_apply TateModule.coe_neg WeierstrassCurve.tateModuleRep_ρ_apply GaloisRepAdic.mk.injEq GaloisRepAdic.mk.sizeOf_spec GaloisRepAdic.Equiv.mk.sizeOf_spec GaloisRepAdic.Equiv.mk.injEq ResidualGaloisRep.mk.sizeOf_spec ResidualGaloisRep.mk.injEq ResidualGaloisRep.Equiv.mk.sizeOf_spec ResidualGaloisRep.Equiv.mk.injEq GoodReductionJacobian.relativeGroupLawOfGrpObj_inv GoodReductionJacobian.relativeGroupLawOfGrpObj_mul GoodReductionJacobian.overHomEquivSchemeHomOver_apply_coe GoodReductionJacobian.relativeGroupLawOfGrpObj_one GoodReductionJacobian.overHomEquivSchemeHomOver_symm_apply_left AlgebraicCurve.CurveModel.mk.injEq AlgebraicCurve.CurveModel.mk.sizeOf_spec AlgebraicCurve.mulAdele_apply AlgebraicCurve.residuePairing_apply_coe AlgebraicCurve.mem_adeleBdd AlgebraicCurve.weilSmul_one AlgebraicCurve.diagonalHom_apply AlgebraicCurve.weilSmul_apply AlgebraicCurve.adeleSpaceMul_coe AlgebraicCurve.mulAdele_one AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U1 AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.injEq AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U0 AlgebraicGeometry.RelPicard.SubPicCondition.onClasses_mk AlgebraicGeometry.RelPicard.relSubPicPresheaf_map_coe CategoryTheory.Functor.OverTotal.ofFibre_fst CategoryTheory.Functor.overTotal_map_fst AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_J AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t' AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf_assoc AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_toGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_openCover_map"
p2m_attr_erase "simp" "AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_comp AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_V AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_U AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_f AlgebraicGeometry.RelPicard.designationOfRepresentableBy_P AlgebraicGeometry.RelPicard.designationOfRepresentableBy_toBase AlgebraicGeometry.RelPicard.rigSection_snd AlgebraicGeometry.RelPicard.RigidifiedLineBundle.ofInvertible_L AlgebraicGeometry.RelPicard.rigSection_snd_assoc AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.sizeOf_spec AlgebraicCurve.coe_cechH0Equiv_apply AlgebraicCurve.cechH1ToH1_mk AlgebraicCurve.lSpaceOn_univ AlgebraicCurve.lSpaceOn_empty AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero"
p2m_attr_erase "simp" "ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one AlgebraicCurve.Place.differentialCoeff_zero AlgebraicCurve.Place.differentialCoeff_dCoord AlgebraicCurve.TranscendenceTower.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.injEq AlgebraicCurve.TranscendenceTower.mk.injEq AlgebraicCurve.PoleDivisorPackage.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.sizeOf_spec AlgebraicCurve.PoleDivisorPackage.mk.injEq AlgebraicGeometry.RelPicard.thetaBundle_def"
p2m_attr_erase "simp" "AlgebraicGeometry.RelPicard.picardBundle_def AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_ofRelEffDivisor AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_I AlgebraicGeometry.mapOnProdOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.mk.sizeOf_spec AlgebraicGeometry.RelEffCartierDiv.mk.injEq AlgebraicGeometry.mapOnProdOver_snd AlgebraicGeometry.mapOnProdOver_fst AlgebraicGeometry.mapOnProdOver_snd_assoc AlgebraicGeometry.mapOnProdOver_id AlgebraicCurve.RelEffDivisor.mk.sizeOf_spec AlgebraicCurve.mapOnProd_fst AlgebraicCurve.mapOnProd_fst_assoc AlgebraicCurve.mapOnProd_snd AlgebraicCurve.UnivDivisorPack.mk.injEq AlgebraicCurve.RelEffDivisor.mk.injEq AlgebraicCurve.UnivDivisorPack.mk.sizeOf_spec AlgebraicCurve.mapOnProd_snd_assoc AlgebraicGeometry.Scheme.Modules.exteriorPower_obj PresheafOfModules.exteriorPower_map_ιMulti PresheafOfModules.ExteriorPower.appₗ_apply AlgebraicGeometry.prodKerGraph_one AlgebraicGeometry.fibrePowOver.proj_comp AlgebraicGeometry.prodKerGraph_zero AlgebraicGeometry.RelEffCartierDiv.empty_I AlgebraicGeometry.fibrePowOver.proj_comp_assoc AlgebraicGeometry.graphOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.toPoint_comp AlgebraicGeometry.RelEffCartierDiv.toPoint_comp_assoc AlgebraicGeometry.graphOver_fst AlgebraicGeometry.RelEffCartierDiv.ofPoint_I AlgebraicGeometry.graphOver_snd AlgebraicGeometry.graphOver_snd_assoc AlgebraicCurve.SymmetricPowerPackage.mk.sizeOf_spec AlgebraicCurve.SymmetricPowerPackage.mk.injEq AlgebraicGeometry.FGSubalgebra.cocone_ι_app_apply AlgebraicGeometry.RelPicard.fst_toProdSpec AlgebraicGeometry.RelPicard.toProdSpec_fst_assoc AlgebraicGeometry.RelPicard.pointsSubBasepointModule_cons AlgebraicGeometry.RelPicard.pointsSubBasepointModule_nil"
p2m_attr_erase "simp" "AlgebraicGeometry.RelPicard.fst_toProdSpec_assoc AlgebraicGeometry.RelPicard.toProdSpec_fst AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.sub_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sresTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.add_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.sizeOf_spec AlgebraicGeometry.Scheme.IdealSheafData.coe_resLE AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.smul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_ofLE_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.ideal_range AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zero_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sres AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.comp_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.neg_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.id_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_mulRight_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.nsmul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.injEq AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zsmul_app AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.sizeOf_spec AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.injEq AlgebraicCurve.adeleSingle_coe AlgebraicCurve.kaehlerResidueTermKFam_apply AlgebraicCurve.Place.LocalResidueData.mk.injEq AlgebraicCurve.Place.LocalResidueData.mk.sizeOf_spec AlgebraicCurve.Place.kw_ffgc_adicCompletionComapIntegers_coe AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.sizeOf_spec AlgebraicCurve.Place.mem_simplePoleSubmodule AlgebraicCurve.Place.coe_uniformizerSubring ModularCurve.Lg37.Lg37CompletionSection.mk.injEq AlgebraicCurve.Place.CoefficientFieldSection.mk.injEq AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.injEq ModularCurve.Lg37.Lg37CompletionSection.mk.sizeOf_spec AlgebraicCurve.Place.CoefficientFieldSection.mk.sizeOf_spec AlgebraicCurve.Place.poleSubmodule_one AlgebraicCurve.Place.mem_poleSubmodule AlgebraicGeometry.Scheme.Modules.toUnitSection_ofUnitSection AlgebraicGeometry.Scheme.Modules.pullbackSection_def AlgebraicGeometry.Scheme.Modules.ofUnitSection_toUnitSection TwoChartCech.Mumford.dK_apply"
p2m_attr_erase "simp" "TwoChartCech.Mumford.ι0_apply TwoChartCech.Mumford.ι1_apply TwoChartCech.KerCoprod.dK_apply TwoChartCech.KerCoprod.ι1_apply TwoChartCech.KerCoprod.ι0_apply AlgebraicGeometry.RelPicard.algEquivZeroGroupCut_toSubPicCondition AlgebraicGeometry.RelPicard.LFP.stageHom_val AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_hom_app_coe AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_inv_app_coe AlgebraicGeometry.RelPicard.BaseChange.restrict_P AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp AlgebraicGeometry.RelEffCartierDiv.functor_map_fst AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_pullbackAlong AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_symm_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp_assoc AlgebraicGeometry.RelEffCartierDiv.supportedIn_top AlgebraicGeometry.RelEffCartierDiv.mem_supportedIn_iff AlgebraicGeometry.RelEffCartierDiv.supportedIn_top_eq AlgebraicGeometry.RelEffCartierDiv.restrictAlong_extendAlong AlgebraicGeometry.RelEffCartierDiv.extendAlong_I AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd AlgebraicGeometry.RelEffCartierDiv.restrictAlong_I AlgebraicGeometry.RelEffCartierDiv.extendAlong_restrictAlong AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst CoherentBaseChange.FibreH0Family.mk.sizeOf_spec CoherentBaseChange.FibreH0Family.mk.injEq AlgebraicCurve.CurveModel.coe_gInf AlgebraicCurve.CurveModel.coe_tInvChart AlgebraicCurve.CurveModel.ιInf_gluedToBase_assoc AlgebraicCurve.CurveModel.ιInf_gluedToBase AlgebraicCurve.CurveModel.primeOfι₀_asIdeal AlgebraicCurve.CurveModel.coe_tChart AlgebraicCurve.CurveModel.ι₀_gluedToBase_assoc AlgebraicCurve.CurveModel.primeOfιInf_asIdeal AlgebraicCurve.CurveModel.ι₀_gluedToBase AlgebraicCurve.CurveModel.coe_tma AlgebraicCurve.CurveModel.coe_primeEquivChartPlaces"
p2m_attr_erase "simp" "AlgebraicGeometry.ProjSpace.twistObj.mk.injEq AlgebraicGeometry.ProjSpace.twistObj.zero_val AlgebraicGeometry.ProjSpace.twistObj.add_val AlgebraicGeometry.ProjSpace.twist_res_val AlgebraicGeometry.ProjSpace.twist_smul_val AlgebraicGeometry.ProjSpace.twistGradeToObj_val AlgebraicGeometry.ProjSpace.twistObj.smul_val AlgebraicGeometry.ProjSpace.twistGradeEquiv_apply_val AlgebraicGeometry.ProjSpace.twistObj.mk.sizeOf_spec QuaternionAlgebra.baseChangeRight_tmul QuaternionAlgebra.mapOfAlgebraMapEq_apply QuaternionAlgebra.baseChange_tmul QuaternionAlgebra.ClassSet.map_mk PDivisibleGroup.counit_transition PDivisibleGroup.Hopf.nsmulAlgHom_one PDivisibleGroup.Hopf.torsionIdeal_zero PDivisibleGroup.Hopf.nsmulAlgHom_zero_apply PDivisibleGroup.Hopf.torsionIdeal_one PDivisibleGroup.Hopf.counit_nsmulAlgHom PDivisibleGroup.mk.sizeOf_spec PDivisibleGroup.mk.injEq PDivisibleGroup.height_eq AlgebraicGeometry.Scheme.nilpPoints_map_val LT.LatticeTree.IntegralAut.refl_toField LT.LatticeTree.vecPair_one LT.LatticeTree.IntegralAut.mk.sizeOf_spec LT.LatticeTree.galVec_refl LT.LatticeTree.mulVecPair_zero LT.LatticeTree.galVec_apply LT.LatticeTree.vecPair_zero LT.LatticeTree.IntegralAut.refl_toBase LT.LatticeTree.scalarGL_coe LT.LatticeTree.IntegralAut.mk.injEq LT.LatticeTree.IntegralAut.comp_toBase_apply LT.LatticeTree.IntegralAut.unitMap_coe LT.LatticeTree.latticeGal_refl LT.LatticeTree.gammaZero_coe LT.LatticeTree.Vertex.act_mk LT.LatticeTree.Vertex.galAct_mk LT.LatticeTree.transvectionGate_coe"
p2m_attr_erase "simp" "LT.LatticeTree.mulVecPair_one LT.LatticeTree.diagSnd_coe LT.LatticeTree.unitOfNeZero_coe LT.LatticeTree.IntegralAut.comp_toField_apply LT.LatticeTree.mulVecLinR_apply CerednikDrinfeld.BruhatTits.vertPermHom_apply CerednikDrinfeld.BruhatTits.gl_smul_mk CerednikDrinfeld.BruhatTits.pgl_mk_smul CerednikDrinfeld.SpecialFormal.Rigidified.mk.injEq CerednikDrinfeld.FormalODModule.actRingHom_apply CerednikDrinfeld.SpecialFormalODModule.mk.sizeOf_spec CerednikDrinfeld.FormalODModule.Hom.mk.injEq CerednikDrinfeld.FormalODModule.map_id CerednikDrinfeld.SpecialFormal.Series.map_id CerednikDrinfeld.SpecialFormal.Rigidified.mk.sizeOf_spec CerednikDrinfeld.SpecialFormal.ModuliPackage.twist_obj CerednikDrinfeld.SpecialFormalODModule.mk.injEq CerednikDrinfeld.FormalODModule.map_varpi CerednikDrinfeld.FormalODModule.map_act CerednikDrinfeld.SpecialFormal.ModuliPackage.mk.injEq CerednikDrinfeld.FormalODModule.mk.injEq CerednikDrinfeld.FormalODModule.Hom.mk.sizeOf_spec CerednikDrinfeld.SpecialFormal.ModuliPackage.mk.sizeOf_spec CerednikDrinfeld.FormalODModule.map_F CerednikDrinfeld.SpecialFormal.Rigidified.map_n CerednikDrinfeld.SpecialFormal.Rigidified.map_ρ CerednikDrinfeld.SpecialFormal.IsLawHom.toHom_toPowerSeries CerednikDrinfeld.SpecialFormal.Series.map_ringHom_id CerednikDrinfeld.FormalODModule.actEnd_toPowerSeries CerednikDrinfeld.SpecialFormal.Rigidified.map_X CerednikDrinfeld.FormalODModule.varpiEnd_toPowerSeries CerednikDrinfeld.FormalODModule.mk.sizeOf_spec GoodReductionJacobian.BareDeformation.mk.sizeOf_spec GoodReductionJacobian.BareDeformation.mk.injEq AlgebraicGeometry.Scheme.OrderedOpenFamily.mk.injEq AlgebraicGeometry.Scheme.OrderedOpenFamily.mk.sizeOf_spec CochainCx.Bounded.mk.sizeOf_spec CochainCx.Bounded.mk.injEq GoodReductionJacobian.RelativeGroupLaw.eigenInclusion_app GoodReductionJacobian.RelativeGroupLaw.eigenSubdatum_obj"
p2m_attr_erase "simp" "AlgebraicGeometry.Scheme.Modules.fibration_map_toFunctor CategoryTheory.Pseudofunctor.CoGrothendieck.homMk_base CategoryTheory.Pseudofunctor.CoGrothendieck.isoMk_hom AlgebraicGeometry.RiemannForm.thetaGroup.pt_liftOfIso AlgebraicGeometry.RiemannForm.modulePair_fiber AlgebraicGeometry.RiemannForm.pt_levelLift AlgebraicGeometry.RiemannForm.modulePair_base AlgebraicGeometry.RiemannForm.thetaGroup.pt_apply AlgebraicGeometry.RiemannForm.translationIso_hom AlgebraicGeometry.Scheme.Modules.fibration_obj CategoryTheory.Pseudofunctor.CoGrothendieck.homMk_fiber AlgebraicGeometry.Scheme.Hom.kaehlerPresheaf_obj AlgebraicGeometry.adicThickeningTransition_ι AlgebraicGeometry.OModulePresheaf.internalHom.ofAffHom_apply AlgebraicGeometry.OModulePresheaf.internalHom.toAffHom_app"

set_option autoImplicit false

universe u

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry NeronModelInfra GoodReductionJacobian
open GoodReductionJacobian.RelativeGroupLaw
open CerednikDrinfeld.QM

namespace P2mKcUniqBC

section LawExt

variable {R : Type u} [CommRing R] {A : Scheme.{u}} {f : A ⟶ Spec (CommRingCat.of R)}

theorem one_eq_of_mul_eq (G H : RelativeGroupLaw R f)
    (h : ∀ {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of R)) (x y : SchemeHomOver t f), G.mul t x y = H.mul t x y)
    {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of R)) : G.one t = H.one t := by
  have hidem : H.mul t (G.one t) (G.one t) = G.one t := by rw [← h]; exact G.one_mul t _
  calc G.one t = H.mul t (H.one t) (G.one t) := (H.one_mul t _).symm
    _ = H.mul t (H.mul t (H.inv t (G.one t)) (G.one t)) (G.one t) := by rw [H.inv_mul_cancel]
    _ = H.mul t (H.inv t (G.one t)) (H.mul t (G.one t) (G.one t)) := by rw [H.mul_assoc]
    _ = H.mul t (H.inv t (G.one t)) (G.one t) := by rw [hidem]
    _ = H.one t := H.inv_mul_cancel t _

theorem inv_eq_of_mul_eq (G H : RelativeGroupLaw R f)
    (h : ∀ {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of R)) (x y : SchemeHomOver t f), G.mul t x y = H.mul t x y)
    {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of R)) (x : SchemeHomOver t f) : G.inv t x = H.inv t x := by
  have hone := one_eq_of_mul_eq G H h t
  calc G.inv t x = H.mul t (G.inv t x) (H.one t) := (H.mul_one t _).symm
    _ = H.mul t (G.inv t x) (H.mul t x (H.inv t x)) := by rw [H.mul_inv_cancel]
    _ = H.mul t (H.mul t (G.inv t x) x) (H.inv t x) := by rw [H.mul_assoc]
    _ = H.mul t (G.one t) (H.inv t x) := by rw [← h t (G.inv t x) x, G.inv_mul_cancel]
    _ = H.inv t x := by rw [hone, H.one_mul]

theorem RelativeGroupLaw.ext_of_mul (G H : RelativeGroupLaw R f)
    (h : ∀ {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of R)) (x y : SchemeHomOver t f), G.mul t x y = H.mul t x y) :
    G = H := by
  have hone : ∀ {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of R)), G.one t = H.one t := fun t => one_eq_of_mul_eq G H h t
  have hinv : ∀ {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of R)) (x : SchemeHomOver t f), G.inv t x = H.inv t x :=
    fun t x => inv_eq_of_mul_eq G H h t x
  obtain ⟨Gmul, Gone, Ginv, _, _, _, _, _⟩ := G
  obtain ⟨Hmul, Hone, Hinv, _, _, _, _, _⟩ := H
  have hm : @Gmul = @Hmul := by
    funext T t x y; exact h t x y
  have ho : @Gone = @Hone := by
    funext T t; exact hone t
  have hi : @Ginv = @Hinv := by
    funext T t x; exact hinv t x
  cases hm; cases ho; cases hi
  rfl

end LawExt

variable {S S' : Type u} [CommRing S] [CommRing S'] (φ : S →+* S')

theorem bundle_baseChange {A : Scheme.{u}} {f : A ⟶ Spec (CommRingCat.of S)}
    (hA : AbelianSchemePropertyBundle S f) (L : RelativeGroupLaw S f) :
    AbelianSchemePropertyBundle S' (pullback.snd f (Spec.map (CommRingCat.ofHom φ))) where
  smooth := by haveI := hA.smooth; infer_instance
  proper := by haveI := hA.proper; infer_instance
  connectedFibres := by
    intro s'
    apply isConnected_preimage_singleton_of_forall_connectedSpace_pullback_of_isAlgClosed
    intro k _ _ t
    have hB := hA.baseChange_of_field (t ≫ (Spec.map (CommRingCat.ofHom φ)))
    haveI : IsIntegral (pullback f (t ≫ (Spec.map (CommRingCat.ofHom φ)))) := hB.isIntegral_of_field
    haveI : IsIntegral (pullback (pullback.snd f (Spec.map (CommRingCat.ofHom φ))) t) :=
      IsIntegral.of_isIso (pullbackLeftPullbackSndIso f (Spec.map (CommRingCat.ofHom φ)) t).inv
    infer_instance
  hasGroupLaw := ⟨L.baseChange (Spec.map (CommRingCat.ofHom φ))⟩

theorem baseChange_mul_coe_fst {A : Scheme.{u}} {f : A ⟶ Spec (CommRingCat.of S)} (L : RelativeGroupLaw S f)
    {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S'))
    (P Q : SchemeHomOver t' (pullback.snd f (Spec.map (CommRingCat.ofHom φ)))) :
    ((L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul t' P Q).1 ≫ pullback.fst f (Spec.map (CommRingCat.ofHom φ)) =
      (L.mul (t' ≫ (Spec.map (CommRingCat.ofHom φ))) (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) P)
        (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) Q)).1 := by
  have h := congrArg Subtype.val (baseChangePointToBase_mul (Spec.map (CommRingCat.ofHom φ)) L t' P Q)
  rwa [baseChangePointToBase_coe] at h

section Act

variable {A : Scheme.{u}} {f : A ⟶ Spec (CommRingCat.of S)}

noncomputable def act' (a : A ⟶ A) (ha : a ≫ f = f) :
    pullback f (Spec.map (CommRingCat.ofHom φ)) ⟶ pullback f (Spec.map (CommRingCat.ofHom φ)) :=
  pullback.lift (pullback.fst f (Spec.map (CommRingCat.ofHom φ)) ≫ a) (pullback.snd f (Spec.map (CommRingCat.ofHom φ)))
    (by rw [Category.assoc, ha]; exact pullback.condition)

@[scoped simp] theorem act'_fst (a : A ⟶ A) (ha : a ≫ f = f) :
    act' φ a ha ≫ pullback.fst f (Spec.map (CommRingCat.ofHom φ)) = pullback.fst f (Spec.map (CommRingCat.ofHom φ)) ≫ a :=
  pullback.lift_fst _ _ _

@[scoped simp] theorem act'_over (a : A ⟶ A) (ha : a ≫ f = f) :
    act' φ a ha ≫ pullback.snd f (Spec.map (CommRingCat.ofHom φ)) = pullback.snd f (Spec.map (CommRingCat.ofHom φ)) :=
  pullback.lift_snd _ _ _

theorem baseChangePointToBase_pushPt (a : A ⟶ A) (ha : a ≫ f = f)
    {T : Scheme.{u}} {t' : T ⟶ Spec (CommRingCat.of S')}
    (P : SchemeHomOver t' (pullback.snd f (Spec.map (CommRingCat.ofHom φ)))) :
    baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) (pushPt (act' φ a ha) (act'_over φ a ha) P) =
      pushPt a ha (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) P) := by
  apply Subtype.ext
  simp only [baseChangePointToBase_coe, mapPt_coe, Category.assoc, act'_fst]

theorem act'_id (a : A ⟶ A) (ha : a ≫ f = f) (h : a = 𝟙 A) : act' φ a ha = 𝟙 _ := by
  subst h
  apply pullback.hom_ext
  · rw [act'_fst, Category.id_comp, Category.comp_id]
  · rw [act'_over, Category.id_comp]

theorem act'_comp (a b c : A ⟶ A) (ha : a ≫ f = f) (hb : b ≫ f = f) (hc : c ≫ f = f) (h : c = b ≫ a) :
    act' φ c hc = act' φ b hb ≫ act' φ a ha := by
  subst h
  apply pullback.hom_ext
  · rw [act'_fst, Category.assoc, act'_fst, ← Category.assoc (act' φ b hb), act'_fst, Category.assoc]
  · rw [act'_over, Category.assoc, act'_over, act'_over]

theorem act'_hom (L : RelativeGroupLaw S f) (a : A ⟶ A) (ha : a ≫ f = f)
    (hhom : ∀ {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of S)) (P Q : SchemeHomOver t f),
      pushPt a ha (L.mul t P Q) = L.mul t (pushPt a ha P) (pushPt a ha Q))
    {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S'))
    (P Q : SchemeHomOver t' (pullback.snd f (Spec.map (CommRingCat.ofHom φ)))) :
    pushPt (act' φ a ha) (act'_over φ a ha) ((L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul t' P Q) =
      (L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul t' (pushPt (act' φ a ha) (act'_over φ a ha) P)
        (pushPt (act' φ a ha) (act'_over φ a ha) Q) := by
  apply (baseChangePointEquiv (Spec.map (CommRingCat.ofHom φ)) t').injective
  show baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) _ = baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) _
  rw [baseChangePointToBase_pushPt, baseChangePointToBase_mul, hhom, baseChangePointToBase_mul,
    baseChangePointToBase_pushPt, baseChangePointToBase_pushPt]

theorem act'_add (L : RelativeGroupLaw S f) (a b c : A ⟶ A) (ha : a ≫ f = f) (hb : b ≫ f = f) (hc : c ≫ f = f)
    (hadd : ∀ {T : Scheme.{u}} (t : T ⟶ Spec (CommRingCat.of S)) (P : SchemeHomOver t f),
      pushPt c hc P = L.mul t (pushPt a ha P) (pushPt b hb P))
    {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S'))
    (P : SchemeHomOver t' (pullback.snd f (Spec.map (CommRingCat.ofHom φ)))) :
    pushPt (act' φ c hc) (act'_over φ c hc) P =
      (L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul t' (pushPt (act' φ a ha) (act'_over φ a ha) P)
        (pushPt (act' φ b hb) (act'_over φ b hb) P) := by
  apply (baseChangePointEquiv (Spec.map (CommRingCat.ofHom φ)) t').injective
  show baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) _ = baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) _
  rw [baseChangePointToBase_pushPt, hadd, baseChangePointToBase_mul, baseChangePointToBase_pushPt,
    baseChangePointToBase_pushPt]

end Act

section FEC

open scoped Quaternion
variable {a b : ℚ} {Λ : Submodule ℤ ℍ[ℚ, a, b]} {N : ℕ}

theorem fec_bundle (E : FakeEllipticCurve Λ N S) :
    AbelianSchemePropertyBundle S' (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))) :=
  bundle_baseChange φ E.bundle E.L

theorem fec_comm (E : FakeEllipticCurve Λ N S) : (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).IsCommutative :=
  RelativeGroupLaw.IsCommutative.baseChange (Spec.map (CommRingCat.ofHom φ)) (G := E.L) E.comm

theorem fec_act_hom (E : FakeEllipticCurve Λ N S) (x : ↥Λ) {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S'))
    (P Q : SchemeHomOver t' (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))) :
    pushPt (act' φ (E.act x) (E.act_over x)) (act'_over φ _ _) ((E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul t' P Q) =
      (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul t' (pushPt (act' φ (E.act x) (E.act_over x)) (act'_over φ _ _) P)
        (pushPt (act' φ (E.act x) (E.act_over x)) (act'_over φ _ _) Q) :=
  act'_hom φ E.L (E.act x) (E.act_over x) (E.act_hom x) t' P Q

theorem fec_act_one (E : FakeEllipticCurve Λ N S) (h : (1 : ℍ[ℚ, a, b]) ∈ Λ) :
    act' φ (E.act ⟨1, h⟩) (E.act_over _) = 𝟙 _ := act'_id φ _ _ (E.act_one h)

theorem fec_act_mul (E : FakeEllipticCurve Λ N S) (x y : ↥Λ) (h : (x : ℍ[ℚ, a, b]) * (y : ℍ[ℚ, a, b]) ∈ Λ) :
    act' φ (E.act ⟨(x : ℍ[ℚ, a, b]) * (y : ℍ[ℚ, a, b]), h⟩) (E.act_over _) =
      act' φ (E.act y) (E.act_over y) ≫ act' φ (E.act x) (E.act_over x) :=
  act'_comp φ _ _ _ _ _ _ (E.act_mul x y h)

theorem fec_act_add (E : FakeEllipticCurve Λ N S) (x y : ↥Λ) {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S'))
    (P : SchemeHomOver t' (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))) :
    pushPt (act' φ (E.act (x + y)) (E.act_over (x + y))) (act'_over φ _ _) P =
      (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul t' (pushPt (act' φ (E.act x) (E.act_over x)) (act'_over φ _ _) P)
        (pushPt (act' φ (E.act y) (E.act_over y)) (act'_over φ _ _) P) :=
  act'_add φ E.L _ _ _ _ _ _ (fun t Q => E.act_add x y t Q) t' P

theorem fec_mul_compat (E : FakeEllipticCurve Λ N S) {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S'))
    (P Q : SchemeHomOver t' (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))) :
    ((E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul t' P Q).1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom φ)) =
      (E.L.mul (t' ≫ (Spec.map (CommRingCat.ofHom φ)))
        ⟨P.1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom φ)), by
          rw [Category.assoc, pullback.condition, ← Category.assoc, P.2]⟩
        ⟨Q.1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom φ)), by
          rw [Category.assoc, pullback.condition, ← Category.assoc, Q.2]⟩).1 :=
  baseChange_mul_coe_fst φ E.L t' P Q

theorem law_eq_baseChange (E : FakeEllipticCurve Λ N S)
    (L' : RelativeGroupLaw S' (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))))
    (hL' : ∀ (T : Scheme.{u}) (t' : T ⟶ Spec (CommRingCat.of S'))
        (P Q : SchemeHomOver t' (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))),
        (L'.mul t' P Q).1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom φ)) =
          (E.L.mul (t' ≫ (Spec.map (CommRingCat.ofHom φ)))
            ⟨P.1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom φ)), by
              rw [Category.assoc, pullback.condition, ← Category.assoc, P.2]⟩
            ⟨Q.1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom φ)), by
              rw [Category.assoc, pullback.condition, ← Category.assoc, Q.2]⟩).1) :
    L' = E.L.baseChange (Spec.map (CommRingCat.ofHom φ)) := by
  refine RelativeGroupLaw.ext_of_mul _ _ (fun {T} t' P Q => ?_)
  apply Subtype.ext
  apply pullback.hom_ext
  · rw [hL' T t' P Q, fec_mul_compat]
  · rw [(L'.mul t' P Q).2, ((E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul t' P Q).2]

end FEC

section Level

variable {A C : Scheme.{u}} (f : A ⟶ Spec (CommRingCat.of S)) (lev : C ⟶ A)

noncomputable def levBC :
    pullback (lev ≫ f) (Spec.map (CommRingCat.ofHom φ)) ⟶ pullback f (Spec.map (CommRingCat.ofHom φ)) :=
  pullback.lift (pullback.fst (lev ≫ f) (Spec.map (CommRingCat.ofHom φ)) ≫ lev)
    (pullback.snd (lev ≫ f) (Spec.map (CommRingCat.ofHom φ)))
    (by rw [Category.assoc, pullback.condition])

@[scoped simp] theorem levBC_snd :
    levBC φ f lev ≫ pullback.snd f (Spec.map (CommRingCat.ofHom φ)) = pullback.snd (lev ≫ f) (Spec.map (CommRingCat.ofHom φ)) :=
  pullback.lift_snd _ _ _

@[scoped simp] theorem levBC_fst :
    levBC φ f lev ≫ pullback.fst f (Spec.map (CommRingCat.ofHom φ)) = pullback.fst (lev ≫ f) (Spec.map (CommRingCat.ofHom φ)) ≫ lev :=
  pullback.lift_fst _ _ _

theorem isPullback_levBC :
    IsPullback (pullback.fst (lev ≫ f) (Spec.map (CommRingCat.ofHom φ))) (levBC φ f lev) lev
      (pullback.fst f (Spec.map (CommRingCat.ofHom φ))) := by
  refine IsPullback.of_bot (v₂₁ := pullback.snd f (Spec.map (CommRingCat.ofHom φ))) (v₂₂ := f)
    (h₃₁ := (Spec.map (CommRingCat.ofHom φ))) ?_ (levBC_fst φ f lev).symm
    (IsPullback.of_hasPullback f (Spec.map (CommRingCat.ofHom φ)))
  rw [levBC_snd]
  exact IsPullback.of_hasPullback (lev ≫ f) (Spec.map (CommRingCat.ofHom φ))

theorem isClosedImmersion_levBC [IsClosedImmersion lev] : IsClosedImmersion (levBC φ f lev) :=
  MorphismProperty.of_isPullback (P := @IsClosedImmersion) (isPullback_levBC φ f lev) inferInstance

scoped instance levBC_comp_isFinite [IsFinite (lev ≫ f)] :
    IsFinite (levBC φ f lev ≫ pullback.snd f (Spec.map (CommRingCat.ofHom φ))) := by
  rw [levBC_snd]; infer_instance

scoped instance levBC_comp_flat [Flat (lev ≫ f)] : Flat (levBC φ f lev ≫ pullback.snd f (Spec.map (CommRingCat.ofHom φ))) := by
  rw [levBC_snd]; infer_instance

scoped instance levBC_comp_lofp [LocallyOfFinitePresentation (lev ≫ f)] :
    LocallyOfFinitePresentation (levBC φ f lev ≫ pullback.snd f (Spec.map (CommRingCat.ofHom φ))) := by
  rw [levBC_snd]; infer_instance

theorem finrank_levBC [IsFinite (lev ≫ f)] [Flat (lev ≫ f)] (N : ℕ)
    (hrank : ∀ s : ↥(Spec (CommRingCat.of S)), (lev ≫ f).finrank s = N ^ 2) (s' : ↥(Spec (CommRingCat.of S'))) :
    (levBC φ f lev ≫ pullback.snd f (Spec.map (CommRingCat.ofHom φ))).finrank s' = N ^ 2 := by
  rw [levBC_snd, Scheme.Hom.finrank_pullback_snd, hrank]

theorem factorsThrough_iff {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S'))
    (P : SchemeHomOver t' (pullback.snd f (Spec.map (CommRingCat.ofHom φ)))) :
    FactorsThrough (levBC φ f lev) P ↔ FactorsThrough lev (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) P) := by
  constructor
  · rintro ⟨P₀, hP₀⟩
    refine ⟨P₀ ≫ pullback.fst (lev ≫ f) (Spec.map (CommRingCat.ofHom φ)), ?_⟩
    rw [baseChangePointToBase_coe, ← hP₀, Category.assoc, Category.assoc, levBC_fst]
  · rintro ⟨P₀, hP₀⟩
    refine ⟨pullback.lift P₀ (P.1 ≫ pullback.snd f (Spec.map (CommRingCat.ofHom φ)))
      (by rw [← Category.assoc, hP₀, baseChangePointToBase_coe, Category.assoc, Category.assoc, pullback.condition]), ?_⟩
    apply pullback.hom_ext
    · rw [Category.assoc, levBC_fst, ← Category.assoc, pullback.lift_fst, hP₀, baseChangePointToBase_coe]
    · rw [Category.assoc, levBC_snd, pullback.lift_snd]

theorem baseChangePointToBase_nsmulPt (L : RelativeGroupLaw S f) {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S'))
    (n : ℕ) (P : SchemeHomOver t' (pullback.snd f (Spec.map (CommRingCat.ofHom φ)))) :
    baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) (nsmulPt (L.baseChange (Spec.map (CommRingCat.ofHom φ))) t' n P) =
      nsmulPt L (t' ≫ (Spec.map (CommRingCat.ofHom φ))) n (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) P) := by
  induction n with
  | zero => exact baseChangePointToBase_one (Spec.map (CommRingCat.ofHom φ)) L t'
  | succ n ih =>
    show baseChangePointToBase (Spec.map (CommRingCat.ofHom φ))
        ((L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul t'
          (nsmulPt (L.baseChange (Spec.map (CommRingCat.ofHom φ))) t' n P) P) =
      L.mul _ (nsmulPt L _ n (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) P))
        (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) P)
    rw [baseChangePointToBase_mul, ih]

def rebase {T : Scheme.{u}} {t₁ t₂ : T ⟶ Spec (CommRingCat.of S)} (h : t₁ = t₂) (P : SchemeHomOver t₁ f) :
    SchemeHomOver t₂ f := ⟨P.1, P.2.trans h⟩

@[scoped simp] theorem rebase_coe {T : Scheme.{u}} {t₁ t₂ : T ⟶ Spec (CommRingCat.of S)} (h : t₁ = t₂) (P : SchemeHomOver t₁ f) :
    (rebase f h P).1 = P.1 := rfl

theorem rebase_mul (L : RelativeGroupLaw S f) {T : Scheme.{u}} {t₁ t₂ : T ⟶ Spec (CommRingCat.of S)} (h : t₁ = t₂)
    (P Q : SchemeHomOver t₁ f) : rebase f h (L.mul t₁ P Q) = L.mul t₂ (rebase f h P) (rebase f h Q) := by
  subst h; rfl

theorem rebase_one (L : RelativeGroupLaw S f) {T : Scheme.{u}} {t₁ t₂ : T ⟶ Spec (CommRingCat.of S)} (h : t₁ = t₂) :
    rebase f h (L.one t₁) = L.one t₂ := by
  subst h; rfl

theorem geomPoint_comp (k : Type u) [Field k] (sk' : S' →+* k) :
    geomPoint k sk' ≫ (Spec.map (CommRingCat.ofHom φ)) = geomPoint k (sk'.comp φ) := by
  rw [geomPoint, geomPoint, ← Spec.map_comp]; rfl

theorem tangentBase_comp (k : Type u) [Field k] (sk' : S' →+* k) :
    tangentBase k sk' ≫ (Spec.map (CommRingCat.ofHom φ)) = tangentBase k (sk'.comp φ) := by
  rw [tangentBase, tangentBase, ← Spec.map_comp]; rfl

theorem tangentZero_tangentBase {R₁ : Type u} [CommRing R₁] (k : Type u) [Field k] (sk : R₁ →+* k) :
    tangentZero k ≫ tangentBase k sk = geomPoint k sk := by
  have h : CommRingCat.ofHom ((algebraMap k (DualNumber k)).comp sk) ≫
      CommRingCat.ofHom (TrivSqZeroExt.fstHom k k k).toRingHom = CommRingCat.ofHom sk := by
    ext r; rfl
  rw [tangentZero, tangentBase, geomPoint, ← Spec.map_comp, h]

end Level

section LevelFEC

open scoped Quaternion
variable {a b : ℚ} {Λ : Submodule ℤ ℍ[ℚ, a, b]} {N : ℕ}

theorem fec_lev_closed (E : FakeEllipticCurve Λ N S) : IsClosedImmersion (levBC φ E.f E.lev) :=
  haveI := E.lev_closed; isClosedImmersion_levBC φ E.f E.lev

theorem fec_lev_sub (E : FakeEllipticCurve Λ N S) {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S'))
    (P Q : SchemeHomOver t' (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))) :
    FactorsThrough (levBC φ E.f E.lev) P → FactorsThrough (levBC φ E.f E.lev) Q →
      FactorsThrough (levBC φ E.f E.lev) ((E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul t' P Q) ∧
      FactorsThrough (levBC φ E.f E.lev) ((E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).inv t' P) := by
  intro hP hQ
  rw [factorsThrough_iff] at hP hQ
  rw [factorsThrough_iff, factorsThrough_iff, baseChangePointToBase_mul, baseChangePointToBase_inv]
  exact E.lev_sub _ _ _ hP hQ

theorem fec_lev_one (E : FakeEllipticCurve Λ N S) {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S')) :
    FactorsThrough (levBC φ E.f E.lev) ((E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).one t') := by
  rw [factorsThrough_iff, baseChangePointToBase_one]
  exact E.lev_one _

theorem fec_lev_torsion (E : FakeEllipticCurve Λ N S) {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S'))
    (P : SchemeHomOver t' (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))) :
    FactorsThrough (levBC φ E.f E.lev) P →
      nsmulPt (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))) t' N P =
        (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).one t' := by
  intro hP
  rw [factorsThrough_iff] at hP
  apply (baseChangePointEquiv (Spec.map (CommRingCat.ofHom φ)) t').injective
  show baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) _ = baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) _
  rw [baseChangePointToBase_nsmulPt, baseChangePointToBase_one]
  exact E.lev_torsion _ _ hP

theorem fec_lev_stable (E : FakeEllipticCurve Λ N S) (x : ↥Λ) {T : Scheme.{u}} (t' : T ⟶ Spec (CommRingCat.of S'))
    (P : SchemeHomOver t' (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))) :
    FactorsThrough (levBC φ E.f E.lev) P →
      FactorsThrough (levBC φ E.f E.lev) (pushPt (act' φ (E.act x) (E.act_over x)) (act'_over φ _ _) P) := by
  intro hP
  rw [factorsThrough_iff] at hP
  rw [factorsThrough_iff, baseChangePointToBase_pushPt]
  exact E.lev_stable x _ _ hP

theorem fec_lev_finite (E : FakeEllipticCurve Λ N S) :
    IsFinite (levBC φ E.f E.lev ≫ pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))) :=
  haveI := E.lev_finite; inferInstance

theorem fec_lev_flat (E : FakeEllipticCurve Λ N S) :
    Flat (levBC φ E.f E.lev ≫ pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))) :=
  haveI := E.lev_flat; inferInstance

theorem fec_lev_fp (E : FakeEllipticCurve Λ N S) :
    LocallyOfFinitePresentation (levBC φ E.f E.lev ≫ pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))) :=
  haveI := E.lev_finitePresentation; inferInstance

theorem fec_lev_rank (E : FakeEllipticCurve Λ N S) (s' : ↥(Spec (CommRingCat.of S'))) :
    (levBC φ E.f E.lev ≫ pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))).finrank s' = N ^ 2 :=
  haveI := E.lev_finite; haveI := E.lev_flat; finrank_levBC φ E.f E.lev N E.lev_rank s'

theorem factorsThrough_rebase {A C : Scheme.{u}} {f : A ⟶ Spec (CommRingCat.of S)} (lev : C ⟶ A) {T : Scheme.{u}}
    {t₁ t₂ : T ⟶ Spec (CommRingCat.of S)} (h : t₁ = t₂) (P : SchemeHomOver t₁ f) :
    FactorsThrough lev (rebase f h P) ↔ FactorsThrough lev P := by
  subst h; exact Iff.rfl

noncomputable def levPtToBase (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk' : S' →+* k)
    (P : {P : SchemeHomOver (geomPoint k sk') (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))) //
      FactorsThrough (levBC φ E.f E.lev) P}) :
    {P : SchemeHomOver (geomPoint k (sk'.comp φ)) E.f // FactorsThrough E.lev P} :=
  ⟨rebase E.f (geomPoint_comp φ k sk') (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) P.1),
    (factorsThrough_rebase E.lev (geomPoint_comp φ k sk') _).mpr ((factorsThrough_iff φ E.f E.lev _ P.1).mp P.2)⟩

noncomputable def levPtOfBase (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk' : S' →+* k)
    (Q : {P : SchemeHomOver (geomPoint k (sk'.comp φ)) E.f // FactorsThrough E.lev P}) :
    {P : SchemeHomOver (geomPoint k sk') (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))) //
      FactorsThrough (levBC φ E.f E.lev) P} :=
  ⟨baseChangePointOfBase (Spec.map (CommRingCat.ofHom φ)) (rebase E.f (geomPoint_comp φ k sk').symm Q.1), by
    rw [factorsThrough_iff, baseChangePointToBase_ofBase, factorsThrough_rebase]; exact Q.2⟩

theorem rebase_symm_rebase {A : Scheme.{u}} (f : A ⟶ Spec (CommRingCat.of S)) {T : Scheme.{u}}
    {t₁ t₂ : T ⟶ Spec (CommRingCat.of S)} (h : t₁ = t₂) (P : SchemeHomOver t₁ f) : rebase f h.symm (rebase f h P) = P := by
  subst h; rfl

theorem rebase_rebase_symm {A : Scheme.{u}} (f : A ⟶ Spec (CommRingCat.of S)) {T : Scheme.{u}}
    {t₁ t₂ : T ⟶ Spec (CommRingCat.of S)} (h : t₁ = t₂) (Q : SchemeHomOver t₂ f) : rebase f h (rebase f h.symm Q) = Q := by
  subst h; rfl

theorem levPtOfBase_toBase (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk' : S' →+* k)
    (P : {P : SchemeHomOver (geomPoint k sk') (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))) //
      FactorsThrough (levBC φ E.f E.lev) P}) :
    levPtOfBase φ E k sk' (levPtToBase φ E k sk' P) = P := by
  apply Subtype.ext
  show baseChangePointOfBase (Spec.map (CommRingCat.ofHom φ)) (rebase E.f (geomPoint_comp φ k sk').symm
    (rebase E.f (geomPoint_comp φ k sk') (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) P.1))) = P.1
  rw [rebase_symm_rebase, baseChangePointOfBase_toBase]

theorem levPtToBase_ofBase (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk' : S' →+* k)
    (Q : {P : SchemeHomOver (geomPoint k (sk'.comp φ)) E.f // FactorsThrough E.lev P}) :
    levPtToBase φ E k sk' (levPtOfBase φ E k sk' Q) = Q := by
  apply Subtype.ext
  show rebase E.f (geomPoint_comp φ k sk') (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ))
    (baseChangePointOfBase (Spec.map (CommRingCat.ofHom φ)) (rebase E.f (geomPoint_comp φ k sk').symm Q.1))) = Q.1
  rw [baseChangePointToBase_ofBase, rebase_rebase_symm]

noncomputable def levPtEquiv (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk' : S' →+* k) :
    {P : SchemeHomOver (geomPoint k sk') (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))) //
      FactorsThrough (levBC φ E.f E.lev) P} ≃
    {P : SchemeHomOver (geomPoint k (sk'.comp φ)) E.f // FactorsThrough E.lev P} :=
  ⟨levPtToBase φ E k sk', levPtOfBase φ E k sk', levPtOfBase_toBase φ E k sk', levPtToBase_ofBase φ E k sk'⟩

theorem levPtOfBase_mul (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk' : S' →+* k)
    (Q R : {P : SchemeHomOver (geomPoint k (sk'.comp φ)) E.f // FactorsThrough E.lev P})
    (QR : {P : SchemeHomOver (geomPoint k (sk'.comp φ)) E.f // FactorsThrough E.lev P})
    (h : QR.1 = E.L.mul (geomPoint k (sk'.comp φ)) Q.1 R.1) :
    (levPtOfBase φ E k sk' QR).1 =
      (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul (geomPoint k sk') (levPtOfBase φ E k sk' Q).1
        (levPtOfBase φ E k sk' R).1 := by
  show baseChangePointOfBase (Spec.map (CommRingCat.ofHom φ)) (rebase E.f (geomPoint_comp φ k sk').symm QR.1) =
    (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul (geomPoint k sk')
      (baseChangePointOfBase (Spec.map (CommRingCat.ofHom φ)) (rebase E.f (geomPoint_comp φ k sk').symm Q.1))
      (baseChangePointOfBase (Spec.map (CommRingCat.ofHom φ)) (rebase E.f (geomPoint_comp φ k sk').symm R.1))
  rw [baseChange_mul, baseChangePointToBase_ofBase, baseChangePointToBase_ofBase, ← rebase_mul, ← h]

theorem fec_lev_fibre (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] [IsAlgClosed k] (sk' : S' →+* k)
    (hN : (N : k) ≠ 0) :
    ∃ e : ZMod N × ZMod N ≃ {P : SchemeHomOver (geomPoint k sk') (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))) //
        FactorsThrough (levBC φ E.f E.lev) P},
      ∀ x y : ZMod N × ZMod N,
        (e (x + y) : SchemeHomOver (geomPoint k sk') (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))) =
          (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul (geomPoint k sk') (e x) (e y) := by
  obtain ⟨e₀, he₀⟩ := E.lev_fibre k (sk'.comp φ) hN
  exact ⟨e₀.trans (levPtEquiv φ E k sk').symm, fun x y =>
    levPtOfBase_mul φ E k sk' (e₀ x) (e₀ y) (e₀ (x + y)) (he₀ x y)⟩

end LevelFEC

section Trace

open scoped Quaternion
variable {a b : ℚ} {Λ : Submodule ℤ ℍ[ℚ, a, b]} {N : ℕ}

noncomputable def tanToBase (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk : S' →+* k)
    (P : SchemeHomOver (tangentBase k sk) (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))) :
    SchemeHomOver (tangentBase k (sk.comp φ)) E.f :=
  rebase E.f (tangentBase_comp φ k sk) (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) P)

theorem tanToBase_coe (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk : S' →+* k)
    (P : SchemeHomOver (tangentBase k sk) (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))) :
    (tanToBase φ E k sk P).1 = P.1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom φ)) := rfl

theorem tanToBase_injective (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk : S' →+* k) :
    Function.Injective (tanToBase φ E k sk) := fun P Q h => by
  apply (baseChangePointEquiv (Spec.map (CommRingCat.ofHom φ)) (tangentBase k sk)).injective
  apply Subtype.ext
  show (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) P).1 =
    (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) Q).1
  exact (tanToBase_coe φ E k sk P).symm.trans ((congrArg Subtype.val h).trans (tanToBase_coe φ E k sk Q))

theorem tanToBase_mul (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk : S' →+* k)
    (P Q : SchemeHomOver (tangentBase k sk) (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))) :
    tanToBase φ E k sk ((E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul (tangentBase k sk) P Q) =
      E.L.mul (tangentBase k (sk.comp φ)) (tanToBase φ E k sk P) (tanToBase φ E k sk Q) := by
  show rebase E.f (tangentBase_comp φ k sk) (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ)) _) = _
  rw [baseChangePointToBase_mul, rebase_mul]; rfl

noncomputable def tanOfBase (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk : S' →+* k)
    (P : SchemeHomOver (tangentBase k (sk.comp φ)) E.f) :
    SchemeHomOver (tangentBase k sk) (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))) :=
  baseChangePointOfBase (Spec.map (CommRingCat.ofHom φ)) (rebase E.f (tangentBase_comp φ k sk).symm P)

theorem tanToBase_ofBase (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk : S' →+* k)
    (P : SchemeHomOver (tangentBase k (sk.comp φ)) E.f) : tanToBase φ E k sk (tanOfBase φ E k sk P) = P := by
  show rebase E.f (tangentBase_comp φ k sk) (baseChangePointToBase (Spec.map (CommRingCat.ofHom φ))
    (baseChangePointOfBase (Spec.map (CommRingCat.ofHom φ)) (rebase E.f (tangentBase_comp φ k sk).symm P))) = P
  rw [baseChangePointToBase_ofBase, rebase_rebase_symm]

theorem tanOfBase_coe_fst (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk : S' →+* k)
    (P : SchemeHomOver (tangentBase k (sk.comp φ)) E.f) :
    (tanOfBase φ E k sk P).1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom φ)) = P.1 := by
  have h := congrArg Subtype.val
    (baseChangePointToBase_ofBase (Spec.map (CommRingCat.ofHom φ)) (rebase E.f (tangentBase_comp φ k sk).symm P))
  rw [baseChangePointToBase_coe, rebase_coe] at h
  exact h

theorem baseChange_one_coe_fst (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk : S' →+* k) :
    ((E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).one (geomPoint k sk)).1 ≫
        pullback.fst E.f (Spec.map (CommRingCat.ofHom φ)) =
      (E.L.one (geomPoint k (sk.comp φ))).1 := by
  have h1 := congrArg Subtype.val (baseChangePointToBase_one (Spec.map (CommRingCat.ofHom φ)) E.L (geomPoint k sk))
  rw [baseChangePointToBase_coe] at h1
  rw [h1]
  have h2 := congrArg Subtype.val (rebase_one E.f E.L (geomPoint_comp φ k sk))
  rw [rebase_coe] at h2
  exact h2

theorem isTangentVector_tanToBase (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk : S' →+* k)
    (P : SchemeHomOver (tangentBase k sk) (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))))
    (hP : IsTangentVector (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))) k sk P) :
    IsTangentVector E.L k (sk.comp φ) (tanToBase φ E k sk P) := by
  show tangentZero k ≫ (P.1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom φ))) = (E.L.one (geomPoint k (sk.comp φ))).1
  rw [← Category.assoc, show tangentZero k ≫ P.1 = _ from hP, baseChange_one_coe_fst]

theorem isTangentVector_tanOfBase (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] (sk : S' →+* k)
    (P : SchemeHomOver (tangentBase k (sk.comp φ)) E.f) (hP : IsTangentVector E.L k (sk.comp φ) P) :
    IsTangentVector (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))) k sk (tanOfBase φ E k sk P) := by
  show tangentZero k ≫ (tanOfBase φ E k sk P).1 =
    ((E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).one (geomPoint k sk)).1
  apply pullback.hom_ext
  · rw [Category.assoc, baseChange_one_coe_fst, tanOfBase_coe_fst]
    exact hP
  · rw [Category.assoc, (tanOfBase φ E k sk P).2, ((E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).one (geomPoint k sk)).2,
      tangentZero_tangentBase]

theorem fec_act_trace (E : FakeEllipticCurve Λ N S) (k : Type u) [Field k] [IsAlgClosed k] (sk : S' →+* k)
    (V : Type u) [AddCommGroup V] [Module k V] [Module.Finite k V]
    (τ : V → SchemeHomOver (tangentBase k sk) (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ)))) :
    Function.Injective τ →
    (∀ P : SchemeHomOver (tangentBase k sk) (pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))),
      P ∈ Set.range τ ↔ IsTangentVector (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))) k sk P) →
    (∀ v w : V, τ (v + w) = (E.L.baseChange (Spec.map (CommRingCat.ofHom φ))).mul (tangentBase k sk) (τ v) (τ w)) →
    (∀ (c : k) (v : V), (τ (c • v)).1 = tangentScale k c ≫ (τ v).1) →
    ∀ (m : ↥Λ) (Φ : V →ₗ[k] V),
      (∀ v : V, τ (Φ v) = pushPt (act' φ (E.act m) (E.act_over m)) (act'_over φ _ _) (τ v)) →
    ∀ n : ℤ, (m : ℍ[ℚ, a, b]) + star (m : ℍ[ℚ, a, b]) = ((n : ℚ) : ℍ[ℚ, a, b]) →
      LinearMap.trace k V Φ = (n : k) := by
  intro hinj hrange hadd hscale m Φ hΦ n hn
  refine E.act_trace k (sk.comp φ) V (fun v => tanToBase φ E k sk (τ v)) ?_ ?_ ?_ ?_ m Φ ?_ n hn
  · exact (tanToBase_injective φ E k sk).comp hinj
  · intro P
    constructor
    · rintro ⟨v, rfl⟩
      exact isTangentVector_tanToBase φ E k sk (τ v) ((hrange (τ v)).mp ⟨v, rfl⟩)
    · intro hP
      obtain ⟨v, hv⟩ := (hrange (tanOfBase φ E k sk P)).mpr (isTangentVector_tanOfBase φ E k sk P hP)
      exact ⟨v, by show tanToBase φ E k sk (τ v) = P; rw [hv, tanToBase_ofBase]⟩
  · intro v w
    show tanToBase φ E k sk (τ (v + w)) = E.L.mul _ (tanToBase φ E k sk (τ v)) (tanToBase φ E k sk (τ w))
    rw [hadd, tanToBase_mul]
  · intro c v
    show (tanToBase φ E k sk (τ (c • v))).1 = tangentScale k c ≫ (tanToBase φ E k sk (τ v)).1
    rw [tanToBase_coe, tanToBase_coe, hscale, Category.assoc]
  · intro v
    apply Subtype.ext
    show (tanToBase φ E k sk (τ (Φ v))).1 = (pushPt (E.act m) (E.act_over m) (tanToBase φ E k sk (τ v))).1
    rw [tanToBase_coe, hΦ, mapPt_coe, mapPt_coe, Category.assoc, act'_fst, tanToBase_coe, Category.assoc]

end Trace

section Package

open scoped Quaternion
variable {a b : ℚ} {Λ : Submodule ℤ ℍ[ℚ, a, b]} {N : ℕ}

noncomputable def baseChangeFEC (E : FakeEllipticCurve Λ N S) : FakeEllipticCurve Λ N S' where
  A := pullback E.f (Spec.map (CommRingCat.ofHom φ))
  f := pullback.snd E.f (Spec.map (CommRingCat.ofHom φ))
  L := E.L.baseChange (Spec.map (CommRingCat.ofHom φ))
  comm := fec_comm φ E
  bundle := fec_bundle φ E
  dim_fibre := fun s' => by
    haveI := E.bundle.smooth
    simpa using AlgebraicGeometry.topologicalKrullDim_preimage_pullback_snd_eq_of_smooth_of_isConnected
      φ E.f E.bundle.connectedFibres 2 E.dim_fibre s'
  act := fun x => act' φ (E.act x) (E.act_over x)
  act_over := fun x => act'_over φ _ _
  act_hom := fun x {T} t P Q => fec_act_hom φ E x t P Q
  act_one := fec_act_one φ E
  act_mul := fec_act_mul φ E
  act_add := fun x y {T} t P => fec_act_add φ E x y t P
  act_trace := fec_act_trace φ E
  C := pullback (E.lev ≫ E.f) (Spec.map (CommRingCat.ofHom φ))
  lev := levBC φ E.f E.lev
  lev_closed := fec_lev_closed φ E
  lev_sub := fec_lev_sub φ E
  lev_one := fec_lev_one φ E
  lev_torsion := fec_lev_torsion φ E
  lev_stable := fec_lev_stable φ E
  lev_finite := fec_lev_finite φ E
  lev_flat := fec_lev_flat φ E
  lev_finitePresentation := fec_lev_fp φ E
  lev_rank := fec_lev_rank φ E
  lev_fibre := fec_lev_fibre φ E

end Package

end P2mKcUniqBC
p2m_reactivate "P2MW.S_CerednikDrinfeld_QM_FakeEllipticCurve_locIsoOnBase_of_isCanonicalPolData_pullback_of_isUnit_two.P2mKcUniqBC"

open scoped TensorProduct Quaternion
p2m_open "CategoryTheory.MonoidalCategory QuaternionAlgebra~baseChange CerednikDrinfeld AlgebraicGeometry.Polarisation"

theorem solution
    {q q' : ℕ} [Fact q.Prime] [Fact q'.Prime] (hqq' : q' ≠ q)
    {a b : ℚ} (hB : IsIndefiniteRamifiedExactlyAt a b q q')
    (Λ : Submodule ℤ ℍ[ℚ, a, b]) (hΛ : IsMaximalOrder Λ)
    (μ : ↥Λ) (hμ : (μ : ℍ[ℚ, a, b]) * (μ : ℍ[ℚ, a, b]) = -(((q * q' : ℕ) : ℚ) • (1 : ℍ[ℚ, a, b])))
    (star : ↥Λ → ↥Λ) (hstar : ∀ x : ↥Λ, (μ : ℍ[ℚ, a, b]) * (star x : ℍ[ℚ, a, b]) = Star.star (x : ℍ[ℚ, a, b]) * μ)
    (N : ℕ) (S : Type) [CommRing S] (h2 : IsUnit (2 : S)) (E : FakeEllipticCurve Λ N S) :
    ∀ (R : Type) [CommRing R] [Algebra S R]
      (L' : RelativeGroupLaw R (pullback.snd E.f (Spec.map (CommRingCat.ofHom (algebraMap S R))))),
      (∀ (T : Scheme) (t' : T ⟶ Spec (CommRingCat.of R))
            (P Q : SchemeHomOver t' (pullback.snd E.f (Spec.map (CommRingCat.ofHom (algebraMap S R))))),
            (L'.mul t' P Q).1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom (algebraMap S R))) =
              (E.L.mul (t' ≫ (Spec.map (CommRingCat.ofHom (algebraMap S R))))
                ⟨P.1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom (algebraMap S R))), by rw [Category.assoc, pullback.condition, ← Category.assoc, P.2]⟩
                ⟨Q.1 ≫ pullback.fst E.f (Spec.map (CommRingCat.ofHom (algebraMap S R))), by rw [Category.assoc, pullback.condition, ← Category.assoc, Q.2]⟩).1) →
      ∀ (𝓛 𝓛' : (pullback E.f (Spec.map (CommRingCat.ofHom (algebraMap S R)))).Modules),
        CerednikDrinfeld.QM.IsCanonicalPolData (pullback.snd E.f (Spec.map (CommRingCat.ofHom (algebraMap S R)))) L'
            (fun x : ↥Λ => pullback.lift (pullback.fst E.f (Spec.map (CommRingCat.ofHom (algebraMap S R))) ≫ E.act x) (pullback.snd E.f (Spec.map (CommRingCat.ofHom (algebraMap S R))))
              (by rw [Category.assoc, E.act_over]; exact pullback.condition))
            (fun x => pullback.lift_snd _ _ _)
            star 𝓛 →
        CerednikDrinfeld.QM.IsCanonicalPolData (pullback.snd E.f (Spec.map (CommRingCat.ofHom (algebraMap S R)))) L'
            (fun x : ↥Λ => pullback.lift (pullback.fst E.f (Spec.map (CommRingCat.ofHom (algebraMap S R))) ≫ E.act x) (pullback.snd E.f (Spec.map (CommRingCat.ofHom (algebraMap S R))))
              (by rw [Category.assoc, E.act_over]; exact pullback.condition))
            (fun x => pullback.lift_snd _ _ _)
            star 𝓛' →
        LocIsoOnBase (pullback.snd E.f (Spec.map (CommRingCat.ofHom (algebraMap S R)))) 𝓛 𝓛' := by
  intro R _ _ L' hL' 𝓛 𝓛' h h'
  obtain rfl : L' = E.L.baseChange (Spec.map (CommRingCat.ofHom (algebraMap S R))) :=
    P2mKcUniqBC.law_eq_baseChange (algebraMap S R) E L' hL'
  have h2R : IsUnit (2 : R) := by
    have h := h2.map (algebraMap S R)
    rwa [map_ofNat] at h
  exact CerednikDrinfeld.QM.FakeEllipticCurve.locIsoOnBase_of_isCanonicalPol_of_isUnit_two hqq' hB Λ hΛ μ hμ star hstar N R h2R
    (P2mKcUniqBC.baseChangeFEC (algebraMap S R) E) 𝓛 𝓛' h h'

end S_CerednikDrinfeld_QM_FakeEllipticCurve_locIsoOnBase_of_isCanonicalPolData_pullback_of_isUnit_two
end P2MW
export P2MW.S_CerednikDrinfeld_QM_FakeEllipticCurve_locIsoOnBase_of_isCanonicalPolData_pullback_of_isUnit_two (solution)
