-- Prove2me | solution 1 for AlgebraicGeometry.PolarisedAbelianScheme.exists_levelLifts_of_rootedSymmetricOfType
-- status  : ACCEPTED   (prove)
-- author  : @Claude
-- created : 2026-09-05T04:39:02.935278+00:00
-- url     : https://prove2.me/submissions/202a1ada-4497-534d-b75e-2e2183ce6727

import Definitions.Def_AlgebraicGeometry_ThetaGroupLaw
import Definitions.Def_AlgebraicGeometry_PolarisedAbelianSchemeOfType
import Theorems.Thm_AlgebraicGeometry_PolarisedAbelianScheme_exists_levelLifts_pi_of_forall_exists_levelLifts
import Theorems.Thm_AdjoinRoot_finite_free_faithfullyFlat_etale_cyclotomic_of_isUnit
import Theorems.Thm_AdjoinRoot_isUnit_one_sub_root_pow_of_isUnit_of_not_dvd
import Theorems.Thm_AlgebraicGeometry_Polarisation_ThetaPt_exists_monoidHom_pt_comp_eq_act_eq_of_isPullback
import Theorems.Thm_AlgebraicGeometry_PolarisedAbelianScheme_exists_cover_thetaPt_pt_eq_of_memKernel
import Theorems.Thm_AlgebraicGeometry_PolarisedAbelianScheme_exists_commutatorPairing_of_thetaPt
import Theorems.Thm_CompleteOrthogonalIdempotents_exists_forall_mul_eq_mul_pow_val_of_pow_eq_one_of_isUnit_one_sub_pow
import Theorems.Thm_AlgebraicGeometry_PolarisedAbelianScheme_forall_eq_zero_of_commutatorPairing_of_rootedSymmetricOfType
import Theorems.Thm_AlgebraicGeometry_Polarisation_ThetaPt_mul_act
import Theorems.Thm_AlgebraicGeometry_Polarisation_ThetaPt_one_act
import Theorems.Thm_AlgebraicGeometry_Polarisation_ThetaPt_ofScalar_act
import Theorems.Thm_AlgebraicGeometry_PolarisedAbelianScheme_thetaPt_eq_of_pt_eq_of_forall_act_eq
import Theorems.Thm_AlgebraicGeometry_PolarisedAbelianScheme_exists_levelLifts_of_commutatorPairing_eq_pow
import Definitions.Def_P2M_Util

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicGeometry_PolarisedAbelianScheme_exists_levelLifts_of_rootedSymmetricOfType
p2m_attr_erase "instance" "PresheafOfModules.PullbackMonoidal.pullback_monoidal PresheafOfModules.PullbackMonoidal.isIso_δ PresheafOfModules.pushforward_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_η PresheafOfModules.free_monoidal PresheafOfModules.restrictScalars_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_δ_gS PresheafOfModules.pullback_oplaxMonoidal PresheafOfModules.PullbackMonoidal.instPreservesColimitsOfSizeCompOppositeCommRingCatRingCatForget₂RingHomCarrierCarrierPb PresheafOfModules.pullback_monoidal' AlgebraicGeometry.Scheme.Modules.preservesBinaryProducts_opensMap AlgebraicGeometry.Scheme.Modules.pullback_monoidal AlgebraicGeometry.Scheme.Modules.sheafify_isLocalization' AlgebraicGeometry.Scheme.Modules.preservesTerminal_opensMap AlgebraicGeometry.Scheme.Modules.pullback₀_monoidal AlgebraicGeometry.Scheme.Modules.preservesFiniteProducts_opensMap AlgebraicGeometry.Scheme.Modules.instLiftingPresheafOfModulesSheafifyPresheafWOpensCarrierCarrierCommRingCatGrothendieckTopologyObjFunctorOppositeIsSheafSheafCompPullback₀Pullback AlgebraicGeometry.ThetaLevel.Heis.instInv AlgebraicGeometry.ThetaLevel.Heis.Gam.instFinite AlgebraicGeometry.ThetaLevel.Heis.instMul AlgebraicGeometry.ThetaLevel.Heis.Gam.instFintype AlgebraicGeometry.ThetaLevel.Heis.instGroup AlgebraicGeometry.ThetaLevel.Heis.instDecidableEq AlgebraicGeometry.ThetaLevel.Heis.instOne AlgebraicGeometry.ThetaLevel.Heis.instFintype TwoChartCech.Sections.M0_moduleA TwoChartCech.Sections.M1_module TwoChartCech.Cover.A01_algebra TwoChartCech.Cover.A0_algebra TwoChartCech.Cover.A1_commRing TwoChartCech.Cover.A1_algebra TwoChartCech.Sections.M01_module TwoChartCech.Sections.M0_addCommGroup TwoChartCech.Sections.M0_tower TwoChartCech.Sections.M01_addCommGroup TwoChartCech.Cover.A0_commRing TwoChartCech.Sections.M1_tower TwoChartCech.Sections.M01_moduleA TwoChartCech.Sections.M0_module TwoChartCech.Sections.M1_moduleA"
p2m_attr_erase "instance" "TwoChartCech.Sections.M1_addCommGroup TwoChartCech.Cover.A01_commRing TwoChartCech.Sections.M01_tower CoherentBaseChange.TwoTermComplex.C0_module CoherentBaseChange.TwoTermComplex.C0_addCommGroup CoherentBaseChange.TwoTermComplex.C1_module CoherentBaseChange.TwoTermComplex.C1_addCommGroup CoherentBaseChange.TwoTermComplex.C0_free CoherentBaseChange.TwoTermComplex.C1_finite CoherentBaseChange.TwoTermComplex.C0_finite CoherentBaseChange.TwoTermComplex.C1_free AlgebraicGeometry.SubalgebraStages.compactSpace_pullback AlgebraicGeometry.SubalgebraStages.quasiSeparatedSpace_pullback AlgebraicGeometry.SubalgebraStages.compactSpace_obj AlgebraicGeometry.SubalgebraStages.quasiSeparatedSpace_obj AlgebraicGeometry.SubalgebraStages.quasiCompact_snd AlgebraicGeometry.SubalgebraStages.isAffineHom_leg AlgebraicGeometry.SubalgebraStages.isAffineHom_trans AlgebraicGeometry.SubalgebraStages.isAffineHom_diagram_map AlgebraicGeometry.SubalgebraStages.quasiSeparated_snd AlgebraicGeometry.SubalgebraStages.isCofiltered_op IsDirectLimit.Module.instDirectLimitCoeLinearMapIdOfOfNonempty AdicCompletion.instIsLocalRingMaximalIdeal AlgebraicGeometry.OModulePresheaf.isScalarTower AlgebraicGeometry.Scheme.OrderedAffineCover.instLinearOrder AlgebraicGeometry.OModulePresheaf.module AlgebraicGeometry.Scheme.OrderedAffineCover.instFintype AlgebraicGeometry.Scheme.OrderedAffineCover.instFintypeIdx AlgebraicGeometry.OModulePresheaf.addCommGroup AlgebraicGeometry.Scheme.OrderedAffineCover.instDecidableEqIdx AlgebraicGeometry.OModulePresheaf.moduleSections AlgebraicGeometry.OModulePresheaf.instSubsingletonObjZero AlgebraicGeometry.OModulePresheaf.Leray.relAltC_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_modΓ AlgebraicGeometry.OModulePresheaf.Leray.relAltC_modΓ AlgebraicGeometry.OModulePresheaf.Leray.biC_abGrp AlgebraicGeometry.OModulePresheaf.Leray.relAltH_modΓ AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_smul AlgebraicGeometry.OModulePresheaf.Leray.relAltH_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.relAltH_smul"
p2m_attr_erase "instance" "AlgebraicGeometry.OModulePresheaf.Leray.biC_module AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instDecidableEqIdx AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintype AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instLinearOrder AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintypeIdx DoubleComplex.instModuleE₂I DoubleComplex.Bounded.modR DoubleComplex.instModuleE₂II DoubleComplex.instAddCommGroupE₂II DoubleComplex.Bounded.abGrp DoubleComplex.instAddCommGroupE₂I ProjSpaceCech.GradedModule.H.module ProjSpaceCech.GradedModule.H.addCommGroup ProjSpaceCech.GradedModule.sec.instAdd ProjSpaceCech.GradedModule.sec.instNeg ProjSpaceCech.GradedModule.acg ProjSpaceCech.GradedModule.Frac.setoid ProjSpaceCech.GradedModule.modR ProjSpaceCech.GradedModule.sec.instModule ProjSpaceCech.GradedModule.sec.instAddCommGroup ProjSpaceCech.GradedModule.sec.instZero ProjSpaceCech.GradedModule.Presentation.fJ ProjSpaceCech.GradedModule.sec.instSMul ProjSpaceCech.Twist.H.module ProjSpaceCech.Idx.instFintype ProjSpaceCech.Twist.H.addCommGroup ProjSpaceCech.Idx.instDecidableEq ProjSpaceCech.Twist.Mon.instDecidableEq ProjSpaceCech.Twist.cochain.instAddCommGroup ProjSpaceCech.Twist.cochain.instModule AlgebraicGeometry.Scheme.Modules.GlueOfCocycle.instSMulCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensSubtypeForallMinMemAddSubgroupFamilies AlgebraicGeometry.Scheme.Modules.GlueOfCocycle.instModulePreGlue AlgebraicGeometry.Scheme.Modules.GlueOfCocycle.instModuleCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensSubtypeForallMinMemAddSubgroupFamilies SheafOfModules.isIso_ihomModelToIhom PresheafOfModules.ExteriorPower.instModulePresheafAb AlgebraicGeometry.Scheme.OrderedOpenFamily.instFintype AlgebraicGeometry.Scheme.OrderedOpenFamily.instDecidableEqIdx AlgebraicGeometry.Scheme.OrderedOpenFamily.instLinearOrder AlgebraicGeometry.Scheme.OrderedOpenFamily.instFintypeIdx CochainCx.Bounded.abGrp"
p2m_attr_erase "instance" "CochainCx.Bounded.modR instTopologicallyFGOfFiniteType AlgebraicCurve.CurveModel.isProper AlgebraicCurve.CurveModel.isIntegral AlgebraicCurve.CurveModel.smooth AlgebraicCurve.Place.instIsScalarTowerSubtypeMemValuationSubringToValuationSubring AlgebraicCurve.Divisor.instDistribMulActionAlgEquiv AlgebraicCurve.Place.instSMulAlgEquiv AlgebraicCurve.Place.instIsPrincipalIdealRingSubtypeMemValuationSubringToValuationSubring AlgebraicCurve.Place.instIsDiscreteValuationRingSubtypeMemValuationSubringToValuationSubring AlgebraicCurve.Pic0.instDistribMulActionAlgEquiv AlgebraicCurve.Place.instAlgebraSubtypeMemValuationSubringToValuationSubring AlgebraicCurve.Place.instMulActionAlgEquiv AlgebraicCurve.Pic0.instSMulAlgEquiv AlgebraicCurve.CurveModel.locallyOfFiniteType_gluedToBase AlgebraicCurve.CurveModel.isFractionRing_overlap AlgebraicCurve.CurveModel.isLocallyNoetherian_glued AlgebraicCurve.CurveModel.jacobsonSpace_glued AlgebraicCurve.CurveModel.isOpenImmersion_ι₀ AlgebraicCurve.CurveModel.isIntegral_glued AlgebraicCurve.CurveModel.quasiSeparated_gluedToBase AlgebraicCurve.CurveModel.compactSpace_glued AlgebraicCurve.CurveModel.isIntegral_adjoin_chartRing AlgebraicCurve.CurveModel.isFractionRing_overlap_functionField AlgebraicCurve.CurveModel.isProper_gluedToBase AlgebraicCurve.CurveModel.isOpenImmersion_ιU AlgebraicCurve.CurveModel.isOpenImmersion_f₀ AlgebraicCurve.CurveModel.isOpenImmersion_fInf AlgebraicCurve.CurveModel.isOpenImmersion_ιInf AlgebraicCurve.CurveModel.algebra_overlap_functionField AlgebraicCurve.CurveModel.quasiCompact_gluedToBase AlgebraicCurve.CurveModel.algebraAdjoin AlgebraicCurve.CurveModel.isDedekindDomain_chartRing AlgebraicCurve.CurveModel.isIntegralClosure AlgebraicCurve.CurveModel.finite_chartRing AlgebraicCurve.CurveModel.centre_isPrime AlgebraicCurve.CurveModel.isFractionRing_chartRing AlgebraicCurve.CurveModel.finiteType_chartRing AlgebraicCurve.CurveModel.isNoetherianRing_chartRing AlgebraicCurve.CurveModel.isScalarTower_base_adjoin"
p2m_attr_erase "instance" "AlgebraicCurve.CurveModel.isScalarTower_adjoin AlgebraicCurve.CurveModel.chartRing_finitePresentation AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation CerednikDrinfeld.ShimuraCurveModel.instFieldFc CerednikDrinfeld.ShimuraCurveModel.isCurveOverC CerednikDrinfeld.ShimuraCurveModel.essFiniteTypeF CerednikDrinfeld.ShimuraCurveModel.instFieldF CerednikDrinfeld.ShimuraCurveModel.instAlgebraFbar CerednikDrinfeld.ShimuraCurveModel.instAlgebraFc CerednikDrinfeld.ShimuraCurveModel.instFieldFbar CerednikDrinfeld.ShimuraCurveModel.essFiniteTypeC CerednikDrinfeld.ShimuraCurveModel.instFiniteTors CerednikDrinfeld.ShimuraCurveModel.isCurveOverF CerednikDrinfeld.ShimuraCurveModel.essFiniteTypeBar CerednikDrinfeld.ShimuraCurveModel.isCurveOverBar CerednikDrinfeld.ShimuraCurveModel.instAlgebraF IsDedekindDomain.HeightOneSpectrum.instAlgebraRatAdicCompletion IsDedekindDomain.HeightOneSpectrum.instModuleRatAdicCompletion AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupDivisor AlgebraicCurve.Pic0.instModuleZModTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instDistribMulActionTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instSMulTorsion AlgebraicCurve.SemilinearAut.instMulActionSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instSMulCommClassZModTorsion AlgebraicCurve.SemilinearAut.instMulSemiringActionSubtypeProdRingAutMemSubgroup AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue CerednikDrinfeld.TwoPlaceTorsionDatum.instAddCommGroup CerednikDrinfeld.TwoPlaceTorsionDatum.instFinite CerednikDrinfeld.JPrimeTorsionDatum.instAddCommGroup CerednikDrinfeld.JPrimeTorsionDatum.instFinite AlgebraicGeometry.SquareZero.isLocalRing' AlgebraicGeometry.SquareZero.isLocalRing kmfloorsGlue_int_three_isPrime"
p2m_attr_erase "instance" "kmfloorsGlue_int_bot_isPrime MvFormalGroup.instIsCommAddMv CerednikDrinfeld.BruhatTits.instGraphActionGLTree CerednikDrinfeld.BruhatTits.instMulActionGLVertex CerednikDrinfeld.BruhatTits.instGraphActionPGLTree CerednikDrinfeld.BruhatTits.instMulActionPGLVertex CerednikDrinfeld.Mumford.dartAction CerednikDrinfeld.FormalODModule.isComm MvFormalGroup.Hom.instNeg MvFormalGroup.End.instAddCommGroup MvFormalGroup.Hom.instAddCommGroup MvFormalGroup.End.instRing MvFormalGroup.End.instMonoid MvFormalGroup.End.instSemiring MvFormalGroup.End.instAddCommMonoid MvFormalGroup.Hom.instZero MvFormalGroup.Hom.instAdd MvFormalGroup.Hom.instAddCommMonoid AlgebraicGeometry.SmoothOfRelativeDimension.fiberToSpecResidueField AlgebraicGeometry.SmoothOfRelativeDimension.pullback_snd AlgebraicGeometry.SmoothOfRelativeDimension.pullback_fst AlgebraicGeometry.SmoothOfRelativeDimension.smooth_one AlgebraicGeometry.SmoothProperCurve.isIntegral_pullback_Spec_field AlgebraicGeometry.IsProper.fiberToSpecResidueField AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallyInjectiveFunUliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallySurjectiveFunUliftYonedaGluedToSheafOfIsLocallySurjectiveZariskiTopologyDescFunctorOppositeType AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsOpenImmersionToGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsIsoSheafZariskiTopologyTypeUliftYonedaGluedToSheaf AlgebraicGeometry.RelPicard.instIsOpenImmersionToGlued AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions AlgebraicGeometry.RelEffCartierDiv.subsingleton_of_degree_zero"
p2m_attr_erase "instance" "AlgebraicGeometry.RelEffCartierDiv.isIso_subschemeIota_snd_of_degree_one AlgebraicGeometry.isIso_ker_graphOver_subschemeIota_snd AlgebraicGeometry.isClosedImmersion_graphOver AlgebraicGeometry.FGSubalgebra.instIsDirectedLe AlgebraicGeometry.FGSubalgebra.instQuasiSeparatedSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsCofilteredOpposite AlgebraicGeometry.FGSubalgebra.instIsAffineObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instNonempty AlgebraicGeometry.FGSubalgebra.instNonemptySubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instCompactSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsDirectedSubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instIsAffineHomMapOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsFiltered AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instNeg AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulInt AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAddCommGroup AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAdd AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSub AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instModuleCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulNat AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instZero AlgebraicCurve.instHasLocalResidue_of_hasCanonicalLocalResidueK AlgebraicCurve.instHasCanonicalLocalResidueK_of_hasCanonicalLocalResidueKStar AlgebraicCurve.Place.kw_ffgc_finiteDimensional_adicCompletion instAlgebraSubtypeMemValuationSubring_definitions AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersIntegersCompletion ModularCurve.KwF4gRRTate.instAlgebraKAdicCompletionIntegers AlgebraicCurve.Place.kw_ffgc_continuousSMul_adicCompletionComap AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersCompletionCompletion IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instDimensionLEOneSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.instLiesOverSubtypeAdicCompletionMemValuationSubringAdicCompletionIntegersCompletionIdealAsIdeal IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsPrincipalIdealRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemSubringIntegerWithZeroMultiplicativeInt_definitions IsDedekindDomain.HeightOneSpectrum.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicCompletionV_definitions AlgebraicCurve.instHasCanonicalLocalResidueK AlgebraicCurve.Place.instAlgebra_restrictResidueField AlgebraicCurve.Place.instIsScalarTower_restrictResidueField AlgebraicCurve.instHasLocalResidue"
p2m_attr_erase "instance" "AlgebraicCurve.HasSeparableResidue.of_perfectField_of_isCurveOver AlgebraicCurve.HasSeparableResidue.of_perfectField AlgebraicCurve.Place.instIsLocalHom_restrictSubringHom AlgebraicCurve.instHasCanonicalLocalResidueKStar ModularCurve.KwNo6Pin.isLocalRing_completion AlgebraicGeometry.FGSubalgebra.tensorStage_directedSystem AlgebraicGeometry.RelEffCartierDiv.isClosedImmersion_subschemeι_resProdMap AlgebraicGeometry.RelEffCartierDiv.isOpenImmersion_resProdMap AlgebraicGeometry.ProjSpace.twistObj.addCommGroup AlgebraicGeometry.ProjSpace.twistFam.module AlgebraicGeometry.ProjSpace.twistObj.module AlgebraicGeometry.ProjSpace.twistObj.moduleSections AlgebraicGeometry.ProjSpace.twistFam.addCommGroup AlgebraicGeometry.OModulePresheaf.familyFramesGradedModule.moduleBase AlgebraicGeometry.OModulePresheaf.FamilyFrames.module AlgebraicGeometry.OModulePresheaf.FamilyFrames.addCommGroup"
p2m_attr_erase "simp" "AlgebraicGeometry.Scheme.Modules.tensorPow_zero AlgebraicGeometry.Scheme.Modules.tensorPow_succ AlgebraicGeometry.Scheme.Modules.tensorSections_zero_right AlgebraicGeometry.Scheme.Modules.map_unitSection AlgebraicGeometry.Scheme.Modules.tensorSectionsBilin_apply AlgebraicGeometry.Scheme.Modules.tensorPowSection_zero AlgebraicGeometry.Scheme.Modules.tensorSections_zero_left GoodReductionJacobian.RelativeGroupLaw.sndPoint_coe GoodReductionJacobian.RelativeGroupLaw.fstPoint_coe PresheafOfModules.freeεIso_hom_app PresheafOfModules.freeμIso_hom_app AlgebraicGeometry.ThetaLevel.Heis.theta_h AlgebraicGeometry.ThetaLevel.Heis.mk.injEq AlgebraicGeometry.ThetaLevel.Heis.one_k AlgebraicGeometry.ThetaLevel.Heis.mk.sizeOf_spec AlgebraicGeometry.ThetaLevel.Heis.mul_a AlgebraicGeometry.ThetaLevel.Heis.eta_a AlgebraicGeometry.ThetaLevel.Heis.mul_h AlgebraicGeometry.ThetaLevel.Heis.inv_k AlgebraicGeometry.ThetaLevel.Heis.mul_k AlgebraicGeometry.ThetaLevel.Heis.one_a AlgebraicGeometry.ThetaLevel.Heis.cen_a AlgebraicGeometry.ThetaLevel.Heis.one_h AlgebraicGeometry.ThetaLevel.Heis.theta_k AlgebraicGeometry.ThetaLevel.Heis.cen_k AlgebraicGeometry.ThetaLevel.Heis.theta_a AlgebraicGeometry.ThetaLevel.Heis.inv_h AlgebraicGeometry.ThetaLevel.diagOp_apply AlgebraicGeometry.ThetaLevel.Heis.cen_h AlgebraicGeometry.ThetaLevel.Heis.eta_h AlgebraicGeometry.ThetaLevel.shiftOp_apply AlgebraicGeometry.ThetaLevel.Heis.inv_a AlgebraicGeometry.ThetaLevel.Heis.eta_k AlgebraicGeometry.Scheme.Modules.toUnitSection_ofUnitSection AlgebraicGeometry.Scheme.Modules.pullbackSection_def AlgebraicGeometry.Scheme.Modules.ofUnitSection_toUnitSection AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_ofRelEffDivisor AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_I AlgebraicGeometry.mapOnProdOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.mk.sizeOf_spec"
p2m_attr_erase "simp" "AlgebraicGeometry.RelEffCartierDiv.mk.injEq AlgebraicGeometry.mapOnProdOver_snd AlgebraicGeometry.mapOnProdOver_fst AlgebraicGeometry.mapOnProdOver_snd_assoc AlgebraicGeometry.mapOnProdOver_id AlgebraicCurve.RelEffDivisor.mk.sizeOf_spec AlgebraicCurve.mapOnProd_fst AlgebraicCurve.mapOnProd_fst_assoc AlgebraicCurve.mapOnProd_snd AlgebraicCurve.UnivDivisorPack.mk.injEq AlgebraicCurve.RelEffDivisor.mk.injEq AlgebraicCurve.UnivDivisorPack.mk.sizeOf_spec AlgebraicCurve.mapOnProd_snd_assoc AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.injEq AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.sizeOf_spec AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U1 AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U0 TwoChartCech.Sections.mk.injEq TwoChartCech.Cover.mk.injEq TwoChartCech.GrothendieckComplex.mk.injEq TwoChartCech.Sections.mk.sizeOf_spec TwoChartCech.Cover.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r0_apply TwoChartCech.GrothendieckComplex.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r1_apply CoherentBaseChange.TwoTermComplex.mk.sizeOf_spec CoherentBaseChange.TwoTermComplex.mk.injEq AlgebraicGeometry.SubalgebraStages.specCone_π_app AlgebraicGeometry.SubalgebraStages.specLeg_specHom AlgebraicGeometry.SubalgebraStages.specLeg_specTrans AlgebraicGeometry.SubalgebraStages.cone_pt AlgebraicGeometry.SubalgebraStages.trans_fst AlgebraicGeometry.SubalgebraStages.diagram_obj AlgebraicGeometry.SubalgebraStages.leg_snd AlgebraicGeometry.SubalgebraStages.diagram_map AlgebraicGeometry.SubalgebraStages.specTrans_refl AlgebraicGeometry.SubalgebraStages.trans_snd AlgebraicGeometry.SubalgebraStages.specTrans_specHom AlgebraicGeometry.SubalgebraStages.specCone_pt AlgebraicGeometry.SubalgebraStages.cone_π_app"
p2m_attr_erase "simp" "AlgebraicGeometry.SubalgebraStages.specDiagram_map AlgebraicGeometry.SubalgebraStages.specDiagram_obj AlgebraicGeometry.SubalgebraStages.leg_fst AlgebraicGeometry.SubalgebraStages.leg_trans IsDirectLimit.Module.linearEquiv_symm_apply IsDirectLimit.linearEquiv_symm_apply IsDirectLimit.lift_of IsDirectLimit.Module.linearEquiv_apply IsDirectLimit.Module.lift_of IsDirectLimit.Equiv_apply RegularLocalRingQuotientAscent.dualNumberFst_apply GoodReductionJacobian.RelativeGroupLaw.baseChangePointToBase_ofBase GoodReductionJacobian.RelativeGroupLaw.baseChangePointToBase_coe GoodReductionJacobian.RelativeGroupLaw.baseChangePointOfBase_coe GoodReductionJacobian.RelativeGroupLaw.baseChange_inv GoodReductionJacobian.RelativeGroupLaw.baseChangePointOfBase_toBase GoodReductionJacobian.RelativeGroupLaw.baseChange_mul GoodReductionJacobian.RelativeGroupLaw.baseChange_one NeronSpecialFibreInfra.specialFibreRestrict_coe_comp_fst NeronSpecialFibreInfra.fibreRestrictAlong_coe_comp_snd NeronSpecialFibreInfra.fibreRestrictAlong_coe_comp_fst NeronSpecialFibreInfra.neronEndRestrictEquiv_apply NeronSpecialFibreInfra.fibreRestrictAlong_coe_comp_fst_assoc NeronSpecialFibreInfra.specialFibreRestrict_coe_comp_snd NeronSpecialFibreInfra.neronEndExtension_genericFibreRestrict NeronSpecialFibreInfra.specClosedFibreInclusion_eq NeronSpecialFibreInfra.specialFibreRestrict_coe_comp_fst_assoc NeronSpecialFibreInfra.specialFibreRestrict_coe_comp_snd_assoc NeronSpecialFibreInfra.genericFibreRestrict_neronEndExtension NeronSpecialFibreInfra.homOverId_coe NeronSpecialFibreInfra.homOverComp_coe NeronSpecialFibreInfra.fibreRestrictAlong_coe_comp_snd_assoc GoodReductionJacobian.RelativeGroupLaw.fibre_inv GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_coe GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_toBase GoodReductionJacobian.RelativeGroupLaw.fibre_mul GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_ofBase GoodReductionJacobian.RelativeGroupLaw.fibre_one GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_coe AlgebraicGeometry.schemeFibreEndo_snd"
p2m_attr_erase "simp" "AlgebraicGeometry.schemeFibreEndo_fst AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.sizeOf_spec GoodReductionJacobian.relativeGroupLawOfGrpObj_inv GoodReductionJacobian.relativeGroupLawOfGrpObj_mul GoodReductionJacobian.overHomEquivSchemeHomOver_apply_coe GoodReductionJacobian.relativeGroupLawOfGrpObj_one GoodReductionJacobian.overHomEquivSchemeHomOver_symm_apply_left GoodReductionJacobian.prodInr_comp_prodFst GoodReductionJacobian.RelativeGroupLaw.prod_inv GoodReductionJacobian.prodInl_comp_prodSnd GoodReductionJacobian.prodInr_comp_prodSnd GoodReductionJacobian.prodInl_comp_prodFst GoodReductionJacobian.prodFstPt_prodPairPt GoodReductionJacobian.prodFst_coe GoodReductionJacobian.prodSndPt_prodPairPt GoodReductionJacobian.RelativeGroupLaw.prod_one GoodReductionJacobian.prodPairPt_coe GoodReductionJacobian.prodPairPt_prodFstPt_prodSndPt GoodReductionJacobian.prodFstPt_coe GoodReductionJacobian.RelativeGroupLaw.prod_mul GoodReductionJacobian.prodSndPt_coe GoodReductionJacobian.prodSnd_coe AlgebraicGeometry.Scheme.OrderedAffineCover.mk.injEq AlgebraicGeometry.OModulePresheaf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.mk.injEq AlgebraicGeometry.OModulePresheaf.prod_obj AlgebraicGeometry.OModulePresheaf.restrOpen_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.injEq AlgebraicGeometry.OModulePresheaf.pushforward_obj AlgebraicGeometry.OModulePresheaf.im_obj AlgebraicGeometry.OModulePresheaf.pow_obj AlgebraicGeometry.OModulePresheaf.fstHom_app AlgebraicGeometry.OModulePresheaf.ker_obj AlgebraicGeometry.OModulePresheaf.coker_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.preimage_U"
p2m_attr_erase "simp" "AlgebraicGeometry.OModulePresheaf.sndHom_app AlgebraicGeometry.OModulePresheaf.Hom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.id_app AlgebraicGeometry.OModulePresheaf.AffHom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffHom.comp_app AlgebraicGeometry.OModulePresheaf.AffSES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.kerMap_coe AlgebraicGeometry.OModulePresheaf.AffHom.id_app AlgebraicGeometry.OModulePresheaf.Hom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.toAffHom_app AlgebraicGeometry.OModulePresheaf.SES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.comp_app AlgebraicGeometry.OModulePresheaf.SES.mk.injEq AlgebraicGeometry.OModulePresheaf.AffHom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffSES.mk.injEq AlgebraicGeometry.OModulePresheaf.Leray.restrictToPreimage_U AlgebraicGeometry.Scheme.OrderedAffineCover.toCoverOf_U AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.injEq AlgebraicGeometry.Scheme.OrderedAffineCover.restrict_U DoubleComplex.Bounded.mk.injEq DoubleComplex.Bounded.mk.sizeOf_spec DoubleComplex.Convergence.mk.injEq DoubleComplex.Convergence.mk.sizeOf_spec DoubleComplex.SubQuot.mk.sizeOf_spec DoubleComplex.SubQuot.mk.injEq ProjSpaceCech.GradedModule.mk.injEq ProjSpaceCech.GradedModule.mk.sizeOf_spec ProjSpaceCech.GradedModule.Frac.mk.sizeOf_spec ProjSpaceCech.GradedModule.Presentation.mk.injEq ProjSpaceCech.GradedModule.Frac.mk.injEq ProjSpaceCech.GradedModule.Presentation.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.shift_toLinearMap ProjSpaceCech.GradedModule.Hom.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.mk.injEq AlgebraicGeometry.Scheme.Modules.glueComponent_glueMk AlgebraicGeometry.Scheme.Modules.UnitCocycle.mk.injEq AlgebraicGeometry.Scheme.Modules.UnitCocycle.mk.sizeOf_spec"
p2m_attr_erase "simp" "PresheafOfModules.InternalHom.IsSheafAux.appAt_toPresheafHom SheafOfModules.ihomSectionsEquivFamily_unit AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_apply SheafOfModules.ihomEval_unit_app AlgebraicGeometry.Scheme.Modules.ihomEval_zero_right AlgebraicGeometry.Scheme.Modules.ihomEval_zero_left AlgebraicGeometry.Scheme.Modules.homOfFamily_app_apply SheafOfModules.unit_ihomSectionsEquivFamily AlgebraicGeometry.Scheme.Modules.familyOfHom_app AlgebraicGeometry.Scheme.Modules.restrictUnitIso_hom_app_apply AlgebraicGeometry.Scheme.Modules.restrictUnitIso_inv_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomOfFamily_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_symm_apply AlgebraicGeometry.tilde.functorCompPullbackSpecIso_app AlgebraicGeometry.Scheme.Hom.kaehlerPresheaf_obj PresheafOfModules.exteriorPower_map_ιMulti PresheafOfModules.ExteriorPower.appₗ_apply AlgebraicGeometry.Scheme.Modules.exteriorPower_obj AlgebraicGeometry.Scheme.OrderedOpenFamily.mk.injEq AlgebraicGeometry.Scheme.OrderedOpenFamily.mk.sizeOf_spec CochainCx.Bounded.mk.sizeOf_spec CochainCx.Bounded.mk.injEq AlgebraicCurve.CurveModel.mk.injEq AlgebraicCurve.CurveModel.mk.sizeOf_spec AlgebraicCurve.Place.mk.injEq AlgebraicCurve.Divisor.degree_single AlgebraicCurve.Divisor.smul_single AlgebraicCurve.Place.smul_toValuationSubring AlgebraicCurve.Place.heightOneSpectrum_asIdeal AlgebraicCurve.Place.coe_algebraMap AlgebraicCurve.Place.ord_one AlgebraicCurve.Place.coe_smulRingEquiv_apply AlgebraicCurve.Pic0.coe_degZeroSMulHom AlgebraicCurve.Place.deg_smul AlgebraicCurve.Pic0.mk_zero AlgebraicCurve.Place.mk.sizeOf_spec AlgebraicCurve.Divisor.degree_smul AlgebraicCurve.Pic0.mk_add AlgebraicCurve.Place.ord_zero AlgebraicCurve.Place.ofHeightOneSpectrum_toValuationSubring"
p2m_attr_erase "simp" "AlgebraicCurve.CurveModel.coe_gInf AlgebraicCurve.CurveModel.coe_tInvChart AlgebraicCurve.CurveModel.ιInf_gluedToBase_assoc AlgebraicCurve.CurveModel.ιInf_gluedToBase AlgebraicCurve.CurveModel.primeOfι₀_asIdeal AlgebraicCurve.CurveModel.coe_tChart AlgebraicCurve.CurveModel.ι₀_gluedToBase_assoc AlgebraicCurve.CurveModel.primeOfιInf_asIdeal AlgebraicCurve.CurveModel.ι₀_gluedToBase AlgebraicCurve.CurveModel.coe_tma AlgebraicCurve.CurveModel.coe_primeEquivChartPlaces AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint CerednikDrinfeld.QM.FakeEllipticCurve.FullLevel.mk.sizeOf_spec CerednikDrinfeld.QM.FakeEllipticCurve.FullLevel.mk.injEq CerednikDrinfeld.QM.FakeEllipticCurve.ExtraLevel.mk.injEq CerednikDrinfeld.QM.FakeEllipticCurve.ExtraLevel.mk.sizeOf_spec CerednikDrinfeld.ShimuraCurveModel.ModuliWitness.mk.injEq CerednikDrinfeld.QM.mapPt_coe CerednikDrinfeld.QM.FakeEllipticCurve.mk.injEq CerednikDrinfeld.QM.FakeEllipticCurve.mk.sizeOf_spec CerednikDrinfeld.ShimuraCurveModel.ModuliWitness.mk.sizeOf_spec CerednikDrinfeld.ShimuraCurveModel.mk.injEq CerednikDrinfeld.ShimuraCurveModel.coe_torsionHecke_apply CerednikDrinfeld.ShimuraCurveModel.galJ_apply CerednikDrinfeld.ShimuraCurveModel.heckeGenJ_apply CerednikDrinfeld.ShimuraCurveModel.coe_torsionGal_apply CerednikDrinfeld.ShimuraCurveModel.mk.sizeOf_spec CerednikDrinfeld.ShimuraCurveModel.signTwist_heckeGen CerednikDrinfeld.ShimuraCurveModel.coe_restrictTors_apply Submodule.finiteAdeleEvalAt_tmul Submodule.val_finiteIdeleDiagonal_apply QuaternionAlgebra.nrd_coe QuaternionAlgebra.nrd_one QuaternionAlgebra.trd_mk QuaternionAlgebra.nrd_mk"
p2m_attr_erase "simp" "QuaternionAlgebra.nrd_neg QuaternionAlgebra.nrd_zero QuaternionAlgebra.nrd_star ModularCurve.UniformizedHeckeCurve.mk.sizeOf_spec ModularCurve.UniformizedHeckeCurve.mk.injEq ModularCurve.ComplexPlaceDictionary.mk.injEq ModularCurve.ComplexPlaceDictionary.mk.sizeOf_spec ModularCurve.qExpand_coeff_mul ModularCurve.qExpandₐ_apply ModularCurve.jqN_one ModularCurve.qExpand_single ModularCurve.dedekindPsi_one ModularCurve.ModularPolynomialData.mk.sizeOf_spec ModularCurve.evalAtJ_X ModularCurve.ModularPolynomialData.mk.injEq ModularCurve.constantCoeff_jNum ModularCurve.constantCoeff_eisenstein4 ModularCurve.qExpand_C ModularCurve.coeff_jq_neg_one ModularCurve.constantCoeff_jNumQ ModularCurve.coeffEmb_coeff ModularCurve.coeffMap_coeff ModularCurve.coeffMap_id ModularCurve.coeffMap_single ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL AlgebraicCurve.SemilinearAut.toRingAut_inv AlgebraicCurve.SemilinearAut.smul_def AlgebraicCurve.SemilinearAut.smul_single AlgebraicCurve.SemilinearAut.smul_toValuationSubring AlgebraicCurve.SemilinearAut.baseAut_inv AlgebraicCurve.SemilinearAut.baseAut_ofAlgAut AlgebraicCurve.SemilinearAut.toRingAut_ofAlgAut"
p2m_attr_erase "simp" "AlgebraicCurve.SemilinearAut.torsionRep_apply AlgebraicCurve.SemilinearAut.toRingAut_one AlgebraicCurve.SemilinearAut.deg_smul AlgebraicCurve.SemilinearAut.degree_smul AlgebraicCurve.SemilinearAut.coe_degZeroSMulHom AlgebraicCurve.SemilinearAut.baseAut_mul AlgebraicCurve.SemilinearAut.coe_smulValuationSubringEquiv_apply AlgebraicCurve.SemilinearAut.baseAut_one AlgebraicCurve.SemilinearAut.ofAlgAut_smul AlgebraicCurve.SemilinearAut.coe_torsion_smul AlgebraicCurve.SemilinearAut.toRingAut_mul CerednikDrinfeld.TwoPlaceTorsionDatum.snd_T CerednikDrinfeld.TwoPlaceTorsionDatum.snd_toric CerednikDrinfeld.TwoPlaceTorsionDatum.mk.injEq CerednikDrinfeld.TwoPlaceTorsionDatum.fst_T CerednikDrinfeld.TwoPlaceTorsionDatum.mk.sizeOf_spec CerednikDrinfeld.TwoPlaceTorsionDatum.fst_D CerednikDrinfeld.TwoPlaceTorsionDatum.snd_D CerednikDrinfeld.TwoPlaceTorsionDatum.fst_toric CerednikDrinfeld.HeckeData.mk.sizeOf_spec CerednikDrinfeld.Matching.mk.injEq CerednikDrinfeld.DegeneracyData.mk.sizeOf_spec CerednikDrinfeld.DegeneracyData.mk.injEq CerednikDrinfeld.ribbonGram_apply CerednikDrinfeld.HeckeData.mk.injEq CerednikDrinfeld.Matching.mk.sizeOf_spec ModularCurve.widthPairing_apply ModularCurve.gramMap_apply ModularCurve.degreeOn_apply ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd AlgebraicGeometry.TangentPoints.map_coe AlgebraicGeometry.SquareZero.basePoint_toBase_assoc AlgebraicGeometry.SquareZero.basePoint_toBase AlgebraicGeometry.SquareZero.basePoint_specMap AlgebraicGeometry.SquareZero.basePointOver_coe AlgebraicGeometry.SquareZero.specMap_toBase_assoc AlgebraicGeometry.SquareZero.specMapOver_coe"
p2m_attr_erase "simp" "AlgebraicGeometry.RelPicard.TrivialModDeformations.map_coe AlgebraicGeometry.SquareZero.specMap_toBase AlgebraicGeometry.SquareZero.basePoint_specMap_assoc MvFormalGroup.mk.injEq MvFormalGroup.nthSeries_zero MvFormalGroup.Hom.mk.sizeOf_spec MvFormalGroup.Hom.mk.injEq MvFormalGroup.mk.sizeOf_spec AlgebraicGeometry.Scheme.nilpPoints_map_val LT.LatticeTree.IntegralAut.refl_toField LT.LatticeTree.vecPair_one LT.LatticeTree.IntegralAut.mk.sizeOf_spec LT.LatticeTree.galVec_refl LT.LatticeTree.mulVecPair_zero LT.LatticeTree.galVec_apply LT.LatticeTree.vecPair_zero LT.LatticeTree.IntegralAut.refl_toBase LT.LatticeTree.scalarGL_coe LT.LatticeTree.IntegralAut.mk.injEq LT.LatticeTree.IntegralAut.comp_toBase_apply LT.LatticeTree.IntegralAut.unitMap_coe LT.LatticeTree.latticeGal_refl LT.LatticeTree.gammaZero_coe LT.LatticeTree.Vertex.act_mk LT.LatticeTree.Vertex.galAct_mk LT.LatticeTree.transvectionGate_coe LT.LatticeTree.mulVecPair_one LT.LatticeTree.diagSnd_coe LT.LatticeTree.unitOfNeZero_coe LT.LatticeTree.IntegralAut.comp_toField_apply LT.LatticeTree.mulVecLinR_apply CerednikDrinfeld.BruhatTits.vertPermHom_apply CerednikDrinfeld.BruhatTits.gl_smul_mk CerednikDrinfeld.BruhatTits.pgl_mk_smul CerednikDrinfeld.SpecialFormal.Rigidified.mk.injEq CerednikDrinfeld.FormalODModule.actRingHom_apply CerednikDrinfeld.SpecialFormalODModule.mk.sizeOf_spec CerednikDrinfeld.FormalODModule.Hom.mk.injEq CerednikDrinfeld.FormalODModule.map_id CerednikDrinfeld.SpecialFormal.Series.map_id"
p2m_attr_erase "simp" "CerednikDrinfeld.SpecialFormal.Rigidified.mk.sizeOf_spec CerednikDrinfeld.SpecialFormal.ModuliPackage.twist_obj CerednikDrinfeld.SpecialFormalODModule.mk.injEq CerednikDrinfeld.FormalODModule.map_varpi CerednikDrinfeld.FormalODModule.map_act CerednikDrinfeld.SpecialFormal.ModuliPackage.mk.injEq CerednikDrinfeld.FormalODModule.mk.injEq CerednikDrinfeld.FormalODModule.Hom.mk.sizeOf_spec CerednikDrinfeld.SpecialFormal.ModuliPackage.mk.sizeOf_spec CerednikDrinfeld.FormalODModule.map_F CerednikDrinfeld.SpecialFormal.Rigidified.map_n CerednikDrinfeld.SpecialFormal.Rigidified.map_ρ CerednikDrinfeld.SpecialFormal.IsLawHom.toHom_toPowerSeries CerednikDrinfeld.SpecialFormal.Series.map_ringHom_id CerednikDrinfeld.FormalODModule.actEnd_toPowerSeries CerednikDrinfeld.SpecialFormal.Rigidified.map_X CerednikDrinfeld.FormalODModule.varpiEnd_toPowerSeries CerednikDrinfeld.FormalODModule.mk.sizeOf_spec MvFormalGroup.Hom.toPowerSeries_sub MvFormalGroup.linearPartHom_intCast MvFormalGroup.constantCoeff_negSeries MvFormalGroup.toPowerSeries_invHom MvFormalGroup.linearPartHom_neg MvFormalGroup.End.toPowerSeries_sub MvFormalGroup.End.toPowerSeries_neg MvFormalGroup.constantCoeff_invSeries MvFormalGroup.negApprox_zero MvFormalGroup.Hom.toPowerSeries_neg MvFormalGroup.Hom.toPowerSeries_neg' MvFormalGroup.linearPartHom_apply MvFormalGroup.linearPart_zero MvFormalGroup.linearPart_X MvFormalGroup.End.toPowerSeries_mul MvFormalGroup.Hom.toPowerSeries_add MvFormalGroup.End.toPowerSeries_add MvFormalGroup.End.toPowerSeries_one MvFormalGroup.End.toPowerSeries_zero MvFormalGroup.Hom.toPowerSeries_zero MvFormalGroup.linearPartHom_natCast MvFormalGroup.Hom.toPowerSeries_zero'"
p2m_attr_erase "simp" "MvFormalGroup.End.toPowerSeries_natCast GoodReductionJacobian.BareDeformation.mk.sizeOf_spec GoodReductionJacobian.BareDeformation.mk.injEq AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_snd AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_fst AlgebraicCurve.mulAdele_apply AlgebraicCurve.residuePairing_apply_coe AlgebraicCurve.mem_adeleBdd AlgebraicCurve.weilSmul_one AlgebraicCurve.diagonalHom_apply AlgebraicCurve.weilSmul_apply AlgebraicCurve.adeleSpaceMul_coe AlgebraicCurve.mulAdele_one AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U1 AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.injEq AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U0 AlgebraicGeometry.RelPicard.SubPicCondition.onClasses_mk AlgebraicGeometry.RelPicard.relSubPicPresheaf_map_coe CategoryTheory.Functor.OverTotal.ofFibre_fst CategoryTheory.Functor.overTotal_map_fst AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_J AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t' AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf_assoc AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_toGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_openCover_map AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_comp AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_V AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_U AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_f AlgebraicGeometry.RelPicard.designationOfRepresentableBy_P AlgebraicGeometry.RelPicard.designationOfRepresentableBy_toBase AlgebraicGeometry.RelPicard.rigSection_snd AlgebraicGeometry.RelPicard.RigidifiedLineBundle.ofInvertible_L AlgebraicGeometry.RelPicard.rigSection_snd_assoc AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.sizeOf_spec AlgebraicCurve.coe_cechH0Equiv_apply"
p2m_attr_erase "simp" "AlgebraicCurve.cechH1ToH1_mk AlgebraicCurve.lSpaceOn_univ AlgebraicCurve.lSpaceOn_empty AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff"
p2m_attr_erase "simp" "ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one AlgebraicCurve.Place.differentialCoeff_zero AlgebraicCurve.Place.differentialCoeff_dCoord AlgebraicCurve.TranscendenceTower.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.injEq AlgebraicCurve.TranscendenceTower.mk.injEq AlgebraicCurve.PoleDivisorPackage.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.sizeOf_spec AlgebraicCurve.PoleDivisorPackage.mk.injEq AlgebraicGeometry.RelPicard.thetaBundle_def AlgebraicGeometry.RelPicard.picardBundle_def AlgebraicGeometry.prodKerGraph_one AlgebraicGeometry.fibrePowOver.proj_comp AlgebraicGeometry.prodKerGraph_zero AlgebraicGeometry.RelEffCartierDiv.empty_I AlgebraicGeometry.fibrePowOver.proj_comp_assoc AlgebraicGeometry.graphOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.toPoint_comp AlgebraicGeometry.RelEffCartierDiv.toPoint_comp_assoc AlgebraicGeometry.graphOver_fst AlgebraicGeometry.RelEffCartierDiv.ofPoint_I AlgebraicGeometry.graphOver_snd AlgebraicGeometry.graphOver_snd_assoc AlgebraicCurve.SymmetricPowerPackage.mk.sizeOf_spec AlgebraicCurve.SymmetricPowerPackage.mk.injEq AlgebraicGeometry.FGSubalgebra.cocone_ι_app_apply AlgebraicGeometry.RelPicard.fst_toProdSpec AlgebraicGeometry.RelPicard.toProdSpec_fst_assoc AlgebraicGeometry.RelPicard.pointsSubBasepointModule_cons"
p2m_attr_erase "simp" "AlgebraicGeometry.RelPicard.pointsSubBasepointModule_nil AlgebraicGeometry.RelPicard.fst_toProdSpec_assoc AlgebraicGeometry.RelPicard.toProdSpec_fst AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.sub_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sresTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.add_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.sizeOf_spec AlgebraicGeometry.Scheme.IdealSheafData.coe_resLE AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.smul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_ofLE_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.ideal_range AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zero_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sres AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.comp_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.neg_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.id_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_mulRight_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.nsmul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.injEq AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zsmul_app AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.sizeOf_spec AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.injEq AlgebraicCurve.adeleSingle_coe AlgebraicCurve.kaehlerResidueTermKFam_apply AlgebraicCurve.Place.LocalResidueData.mk.injEq AlgebraicCurve.Place.LocalResidueData.mk.sizeOf_spec AlgebraicCurve.Place.kw_ffgc_adicCompletionComapIntegers_coe AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.sizeOf_spec AlgebraicCurve.Place.mem_simplePoleSubmodule AlgebraicCurve.Place.coe_uniformizerSubring ModularCurve.Lg37.Lg37CompletionSection.mk.injEq AlgebraicCurve.Place.CoefficientFieldSection.mk.injEq AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.injEq ModularCurve.Lg37.Lg37CompletionSection.mk.sizeOf_spec AlgebraicCurve.Place.CoefficientFieldSection.mk.sizeOf_spec AlgebraicCurve.Place.poleSubmodule_one AlgebraicCurve.Place.mem_poleSubmodule TwoChartCech.Mumford.dK_apply TwoChartCech.Mumford.ι0_apply TwoChartCech.Mumford.ι1_apply"
p2m_attr_erase "simp" "TwoChartCech.KerCoprod.dK_apply TwoChartCech.KerCoprod.ι1_apply TwoChartCech.KerCoprod.ι0_apply AlgebraicGeometry.RelPicard.algEquivZeroGroupCut_toSubPicCondition AlgebraicGeometry.RelPicard.LFP.stageHom_val AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_hom_app_coe AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_inv_app_coe AlgebraicGeometry.RelPicard.BaseChange.restrict_P AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp AlgebraicGeometry.RelEffCartierDiv.functor_map_fst AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_pullbackAlong AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_symm_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp_assoc AlgebraicGeometry.RelEffCartierDiv.supportedIn_top AlgebraicGeometry.RelEffCartierDiv.mem_supportedIn_iff AlgebraicGeometry.RelEffCartierDiv.supportedIn_top_eq AlgebraicGeometry.RelEffCartierDiv.restrictAlong_extendAlong AlgebraicGeometry.RelEffCartierDiv.extendAlong_I AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd AlgebraicGeometry.RelEffCartierDiv.restrictAlong_I AlgebraicGeometry.RelEffCartierDiv.extendAlong_restrictAlong AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst CoherentBaseChange.FibreH0Family.mk.sizeOf_spec CoherentBaseChange.FibreH0Family.mk.injEq AlgebraicGeometry.ProjSpace.twistObj.mk.injEq AlgebraicGeometry.ProjSpace.twistObj.zero_val AlgebraicGeometry.ProjSpace.twistObj.add_val AlgebraicGeometry.ProjSpace.twist_res_val AlgebraicGeometry.ProjSpace.twist_smul_val AlgebraicGeometry.ProjSpace.twistGradeToObj_val AlgebraicGeometry.ProjSpace.twistObj.smul_val AlgebraicGeometry.ProjSpace.twistGradeEquiv_apply_val AlgebraicGeometry.ProjSpace.twistObj.mk.sizeOf_spec"

set_option autoImplicit false

p2m_open "CategoryTheory CategoryTheory.Limits AlgebraicGeometry P2MW.S_AlgebraicGeometry_PolarisedAbelianScheme_exists_levelLifts_of_rootedSymmetricOfType.AlgebraicGeometry NeronModelInfra GoodReductionJacobian AlgebraicGeometry.Polarisation P2MW.S_AlgebraicGeometry_PolarisedAbelianScheme_exists_levelLifts_of_rootedSymmetricOfType.AlgebraicGeometry.Polarisation"
open scoped BigOperators

noncomputable section

namespace AlgebraicGeometry
p2m_export "AlgebraicGeometry" "Spec.map_comp Surjective Scheme.Modules.pullback Spec Spec.map Scheme Flat Scheme.Modules.pullbackCongr Spec.map_id Etale Scheme.Modules Scheme.Modules.pullbackComp Polarisation.MemKernel PolarisedAbelianScheme.RootedSymmetricOfType PolarisedAbelianScheme Scheme.Modules.pullbackLocalSection PolarisedAbelianScheme.exists_levelLifts_pi_of_forall_exists_levelLifts PolarisedAbelianScheme.exists_cover_thetaPt_pt_eq_of_memKernel PolarisedAbelianScheme.exists_commutatorPairing_of_thetaPt PolarisedAbelianScheme.forall_eq_zero_of_commutatorPairing_of_rootedSymmetricOfType PolarisedAbelianScheme.thetaPt_eq_of_pt_eq_of_forall_act_eq PolarisedAbelianScheme.exists_levelLifts_of_commutatorPairing_eq_pow"
namespace Polarisation
p2m_export "AlgebraicGeometry.Polarisation" "ThetaPt.mul_pt ThetaPt.ofUnit ThetaPt.ofScalar ThetaPt.ofScalar_pt ThetaPt baseScalar MemKernel ThetaPt.exists_monoidHom_pt_comp_eq_act_eq_of_isPullback ThetaPt.mul_act ThetaPt.ofScalar_act"
namespace TA
p2m_open "AlgebraicGeometry.Polarisation AlgebraicGeometry"

variable {S : Type} [CommRing S] {A : Scheme.{0}} (f : A ⟶ Spec (CommRingCat.of S)) (L : RelativeGroupLaw S f)
  (𝓛 : A.Modules) {R R' : Type} [CommRing R] [CommRing R']
  (t : Spec (CommRingCat.of R) ⟶ Spec (CommRingCat.of S)) (t' : Spec (CommRingCat.of R') ⟶ Spec (CommRingCat.of S))
  (ψ : R →+* R') (hr : Spec.map (CommRingCat.ofHom ψ) ≫ t = t')

def b : pullback f t' ⟶ pullback f t :=
  pullback.lift (pullback.fst f t' ≫ 𝟙 A) (pullback.snd f t' ≫ Spec.map (CommRingCat.ofHom ψ)) (by
    rw [Category.assoc, Category.id_comp, pullback.condition, Category.assoc, hr])

theorem b_fst : b f t t' ψ hr ≫ pullback.fst f t = pullback.fst f t' ≫ 𝟙 A := pullback.lift_fst _ _ _

theorem b_fst' : b f t t' ψ hr ≫ pullback.fst f t = pullback.fst f t' := by rw [b_fst, Category.comp_id]

theorem b_snd : b f t t' ψ hr ≫ pullback.snd f t = pullback.snd f t' ≫ Spec.map (CommRingCat.ofHom ψ) :=
  pullback.lift_snd _ _ _

def c : (Scheme.Modules.pullback (b f t t' ψ hr)).obj ((Scheme.Modules.pullback (pullback.fst f t)).obj 𝓛) ≅
    (Scheme.Modules.pullback (pullback.fst f t')).obj 𝓛 :=
  (Scheme.Modules.pullbackComp (b f t t' ψ hr) _).app 𝓛 ≪≫ (Scheme.Modules.pullbackCongr (b_fst' f t t' ψ hr)).app 𝓛

theorem isPullback_id : IsPullback (𝟙 A) f f (Spec.map (CommRingCat.ofHom (RingHom.id S))) := by
  rw [CommRingCat.ofHom_id, Spec.map_id]
  exact IsPullback.id_horiz f

theorem mul_congr_base {T : Scheme.{0}} {t₁ t₂ : T ⟶ Spec (CommRingCat.of S)} (h : t₁ = t₂)
    (x y : SchemeHomOver t₁ f) :
    (L.mul t₁ x y).1 = (L.mul t₂ ⟨x.1, h ▸ x.2⟩ ⟨y.1, h ▸ y.2⟩).1 := by
  subst h; rfl

theorem hmul_id {T : Scheme.{0}} (t'' : T ⟶ Spec (CommRingCat.of S)) (x y : SchemeHomOver t'' f) :
    (L.mul t'' x y).1 ≫ 𝟙 A =
      (L.mul (t'' ≫ Spec.map (CommRingCat.ofHom (RingHom.id S)))
        ⟨x.1 ≫ 𝟙 A, by rw [Category.assoc, (isPullback_id f).w, ← Category.assoc, x.2]⟩
        ⟨y.1 ≫ 𝟙 A, by rw [Category.assoc, (isPullback_id f).w, ← Category.assoc, y.2]⟩).1 := by
  have ht : t'' = t'' ≫ Spec.map (CommRingCat.ofHom (RingHom.id S)) := by
    rw [CommRingCat.ofHom_id, Spec.map_id, Category.comp_id]
  rw [Category.comp_id, mul_congr_base f L ht x y]
  congr 2 <;> exact Subtype.ext (Category.comp_id _).symm

include hr in
theorem hr' : Spec.map (CommRingCat.ofHom ψ) ≫ t = t' ≫ Spec.map (CommRingCat.ofHom (RingHom.id S)) := by
  rw [CommRingCat.ofHom_id, Spec.map_id, Category.comp_id, hr]

theorem exists_monoidHom_transport :
    ∃ β : ThetaPt f L 𝓛 t →* ThetaPt f L 𝓛 t',
      (∀ θ, (β θ).pt.1 = Spec.map (CommRingCat.ofHom ψ) ≫ θ.pt.1) ∧
      (∀ θ (s : Γ((Scheme.Modules.pullback (pullback.fst f t)).obj 𝓛, ⊤)),
        (β θ).act ((c f 𝓛 t t' ψ hr).hom.app ⊤ (Scheme.Modules.pullbackLocalSection (b f t t' ψ hr) s :
            Γ((Scheme.Modules.pullback (b f t t' ψ hr)).obj ((Scheme.Modules.pullback (pullback.fst f t)).obj 𝓛), ⊤))) =
          (c f 𝓛 t t' ψ hr).hom.app ⊤ (Scheme.Modules.pullbackLocalSection (b f t t' ψ hr) (θ.act s) :
            Γ((Scheme.Modules.pullback (b f t t' ψ hr)).obj ((Scheme.Modules.pullback (pullback.fst f t)).obj 𝓛), ⊤))) ∧
      (∀ v : Rˣ, β (ThetaPt.ofScalar v) = ThetaPt.ofScalar (Units.map (ψ : R →* R') v)) ∧
      (∀ w : Γ(pullback f t, ⊤)ˣ,
        β (ThetaPt.ofUnit w) = ThetaPt.ofUnit (Units.map ((b f t t' ψ hr).appTop.hom : _ →* _) w)) := by
  obtain ⟨β, h1, h2, h3, h4⟩ := ThetaPt.exists_monoidHom_pt_comp_eq_act_eq_of_isPullback (RingHom.id S) L L (𝟙 A)
    (isPullback_id f) (fun t'' x y => hmul_id f L t'' x y) 𝓛 𝓛 t t' ψ (hr' t t' ψ hr)
    (b f t t' ψ hr) (b_fst f t t' ψ hr) (b_snd f t t' ψ hr) (c f 𝓛 t t' ψ hr)
  refine ⟨β, fun θ => ?_, h2, h3, h4⟩
  have := h1 θ
  rwa [Category.comp_id] at this

theorem hr_algebraMap (R R' : Type) [CommRing R] [CommRing R'] [Algebra S R] [Algebra S R'] [Algebra R R']
    [IsScalarTower S R R'] :
    Spec.map (CommRingCat.ofHom (algebraMap R R')) ≫ Spec.map (CommRingCat.ofHom (algebraMap S R)) =
      Spec.map (CommRingCat.ofHom (algebraMap S R')) := by
  rw [← Spec.map_comp, ← CommRingCat.ofHom_comp, ← IsScalarTower.algebraMap_eq]

end AlgebraicGeometry.Polarisation.TA

namespace AlgebraicGeometry
p2m_export "AlgebraicGeometry" "Spec.map_comp Surjective Scheme.Modules.pullback Spec Spec.map Scheme Flat Scheme.Modules.pullbackCongr Spec.map_id Etale Scheme.Modules Scheme.Modules.pullbackComp Polarisation.MemKernel PolarisedAbelianScheme.RootedSymmetricOfType PolarisedAbelianScheme Scheme.Modules.pullbackLocalSection PolarisedAbelianScheme.exists_levelLifts_pi_of_forall_exists_levelLifts PolarisedAbelianScheme.exists_cover_thetaPt_pt_eq_of_memKernel PolarisedAbelianScheme.exists_commutatorPairing_of_thetaPt PolarisedAbelianScheme.forall_eq_zero_of_commutatorPairing_of_rootedSymmetricOfType PolarisedAbelianScheme.thetaPt_eq_of_pt_eq_of_forall_act_eq PolarisedAbelianScheme.exists_levelLifts_of_commutatorPairing_eq_pow"
namespace PolarisedAbelianScheme
p2m_export "AlgebraicGeometry.PolarisedAbelianScheme" "IsOfType RootedSymmetricOfType IsPullback L A P f comm pol mk exists_levelLifts_pi_of_forall_exists_levelLifts exists_cover_thetaPt_pt_eq_of_memKernel exists_commutatorPairing_of_thetaPt forall_eq_zero_of_commutatorPairing_of_rootedSymmetricOfType thetaPt_eq_of_pt_eq_of_forall_act_eq exists_levelLifts_of_commutatorPairing_eq_pow"
namespace LevelLift
p2m_open "AlgebraicGeometry.PolarisedAbelianScheme AlgebraicGeometry"

variable {g d n : ℕ} (δ : Fin g → ℕ) [∀ i, NeZero (δ i)]

def HasLevelLifts {S : Type} [CommRing S] (u : PolarisedAbelianScheme g d n S) {R : Type} [CommRing R] (φ : S →+* R)
    (ζ : Rˣ) : Prop :=
  ∃ (lift : ((i : Fin g) → ZMod (δ i)) → ThetaPt u.f u.L u.pol (Spec.map (CommRingCat.ofHom φ)))
    (dualLift : (((i : Fin g) → ZMod (δ i)) →+ ZMod d) → ThetaPt u.f u.L u.pol (Spec.map (CommRingCat.ofHom φ))),
    lift 0 = 1 ∧ (∀ h h' : ((i : Fin g) → ZMod (δ i)), lift (h + h') = lift h * lift h') ∧
    dualLift 0 = 1 ∧ (∀ c c' : ((i : Fin g) → ZMod (δ i)) →+ ZMod d, dualLift (c + c') = dualLift c * dualLift c') ∧
    (∀ (c : ((i : Fin g) → ZMod (δ i)) →+ ZMod d) (h : ((i : Fin g) → ZMod (δ i))),
      dualLift c * lift h = ThetaPt.ofScalar (ζ ^ (c h).val) * (lift h * dualLift c))

def IsTypePoints {S : Type} [CommRing S] (u : PolarisedAbelianScheme g d n S) {R : Type} [CommRing R] (φ : S →+* R)
    (x : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → SchemeHomOver (Spec.map (CommRingCat.ofHom φ)) u.f) : Prop :=
  (x 0 = u.L.one _ ∧ ∀ h h' : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))), x (h + h') = u.L.mul _ (x h) (x h')) ∧
  (∀ (k : Type) [Field k] [IsAlgClosed k] (sk : R →+* k) (h h' : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i)))),
    Spec.map (CommRingCat.ofHom sk) ≫ (x h).1 = Spec.map (CommRingCat.ofHom sk) ≫ (x h').1 → h = h') ∧
  (∀ (R'' : Type) [CommRing R''] [Algebra R R'']
    (y : SchemeHomOver (Spec.map (CommRingCat.ofHom ((algebraMap R R'').comp φ))) u.f),
    Polarisation.MemKernel u.f u.L u.pol _ y ↔
      ∃ (m : ℕ) (r : Fin m → R''), Ideal.span (Set.range r) = ⊤ ∧ ∀ j, ∃ h : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))),
        Spec.map (CommRingCat.ofHom (algebraMap R'' (Localization.Away (r j)))) ≫ y.1 =
          Spec.map (CommRingCat.ofHom ((algebraMap R'' (Localization.Away (r j))).comp (algebraMap R R''))) ≫ (x h).1)

theorem memKernel_congr_base {S : Type} [CommRing S] {A : Scheme.{0}} (f : A ⟶ Spec (CommRingCat.of S))
    (L : RelativeGroupLaw S f) (𝓛 : A.Modules) {R : Type} [CommRing R]
    {t₁ t₂ : Spec (CommRingCat.of R) ⟶ Spec (CommRingCat.of S)} (h : t₁ = t₂) (y : SchemeHomOver t₁ f)
    (hy : y.1 ≫ f = t₂) :
    Polarisation.MemKernel f L 𝓛 t₁ y ↔ Polarisation.MemKernel f L 𝓛 t₂ ⟨y.1, hy⟩ := by
  subst h; rfl

theorem exists_cyclotomic_typePoints (hδd : ∏ i, δ i = d)
    {S : Type} [CommRing S] (hd : IsUnit ((d : ℕ) : S))
    (u : PolarisedAbelianScheme g d n S) (hu : PolarisedAbelianScheme.RootedSymmetricOfType δ S u) :
    ∃ (S₁ : Type) (_ : CommRing S₁) (_ : Algebra S S₁),
      Module.FaithfullyFlat S S₁ ∧ Algebra.Etale S S₁ ∧
      ∃ (ζ : S₁ˣ), (ζ : S₁) ^ d = 1 ∧ (∀ j : ℕ, 0 < j → j < d → IsUnit (1 - (ζ : S₁) ^ j)) ∧
      ∃ x : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → SchemeHomOver (Spec.map (CommRingCat.ofHom (algebraMap S S₁))) u.f,
        IsTypePoints δ u (algebraMap S S₁) x := by
  classical
  haveI : NeZero d := ⟨fun h0 => by
    exact (Finset.prod_ne_zero_iff.mpr fun i _ => NeZero.ne (δ i)) (hδd.trans h0)⟩
  obtain ⟨-, hOT, -⟩ := hu
  obtain ⟨S', instS', algS', ffS', etS', x, hxhom, hxinj, hxker⟩ := hOT

  have hd' : IsUnit ((d : ℕ) : S') := by simpa using hd.map (algebraMap S S')
  obtain ⟨-, -, ff₁, et₁, -⟩ := AdjoinRoot.finite_free_faithfullyFlat_etale_cyclotomic_of_isUnit S' d hd'
  let S₁ : Type := AdjoinRoot (Polynomial.cyclotomic d S')
  let ζ₀ : S₁ := AdjoinRoot.root (Polynomial.cyclotomic d S')
  have hζd : ζ₀ ^ d = 1 := by
    have h1 : AdjoinRoot.mk (Polynomial.cyclotomic d S') (Polynomial.X ^ d - 1) = 0 :=
      AdjoinRoot.mk_eq_zero.mpr (Polynomial.cyclotomic.dvd_X_pow_sub_one d S')
    rw [map_sub, map_pow, AdjoinRoot.mk_X, map_one, sub_eq_zero] at h1
    exact h1
  have hζunit : IsUnit ζ₀ := IsUnit.of_pow_eq_one hζd (NeZero.ne d)
  let ζ : S₁ˣ := hζunit.unit
  have hζ : (ζ : S₁) = ζ₀ := hζunit.unit_spec
  haveI : Module.FaithfullyFlat S S₁ := Module.FaithfullyFlat.trans S S' S₁
  haveI : Algebra.Etale S S₁ := Algebra.Etale.comp S S' S₁

  let ψ : Spec (CommRingCat.of S₁) ⟶ Spec (CommRingCat.of S') := Spec.map (CommRingCat.ofHom (algebraMap S' S₁))
  have hψ : ψ ≫ Spec.map (CommRingCat.ofHom (algebraMap S S')) = Spec.map (CommRingCat.ofHom (algebraMap S S₁)) := by
    rw [← Spec.map_comp, ← CommRingCat.ofHom_comp, ← IsScalarTower.algebraMap_eq S S' S₁]
  refine ⟨S₁, inferInstance, inferInstance, inferInstance, inferInstance, ζ, ?_, ?_,
    fun h => GoodReductionJacobian.schemeHomOverComp ψ hψ (x h), ?_, ?_, ?_⟩
  · rw [hζ]; exact hζd
  · intro j hj hjd
    rw [hζ]
    exact AdjoinRoot.isUnit_one_sub_root_pow_of_isUnit_of_not_dvd S' d hd' j
      (fun hdj => absurd (Nat.le_of_dvd hj hdj) (not_le.mpr hjd))
  ·
    refine ⟨?_, fun h h' => ?_⟩
    · show GoodReductionJacobian.schemeHomOverComp ψ hψ (x 0) = _
      rw [hxhom.1]; exact u.L.one_natural _ _ ψ hψ
    · show GoodReductionJacobian.schemeHomOverComp ψ hψ (x (h + h')) =
        u.L.mul _ (GoodReductionJacobian.schemeHomOverComp ψ hψ (x h)) (GoodReductionJacobian.schemeHomOverComp ψ hψ (x h'))
      rw [hxhom.2]; exact u.L.mul_natural _ _ ψ hψ _ _
  ·
    intro k _ _ sk h h' heq
    apply hxinj k (sk.comp (algebraMap S' S₁)) h h'
    simp only [GoodReductionJacobian.schemeHomOverComp_coe] at heq
    simpa only [CommRingCat.ofHom_comp, Spec.map_comp, Category.assoc] using heq
  ·
    intro R'' _ _ y
    letI algR : Algebra S' R'' := ((algebraMap S₁ R'').comp (algebraMap S' S₁)).toAlgebra
    have halg : (algebraMap S' R'') = (algebraMap S₁ R'').comp (algebraMap S' S₁) := rfl
    have hb : Spec.map (CommRingCat.ofHom ((algebraMap S₁ R'').comp (algebraMap S S₁))) =
        Spec.map (CommRingCat.ofHom ((algebraMap S' R'').comp (algebraMap S S'))) := by
      rw [halg, IsScalarTower.algebraMap_eq S S' S₁, RingHom.comp_assoc]
    have key := hxker R'' ⟨y.1, y.2.trans hb⟩
    rw [← memKernel_congr_base u.f u.L u.pol hb y (y.2.trans hb)] at key
    rw [key]
    simp only [ψ, GoodReductionJacobian.schemeHomOverComp_coe, halg, CommRingCat.ofHom_comp, Spec.map_comp, Category.assoc]

section B2helpers

omit δ

theorem span_range_prod_eq_top {R : Type} [CommRing R] {K : Type} [Fintype K] [DecidableEq K] {m : K → ℕ}
    (r : (k : K) → Fin (m k) → R) (hr : ∀ k, Ideal.span (Set.range (r k)) = ⊤) :
    Ideal.span (Set.range fun f : (k : K) → Fin (m k) => ∏ k, r k (f k)) = ⊤ := by
  classical
  have hc : ∀ k, ∃ c : Fin (m k) → R, ∑ j, c j * r k j = 1 := fun k =>
    Ideal.mem_span_range_iff_exists_fun.mp ((hr k).symm ▸ Submodule.mem_top)
  choose c hc using hc
  rw [Ideal.eq_top_iff_one, Ideal.mem_span_range_iff_exists_fun]
  refine ⟨fun f => ∏ k, c k (f k), ?_⟩
  calc ∑ f : (k : K) → Fin (m k), (∏ k, c k (f k)) * ∏ k, r k (f k)
      = ∑ f : (k : K) → Fin (m k), ∏ k, (c k (f k) * r k (f k)) := by
        refine Finset.sum_congr rfl fun f _ => ?_; rw [Finset.prod_mul_distrib]
    _ = ∏ k, ∑ j, c k j * r k j := (Finset.prod_univ_sum (fun _ => Finset.univ) fun k j => c k j * r k j).symm
    _ = 1 := Finset.prod_eq_one fun k _ => hc k

theorem memKernel_congr {S : Type} [CommRing S] {A : Scheme.{0}} (f : A ⟶ Spec (CommRingCat.of S)) (L : RelativeGroupLaw S f)
    (𝓛 : A.Modules) {R : Type} [CommRing R] {t t' : Spec (CommRingCat.of R) ⟶ Spec (CommRingCat.of S)} (h : t = t')
    (y : SchemeHomOver t f) :
    Polarisation.MemKernel f L 𝓛 t y ↔ Polarisation.MemKernel f L 𝓛 t' ⟨y.1, by rw [← h]; exact y.2⟩ := by
  subst h; rfl

end B2helpers

omit [∀ i, NeZero (δ i)] in

theorem isTypePoints_of_comp
    {S : Type} [CommRing S] (u : PolarisedAbelianScheme g d n S)
    {S₁ : Type} [CommRing S₁] (φ₁ : S →+* S₁) (R : Type) [CommRing R] [Algebra S₁ R]
    (x : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → SchemeHomOver (Spec.map (CommRingCat.ofHom φ₁)) u.f) (hx : IsTypePoints δ u φ₁ x)
    (x' : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → SchemeHomOver (Spec.map (CommRingCat.ofHom ((algebraMap S₁ R).comp φ₁))) u.f)
    (hx' : ∀ k, (x' k).1 = Spec.map (CommRingCat.ofHom (algebraMap S₁ R)) ≫ (x k).1) :
    IsTypePoints δ u ((algebraMap S₁ R).comp φ₁) x' := by
  have hψ : Spec.map (CommRingCat.ofHom (algebraMap S₁ R)) ≫ Spec.map (CommRingCat.ofHom φ₁) =
      Spec.map (CommRingCat.ofHom ((algebraMap S₁ R).comp φ₁)) := by
    rw [← Spec.map_comp, ← CommRingCat.ofHom_comp]
  have hcomp : ∀ k, x' k = schemeHomOverComp (Spec.map (CommRingCat.ofHom (algebraMap S₁ R))) hψ (x k) :=
    fun k => Subtype.ext (hx' k)
  obtain ⟨⟨h0, hmul⟩, hinj, hker⟩ := hx
  refine ⟨⟨?_, fun h h' => ?_⟩, fun k' _ _ sk h h' hh => ?_, fun R'' _ _ y => ?_⟩
  · rw [hcomp, h0, RelativeGroupLaw.one_natural]
  · rw [hcomp, hcomp, hcomp, hmul, u.L.mul_natural]
  · apply hinj k' (sk.comp (algebraMap S₁ R)) h h'
    rw [CommRingCat.ofHom_comp, Spec.map_comp, Category.assoc, Category.assoc, ← hx' h, ← hx' h', hh]
  · letI : Algebra S₁ R'' := ((algebraMap R R'').comp (algebraMap S₁ R)).toAlgebra
    have ht : Spec.map (CommRingCat.ofHom ((algebraMap R R'').comp ((algebraMap S₁ R).comp φ₁))) =
        Spec.map (CommRingCat.ofHom ((algebraMap S₁ R'').comp φ₁)) := by
      rw [← RingHom.comp_assoc]
    refine (memKernel_congr u.f u.L u.pol ht y).trans ((hker R'' ⟨y.1, y.2.trans ht⟩).trans ?_)
    refine exists_congr fun m => exists_congr fun r => and_congr_right fun _ => forall_congr' fun j =>
      exists_congr fun h => ?_
    rw [hx' h, ← Category.assoc (Spec.map _), ← Spec.map_comp, ← CommRingCat.ofHom_comp, RingHom.comp_assoc]

theorem exists_cover_theta0
    {S : Type} [CommRing S] (u : PolarisedAbelianScheme g d n S)
    {S₁ : Type} [CommRing S₁] (φ₁ : S →+* S₁)
    (x : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → SchemeHomOver (Spec.map (CommRingCat.ofHom φ₁)) u.f) (hx : IsTypePoints δ u φ₁ x) :
    ∃ (m : ℕ) (r : Fin m → S₁), Ideal.span (Set.range r) = ⊤ ∧
      ∀ j : Fin m,
        ∃ (xj : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → SchemeHomOver
            (Spec.map (CommRingCat.ofHom ((algebraMap S₁ (Localization.Away (r j))).comp φ₁))) u.f)
          (θ₀ : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → ThetaPt u.f u.L u.pol
            (Spec.map (CommRingCat.ofHom ((algebraMap S₁ (Localization.Away (r j))).comp φ₁)))),
          IsTypePoints δ u ((algebraMap S₁ (Localization.Away (r j))).comp φ₁) xj ∧
          (∀ k, (xj k).1 = Spec.map (CommRingCat.ofHom (algebraMap S₁ (Localization.Away (r j)))) ≫ (x k).1) ∧
          (∀ k, (θ₀ k).pt = xj k) := by
  classical

  have hid : (algebraMap S₁ S₁).comp φ₁ = φ₁ := RingHom.ext fun _ => rfl
  let y : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → SchemeHomOver (Spec.map (CommRingCat.ofHom ((algebraMap S₁ S₁).comp φ₁))) u.f :=
    fun k => ⟨(x k).1, by rw [hid]; exact (x k).2⟩
  have hmem : ∀ k, Polarisation.MemKernel u.f u.L u.pol _ (y k) := by
    intro k
    refine (hx.2.2 S₁ (y k)).mpr ⟨1, fun _ => 1, ?_, fun j => ⟨k, ?_⟩⟩
    · rw [Ideal.eq_top_iff_one]; exact Ideal.subset_span ⟨0, rfl⟩
    · exact congrArg (fun φ => Spec.map (CommRingCat.ofHom φ) ≫ (x k).1)
        (RingHom.ext fun _ => rfl : algebraMap S₁ (Localization.Away (1 : S₁)) = (algebraMap S₁ _).comp (algebraMap S₁ S₁))

  have HL0 := fun k => AlgebraicGeometry.PolarisedAbelianScheme.exists_cover_thetaPt_pt_eq_of_memKernel u _ (y k) (hmem k)
  choose mK rK hrK hθK using HL0
  choose θK hθK using hθK

  let eJ := Fintype.equivFin ((k : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i)))) → Fin (mK k))
  refine ⟨Fintype.card ((k : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i)))) → Fin (mK k)), fun i => ∏ k, rK k (eJ.symm i k), ?_, fun i => ?_⟩
  · have key := span_range_prod_eq_top rK hrK
    rw [← key]
    congr 1
    ext s
    simp only [Set.mem_range]
    constructor
    · rintro ⟨i, rfl⟩; exact ⟨eJ.symm i, rfl⟩
    · rintro ⟨f, rfl⟩; exact ⟨eJ f, by rw [Equiv.symm_apply_apply]⟩

  have hunit : ∀ k, IsUnit (algebraMap S₁ (Localization.Away (∏ k, rK k (eJ.symm i k))) (rK k (eJ.symm i k))) :=
    fun k => isUnit_of_dvd_unit (map_dvd _ (Finset.dvd_prod_of_mem (fun k' => rK k' (eJ.symm i k')) (Finset.mem_univ k)))
      (IsLocalization.Away.algebraMap_isUnit _)
  let ψ : ∀ k, Localization.Away (rK k (eJ.symm i k)) →+* Localization.Away (∏ k, rK k (eJ.symm i k)) :=
    fun k => IsLocalization.Away.lift (rK k (eJ.symm i k)) (hunit k)
  have hψ : ∀ k (s : S₁), ψ k (algebraMap S₁ _ s) = algebraMap S₁ _ s := fun k s =>
    IsLocalization.Away.lift_eq _ (hunit k) s
  have hr : ∀ k, Spec.map (CommRingCat.ofHom (ψ k)) ≫
      (Spec.map (CommRingCat.ofHom (algebraMap S₁ (Localization.Away (rK k (eJ.symm i k))))) ≫
        Spec.map (CommRingCat.ofHom ((algebraMap S₁ S₁).comp φ₁))) =
      Spec.map (CommRingCat.ofHom ((algebraMap S₁ (Localization.Away (∏ k, rK k (eJ.symm i k)))).comp φ₁)) := by
    intro k
    rw [← Spec.map_comp, ← Spec.map_comp, ← CommRingCat.ofHom_comp, ← CommRingCat.ofHom_comp]
    congr 2
    apply RingHom.ext; intro s
    show ψ k (algebraMap S₁ _ (φ₁ s)) = algebraMap S₁ _ (φ₁ s)
    exact hψ k _
  have Hβ := fun k => AlgebraicGeometry.Polarisation.TA.exists_monoidHom_transport u.f u.L u.pol _ _ (ψ k) (hr k)
  choose β hβpt hβ2 hβ3 hβ4 using Hβ
  have hpt : ∀ k, ((β k (θK k (eJ.symm i k))).pt).1 =
      Spec.map (CommRingCat.ofHom (algebraMap S₁ (Localization.Away (∏ k, rK k (eJ.symm i k))))) ≫ (x k).1 := by
    intro k
    rw [hβpt, hθK, ← Category.assoc, ← Spec.map_comp, ← CommRingCat.ofHom_comp]
    show Spec.map (CommRingCat.ofHom ((ψ k).comp (algebraMap S₁ _))) ≫ (x k).1 = _
    congr 3
    exact RingHom.ext (hψ k)
  exact ⟨fun k => (β k (θK k (eJ.symm i k))).pt, fun k => β k (θK k (eJ.symm i k)),
    isTypePoints_of_comp δ u φ₁ _ x hx _ hpt, hpt, fun k => rfl⟩

theorem exists_pairing_idempotents [NeZero d] (hδd : ∏ i, δ i = d)
    {S : Type} [CommRing S] (hd : IsUnit ((d : ℕ) : S))
    (u : PolarisedAbelianScheme g d n S) (hu : PolarisedAbelianScheme.RootedSymmetricOfType δ S u)
    {R : Type} [CommRing R] (φ : S →+* R)
    (ζ : Rˣ) (hζ : (ζ : R) ^ d = 1) (hζu : ∀ j : ℕ, 0 < j → j < d → IsUnit (1 - (ζ : R) ^ j))
    (x : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → SchemeHomOver (Spec.map (CommRingCat.ofHom φ)) u.f) (hx : IsTypePoints δ u φ x)
    (θ₀ : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → ThetaPt u.f u.L u.pol (Spec.map (CommRingCat.ofHom φ))) (hθ₀ : ∀ k, (θ₀ k).pt = x k) :
    ∃ (e : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → Rˣ)
      (ε : ((((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → ZMod d) → R),
      (∀ (k k' : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))))
          (s : Γ((Scheme.Modules.pullback (pullback.fst u.f (Spec.map (CommRingCat.ofHom φ)))).obj u.pol, ⊤)),
        (θ₀ k).act ((θ₀ k').act s) =
          baseScalar u.f (Spec.map (CommRingCat.ofHom φ)) (e k k' : R) • (θ₀ k').act ((θ₀ k).act s)) ∧
      CompleteOrthogonalIdempotents ε ∧
      (∀ (B : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → ZMod d) (k k' : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i)))),
        ε B * (e k k' : R) = ε B * (ζ : R) ^ (B k k').val) ∧
      (∀ B : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → ZMod d, ε B ≠ 0 →
        (∀ k₁ k₂ k' : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))), B (k₁ + k₂) k' = B k₁ k' + B k₂ k') ∧
        (∀ k k₁ k₂ : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))), B k (k₁ + k₂) = B k k₁ + B k k₂) ∧
        (∀ k : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))), B k k = 0) ∧
        (∀ k : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))), (∀ k' : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))), B k k' = 0) → k = 0)) := by
  classical
  obtain ⟨⟨hx0, hxmul⟩, hxinj, hxK⟩ := hx

  obtain ⟨e, he, he₁, he₂, hee, -, -, -⟩ :=
    AlgebraicGeometry.PolarisedAbelianScheme.exists_commutatorPairing_of_thetaPt u (Spec.map (CommRingCat.ofHom φ))
      x hx0 hxmul θ₀ hθ₀

  have he0 : ∀ k', e 0 k' = 1 := fun k' => by
    have h := he₁ 0 0 k'
    rw [add_zero] at h
    exact mul_left_cancel (a := e 0 k') (by rw [mul_one]; exact h.symm)
  have hens : ∀ (m : ℕ) (k k'), e (m • k) k' = e k k' ^ m := by
    intro m k k'
    induction m with
    | zero => rw [zero_smul, pow_zero, he0]
    | succ m ih => rw [add_smul, one_smul, he₁, ih, pow_succ]
  have hdK : ∀ k : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))), d • k = 0 := by
    intro k
    have hcomp : ∀ (h : (i : Fin g) → ZMod (δ i)), d • h = 0 := fun h => by
      funext i
      simp only [Pi.smul_apply, Pi.zero_apply, nsmul_eq_mul]
      have : ((d : ℕ) : ZMod (δ i)) = 0 := by
        rw [← hδd]
        exact (ZMod.natCast_eq_zero_iff _ _).mpr (Finset.dvd_prod_of_mem δ (Finset.mem_univ i))
      rw [this, zero_mul]
    ext <;> simp only [Prod.smul_fst, Prod.smul_snd, Prod.fst_zero, Prod.snd_zero, hcomp]
  have hed : ∀ k k', e k k' ^ d = 1 := fun k k' => by rw [← hens, hdK, he0]

  have hdR : IsUnit ((d : ℕ) : R) := by simpa using hd.map φ
  obtain ⟨ε, hε, hεe, hB⟩ :=
    CompleteOrthogonalIdempotents.exists_forall_mul_eq_mul_pow_val_of_pow_eq_one_of_isUnit_one_sub_pow
      hdR (ζ : R) hζ hζu e hed he₁ he₂ hee

  letI : Algebra S R := φ.toAlgebra
  have hnd := AlgebraicGeometry.PolarisedAbelianScheme.forall_eq_zero_of_commutatorPairing_of_rootedSymmetricOfType δ hδd hd u hu
    (ζ : R) hζ hζu x hx0 hxmul hxinj hxK θ₀ hθ₀ e he ε hε hεe
  exact ⟨e, ε, he, hε, hεe, fun B hB0 => ⟨(hB B hB0).1, (hB B hB0).2.1, (hB B hB0).2.2, hnd B hB0⟩⟩

theorem exists_ffEtale_hasLevelLifts_piece [NeZero d] (hδd : ∏ i, δ i = d)
    {S : Type} [CommRing S] (u : PolarisedAbelianScheme g d n S)
    {R : Type} [CommRing R] (φ : S →+* R) (hdR : IsUnit ((d : ℕ) : R))
    (ζ : Rˣ) (hζ : (ζ : R) ^ d = 1) (hζu : ∀ j : ℕ, 0 < j → j < d → IsUnit (1 - (ζ : R) ^ j))
    (x : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → SchemeHomOver (Spec.map (CommRingCat.ofHom φ)) u.f)
    (hx0 : x 0 = u.L.one _) (hx : ∀ k k' : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))), x (k + k') = u.L.mul _ (x k) (x k'))
    (θ₀ : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → ThetaPt u.f u.L u.pol (Spec.map (CommRingCat.ofHom φ))) (hθ₀ : ∀ k, (θ₀ k).pt = x k)
    (e : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → Rˣ)
    (he : ∀ (k k' : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))))
        (s : Γ((Scheme.Modules.pullback (pullback.fst u.f (Spec.map (CommRingCat.ofHom φ)))).obj u.pol, ⊤)),
      (θ₀ k).act ((θ₀ k').act s) =
        baseScalar u.f (Spec.map (CommRingCat.ofHom φ)) (e k k' : R) • (θ₀ k').act ((θ₀ k).act s))
    (ε₀ : R) (hε₀ : IsIdempotentElem ε₀)
    (B : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → ZMod d)
    (hεe : ∀ k k' : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))), ε₀ * (e k k' : R) = ε₀ * (ζ : R) ^ (B k k').val)
    (hadd₁ : ∀ a b c, B (a + b) c = B a c + B b c) (hadd₂ : ∀ a b c, B a (b + c) = B a b + B a c)
    (halt : ∀ a, B a a = 0) (hnd : ∀ a, (∀ b, B a b = 0) → a = 0) :
    ∃ (R' : Type) (_ : CommRing R') (_ : Algebra (Localization.Away ε₀) R'),
      Module.FaithfullyFlat (Localization.Away ε₀) R' ∧ Algebra.Etale (Localization.Away ε₀) R' ∧
      HasLevelLifts δ u
        ((algebraMap (Localization.Away ε₀) R').comp ((algebraMap R (Localization.Away ε₀)).comp φ))
        (Units.map ((algebraMap (Localization.Away ε₀) R').comp (algebraMap R (Localization.Away ε₀)) : R →* R') ζ) := by
  classical
  letI algSR : Algebra S R := φ.toAlgebra
  have hφ : algebraMap S R = φ := rfl

  have hψε₀ : algebraMap R (Localization.Away ε₀) ε₀ = 1 := by
    have hu : IsUnit (algebraMap R (Localization.Away ε₀) ε₀) := IsLocalization.Away.algebraMap_isUnit ε₀
    have hid : algebraMap R (Localization.Away ε₀) ε₀ * algebraMap R (Localization.Away ε₀) ε₀ =
        algebraMap R (Localization.Away ε₀) ε₀ := by rw [← map_mul, hε₀.eq]

    exact hu.mul_left_cancel (hid.trans (mul_one _).symm)

  have hψe : ∀ k k', Units.map (algebraMap R (Localization.Away ε₀) : R →* Localization.Away ε₀) (e k k') =
      Units.map (algebraMap R (Localization.Away ε₀) : R →* Localization.Away ε₀) ζ ^ (B k k').val := by
    intro k k'
    ext
    have := congrArg (algebraMap R (Localization.Away ε₀)) (hεe k k')
    rw [map_mul, map_mul, hψε₀, one_mul, one_mul, map_pow] at this
    simpa [Units.val_pow_eq_pow_val] using this

  have hr : Spec.map (CommRingCat.ofHom (algebraMap R (Localization.Away ε₀))) ≫ Spec.map (CommRingCat.ofHom φ) =
      Spec.map (CommRingCat.ofHom (algebraMap S (Localization.Away ε₀))) := by
    rw [← hφ]; exact AlgebraicGeometry.Polarisation.TA.hr_algebraMap (S := S) R (Localization.Away ε₀)
  obtain ⟨β, hβpt, -, hβsc, -⟩ := AlgebraicGeometry.Polarisation.TA.exists_monoidHom_transport u.f u.L u.pol
    (Spec.map (CommRingCat.ofHom φ)) (Spec.map (CommRingCat.ofHom (algebraMap S (Localization.Away ε₀))))
    (algebraMap R (Localization.Away ε₀)) hr

  have hHeisR : ∀ k k', θ₀ k * θ₀ k' = ThetaPt.ofScalar (e k k') * (θ₀ k' * θ₀ k) := by
    intro k k'
    apply AlgebraicGeometry.PolarisedAbelianScheme.thetaPt_eq_of_pt_eq_of_forall_act_eq u
    · rw [ThetaPt.mul_pt, ThetaPt.mul_pt, ThetaPt.mul_pt, ThetaPt.ofScalar_pt, u.L.one_mul]; exact u.comm _ _ _
    · intro s; rw [ThetaPt.mul_act, ThetaPt.mul_act, ThetaPt.mul_act, ThetaPt.ofScalar_act, he]
  have hBε : ∀ (k k') (s : Γ((Scheme.Modules.pullback (pullback.fst u.f
      (Spec.map (CommRingCat.ofHom (algebraMap S (Localization.Away ε₀)))))).obj u.pol, ⊤)),
      (β (θ₀ k)).act ((β (θ₀ k')).act s) =
        baseScalar u.f (Spec.map (CommRingCat.ofHom (algebraMap S (Localization.Away ε₀))))
          ((Units.map (algebraMap R (Localization.Away ε₀) : R →* Localization.Away ε₀) ζ : Localization.Away ε₀) ^ (B k k').val) •
          (β (θ₀ k')).act ((β (θ₀ k)).act s) := by
    intro k k' s
    have h1 : β (θ₀ k) * β (θ₀ k') =
        ThetaPt.ofScalar (Units.map (algebraMap R (Localization.Away ε₀) : R →* Localization.Away ε₀) ζ ^ (B k k').val) *
          (β (θ₀ k') * β (θ₀ k)) := by
      rw [← map_mul, hHeisR, map_mul, map_mul, hβsc, hψe]
    rw [← ThetaPt.mul_act, h1, ThetaPt.mul_act, ThetaPt.mul_act, ThetaPt.ofScalar_act, Units.val_pow_eq_pow_val]

  have hx0' : schemeHomOverComp (Spec.map (CommRingCat.ofHom (algebraMap R (Localization.Away ε₀)))) hr (x 0) = u.L.one _ := by
    rw [hx0]; exact u.L.one_natural _ _ _ hr
  have hx' : ∀ k k', schemeHomOverComp (Spec.map (CommRingCat.ofHom (algebraMap R (Localization.Away ε₀)))) hr (x (k + k')) =
      u.L.mul _ (schemeHomOverComp (Spec.map (CommRingCat.ofHom (algebraMap R (Localization.Away ε₀)))) hr (x k))
        (schemeHomOverComp (Spec.map (CommRingCat.ofHom (algebraMap R (Localization.Away ε₀)))) hr (x k')) := fun k k' => by
    rw [← u.L.mul_natural _ _ _ hr, ← hx]
  have hθ' : ∀ k, (β (θ₀ k)).pt = schemeHomOverComp (Spec.map (CommRingCat.ofHom (algebraMap R (Localization.Away ε₀)))) hr (x k) :=
    fun k => Subtype.ext (by rw [hβpt, GoodReductionJacobian.schemeHomOverComp_coe, hθ₀])

  have hdε : IsUnit ((d : ℕ) : Localization.Away ε₀) := by
    have := hdR.map (algebraMap R (Localization.Away ε₀)); rwa [map_natCast] at this
  have hζε₀ : ((Units.map (algebraMap R (Localization.Away ε₀) : R →* Localization.Away ε₀) ζ : Localization.Away ε₀)) ^ d = 1 := by
    show (algebraMap R (Localization.Away ε₀) ζ) ^ d = 1
    rw [← map_pow, hζ, map_one]
  have hζuε : ∀ j : ℕ, 0 < j → j < d →
      IsUnit (1 - ((Units.map (algebraMap R (Localization.Away ε₀) : R →* Localization.Away ε₀) ζ : Localization.Away ε₀)) ^ j) := by
    intro j hj hj'
    show IsUnit (1 - (algebraMap R (Localization.Away ε₀) ζ) ^ j)
    have := (hζu j hj hj').map (algebraMap R (Localization.Away ε₀))
    rwa [map_sub, map_one, map_pow] at this
  obtain ⟨R', instR', algR', algSR', hst, hff, het, lift, dualLift, hl0, hlm, hd0, hdm, hH⟩ :=
    AlgebraicGeometry.PolarisedAbelianScheme.exists_levelLifts_of_commutatorPairing_eq_pow δ hδd u hdε
      (Units.map (algebraMap R (Localization.Away ε₀) : R →* Localization.Away ε₀) ζ) hζε₀ hζuε
      (fun k => schemeHomOverComp (Spec.map (CommRingCat.ofHom (algebraMap R (Localization.Away ε₀)))) hr (x k)) hx0' hx'
      (fun k => β (θ₀ k)) hθ' B hBε hadd₁ hadd₂ halt hnd
  refine ⟨R', instR', algR', hff, het, ?_⟩

  have hmap : (algebraMap (Localization.Away ε₀) R').comp ((algebraMap R (Localization.Away ε₀)).comp φ) = algebraMap S R' := by
    rw [IsScalarTower.algebraMap_eq S (Localization.Away ε₀) R', IsScalarTower.algebraMap_eq S R (Localization.Away ε₀), hφ]
  have hunit : Units.map ((algebraMap (Localization.Away ε₀) R').comp (algebraMap R (Localization.Away ε₀)) : R →* R') ζ =
      Units.map (algebraMap (Localization.Away ε₀) R' : Localization.Away ε₀ →* R')
        (Units.map (algebraMap R (Localization.Away ε₀) : R →* Localization.Away ε₀) ζ) := by
    ext; rfl
  rw [hmap, hunit]
  exact ⟨lift, dualLift, hl0, hlm, hd0, hdm, hH⟩

theorem hasLevelLifts_pi
    {S : Type} [CommRing S] (u : PolarisedAbelianScheme g d n S)
    {m : ℕ} (Rp : Fin m → Type) [∀ p, CommRing (Rp p)] (φ : ∀ p, S →+* Rp p)
    (ζ : ∀ p, (Rp p)ˣ) (hL : ∀ p, HasLevelLifts δ u (φ p) (ζ p)) :
    HasLevelLifts δ u (RingHom.pi φ) (MulEquiv.piUnits.symm ζ) :=
  AlgebraicGeometry.PolarisedAbelianScheme.exists_levelLifts_pi_of_forall_exists_levelLifts δ u Rp φ ζ hL

theorem comap_pi_tower_surjective {S₁ : Type} [CommRing S₁] {m : ℕ} (r : Fin m → S₁) (hr : Ideal.span (Set.range r) = ⊤)
    (Rp : Fin m → Type) [∀ j, CommRing (Rp j)] [∀ j, Algebra (Localization.Away (r j)) (Rp j)]
    [∀ j, Module.FaithfullyFlat (Localization.Away (r j)) (Rp j)] :
    Function.Surjective (PrimeSpectrum.comap (RingHom.pi fun j =>
      (algebraMap (Localization.Away (r j)) (Rp j)).comp (algebraMap S₁ (Localization.Away (r j))))) := by
  intro q
  have hq : ∃ j, r j ∉ q.asIdeal := by
    by_contra h
    push_neg at h
    have : Ideal.span (Set.range r) ≤ q.asIdeal := Ideal.span_le.mpr (by rintro _ ⟨j, rfl⟩; exact h j)
    rw [hr] at this
    exact q.isPrime.ne_top (top_le_iff.mp this)
  obtain ⟨j, hj⟩ := hq
  have hdisj : Disjoint (↑(Submonoid.powers (r j)) : Set S₁) ↑q.asIdeal := by
    rw [Ideal.disjoint_powers_iff_notMem _ q.isPrime.isRadical]
    exact hj
  have hP : (Ideal.map (algebraMap S₁ (Localization.Away (r j))) q.asIdeal).IsPrime :=
    IsLocalization.isPrime_of_isPrime_disjoint (Submonoid.powers (r j)) _ q.asIdeal q.isPrime hdisj

  obtain ⟨Q, hQ⟩ := PrimeSpectrum.comap_surjective_of_faithfullyFlat (A := Localization.Away (r j)) (B := Rp j)
    ⟨_, hP⟩
  refine ⟨⟨Ideal.comap (Pi.evalRingHom Rp j) Q.asIdeal, Ideal.IsPrime.comap _⟩, ?_⟩
  ext x
  change x ∈ Ideal.comap _ (Ideal.comap (Pi.evalRingHom Rp j) Q.asIdeal) ↔ x ∈ q.asIdeal
  rw [Ideal.comap_comap]
  have hcomp : (Pi.evalRingHom Rp j).comp (RingHom.pi fun j =>
      (algebraMap (Localization.Away (r j)) (Rp j)).comp (algebraMap S₁ (Localization.Away (r j)))) =
      (algebraMap (Localization.Away (r j)) (Rp j)).comp (algebraMap S₁ (Localization.Away (r j))) := by
    ext y; rfl
  rw [hcomp, ← Ideal.comap_comap]
  have hQ' : Ideal.comap (algebraMap (Localization.Away (r j)) (Rp j)) Q.asIdeal =
      Ideal.map (algebraMap S₁ (Localization.Away (r j))) q.asIdeal := by
    have := congrArg PrimeSpectrum.asIdeal hQ
    exact this
  rw [hQ']
  have hunder := IsLocalization.comap_map_of_isPrime_disjoint (Submonoid.powers (r j)) (Localization.Away (r j))
    q.isPrime hdisj
  rw [Ideal.under_def] at hunder
  rw [hunder]

theorem faithfullyFlat_and_etale_pi_tower
    {S : Type} [CommRing S] (S₁ : Type) [CommRing S₁] [Algebra S S₁] [Module.FaithfullyFlat S S₁] [Algebra.Etale S S₁]
    {m : ℕ} (r : Fin m → S₁) (hr : Ideal.span (Set.range r) = ⊤)
    (Rp : Fin m → Type) [∀ j, CommRing (Rp j)] [∀ j, Algebra (Localization.Away (r j)) (Rp j)]
    [∀ j, Module.FaithfullyFlat (Localization.Away (r j)) (Rp j)] [∀ j, Algebra.Etale (Localization.Away (r j)) (Rp j)] :
    letI : Algebra S (Π j, Rp j) :=
      (RingHom.pi fun j => (algebraMap (Localization.Away (r j)) (Rp j)).comp
        ((algebraMap S₁ (Localization.Away (r j))).comp (algebraMap S S₁))).toAlgebra
    Module.FaithfullyFlat S (Π j, Rp j) ∧ Algebra.Etale S (Π j, Rp j) := by

  letI algj : ∀ j, Algebra S (Rp j) := fun j =>
    ((algebraMap (Localization.Away (r j)) (Rp j)).comp ((algebraMap S₁ (Localization.Away (r j))).comp (algebraMap S S₁))).toAlgebra
  haveI : ∀ j, IsScalarTower S (Localization.Away (r j)) (Rp j) := fun j =>
    IsScalarTower.of_algebraMap_eq (fun x => rfl)
  haveI : ∀ j, Algebra.Etale S (Rp j) := fun j => Algebra.Etale.comp S (Localization.Away (r j)) (Rp j)
  haveI : ∀ j, Module.Flat S (Rp j) := fun j => Module.Flat.trans S (Localization.Away (r j)) (Rp j)
  have hE : Algebra.Etale S (Π j, Rp j) := inferInstance
  have hF : Module.Flat S (Π j, Rp j) := inferInstance
  have hsurj : Function.Surjective (PrimeSpectrum.comap (algebraMap S (Π j, Rp j))) := by
    have h1 := comap_pi_tower_surjective r hr Rp
    have h2 := PrimeSpectrum.comap_surjective_of_faithfullyFlat (A := S) (B := S₁)
    have : algebraMap S (Π j, Rp j) = (RingHom.pi fun j =>
        (algebraMap (Localization.Away (r j)) (Rp j)).comp (algebraMap S₁ (Localization.Away (r j)))).comp
        (algebraMap S S₁) := by
      ext x j; rfl
    rw [this, PrimeSpectrum.comap_comp]
    exact h2.comp h1
  have hFF : Module.FaithfullyFlat S (Π j, Rp j) := Module.FaithfullyFlat.of_comap_surjective hsurj
  exact ⟨hFF, hE⟩

theorem strong_piUnits {P : Type} [Fintype P] (Rp : P → Type) [∀ p, CommRing (Rp p)] (d : ℕ) (ζ : ∀ p, (Rp p)ˣ)
    (hζ : ∀ p, (ζ p : Rp p) ^ d = 1) (hζu : ∀ p (j : ℕ), 0 < j → j < d → IsUnit (1 - (ζ p : Rp p) ^ j)) :
    ((MulEquiv.piUnits.symm ζ : (Π p, Rp p)ˣ) : Π p, Rp p) ^ d = 1 ∧
      ∀ j : ℕ, 0 < j → j < d → IsUnit (1 - ((MulEquiv.piUnits.symm ζ : (Π p, Rp p)ˣ) : Π p, Rp p) ^ j) := by
  refine ⟨funext fun p => ?_, fun j hj hj' => ?_⟩
  · simpa using hζ p
  · rw [Pi.isUnit_iff]
    intro p
    simpa using hζu p j hj hj'

theorem exists_ffEtale_hasLevelLifts_of_theta0 [NeZero d] (hδd : ∏ i, δ i = d)
    {S : Type} [CommRing S] (hd : IsUnit ((d : ℕ) : S))
    (u : PolarisedAbelianScheme g d n S) (hu : PolarisedAbelianScheme.RootedSymmetricOfType δ S u)
    {R : Type} [CommRing R] (φ : S →+* R)
    (ζ : Rˣ) (hζ : (ζ : R) ^ d = 1) (hζu : ∀ j : ℕ, 0 < j → j < d → IsUnit (1 - (ζ : R) ^ j))
    (x : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → SchemeHomOver (Spec.map (CommRingCat.ofHom φ)) u.f) (hx : IsTypePoints δ u φ x)
    (θ₀ : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → ThetaPt u.f u.L u.pol (Spec.map (CommRingCat.ofHom φ))) (hθ₀ : ∀ k, (θ₀ k).pt = x k) :
    ∃ (R' : Type) (_ : CommRing R') (_ : Algebra R R'),
      Module.FaithfullyFlat R R' ∧ Algebra.Etale R R' ∧
      HasLevelLifts δ u ((algebraMap R R').comp φ) (Units.map (algebraMap R R' : R →* R') ζ) := by

  classical

  obtain ⟨e, ε, he, hε, hεe, hnd⟩ := exists_pairing_idempotents δ hδd hd u hu φ ζ hζ hζu x hx θ₀ hθ₀

  let eP := Fintype.equivFin {B : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → ZMod d // ε B ≠ 0}
  let r : Fin (Fintype.card {B : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → ZMod d // ε B ≠ 0}) → R := fun j => ε (eP.symm j).1
  have hr : Ideal.span (Set.range r) = ⊤ := by
    rw [Ideal.eq_top_iff_one, ← hε.complete]
    refine Ideal.sum_mem _ fun B _ => ?_
    by_cases hB : ε B = 0
    · rw [hB]; exact Ideal.zero_mem _
    · exact Ideal.subset_span ⟨eP ⟨B, hB⟩, by simp only [r, Equiv.symm_apply_apply]⟩
  have hdR : IsUnit ((d : ℕ) : R) := by simpa using hd.map φ

  have HB := fun j => exists_ffEtale_hasLevelLifts_piece δ hδd u φ hdR ζ hζ hζu x hx.1.1 hx.1.2 θ₀ hθ₀ e he (r j)
    (hε.idem _) (eP.symm j).1 (hεe _) (hnd _ (eP.symm j).2).1 (hnd _ (eP.symm j).2).2.1 (hnd _ (eP.symm j).2).2.2.1
    (hnd _ (eP.symm j).2).2.2.2
  choose Rp instR instA hff het hLL using HB
  letI : ∀ j, CommRing (Rp j) := instR
  letI : ∀ j, Algebra (Localization.Away (r j)) (Rp j) := instA
  haveI : ∀ j, Module.FaithfullyFlat (Localization.Away (r j)) (Rp j) := hff
  haveI : ∀ j, Algebra.Etale (Localization.Away (r j)) (Rp j) := het

  have hLL' := hasLevelLifts_pi δ u Rp
    (fun j => (algebraMap (Localization.Away (r j)) (Rp j)).comp ((algebraMap R (Localization.Away (r j))).comp φ))
    (fun j => Units.map ((algebraMap (Localization.Away (r j)) (Rp j)).comp (algebraMap R (Localization.Away (r j))) : R →* Rp j) ζ)
    hLL

  obtain ⟨hffPi, hetPi⟩ := faithfullyFlat_and_etale_pi_tower (S := R) R r hr Rp
  refine ⟨((j : Fin (Fintype.card {B : (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → (((i : Fin g) → ZMod (δ i)) × ((i : Fin g) → ZMod (δ i))) → ZMod d // ε B ≠ 0})) → Rp j), inferInstance,
    (RingHom.pi fun j => (algebraMap (Localization.Away (r j)) (Rp j)).comp
        ((algebraMap R (Localization.Away (r j))).comp (algebraMap R R))).toAlgebra, hffPi, hetPi, ?_⟩
  convert hLL' using 2 <;> first | rfl | (ext; rfl)

end AlgebraicGeometry.PolarisedAbelianScheme.LevelLift

open AlgebraicGeometry.PolarisedAbelianScheme.LevelLift

theorem solution
    {g d n : ℕ} (δ : Fin g → ℕ) [∀ i, NeZero (δ i)] (hδd : ∏ i, δ i = d)
    {S : Type} [CommRing S] (hd : IsUnit ((d : ℕ) : S))
    (u : PolarisedAbelianScheme g d n S) (hu : PolarisedAbelianScheme.RootedSymmetricOfType δ S u) :
    ∃ (S' : Type) (_ : CommRing S') (_ : Algebra S S'),
      Module.FaithfullyFlat S S' ∧ Algebra.Etale S S' ∧
      ∃ (ζ : S'ˣ), (ζ : S') ^ d = 1 ∧ (∀ j : ℕ, 0 < j → j < d → IsUnit (1 - (ζ : S') ^ j)) ∧
      ∃ (lift : ((i : Fin g) → ZMod (δ i)) → ThetaPt u.f u.L u.pol (Spec.map (CommRingCat.ofHom (algebraMap S S'))))
        (dualLift : (((i : Fin g) → ZMod (δ i)) →+ ZMod d) → ThetaPt u.f u.L u.pol (Spec.map (CommRingCat.ofHom (algebraMap S S')))),
        lift 0 = 1 ∧ (∀ h h' : ((i : Fin g) → ZMod (δ i)), lift (h + h') = lift h * lift h') ∧
        dualLift 0 = 1 ∧ (∀ c c' : ((i : Fin g) → ZMod (δ i)) →+ ZMod d, dualLift (c + c') = dualLift c * dualLift c') ∧
        (∀ (c : ((i : Fin g) → ZMod (δ i)) →+ ZMod d) (h : ((i : Fin g) → ZMod (δ i))),
          dualLift c * lift h = ThetaPt.ofScalar (ζ ^ (c h).val) * (lift h * dualLift c)) := by
  classical
  haveI : NeZero d := ⟨fun h0 => by
    have h1 : ∀ i, δ i ≠ 0 := fun i => (NeZero.ne (δ i))
    exact (Finset.prod_ne_zero_iff.mpr fun i _ => h1 i) (hδd.trans h0)⟩

  obtain ⟨S₁, _, _, hff₁, het₁, ζ, hζ, hζu, x, hx⟩ := exists_cyclotomic_typePoints δ hδd hd u hu

  obtain ⟨m, r, hr, hpiece⟩ := exists_cover_theta0 δ u (algebraMap S S₁) x hx
  choose xj θ₀ hxj hxjx hθ₀ using hpiece

  have hdj : ∀ j, IsUnit ((d : ℕ) : Localization.Away (r j)) := fun j => by
    have := (hd.map (algebraMap S S₁)).map (algebraMap S₁ (Localization.Away (r j)))
    rwa [map_natCast, map_natCast] at this
  have hζj : ∀ j, (((Units.map (algebraMap S₁ (Localization.Away (r j)) : S₁ →* Localization.Away (r j)) ζ : (Localization.Away (r j))ˣ) : Localization.Away (r j))) ^ d = 1 :=
    fun j => by rw [Units.coe_map, MonoidHom.coe_coe, ← map_pow, hζ, map_one]
  have hζuj : ∀ j (i : ℕ), 0 < i → i < d →
      IsUnit (1 - (((Units.map (algebraMap S₁ (Localization.Away (r j)) : S₁ →* Localization.Away (r j)) ζ : (Localization.Away (r j))ˣ) : Localization.Away (r j))) ^ i) :=
    fun j i hi hi' => by
      have := (hζu i hi hi').map (algebraMap S₁ (Localization.Away (r j)))
      rwa [map_sub, map_one, map_pow] at this
  have hB3 := fun j => exists_ffEtale_hasLevelLifts_of_theta0 δ hδd hd u hu
    ((algebraMap S₁ (Localization.Away (r j))).comp (algebraMap S S₁))
    (Units.map (algebraMap S₁ (Localization.Away (r j)) : S₁ →* Localization.Away (r j)) ζ) (hζj j) (hζuj j) (xj j) (hxj j) (θ₀ j) (hθ₀ j)
  choose Rp instR instA hffp hetp hLLp using hB3

  letI : ∀ j, CommRing (Rp j) := instR
  letI : ∀ j, Algebra (Localization.Away (r j)) (Rp j) := instA
  haveI : ∀ j, Module.FaithfullyFlat (Localization.Away (r j)) (Rp j) := hffp
  haveI : ∀ j, Algebra.Etale (Localization.Away (r j)) (Rp j) := hetp
  haveI := hff₁
  haveI := het₁
  let φ : ∀ j, S →+* Rp j := fun j => (algebraMap (Localization.Away (r j)) (Rp j)).comp
    ((algebraMap S₁ (Localization.Away (r j))).comp (algebraMap S S₁))
  let ζp : ∀ j, (Rp j)ˣ := fun j =>
    Units.map (algebraMap (Localization.Away (r j)) (Rp j) : _ →* _) (Units.map (algebraMap S₁ (Localization.Away (r j)) : S₁ →* Localization.Away (r j)) ζ)
  have hLL : HasLevelLifts δ u (RingHom.pi φ) (MulEquiv.piUnits.symm ζp) :=
    hasLevelLifts_pi δ u Rp φ ζp (fun j => hLLp j)
  obtain ⟨hffPi, hetPi⟩ := faithfullyFlat_and_etale_pi_tower (S := S) S₁ r hr Rp
  have hζp : ∀ j, (ζp j : Rp j) ^ d = 1 := fun j => by
    change ((algebraMap (Localization.Away (r j)) (Rp j))
      (((Units.map (algebraMap S₁ (Localization.Away (r j)) : S₁ →* Localization.Away (r j)) ζ : (Localization.Away (r j))ˣ) : Localization.Away (r j)))) ^ d = 1
    rw [← map_pow, hζj, map_one]
  have hζpu : ∀ j (i : ℕ), 0 < i → i < d → IsUnit (1 - (ζp j : Rp j) ^ i) := fun j i hi hi' => by
    have := (hζuj j i hi hi').map (algebraMap (Localization.Away (r j)) (Rp j))
    rw [map_sub, map_one, map_pow] at this
    exact this
  obtain ⟨hzPi, hzPiu⟩ := strong_piUnits Rp d ζp hζp hζpu
  letI algPi : Algebra S (Π j, Rp j) := (RingHom.pi φ).toAlgebra
  refine ⟨((j : Fin m) → Rp j), inferInstance, algPi, hffPi, hetPi, MulEquiv.piUnits.symm ζp, hzPi, hzPiu, ?_⟩

  exact hLL

end
end S_AlgebraicGeometry_PolarisedAbelianScheme_exists_levelLifts_of_rootedSymmetricOfType
end P2MW
export P2MW.S_AlgebraicGeometry_PolarisedAbelianScheme_exists_levelLifts_of_rootedSymmetricOfType (solution)
