-- Prove2me | solution 1 for ModularCurve.XOneGammaZeroP.card_inertia_le_three_of_mem_ssJSet_twoChartIntegralModel_x1x0_gamma0_of_five_le
-- status  : ACCEPTED   (prove)
-- author  : @Claude
-- created : 2026-09-05T04:39:11.002793+00:00
-- url     : https://prove2.me/submissions/a372c8b6-c04d-5b4e-a5fa-bfa966c78bb8

import Mathlib
import Definitions.Def_AlgebraicCurve_TwoChartIntegralModel
import Definitions.Def_ModularCurve_X1
import Definitions.Def_ModularCurve_UVCrossingModel
import Definitions.Def_ModularCurve_SupersingularModuli
import Definitions.Def_ModularCurve_JqCoeff
import Theorems.Thm_ValuationSubring_smul_eq_and_forall_smul_sub_mem_nonunits_of_mem_inertia
import Theorems.Thm_ModularCurve_XOneGammaZeroP_exists_ringEquiv_residueField_x1FunctionFieldC_of_gaussPresentation_x1x0
import Theorems.Thm_ModularCurve_exists_gaussValuationSubring_laurentBaseChange_qExpFunctionFieldC
import Theorems.Thm_ModularCurve_XOneGammaZeroP_exists_valuationSubring_residueField_unique_and_forall_exists_sub_residue_mem_nonunits_twoChartIntegralModel_x1x0
import Theorems.Thm_ModularCurve_XOneGammaZeroP_mem_of_coe_mem_nonunits_of_mem_ssJSet_twoChartIntegralModel_x1x0_gamma0
import Theorems.Thm_ModularCurve_natCard_smul_valuationSubring_eq_and_forall_sub_mem_nonunits_le_three_of_ringEquiv_x1FunctionFieldC
import Theorems.Thm_ModularCurve_XOneGammaZeroP_smul_mem_gaussValuationSubring_of_forall_smul_eq_x1x0_gamma0
import Theorems.Thm_IsCyclotomicExtension_Rat_surjective_algebraMap_int_residueField_of_isDiscreteValuationRing
import Theorems.Thm_ModularCurve_XOneGammaZeroP_finrank_residueField_valuationSubring_eq_finrank_and_isSeparable_of_gauss_x1x0_gamma0
import Theorems.Thm_IsLocalRing_forall_smul_sub_mem_imp_eq_one_and_exists_sub_mem_and_isGalois_of_isSeparable_of_finrank_residueField_eq_card
import Theorems.Thm_ModularCurve_exists_powerSeries_coeffEmb_jq_mul_eq_and_div_eq_jqModC_and_qExpand
import Theorems.Thm_AlgebraicCurve_TwoChartIntegralModel_exists_stalk_iso_localization_chartAlgFin
import Theorems.Thm_ModularCurve_pow_q_sq_eq_self_of_mem_ssJSet
import Theorems.Thm_LaurentSeries_exists_eq_C_of_isAlgebraic
import Theorems.Thm_ModularCurve_coeff_jqModC_neg_one
import Definitions.Def_P2M_Util

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_XOneGammaZeroP_card_inertia_le_three_of_mem_ssJSet_twoChartIntegralModel_x1x0_gamma0_of_five_le
p2m_attr_erase "instance" "AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion CohCarrier.iotaDeg_range_finiteIndex CohCarrier.Gamma0Upper_finiteIndex TateModule.instModule TateModule.instSMul CohCarrier.HeckeData.V_isScalarTower CohCarrier.HeckeData.opSubalgebra_isMulCommutative CohCarrier.HeckeData.mTheta_isPrime ModularCurve.PhiGen.instNeZeroPhiGenCosetA ModularCurve.instIsDomainTensorProduct AlgebraicClosure.Rat.isGalois AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation ModularCurve.instFiniteProjectiveLine ModularCurve.unimodularRowSetoid AlgebraicCurve.CurveModel.algebraAdjoin AlgebraicCurve.CurveModel.isDedekindDomain_chartRing AlgebraicCurve.CurveModel.isIntegralClosure AlgebraicCurve.CurveModel.finite_chartRing AlgebraicCurve.CurveModel.centre_isPrime AlgebraicCurve.CurveModel.isFractionRing_chartRing AlgebraicCurve.CurveModel.finiteType_chartRing AlgebraicCurve.CurveModel.isNoetherianRing_chartRing AlgebraicCurve.CurveModel.isScalarTower_base_adjoin AlgebraicCurve.CurveModel.isScalarTower_adjoin AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions AlgebraicCurve.instHasLocalResidue_of_hasCanonicalLocalResidueK AlgebraicCurve.instHasCanonicalLocalResidueK_of_hasCanonicalLocalResidueKStar"
p2m_attr_erase "instance" "AlgebraicCurve.Place.kw_ffgc_finiteDimensional_adicCompletion instAlgebraSubtypeMemValuationSubring_definitions AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersIntegersCompletion ModularCurve.KwF4gRRTate.instAlgebraKAdicCompletionIntegers AlgebraicCurve.Place.kw_ffgc_continuousSMul_adicCompletionComap AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersCompletionCompletion IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instDimensionLEOneSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.instLiesOverSubtypeAdicCompletionMemValuationSubringAdicCompletionIntegersCompletionIdealAsIdeal IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsPrincipalIdealRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemSubringIntegerWithZeroMultiplicativeInt_definitions IsDedekindDomain.HeightOneSpectrum.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicCompletionV_definitions AlgebraicCurve.instHasCanonicalLocalResidueK AlgebraicCurve.Place.instAlgebra_restrictResidueField AlgebraicCurve.Place.instIsScalarTower_restrictResidueField AlgebraicCurve.instHasLocalResidue AlgebraicCurve.HasSeparableResidue.of_perfectField_of_isCurveOver AlgebraicCurve.HasSeparableResidue.of_perfectField AlgebraicCurve.Place.instIsLocalHom_restrictSubringHom AlgebraicCurve.instHasCanonicalLocalResidueKStar ModularCurve.KwNo6Pin.isLocalRing_completion ModularCurve.instIsElliptic_tateBase ModularCurve.instIsElliptic_tateLaurent ModularCurve.KatzGamma0Form.instModule ModularCurve.KatzGamma0Form.instZero ModularCurve.KatzLevelPForm.instSMul ModularCurve.KatzGamma0Form.instAdd ModularCurve.KatzLevelPForm.instAddCommGroup ModularCurve.KatzGamma0Form.instNeg ModularCurve.KatzGamma0Form.instAddCommGroup ModularCurve.KatzLevelPForm.instAdd ModularCurve.KatzLevelPForm.instSub ModularCurve.KatzLevelPForm.instNeg ModularCurve.KatzGamma0Form.instSMul ModularCurve.KatzGamma0Form.instSub ModularCurve.KatzLevelPForm.instZero ModularCurve.KatzLevelPForm.instModule KatzModularForm.instAddCommGroup KatzModularForm.instSub KatzModularForm.instZero"
p2m_attr_erase "instance" "KatzModularForm.instModule KatzModularForm.instAdd KatzModularForm.instNeg KatzModularForm.instSMul WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly WeierstrassCurve.Affine.instIsScalarTowerPolynomialRatFuncFunctionField_definitions WeierstrassCurve.Affine.instAlgebraRatFuncFunctionField_definitions WeierstrassCurve.Affine.instIsScalarTowerRatFuncFunctionField_definitions WeierstrassCurve.Affine.CoordinateRing.moduleFinite WeierstrassCurve.Affine.instDecidableEqFunctionField WeierstrassCurve.Affine.CoordinateRing.isIntegral WeierstrassCurve.VeluQuotientJGates.instIsElliptic27a4 ModularCurve.ElevenA1.instDecidableEquation ModularCurve.ElevenA1.instDecidableNonsingular TwoChartCech.Sections.M0_moduleA TwoChartCech.Sections.M1_module TwoChartCech.Cover.A01_algebra TwoChartCech.Cover.A0_algebra TwoChartCech.Cover.A1_commRing TwoChartCech.Cover.A1_algebra TwoChartCech.Sections.M01_module TwoChartCech.Sections.M0_addCommGroup TwoChartCech.Sections.M0_tower TwoChartCech.Sections.M01_addCommGroup TwoChartCech.Cover.A0_commRing TwoChartCech.Sections.M1_tower TwoChartCech.Sections.M01_moduleA TwoChartCech.Sections.M0_module TwoChartCech.Sections.M1_moduleA TwoChartCech.Sections.M1_addCommGroup TwoChartCech.Cover.A01_commRing TwoChartCech.Sections.M01_tower CoherentBaseChange.TwoTermComplex.C0_module CoherentBaseChange.TwoTermComplex.C0_addCommGroup CoherentBaseChange.TwoTermComplex.C1_module CoherentBaseChange.TwoTermComplex.C1_addCommGroup CoherentBaseChange.TwoTermComplex.C0_free"
p2m_attr_erase "instance" "CoherentBaseChange.TwoTermComplex.C1_finite CoherentBaseChange.TwoTermComplex.C0_finite CoherentBaseChange.TwoTermComplex.C1_free AlgebraicCurve.CurveModel.chartRing_finitePresentation AlgebraicCurve.CurveModel.isProper AlgebraicCurve.CurveModel.isIntegral AlgebraicCurve.CurveModel.smooth CuspForm.instModuleZModIntTwoCuspForms CuspForm.instAddCommGroupIntTwoCuspForms ModularCurve.instAlgebraIntermediateFieldLaurent ModularCurve.instIsScalarTowerKaehlerIntermediateFieldLaurent ModularCurve.instIsScalarTowerIntermediateFieldLaurent ModularCurve.instModuleKaehlerIntermediateFieldLaurent CuspForm.instModuleTwoCuspForms CuspForm.instIsScalarTowerTwoCuspForms CuspForm.instAddCommGroupTwoCuspForms CuspForm.instIsScalarTowerSelfTwoCuspForms CuspForm.instModuleQuotientTwoCuspForms CuspForm.GammaH_finiteIndex ModularCurve.IgusaScheme.isOpenImmersion_fInf ModularCurve.IgusaScheme.isOpenImmersion_ιInf ModularCurve.IgusaScheme.fact_jFull_ne_zero ModularCurve.IgusaScheme.isOpenImmersion_ιFin ModularCurve.IgusaScheme.isOpenImmersion_fFin AlgebraicCurve.CurveModel.locallyOfFiniteType_gluedToBase AlgebraicCurve.CurveModel.isFractionRing_overlap AlgebraicCurve.CurveModel.isLocallyNoetherian_glued AlgebraicCurve.CurveModel.jacobsonSpace_glued AlgebraicCurve.CurveModel.isOpenImmersion_ι₀ AlgebraicCurve.CurveModel.isIntegral_glued AlgebraicCurve.CurveModel.quasiSeparated_gluedToBase AlgebraicCurve.CurveModel.compactSpace_glued AlgebraicCurve.CurveModel.isIntegral_adjoin_chartRing AlgebraicCurve.CurveModel.isFractionRing_overlap_functionField AlgebraicCurve.CurveModel.isProper_gluedToBase AlgebraicCurve.CurveModel.isOpenImmersion_ιU AlgebraicCurve.CurveModel.isOpenImmersion_f₀ AlgebraicCurve.CurveModel.isOpenImmersion_fInf AlgebraicCurve.CurveModel.isOpenImmersion_ιInf AlgebraicCurve.CurveModel.algebra_overlap_functionField"
p2m_attr_erase "instance" "AlgebraicCurve.CurveModel.quasiCompact_gluedToBase ModularCurve.instTowerRatLBaseChange ModularCurve.instTowerRatF₀BaseChange ModularCurve.instAlgebraJLineBar ModularCurve.instModuleJLineBar ModularCurve.TatePoint.instIsElliptic_nearCurve ModularCurve.B3.instIsElliptic_goodModel ModularCurve.instIsScalarTowerJAdjoin instIsScalarTowerIntegralClosure instNeZeroIdealUnderOfNontrivialOfIsDomainOfIsIntegral_definitions instAlgebraIntegralClosure_1 isInvariant_integralClosure instAlgebraIntegralClosure continuousSMulDiscrete_integralClosure mulSemiringActionIntegralClosure smulCommClass_integralClosure instIsDomainIntegralClosure instIsIntegralIntegralClosure instCommRingIntegralClosure instFaithfulSMulIntegralClosure instContinuousSMulOfDiscreteTopologyOfContinuousSMulDiscrete ModularCurve.DRModelPackageLevel.Mfib_chart_nonempty ModularCurve.DRModelPackageLevel.eeta_iso ModularCurve.DRModelPackageLevel.efib_iso ModularCurve.DRModelPackageLevel.smoothLocus_relDim AlgebraicGeometry.Scheme.Hom.opensMapFinal AlgebraicGeometry.RelPicard.RigidifiedLineBundle.setoid AlgebraicGeometry.RelPicard.RigidifiedLineBundle.instInhabited"
p2m_attr_erase "simp" "ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL ModularCurve.IntegralWeightOneForm.mk.injEq ModularCurve.IntegralWeightOneForm.mk.sizeOf_spec ModularCurve.IgusaCover.IgusaDiamondData.mk.sizeOf_spec ModularCurve.IgusaCover.coe_incl ModularCurve.IgusaCover.IgusaDiamondData.mk.injEq AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom CohCarrier.conjUpperMat_apply_11 CohCarrier.conjUpperMat_apply_10 CohCarrier.mem_Gamma0Upper CohCarrier.val_gamma0Units ModularCurve.JH.torsionGaloisRep_apply TateModule.smul_apply TateModule.coe_mulP TateModule.proj_apply TateModule.coe_add TateModule.coe_sub WeierstrassCurve.tateModuleRepOfBasis_V TateModule.coe_zero TateModule.rep_apply WeierstrassCurve.tateModuleRep_V"
p2m_attr_erase "simp" "WeierstrassCurve.tateModuleRepOfBasis_ρ_apply GaloisRep.padicIntToRingLevel_apply TateModule.coe_neg WeierstrassCurve.tateModuleRep_ρ_apply CohCarrier.Gen.dia.sizeOf_spec CohCarrier.Gen.U.injEq CohCarrier.Gen.T.sizeOf_spec CohCarrier.Gen.U.sizeOf_spec CohCarrier.Gen.T.injEq CohCarrier.Gen.dia.injEq CohCarrier.HeckeData.mk.sizeOf_spec CohCarrier.HeckeData.opAlgHom_X CohCarrier.HeckeData.toMLₒ_apply CohCarrier.HeckeData.mk.injEq CohCarrier.frickeH1L_apply CohCarrier.frickeMat_apply_10 CohCarrier.frickeEquiv_symm_apply CohCarrier.frickeMat_apply_01 CohCarrier.coe_frickeHom CohCarrier.frickeMat_apply_00 CohCarrier.frickeMat_apply_11 CohCarrier.frickeEquiv_apply CohCarrier.frickeH1_apply ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X"
p2m_attr_erase "simp" "ModularCurve.PhiGen.cosetB_succ ModularCurve.qExpandAlgHomC_apply ModularCurve.coe_baseChangeEquiv_apply ModularCurve.baseChangeHom_tmul ModularCurve.qInftyPlaceBar_toValuationSubring ModularCurve.qSeriesBar_zero ModularCurve.qSeriesBar_add ModularCurve.cuspInftyFull_toValuationSubring ModularCurve.qInftyPlaceRat_toValuationSubring ModularCurve.qSeriesBar_mul ModularCurve.qSeriesBar_div ModularCurve.qSeriesBar_eq_zero_iff ModularCurve.coe_uniformizerBar ModularCurve.qSeriesBar_pow ModularCurve.cuspInfty_toValuationSubring ModularCurve.qSeriesBar_one ModularCurve.qSeriesBar_inv ModularCurve.qSeriesBar_sub ModularCurve.qSeriesBar_neg ModularCurve.coe_cuspidalDivisor₀ AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply"
p2m_attr_erase "simp" "AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd ModularCurve.eisensteinNumerator_nineteen ModularCurve.eisensteinNumerator_seventeen ModularCurve.eisensteinNumerator_eleven ModularCurve.eisensteinNumerator_five ModularCurve.eisensteinNumerator_seven ModularCurve.eisensteinNumerator_twentythree ModularCurve.eisensteinNumerator_thirteen ModularCurve.constantCoeff_dedekindEtaUnitQ WeierstrassCurve.reducePoint_zero WeierstrassCurve.Affine.Point.galoisRep_apply ModularCurve.ProjectiveLine.map_mk AlgebraicCurve.CurveModel.coe_primeEquivChartPlaces AlgebraicCurve.ConstantReduction.toRegularProlongation_residue AlgebraicCurve.RegularProlongation.mk.sizeOf_spec AlgebraicCurve.ConstantReduction.toRegularProlongation_integers AlgebraicCurve.RegularProlongation.mk.injEq AlgebraicCurve.ConstantReduction.mk.injEq AlgebraicCurve.ConstantReduction.mk.sizeOf_spec AlgebraicCurve.ConstantReduction.divMap_apply AlgebraicCurve.ConstantReduction.coe_degZeroMap AlgebraicCurve.mulAdele_apply AlgebraicCurve.residuePairing_apply_coe AlgebraicCurve.mem_adeleBdd AlgebraicCurve.weilSmul_one AlgebraicCurve.diagonalHom_apply AlgebraicCurve.weilSmul_apply AlgebraicCurve.adeleSpaceMul_coe AlgebraicCurve.mulAdele_one"
p2m_attr_erase "simp" "AlgebraicCurve.TranscendenceTower.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.injEq AlgebraicCurve.TranscendenceTower.mk.injEq AlgebraicCurve.PoleDivisorPackage.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.sizeOf_spec AlgebraicCurve.PoleDivisorPackage.mk.injEq AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.Place.differentialCoeff_zero AlgebraicCurve.Place.differentialCoeff_dCoord AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none ModularCurve.coe_uniformizerMod ModularCurve.qSeriesBar_jModElt ModularCurve.qInftyPlaceMod_toValuationSubring PeriodPair.weierstrassCurve_a₆ PeriodPair.weierstrassCurve_a₃ PeriodPair.weierstrassCurve_a₁ PeriodPair.ofTau_ω₂ PeriodPair.scale_ω₂ PeriodPair.ofTau_ω₁ PeriodPair.toPoint_zero PeriodPair.toPoint_of_mem PeriodPair.weierstrassCurve_a₂ PeriodPair.ofTau_lattice PeriodPair.scale_ω₁ PeriodPair.weierstrassCurve_a₄ AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.sizeOf_spec AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.injEq AlgebraicCurve.adeleSingle_coe AlgebraicCurve.kaehlerResidueTermKFam_apply AlgebraicCurve.Place.LocalResidueData.mk.injEq AlgebraicCurve.Place.LocalResidueData.mk.sizeOf_spec AlgebraicCurve.Place.kw_ffgc_adicCompletionComapIntegers_coe AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.sizeOf_spec AlgebraicCurve.Place.mem_simplePoleSubmodule AlgebraicCurve.Place.coe_uniformizerSubring"
p2m_attr_erase "simp" "ModularCurve.Lg37.Lg37CompletionSection.mk.injEq AlgebraicCurve.Place.CoefficientFieldSection.mk.injEq AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.injEq ModularCurve.Lg37.Lg37CompletionSection.mk.sizeOf_spec AlgebraicCurve.Place.CoefficientFieldSection.mk.sizeOf_spec AlgebraicCurve.Place.poleSubmodule_one AlgebraicCurve.Place.mem_poleSubmodule ModularCurve.LevelN.coe_jGen HahnSeries.ramScale_apply ModularCurve.tateUnivCurve_a₂ ModularCurve.tateUnivCurve_a₃ ModularCurve.tateUnivCurve_a₆ ModularCurve.nonToricPoint_fst ModularCurve.toricPoint_snd ModularCurve.tateUnivCurve_a₁ ModularCurve.nonToricPoint_snd ModularCurve.tateUnivCurve_a₄ ModularCurve.toricPoint_fst ModularCurve.tateLaurent_a₆ ModularCurve.tatePowerSeries_a₄ ModularCurve.tatePowerSeries_a₆ ModularCurve.tateLaurent_a₄ ModularCurve.tatePowerSeries_a₁ ModularCurve.tatePowerSeries_a₂ ModularCurve.tatePowerSeries_a₃ ModularCurve.cuspData_yP ModularCurve.qTwistAlgHom_apply ModularCurve.cuspData_yQ ModularCurve.cuspData_xP ModularCurve.cuspData_xQ ModularCurve.val_cyclZeta ModularCurve.cuspShift_one ModularCurve.cuspShift_zero ModularCurve.LevelPData.mk.sizeOf_spec ModularCurve.KatzLevelPForm.neg_toFun ModularCurve.LevelP.coe_swapW ModularCurve.KatzLevelPForm.swap_swap KatzModularForm.pullbackLevelP_toFun ModularCurve.LevelPData.swap_xQ KatzModularForm.pullbackLevelP_zero"
p2m_attr_erase "simp" "ModularCurve.LevelPData.map_yP ModularCurve.KatzLevelPForm.swap_neg ModularCurve.KatzGamma0Form.toKatzLevelPForm_sub ModularCurve.KatzLevelPForm.swap_add KatzModularForm.swap_pullbackLevelP ModularCurve.KatzGamma0Form.toKatzLevelPForm_add ModularCurve.KatzLevelPForm.swap_smul ModularCurve.LevelPData.map_yQ ModularCurve.KatzLevelPForm.mk.injEq ModularCurve.KatzLevelPForm.zero_toFun KatzModularForm.pullbackLevelP_smul ModularCurve.LevelPData.swap_xP ModularCurve.KatzGamma0Form.toKatzLevelPForm_mul ModularCurve.KatzGamma0Form.toKatzLevelPForm_neg ModularCurve.LevelPData.variableChange_xQ KatzModularForm.pullbackGamma0_toKatzLevelPForm ModularCurve.KatzLevelPForm.mk.sizeOf_spec ModularCurve.KatzLevelPForm.swap_zero ModularCurve.LevelP.coe_unipotentU ModularCurve.KatzLevelPForm.mul_toFun ModularCurve.LevelPData.variableChange_yP ModularCurve.LevelPData.mk.injEq ModularCurve.KatzLevelPForm.sub_toFun ModularCurve.LevelPData.variableChange_xP ModularCurve.KatzLevelPForm.smul_toFun ModularCurve.LevelPData.swap_yP ModularCurve.LevelPData.map_xP ModularCurve.LevelPData.swap_swap ModularCurve.LevelPData.swap_yQ ModularCurve.KatzGamma0Form.toKatzLevelPForm_zero ModularCurve.KatzGamma0Form.mk.injEq ModularCurve.KatzLevelPForm.swap_toFun KatzModularForm.pullbackLevelP_add ModularCurve.KatzGamma0Form.mk.sizeOf_spec ModularCurve.LevelPData.variableChange_yQ ModularCurve.KatzLevelPForm.swap_sub ModularCurve.KatzGamma0Form.toKatzLevelPForm_smul ModularCurve.LevelPData.map_xQ ModularCurve.KatzLevelPForm.add_toFun KatzModularForm.c₆_toFun"
p2m_attr_erase "simp" "KatzModularForm.neg_toFun KatzModularForm.mul_toFun KatzModularForm.qExpansion_neg KatzModularForm.discr_toFun KatzModularForm.qExpansion_sub KatzModularForm.qExpansion_add KatzModularForm.qExpansion_mul KatzModularForm.zero_toFun KatzModularForm.mk.injEq KatzModularForm.qExpansion_smul KatzModularForm.smul_toFun KatzModularForm.add_toFun KatzModularForm.sub_toFun KatzModularForm.c₄_toFun KatzModularForm.qExpansion_zero KatzModularForm.mk.sizeOf_spec TateCurve.tateTorsionPoint_zero_zero TateCurve.cauchyMulInt_zero TateCurve.cauchyMulInt3_zero TateCurve.tent_one TateCurve.Gz_zero TateCurve.cauchyMulInt_one TateCurve.tent_zero TateCurve.Fz_zero TateCurve.xCoeffFull_succ TateCurve.a₆Coeff_zero TateCurve.a₄Coeff_succ TateCurve.a₄Coeff_zero TateCurve.cauchyMul_zero TateCurve.a₆Coeff_succ TateCurve.yCoeffFull_succ TateCurve.xCoeffFull_zero TateCurve.yCoeffFull_zero TateCurve.yfun_zero TateCurve.xfun_zero TateCurve.yTerm_zero TateCurve.xTerm_zero TateCurve.curve_a₂ TateCurve.b_one TateCurve.curve_a₁"
p2m_attr_erase "simp" "TateCurve.term_zero TateCurve.curve_a₆ TateCurve.curve_a₄ TateCurve.curve_a₃ FLT.DivisorConvolution.sigma_zero_right FLT.DivisorConvolution.sigma_one_right FLT.DivisorConvolution.sigmaConv_one FLT.DivisorConvolution.sigmaConv_zero WeierstrassCurve.Affine.Point.netCol_one WeierstrassCurve.Affine.Point.xOrZero_zero WeierstrassCurve.Affine.Point.netPairing_zero_right WeierstrassCurve.Affine.Point.netW20_some WeierstrassCurve.Affine.Point.netCol_zero WeierstrassCurve.Affine.Point.netPairing_zero_left WeierstrassCurve.Affine.Point.xOrZero_some WeierstrassCurve.Affine.Point.netW20_zero compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆"
p2m_attr_erase "simp" "Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two WeierstrassCurve.twoVeluCurve_a₁ WeierstrassCurve.twoVeluCurve_a₂ WeierstrassCurve.twoVeluCurve_a₃ WeierstrassCurve.xVeluCurve_a₃ WeierstrassCurve.xVeluCurve_a₂ WeierstrassCurve.xVeluCurve_a₁ WeierstrassCurve.veluWSum_empty WeierstrassCurve.veluQuotient_a₁ WeierstrassCurve.veluQuotient_a₃ WeierstrassCurve.veluQuotient_empty WeierstrassCurve.veluTSum_empty WeierstrassCurve.veluQuotient_a₂ WeierstrassCurve.veluQuotient2_a₂ WeierstrassCurve.veluQuotient2_a₃ WeierstrassCurve.veluQuotient2_a₁ WeierstrassCurve.veluPointMap2_zero WeierstrassCurve.Affine.Point.coordsOrZero_some WeierstrassCurve.Affine.Point.coordsOrZero_zero WeierstrassCurve.veluY_empty WeierstrassCurve.veluX_empty WeierstrassCurve.map_veluU WeierstrassCurve.map_veluT WeierstrassCurve.map_veluW WeierstrassCurve.map_veluGy WeierstrassCurve.map_veluGx WeierstrassCurve.map_veluWSum_singleton WeierstrassCurve.map_veluTSum_singleton WeierstrassCurve.veluPointMap3_zero WeierstrassCurve.vcInvEmbedding_apply WeierstrassCurve.Affine.IsogenyEndDatum.mk.injEq WeierstrassCurve.Affine.IsogenyHomDatum.mk.sizeOf_spec"
p2m_attr_erase "simp" "WeierstrassCurve.Affine.IsogenyHomDatum.mk.injEq WeierstrassCurve.Affine.IsogenyEndDatum.mk.sizeOf_spec AlgebraicCurve.Pic0.coe_pushforwardAlongDegZero WeierstrassCurve.Affine.pointMapOfPushforward_apply WeierstrassCurve.Affine.pointClass_zero WeierstrassCurve.Affine.pic0ToPoint_pointClass WeierstrassCurve.Affine.deg_placeOfPoint WeierstrassCurve.Affine.coe_pointDivisor WeierstrassCurve.Affine.pointEquivPlace_symm_placeOfPoint WeierstrassCurve.Affine.pointEquivPlace_apply WeierstrassCurve.Affine.genusOnePic0Equiv_symm_apply WeierstrassCurve.Affine.pointDivisor_zero WeierstrassCurve.Affine.pic0ToPoint_mk WeierstrassCurve.Affine.divisorSum_single WeierstrassCurve.Affine.genusOnePic0Equiv_apply WeierstrassCurve.Affine.ratFuncToFunctionField_algebraMap WeierstrassCurve.Affine.pointHom_mk_C_C WeierstrassCurve.Affine.Point.yc_some WeierstrassCurve.Affine.Point.xc_some WeierstrassCurve.Affine.pointPull_algebraMap WeierstrassCurve.Affine.pointHom_mk_C_X WeierstrassCurve.Affine.pointHom_mk_Y WeierstrassCurve.Affine.placeOf_asIdeal AddMonoid.End.DualEndData.symm_trace AddMonoid.End.dualEndData_intCast_norm AddMonoid.End.DualEndData.ofCharPoly_norm AddMonoid.End.DualEndData.mk.sizeOf_spec AddMonoid.End.DualEndData.mk.injEq AddMonoid.End.DualEndData.ofCharPoly_dual AddMonoid.End.dualEndData_intCast_dual AddMonoid.End.DualEndData.intLinComb_norm AddMonoid.End.DualEndData.ofCharPoly_trace AddMonoid.End.DualEndData.intLinComb_dual AddMonoid.End.DualEndData.symm_dual AddMonoid.End.DualEndData.intLinComb_trace AddMonoid.End.dualEndData_intCast_trace AddMonoid.End.DualEndData.symm_norm FormalCoordinates.mk.injEq WeierstrassCurve.formalParam_zero WeierstrassCurve.SmoothLocusReductionData.reduceHom₀_apply"
p2m_attr_erase "simp" "WeierstrassCurve.formalParam_some FormalCoordinates.mk.sizeOf_spec WeierstrassCurve.SmoothLocusReductionData.mk.injEq WeierstrassCurve.reducePointSmooth_zero WeierstrassCurve.SmoothLocusReductionData.mk.sizeOf_spec WeierstrassCurve.mem_zeroComponentSubgroup_iff RegularLocalRingQuotientAscent.dualNumberFst_apply AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.injEq AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.sizeOf_spec AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U1 AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U0 TwoChartCech.Sections.mk.injEq TwoChartCech.Cover.mk.injEq TwoChartCech.GrothendieckComplex.mk.injEq TwoChartCech.Sections.mk.sizeOf_spec TwoChartCech.Cover.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r0_apply TwoChartCech.GrothendieckComplex.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r1_apply CoherentBaseChange.TwoTermComplex.mk.sizeOf_spec CoherentBaseChange.TwoTermComplex.mk.injEq AlgebraicCurve.CurveModel.mk.injEq AlgebraicCurve.CurveModel.mk.sizeOf_spec ModularCurve.coe_heckeBetaModLHOf ModularCurve.pairDiagModL_apply ModularCurve.coe_heckeAlphaModLH ModularCurve.pairUpModL_apply ModularCurve.coeff_qDecimate ModularCurve.coe_qExpFrobeniusModL ModularCurve.coe_qExpFrobeniusDegZeroPullbackModL ModularCurve.coe_qExpFrobeniusDegZeroPushforwardModL ModularCurve.coe_frobeniusModL ModularCurve.coe_frobeniusDegZeroPullbackModL ModularCurve.coe_frobeniusDegZeroPushforwardModL ModularCurve.qEulerFun_coeff ModularCurve.diffQExp_D ModularCurve.qEulerOn_apply ModularCurve.qEuler_coeff ModularCurve.coe_heckeBetaBarRingHom ModularCurve.coe_heckeBetaBar"
p2m_attr_erase "simp" "ModularCurve.coe_heckeAlphaBar AlgebraicCurve.gluedPolarDifferentials.coe_fst_apply AlgebraicCurve.gluedPolarDifferentials.coe_snd_apply AlgebraicCurve.GluedPic0.toPic0Pair_mk AlgebraicCurve.GluedPic0.toPic0Pair_nodeUnit CuspForm.heckeGenH_T CuspForm.coe_twoCuspEnd_apply CuspForm.twoCuspEndMod_reduce CuspForm.heckeGenH_U CuspForm.heckeGenH_dia ModularForm.AtkinLehnerDatum.mk.injEq ModularForm.AtkinLehnerDatum.alGL_coe ModularForm.AtkinLehnerDatum.mk.sizeOf_spec ModularForm.AtkinLehnerDatum.sqUnitSL_coe ModularForm.AtkinLehnerDatum.det_sqUnit ModularForm.AtkinLehnerDatum.det_mat ModularCurve.baseAut_x1ArithFrobC_apply ModularCurve.coe_qExpCoeffRingAut_apply ModularCurve.qExpCoeffSemilinearAutHom_apply ModularCurve.baseAut_x1x0ArithFrobC_apply ModularCurve.baseAut_qExpArithFrobC_apply ModularCurve.baseAut_qExpCoeffSemilinearAut ModularCurve.toRingAut_qExpCoeffSemilinearAut ModularForm.coe_atkinLehnerLin_apply CuspForm.coe_atkinLehnerLin_apply ModularCurve.CharPReduction.coeffRed_coeff ModularCurve.CharPReduction.redLocHom_apply ModularCurve.coe_towerInclBar ModularCurve.coe_towerSubstBar ModularCurve.ComplexPlaceDictionaryOf.pt_ofGamma0 ModularCurve.ComplexPlaceDictionaryOf.mk.injEq ModularCurve.ComplexPlaceDictionaryOf.pt_toGamma0 ModularCurve.ComplexPlaceDictionaryOf.mk.sizeOf_spec ModularCurve.ComplexPlaceDictionary.mk.injEq ModularCurve.ComplexPlaceDictionary.mk.sizeOf_spec ModularCurve.coe_nodeEquiv_symm_apply ModularCurve.frobNodePair_jOfNode ModularCurve.jOfNode_mk ModularCurve.widthOf_mk ModularCurve.frobNodePairEmb_apply"
p2m_attr_erase "simp" "ModularCurve.card_nodePairsOf ModularCurve.frobNodePair_snd ModularCurve.coe_nodeEquiv_apply ModularCurve.frobNodePair_fst ModularCurve.charLGeomModuliDictionary_single ModularCurve.specializeModuli_single ModularCurve.specializePlace_def ModularCurve.IgusaScheme.ιInf_igusaTo_assoc ModularCurve.IgusaScheme.coe_jFull ModularCurve.IgusaScheme.coe_jInvChartInf ModularCurve.IgusaScheme.coe_jChartFin ModularCurve.IgusaScheme.ιFin_igusaTo ModularCurve.IgusaScheme.ιInf_igusaTo ModularCurve.IgusaScheme.ιFin_igusaTo_assoc ModularCurve.toRingAut_coeffSemilinearAut ModularCurve.baseAut_arithFrobC_apply ModularCurve.coe_coeffRingAut_apply ModularCurve.baseAut_coeffSemilinearAut GoodReductionJacobian.RelativePic0Designation.mk.sizeOf_spec GoodReductionJacobian.AvatarSchemeBridge.mk.injEq MilneJVScheme.JacobianSchemeData.mk.injEq GoodReductionJacobian.AvatarSchemeBridge.mk.sizeOf_spec MilneJVScheme.JacobianSchemeData.mk.sizeOf_spec GoodReductionJacobian.RelativePic0Designation.mk.injEq NeronModelInfra.specGenericFibreInclusion_eq NeronModelInfra.genericFibreRestrict_coe_comp_snd NeronModelInfra.genericFibreRestrict_coe_comp_fst GoodReductionJacobian.schemeHomOverComp_coe NeronModelInfra.schemeHomOverEquivOverHom_apply GoodReductionJacobian.RelativeGroupLaw.mk.sizeOf_spec NeronModelInfra.schemeHomOverEquivOverHom_symm_apply NeronModelInfra.overHomToSchemeHomOver_coe GoodReductionJacobian.RelativeGroupLaw.mk.injEq NeronModelInfra.overHomToSchemeHomOver_schemeHomOverToOverHom NeronModelInfra.schemeHomOverToOverHom_left NeronModelInfra.schemeHomOverToOverHom_overHomToSchemeHomOver ModularCurve.reductionDivAlong_apply ModularCurve.coe_reductionDegZeroAlong NeronModelInfra.NeronModelPropertyBundle.endExtensionEquiv_symm_restrict NeronModelInfra.schemeHomOverComp_id_left"
p2m_attr_erase "simp" "NeronModelInfra.schemeHomOverComp_id_right NeronModelInfra.schemeHomOverId_coe NeronModelInfra.NeronModelPropertyBundle.endExtensionEquiv_apply NeronModelInfra.NeronModelPropertyBundle.restrict_endExtensionEquiv_symm NeronModelInfra.schemeHomOverComp_coe ModularCurve.CharPModel.FibreModel.mk.injEq ModularCurve.CharPModel.FibreModel.mk.sizeOf_spec AlgebraicCurve.CurveModel.coe_gInf AlgebraicCurve.CurveModel.coe_tInvChart AlgebraicCurve.CurveModel.ιInf_gluedToBase_assoc AlgebraicCurve.CurveModel.ιInf_gluedToBase AlgebraicCurve.CurveModel.primeOfι₀_asIdeal AlgebraicCurve.CurveModel.coe_tChart AlgebraicCurve.CurveModel.ι₀_gluedToBase_assoc AlgebraicCurve.CurveModel.primeOfιInf_asIdeal AlgebraicCurve.CurveModel.ι₀_gluedToBase AlgebraicCurve.CurveModel.coe_tma ModularCurve.coe_baseChangeRingHom ModularCurve.cuspCount_one WeierstrassCurve.veluQuotientOfSums_a₂ WeierstrassCurve.veluQuotientOfSums_a₁ WeierstrassCurve.veluQuotientOfSums_a₃ ModularCurve.B3.cycOfCongr_apply_coe ModularCurve.B3.cycOfTorsionBy_symm_apply_coe ModularCurve.B3.redPoint_zero ModularCurve.B3.pointAddEquivOfEq_rfl ModularCurve.B3.vcAddEquiv_apply ModularCurve.B3.scaleAddEquiv_apply ModularCurve.B3.cycOfTorsionBy_apply_coe ModularCurve.B3.val_inv_sU ModularCurve.B3.val_sU ModularCurve.B3.resO_apply HahnSeries.coeff_hahnTwist ModularCurve.HahnSpecialise.coe_specialiseCycSub CycSubOf.coe_map ModularCurve.HahnSpecialise.algebraMap_Qbar_apply ModularCurve.HahnSpecialise.resH_apply ModularCurve.HahnSpecialise.liftModel_map_subtype ModularCurve.HahnSpecialise.specialise_zero ModularCurve.PlaceSpecialization.mk.injEq"
p2m_attr_erase "simp" "ModularCurve.PlaceSpecialization.mk.sizeOf_spec ModularCurve.DRModelPackageLevel.mk.injEq ModularCurve.DRModelPackageLevel.mk.sizeOf_spec ModularCurve.DRModelPackageLevel.πw_val ModularCurve.coe_nodeEquivOfPlaces_apply ModularCurve.widthOfPlaces_mk ModularCurve.smulNodePairEmb_apply ModularCurve.card_nodePairsOfPlaces ModularCurve.smulNodePair_snd ModularCurve.smulNodePair_fst ModularCurve.coe_nodeEquivOfPlaces_symm_apply ModularCurve.coe_jGeomGen ModularCurve.coe_jNGeomGen AlgebraicGeometry.RelPicard.RigidifiedLineBundle.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RigidifiedLineBundle.mk.injEq AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.sizeOf_spec AlgebraicCurve.Pic.baseChange_mk AlgebraicCurve.Place.forgetConstants_toValuationSubring AlgebraicCurve.Place.constantFieldEquiv_symm_apply AlgebraicCurve.Place.ord_forgetConstants AlgebraicCurve.Place.extendConstants_toValuationSubring AlgebraicCurve.Place.constantFieldEquiv_apply_toValuationSubring AlgebraicCurve.Place.mem_fiberConstants AlgebraicCurve.Place.restrictConstants_toValuationSubring"

set_option autoImplicit false

noncomputable section

open CategoryTheory AlgebraicGeometry AlgebraicCurve.TwoChartIntegralModel
open IsLocalRing
open scoped Pointwise
p2m_open "ModularCurve P2MW.S_ModularCurve_XOneGammaZeroP_card_inertia_le_three_of_mem_ssJSet_twoChartIntegralModel_x1x0_gamma0_of_five_le.ModularCurve"

namespace ModularCurve
p2m_export "ModularCurve" "qExpFunctionFieldC x1FunctionFieldC x1x0FunctionFieldC jq coeffEmb laurentBaseChange ssJSet jqModC XOneGammaZeroP.exists_ringEquiv_residueField_x1FunctionFieldC_of_gaussPresentation_x1x0 exists_gaussValuationSubring_laurentBaseChange_qExpFunctionFieldC XOneGammaZeroP.exists_valuationSubring_residueField_unique_and_forall_exists_sub_residue_mem_nonunits_twoChartIntegralModel_x1x0 XOneGammaZeroP.mem_of_coe_mem_nonunits_of_mem_ssJSet_twoChartIntegralModel_x1x0_gamma0 natCard_smul_valuationSubring_eq_and_forall_sub_mem_nonunits_le_three_of_ringEquiv_x1FunctionFieldC XOneGammaZeroP.smul_mem_gaussValuationSubring_of_forall_smul_eq_x1x0_gamma0 XOneGammaZeroP.finrank_residueField_valuationSubring_eq_finrank_and_isSeparable_of_gauss_x1x0_gamma0 exists_powerSeries_coeffEmb_jq_mul_eq_and_div_eq_jqModC_and_qExpand pow_q_sq_eq_self_of_mem_ssJSet coeff_jqModC_neg_one"
namespace T4Core
p2m_open "ModularCurve"

section ResidueActionGeneric

variable {K : Type*} [Field K] {G : Type*} [Group G] [MulSemiringAction G K]
  (W : ValuationSubring K) (hGW : ∀ (g : G) (f : K), f ∈ W → g • f ∈ W)

def gaussRingAut (g : G) : RingAut ↥W where
  toFun f := ⟨g • (f : K), hGW g f f.2⟩
  invFun f := ⟨g⁻¹ • (f : K), hGW g⁻¹ f f.2⟩
  left_inv f := Subtype.ext (inv_smul_smul g (f : K))
  right_inv f := Subtype.ext (smul_inv_smul g (f : K))
  map_mul' a b := Subtype.ext (smul_mul' g (a : K) (b : K))
  map_add' a b := Subtype.ext (smul_add g (a : K) (b : K))

@[scoped simp] theorem coe_gaussRingAut_apply (g : G) (f : ↥W) :
    ((gaussRingAut W hGW g f : ↥W) : K) = g • (f : K) := rfl

def gaussRingAutHom : G →* RingAut ↥W where
  toFun := gaussRingAut W hGW
  map_one' := RingEquiv.ext fun f => Subtype.ext (one_smul G (f : K))
  map_mul' g h := RingEquiv.ext fun f => Subtype.ext (mul_smul g h (f : K))

def residueRingAutHom : G →* RingAut (ResidueField ↥W) :=
  (ResidueField.mapAut).comp (gaussRingAutHom W hGW)

theorem residueRingAutHom_apply_residue (g : G) (f : ↥W) :
    residueRingAutHom W hGW g (residue ↥W f) = residue ↥W ⟨g • (f : K), hGW g f f.2⟩ := by
  show ResidueField.mapEquiv (gaussRingAut W hGW g) (residue ↥W f) = _
  rfl

variable {A : Type*} [CommRing A] [IsLocalRing A] [Algebra A K]
  (hAW : ∀ a : A, algebraMap A K a ∈ W) (hGA : ∀ (g : G) (a : A), g • algebraMap A K a = algebraMap A K a)
  [Algebra (ResidueField A) (ResidueField ↥W)]
  (halg : ∀ a : A, algebraMap (ResidueField A) (ResidueField ↥W) (residue A a) =
    residue ↥W ⟨algebraMap A K a, hAW a⟩)

include hGA halg in
theorem residueRingAutHom_algebraMap (g : G) (r : ResidueField A) :
    residueRingAutHom W hGW g (algebraMap (ResidueField A) (ResidueField ↥W) r) =
      algebraMap (ResidueField A) (ResidueField ↥W) r := by
  obtain ⟨a, rfl⟩ := IsLocalRing.residue_surjective r
  rw [halg, residueRingAutHom_apply_residue]
  congr 2
  exact hGA g a

def residueAction : G →* (ResidueField ↥W ≃ₐ[ResidueField A] ResidueField ↥W) where
  toFun g := AlgEquiv.ofRingEquiv (f := residueRingAutHom W hGW g)
    (residueRingAutHom_algebraMap W hGW hAW hGA halg g)
  map_one' := by
    refine AlgEquiv.ext fun x => ?_
    rw [AlgEquiv.ofRingEquiv_apply, map_one, RingAut.one_apply, AlgEquiv.one_apply]
  map_mul' g h := by
    refine AlgEquiv.ext fun x => ?_
    rw [AlgEquiv.ofRingEquiv_apply, map_mul, RingAut.mul_apply, AlgEquiv.mul_apply,
      AlgEquiv.ofRingEquiv_apply, AlgEquiv.ofRingEquiv_apply]

theorem residueAction_apply_residue (g : G) (f : ↥W) :
    residueAction W hGW hAW hGA halg g (residue ↥W f) = residue ↥W ⟨g • (f : K), hGW g f f.2⟩ := by
  show AlgEquiv.ofRingEquiv _ _ = _
  rw [AlgEquiv.ofRingEquiv_apply, residueRingAutHom_apply_residue]

end ResidueActionGeneric

theorem exists_gaussRing
    (p : ℕ) [Fact p.Prime] (M : ℕ) [NeZero M]
    (L : Type) [Field L] [CharZero L]
    (K₁ : IntermediateField L (LaurentSeries L))
    (hK₁ : K₁ = ModularCurve.laurentBaseChange L (ModularCurve.x1x0FunctionFieldC ℚ M p))
    (A : Type) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] [Algebra A L] [IsFractionRing A L]
    [Algebra A ↥K₁] [IsScalarTower A L ↥K₁]
    (j : ↥K₁) (hj : ((j : LaurentSeries L)) = ModularCurve.coeffEmb L ModularCurve.jq) [Fact (j ≠ 0)] :
    ∃ W₀ : ValuationSubring ↥K₁,
      (∀ f : ↥K₁, f ∈ W₀ ↔ ∃ x y : PowerSeries A, y.map (IsLocalRing.residue A) ≠ 0 ∧
        (f : LaurentSeries L) * HahnSeries.ofPowerSeries ℤ L (y.map (algebraMap A L))
          = HahnSeries.ofPowerSeries ℤ L (x.map (algebraMap A L))) ∧
      (∀ a : A, algebraMap A ↥K₁ a ∈ W₀) ∧
      (∀ a ∈ IsLocalRing.maximalIdeal A, algebraMap A ↥K₁ a ∈ W₀.nonunits) ∧
      (∀ P : Polynomial A, P.map (IsLocalRing.residue A) ≠ 0 →
        Polynomial.aeval j P ∈ W₀ ∧ (Polynomial.aeval j P)⁻¹ ∈ W₀) := by
  obtain ⟨W₀, h1, h2, h3, h4, -⟩ :=
    ModularCurve.exists_gaussValuationSubring_laurentBaseChange_qExpFunctionFieldC
      (CongruenceSubgroup.Gamma1 M ⊓ CongruenceSubgroup.Gamma0 p) L K₁ hK₁ A j hj
  exact ⟨W₀, h1, h2, h3, h4⟩

theorem chart_mem_gaussRing
    (L : Type) [Field L] [CharZero L]
    (K₁ : IntermediateField L (LaurentSeries L))
    (A : Type) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] [Algebra A L] [IsFractionRing A L]
    [Algebra A ↥K₁] [IsScalarTower A L ↥K₁]
    (j : ↥K₁) (W₀ : ValuationSubring ↥K₁) (hjW : j ∈ W₀) (hAW : ∀ a : A, algebraMap A ↥K₁ a ∈ W₀)
    (s : ↥(chartAlgFin A (↥K₁) j)) : (s : ↥K₁) ∈ W₀ := by

  let WA : Subalgebra A ↥K₁ :=
    { carrier := W₀
      mul_mem' := fun ha hb => W₀.mul_mem _ _ ha hb
      one_mem' := W₀.one_mem
      add_mem' := fun ha hb => W₀.add_mem _ _ ha hb
      zero_mem' := W₀.zero_mem
      algebraMap_mem' := hAW }
  have hle : Algebra.adjoin A ({j} : Set ↥K₁) ≤ WA :=
    Algebra.adjoin_le (Set.singleton_subset_iff.mpr hjW)

  let incl : ↥(Algebra.adjoin A ({j} : Set ↥K₁)) →+* ↥W₀ :=
    { toFun := fun x => ⟨(x : ↥K₁), hle x.2⟩
      map_one' := rfl
      map_mul' := fun _ _ => rfl
      map_zero' := rfl
      map_add' := fun _ _ => rfl }
  have hint : IsIntegral ↥(Algebra.adjoin A ({j} : Set ↥K₁)) (s : ↥K₁) := s.2
  obtain ⟨P, hPm, hPev⟩ := hint
  have hint' : IsIntegral ↥W₀ (s : ↥K₁) := by
    refine ⟨P.map incl, hPm.map incl, ?_⟩
    rw [Polynomial.eval₂_map]
    have hc : (algebraMap ↥W₀ ↥K₁).comp incl =
        algebraMap ↥(Algebra.adjoin A ({j} : Set ↥K₁)) ↥K₁ := RingHom.ext fun _ => rfl
    rw [hc]
    exact hPev
  obtain ⟨y, hy⟩ := IsIntegrallyClosed.isIntegral_iff.mp hint'
  rw [← hy]
  exact y.2

theorem smul_algebraMap_eq
    (L : Type) [Field L]
    (K₁ : IntermediateField L (LaurentSeries L)) (K₂ : IntermediateField L (LaurentSeries L))
    (A : Type) [CommRing A] [Algebra A L] [Algebra A ↥K₁] [IsScalarTower A L ↥K₁]
    (G : Type) [Group G] [MulSemiringAction G ↥K₁]
    (hGfixK : ∀ (g : G) (x : ↥K₁), (x : LaurentSeries L) ∈ K₂ → g • x = x)
    (g : G) (a : A) : g • algebraMap A ↥K₁ a = algebraMap A ↥K₁ a := by
  apply hGfixK
  rw [IsScalarTower.algebraMap_apply A L ↥K₁]
  exact K₂.algebraMap_mem (algebraMap A L a)

section P6

variable (κ : Type*) [Field κ] (M : ℕ)

theorem transcendental_of_coe_eq_jqModC (J : ↥(x1FunctionFieldC κ M))
    (hJ : (J : LaurentSeries κ) = jqModC κ) : Transcendental κ J := by
  intro hJalg
  have hy' : IsAlgebraic κ (J : LaurentSeries κ) := IntermediateField.isAlgebraic_iff.mp hJalg
  obtain ⟨c, hc⟩ := LaurentSeries.exists_eq_C_of_isAlgebraic (J : LaurentSeries κ) hy'
  have h1 : (jqModC κ).coeff (-1 : ℤ) = 1 := coeff_jqModC_neg_one κ
  rw [← hJ, hc, HahnSeries.C_apply, HahnSeries.coeff_single_of_ne (by decide)] at h1
  exact zero_ne_one h1

theorem transcendental_coe_of_coe_eq_jqModC (J : ↥(x1FunctionFieldC κ M))
    (hJ : (J : LaurentSeries κ) = jqModC κ) : Transcendental κ (J : LaurentSeries κ) := fun h =>
  transcendental_of_coe_eq_jqModC κ M J hJ (IntermediateField.isAlgebraic_iff.mpr h)

end P6

universe uG in

theorem germ_toBase_mem_maximalIdeal_iff
    (R : Type uG) [CommRing R] (F : Type uG) [Field F] [Algebra R F] (j : F) [Fact (j ≠ 0)]
    (y : ↥(XFin R F j)) (r : R) :
    (((AlgebraicCurve.TwoChartIntegralModel R F j).presheaf.germ ⊤ ((ιFin R F j).base y) trivial).hom
        (((toBase R F j).appTop).hom ((Scheme.ΓSpecIso (CommRingCat.of R)).inv.hom r)))
      ∈ IsLocalRing.maximalIdeal ((AlgebraicCurve.TwoChartIntegralModel R F j).presheaf.stalk ((ιFin R F j).base y)) ↔
    algebraMap R ↥(chartAlgFin R F j) r ∈ y.asIdeal := by
  obtain ⟨e, he, -⟩ := exists_stalk_iso_localization_chartAlgFin R F j y ⟨y, trivial, rfl⟩
  let E := e.commRingCatIsoToRingEquiv
  have hE : ∀ x, E x = e.hom.hom x := fun _ => rfl
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, ← isUnit_map_iff E, hE, he,
    IsScalarTower.algebraMap_apply R ↥(chartAlgFin R F j) (Localization.AtPrime y.asIdeal),
    ← mem_nonunits_iff, ← IsLocalRing.mem_maximalIdeal]
  exact IsLocalization.AtPrime.to_map_mem_maximal_iff (Localization.AtPrime y.asIdeal) y.asIdeal _

end ModularCurve.T4Core
p2m_reactivate "P2MW.S_ModularCurve_XOneGammaZeroP_card_inertia_le_three_of_mem_ssJSet_twoChartIntegralModel_x1x0_gamma0_of_five_le.ModularCurve P2MW.S_ModularCurve_XOneGammaZeroP_card_inertia_le_three_of_mem_ssJSet_twoChartIntegralModel_x1x0_gamma0_of_five_le.ModularCurve.T4Core"
p2m_reactivate "P2MW.S_ModularCurve_XOneGammaZeroP_card_inertia_le_three_of_mem_ssJSet_twoChartIntegralModel_x1x0_gamma0_of_five_le.ModularCurve"

set_option synthInstance.maxHeartbeats 1600000 in
set_option maxHeartbeats 3200000 in
open ModularCurve.T4Core in
theorem solution
    (p : ℕ) [Fact p.Prime] (M : ℕ) [NeZero M] (hM : 5 ≤ M) (hpM : ¬ p ∣ M)
    (hp5 : 5 ≤ p)
    (L : Type) [Field L] [CharZero L] [IsCyclotomicExtension {p} ℚ L]
    (ζ : L) (hζ : IsPrimitiveRoot ζ p)
    (K₁ : IntermediateField L (LaurentSeries L))
    (hK₁ : K₁ = ModularCurve.laurentBaseChange L (ModularCurve.x1x0FunctionFieldC ℚ M p))

    (K₂ : IntermediateField L (LaurentSeries L))
    (hK₂ : K₂ = ModularCurve.laurentBaseChange L (ModularCurve.qExpFunctionFieldC ℚ (CongruenceSubgroup.Gamma0 (M * p))))
    (hle : K₂ ≤ K₁)
    (A : Type) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] [Algebra A L] [IsFractionRing A L]
    (hAp : (p : A) ∈ IsLocalRing.maximalIdeal A) (hζA : ∃ z : A, algebraMap A L z = ζ)
    [Algebra A ↥K₁] [IsScalarTower A L ↥K₁]
    [Algebra A ↥K₂] [IsScalarTower A L ↥K₂]
    (j : ↥K₁) (hj : ((j : LaurentSeries L)) = ModularCurve.coeffEmb L ModularCurve.jq) [Fact (j ≠ 0)]
    (j₂ : ↥K₂) (hj₂ : ((j₂ : LaurentSeries L)) = ModularCurve.coeffEmb L ModularCurve.jq) [Fact (j₂ ≠ 0)]
    (ϖ : A) (hϖ : IsLocalRing.maximalIdeal A = Ideal.span {ϖ})

    (π₂ : (AlgebraicCurve.TwoChartIntegralModel A (↥K₁) j) ⟶ (AlgebraicCurve.TwoChartIntegralModel A (↥K₂) j₂))
    (ιF₂ : ↥(chartAlgFin A (↥K₂) j₂) →ₐ[A] ↥(chartAlgFin A (↥K₁) j))
    (hιF₂ : ∀ x, (((ιF₂ x : ↥K₁) : LaurentSeries L)) = ((x : ↥K₂) : LaurentSeries L))
    (hπbase : π₂ ≫ toBase A (↥K₂) j₂ = toBase A (↥K₁) j)
    (hπF : Spec.map (CommRingCat.ofHom ιF₂.toRingHom) ≫ ιFin A (↥K₂) j₂ = ιFin A (↥K₁) j ≫ π₂)
    (hpreF : π₂ ⁻¹ᵁ (ιFin A (↥K₂) j₂).opensRange = (ιFin A (↥K₁) j).opensRange)
    (hπfin : IsFinite π₂) (hιF₂fin : ιF₂.toRingHom.Finite)
    (hintF : ∀ x : ↥K₁, x ∈ chartAlgFin A (↥K₁) j ↔ IsIntegral ↥((ιF₂.range).map (chartAlgFin A (↥K₁) j).val) x)

    (z : ↥(AlgebraicCurve.TwoChartIntegralModel A (↥K₁) j))
    (ϖz : (AlgebraicCurve.TwoChartIntegralModel A (↥K₁) j).presheaf.stalk z)
    (hϖz : ϖz = (((AlgebraicCurve.TwoChartIntegralModel A (↥K₁) j).presheaf.germ ⊤ z trivial).hom (((AlgebraicCurve.TwoChartIntegralModel.toBase A (↥K₁) j).appTop).hom ((Scheme.ΓSpecIso (CommRingCat.of A)).inv.hom ϖ))))
    (hz : ϖz ∈ IsLocalRing.maximalIdeal ((AlgebraicCurve.TwoChartIntegralModel A (↥K₁) j).presheaf.stalk z))
    (y : ↥(XFin A (↥K₁) j)) (hy : (ιFin A (↥K₁) j).base y = z)
    (hss : ∀ (Ω : Type) [Field Ω] [CharP Ω p] [IsAlgClosed Ω] [DecidableEq Ω]
      (φ : ↥(chartAlgFin A (↥K₁) j) →+* Ω),
      RingHom.ker φ = y.asIdeal → φ (jChartFin A (↥K₁) j) ∈ ModularCurve.ssJSet p Ω)

    (G : Type) [Group G] [Fintype G] [MulSemiringAction G ↥K₁] [FaithfulSMul G ↥K₁]
    (hGfixK : ∀ (g : G) (x : ↥K₁), (x : LaurentSeries L) ∈ K₂ → g • x = x)
    (hGinvK : ∀ x : ↥K₁, (∀ g : G, g • x = x) → (x : LaurentSeries L) ∈ K₂)
    [MulSemiringAction G ↥(chartAlgFin A (↥K₁) j)]
    (hGA : ∀ (g : G) (a : ↥(chartAlgFin A (↥K₁) j)), ((g • a : ↥(chartAlgFin A (↥K₁) j)) : ↥K₁) = g • (a : ↥K₁))

    (𝔶 : Ideal ↥(chartAlgFin A (↥K₁) j)) (h𝔶 : 𝔶 = y.asIdeal) :
    Nat.card ↥(𝔶.inertia G) ≤ 3 := by
  classical
  subst hy

  obtain ⟨W₀, hW₀, hAW, hmW, hVj⟩ := exists_gaussRing p M L K₁ hK₁ A j hj
  have hjW : j ∈ W₀ := by
    simpa using (hVj Polynomial.X (by simp)).1

  have hSW₀ : ∀ s : ↥(chartAlgFin A (↥K₁) j), (s : ↥K₁) ∈ W₀ :=
    chart_mem_gaussRing L K₁ A j W₀ hjW hAW

  have hGW : ∀ (g : G) (f : ↥K₁), f ∈ W₀ → g • f ∈ W₀ :=
    ModularCurve.XOneGammaZeroP.smul_mem_gaussValuationSubring_of_forall_smul_eq_x1x0_gamma0
      p M hM hpM L ζ hζ K₁ hK₁ K₂ hK₂ A hAp hζA W₀ hW₀ G hGfixK

  let ιA : A →+* ↥W₀ := (algebraMap A ↥K₁).codRestrict W₀.toSubring (fun a => hAW a)
  haveI hloc : IsLocalHom ιA := by
    refine ⟨fun a ha => ?_⟩
    by_contra hna
    have hmem : a ∈ IsLocalRing.maximalIdeal A := by
      simpa [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff] using hna
    have h1 : ((ιA a : ↥W₀) : ↥K₁) ∈ W₀.nonunits := hmW a hmem
    have h2 : ιA a ∈ IsLocalRing.maximalIdeal ↥W₀ := (ValuationSubring.coe_mem_nonunits_iff).1 h1
    exact ((IsLocalRing.mem_maximalIdeal _).1 h2) ha
  letI : Algebra (ResidueField A) (ResidueField ↥W₀) := (IsLocalRing.ResidueField.map ιA).toAlgebra
  have halg : ∀ a : A, algebraMap (ResidueField A) (ResidueField ↥W₀) (residue A a) =
      residue ↥W₀ ⟨algebraMap A ↥K₁ a, hAW a⟩ := by
    intro a
    rfl

  have hGA' : ∀ (g : G) (a : A), g • algebraMap A ↥K₁ a = algebraMap A ↥K₁ a :=
    smul_algebraMap_eq L K₁ K₂ A G hGfixK
  let Φ : G →* (ResidueField ↥W₀ ≃ₐ[ResidueField A] ResidueField ↥W₀) := residueAction W₀ hGW hAW hGA' halg
  have hΦ : ∀ (g : G) (f : ↥W₀), Φ g (residue ↥W₀ f) = residue ↥W₀ ⟨g • (f : ↥K₁), hGW g f f.2⟩ :=
    residueAction_apply_residue W₀ hGW hAW hGA' halg

  have hfaith : ∀ g : G, (∀ f : ↥K₁, f ∈ W₀ → g • f - f ∈ W₀.nonunits) → g = 1 := by

    let ι₂ : ↥K₂ →+* ↥K₁ := (IntermediateField.inclusion hle).toRingHom
    have hι₂ : ∀ y : ↥K₂, (((ι₂ y : ↥K₁) : LaurentSeries L)) = ((y : ↥K₂) : LaurentSeries L) := fun _ => rfl
    let V₂ : ValuationSubring ↥K₂ := W₀.comap ι₂
    have hV₂ : ∀ y : ↥K₂, y ∈ V₂ ↔ ι₂ y ∈ W₀ := fun _ => Iff.rfl

    letI instGW : MulSemiringAction G ↥W₀ := MulSemiringAction.compHom ↥W₀ (gaussRingAutHom W₀ hGW)
    have hsmulW : ∀ (g : G) (f : ↥W₀), ((g • f : ↥W₀) : ↥K₁) = g • (f : ↥K₁) := fun _ _ => rfl
    let ψ₂ : ↥V₂ →+* ↥W₀ :=
      { toFun := fun v => ⟨ι₂ (v : ↥K₂), (hV₂ v).1 v.2⟩
        map_one' := Subtype.ext (map_one ι₂)
        map_mul' := fun a b => Subtype.ext (map_mul ι₂ _ _)
        map_zero' := Subtype.ext (map_zero ι₂)
        map_add' := fun a b => Subtype.ext (map_add ι₂ _ _) }
    letI algVW : Algebra ↥V₂ ↥W₀ := ψ₂.toAlgebra
    have halgV : ∀ y : ↥V₂, (((algebraMap ↥V₂ ↥W₀ y : ↥W₀) : ↥K₁)) = ι₂ (y : ↥K₂) := fun _ => rfl
    haveI : IsLocalHom (algebraMap ↥V₂ ↥W₀) := by
      refine ⟨fun v hv => ?_⟩

      obtain ⟨w, hw⟩ := hv.exists_right_inv
      have hvK : ι₂ (v : ↥K₂) * (w : ↥K₁) = 1 := by
        have := congrArg (fun x : ↥W₀ => (x : ↥K₁)) hw
        simpa [halgV] using this
      have hv0 : (v : ↥K₂) ≠ 0 := by
        intro h0; rw [h0, map_zero, zero_mul] at hvK; exact zero_ne_one hvK
      have hw' : (w : ↥K₁) = ι₂ ((v : ↥K₂)⁻¹) := by
        rw [map_inv₀]; exact eq_inv_of_mul_eq_one_right hvK
      have hinvV : (v : ↥K₂)⁻¹ ∈ V₂ := by
        show ι₂ _ ∈ W₀
        rw [← hw']; exact w.2
      exact isUnit_iff_exists_inv.2 ⟨⟨(v : ↥K₂)⁻¹, hinvV⟩, Subtype.ext (mul_inv_cancel₀ hv0)⟩
    haveI : SMulCommClass G ↥V₂ ↥W₀ := by
      refine ⟨fun g v f => Subtype.ext ?_⟩
      have hfix : g • ι₂ (v : ↥K₂) = ι₂ (v : ↥K₂) := hGfixK g _ (by rw [hι₂]; exact (v : ↥K₂).2)
      rw [Algebra.smul_def, Algebra.smul_def, hsmulW, MulMemClass.coe_mul, MulMemClass.coe_mul, hsmulW, halgV,
        smul_mul', hfix]
    haveI : Algebra.IsInvariant ↥V₂ ↥W₀ G := by
      refine ⟨fun f hf => ?_⟩
      have hfix : ∀ g : G, g • (f : ↥K₁) = (f : ↥K₁) := fun g => by rw [← hsmulW, hf g]
      have hmem : ((f : ↥K₁) : LaurentSeries L) ∈ K₂ := hGinvK _ hfix
      refine ⟨⟨⟨(f : ↥K₁), hmem⟩, ?_⟩, Subtype.ext ?_⟩
      · rw [hV₂]; convert f.2 using 2 <;> first | (with_reducible_and_instances rfl) | rfl | skip
      · rw [halgV]; rfl
    have hres : ∀ y : ↥V₂, algebraMap (ResidueField ↥V₂) (ResidueField ↥W₀) (residue ↥V₂ y)
        = residue ↥W₀ (algebraMap ↥V₂ ↥W₀ y) := fun y => by
      first | rfl | exact IsLocalRing.ResidueField.algebraMap_residue y | exact IsLocalRing.ResidueField.map_residue _ y

    obtain ⟨hfin, hsep⟩ :=
      ModularCurve.XOneGammaZeroP.finrank_residueField_valuationSubring_eq_finrank_and_isSeparable_of_gauss_x1x0_gamma0
        p M hM hpM L ζ hζ K₁ hK₁ K₂ hK₂ ι₂ hι₂ A hAp hζA j hj W₀ hAW hmW hVj V₂ hV₂ halgV hres

    have hcount : IntermediateField.relfinrank K₂ K₁ = Nat.card G := by
      rw [IntermediateField.relfinrank_eq_finrank_of_le hle, Nat.card_eq_fintype_card, ← FixedPoints.finrank_eq_card G ↥K₁]

      let S : Subfield ↥K₁ := FixedPoints.subfield G ↥K₁
      have hSmem : ∀ x : ↥K₁, x ∈ S ↔ ((x : ↥K₁) : LaurentSeries L) ∈ K₂ :=
        fun x => ⟨fun hx => hGinvK x (fun g => hx g), fun hx g => hGfixK g x hx⟩
      let i : ↥K₂ ≃+* ↥S :=
        { toFun := fun x => ⟨ι₂ x, (hSmem _).2 (by rw [hι₂]; exact x.2)⟩
          invFun := fun s => ⟨((s : ↥K₁) : LaurentSeries L), (hSmem _).1 s.2⟩
          left_inv := fun x => Subtype.ext rfl
          right_inv := fun s => Subtype.ext (Subtype.ext rfl)
          map_mul' := fun a b => Subtype.ext (map_mul ι₂ a b)
          map_add' := fun a b => Subtype.ext (map_add ι₂ a b) }
      let jE : ↥(IntermediateField.extendScalars hle) ≃+* ↥K₁ := RingEquiv.refl _
      symm
      refine Algebra.finrank_eq_of_equiv_equiv i.symm jE.symm ?_
      ext s
      rfl
    have hf := hfin.trans hcount
    obtain ⟨h1, -, -⟩ :=
      IsLocalRing.forall_smul_sub_mem_imp_eq_one_and_exists_sub_mem_and_isGalois_of_isSeparable_of_finrank_residueField_eq_card
        (A := ↥V₂) (B := ↥W₀) G hres hsep hf
    intro g hg
    refine h1 g (fun f => ?_)
    have := hg (f : ↥K₁) f.2
    rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
    exact (ValuationSubring.coe_mem_nonunits_iff).1 (by rw [← hsmulW] at this; exact_mod_cast this) |>
      fun h => (IsLocalRing.mem_maximalIdeal _).1 h
  have hΦinj : Function.Injective Φ := by
    rw [← MonoidHom.ker_eq_bot_iff, Subgroup.eq_bot_iff_forall]
    intro g hg
    refine hfaith g (fun f hf => ?_)
    have h1 : Φ g (residue ↥W₀ ⟨f, hf⟩) = residue ↥W₀ ⟨f, hf⟩ := by
      rw [MonoidHom.mem_ker.1 hg]; rfl
    rw [hΦ] at h1
    have h2 : (⟨g • f, hGW g f hf⟩ : ↥W₀) - ⟨f, hf⟩ ∈ IsLocalRing.maximalIdeal ↥W₀ :=
      Ideal.Quotient.eq.1 h1
    exact (ValuationSubring.coe_mem_nonunits_iff).2 h2

  letI : MulSemiringAction G (ResidueField ↥W₀) := MulSemiringAction.compHom _ Φ
  have hsmulF : ∀ (g : G) (e : ResidueField ↥W₀), g • e = Φ g e := fun _ _ => rfl

  obtain ⟨θ, hθpres, hθconst⟩ :=
    ModularCurve.XOneGammaZeroP.exists_ringEquiv_residueField_x1FunctionFieldC_of_gaussPresentation_x1x0
      p M hM hpM L ζ hζ K₁ hK₁ A hAp hζA W₀ hW₀ hAW

  let ι₁ : ↥(chartAlgFin A (↥K₁) j) →+* ↥W₀ :=
    ((chartAlgFin A (↥K₁) j).val.toRingHom).codRestrict W₀.toSubring (fun s => hSW₀ s)
  let ρ : ↥(chartAlgFin A (↥K₁) j) →+* ResidueField ↥W₀ := (residue ↥W₀).comp ι₁
  have hρapply : ∀ s, ρ s = residue ↥W₀ ⟨(s : ↥K₁), hSW₀ s⟩ := fun s => rfl

  have hJq : ((θ (ρ (jChartFin A (↥K₁) j)) : ↥(ModularCurve.x1FunctionFieldC (ResidueField A) M)) :
      LaurentSeries (ResidueField A)) = ModularCurve.jqModC (ResidueField A) := by
    obtain ⟨⟨x₀, y₀, hy₀0, hpres, hred⟩, -⟩ :=
      ModularCurve.exists_powerSeries_coeffEmb_jq_mul_eq_and_div_eq_jqModC_and_qExpand p L A hAp
    rw [hρapply, ← hred]
    refine hθpres ⟨((jChartFin A (↥K₁) j : ↥(chartAlgFin A (↥K₁) j)) : ↥K₁), hSW₀ _⟩ x₀ y₀ hy₀0 ?_
    have hjc : (((jChartFin A (↥K₁) j : ↥(chartAlgFin A (↥K₁) j)) : ↥K₁) : LaurentSeries L) = ModularCurve.coeffEmb L ModularCurve.jq := by
      rw [← hj]; rfl
    rw [hjc]; exact hpres
  have hρ : ∀ (g : G) (s : ↥(chartAlgFin A (↥K₁) j)), g • ρ s = ρ (g • s) := by
    intro g s
    rw [hsmulF, hρapply, hρapply, hΦ g ⟨(s : ↥K₁), hSW₀ s⟩]
    congr 1
    exact Subtype.ext (hGA g s).symm

  have hy𝔓 : ∀ s : ↥(chartAlgFin A (↥K₁) j), (s : ↥K₁) ∈ W₀.nonunits → s ∈ y.asIdeal := by
    intro s hs
    rw [← h𝔶]
    exact ModularCurve.XOneGammaZeroP.mem_of_coe_mem_nonunits_of_mem_ssJSet_twoChartIntegralModel_x1x0_gamma0
      p M hM hpM L ζ hζ K₁ hK₁ A hAp hζA j hj ϖ hϖ W₀ hW₀ _ ϖz hϖz hz y rfl hss 𝔶 h𝔶 s hs
  have hy₀ : ∃ s : ↥(chartAlgFin A (↥K₁) j), s ∈ y.asIdeal ∧ (s : ↥K₁) ∉ W₀.nonunits := by
    by_contra hcon
    push_neg at hcon

    have hker : RingHom.ker ρ = y.asIdeal := by
      ext s
      rw [RingHom.mem_ker, hρapply, IsLocalRing.residue_eq_zero_iff, ← ValuationSubring.coe_mem_nonunits_iff]
      exact ⟨hy𝔓 s, hcon s⟩

    let Ω : Type := AlgebraicClosure (ResidueField ↥W₀)
    haveI : CharP (ResidueField ↥W₀) p := by
      haveI : CharP (ResidueField A) p := by
        have h0 : ((p : ℕ) : ResidueField A) = 0 := by
          rw [← map_natCast (residue A), IsLocalRing.residue_eq_zero_iff]; exact hAp
        exact (CharP.charP_iff_prime_eq_zero (Fact.out : p.Prime)).2 h0
      exact charP_of_injective_algebraMap (algebraMap (ResidueField A) (ResidueField ↥W₀)).injective p
    let φ : ↥(chartAlgFin A (↥K₁) j) →+* Ω := (algebraMap (ResidueField ↥W₀) Ω).comp ρ
    have hkerφ : RingHom.ker φ = y.asIdeal := by
      rw [← hker]; ext s
      simp only [RingHom.mem_ker, φ, RingHom.comp_apply, map_eq_zero_iff _ (algebraMap (ResidueField ↥W₀) Ω).injective]
    have hssφ := hss Ω φ hkerφ
    have hpow : (ρ (jChartFin A (↥K₁) j)) ^ (p ^ 2) = ρ (jChartFin A (↥K₁) j) := by
      apply (algebraMap (ResidueField ↥W₀) Ω).injective
      rw [map_pow]
      exact ModularCurve.pow_q_sq_eq_self_of_mem_ssJSet p hssφ

    set J := θ (ρ (jChartFin A (↥K₁) j)) with hJdef
    have hJpow : J ^ (p ^ 2) = J := by rw [hJdef, ← map_pow, hpow]
    have halgJ : IsAlgebraic (ResidueField A) J := by
      refine ⟨Polynomial.X ^ (p ^ 2) - Polynomial.X, ?_, ?_⟩
      · exact FiniteField.X_pow_card_sub_X_ne_zero _ (Nat.one_lt_pow two_ne_zero (Fact.out : p.Prime).one_lt)
      · simp [hJpow]
    exact ModularCurve.T4Core.transcendental_of_coe_eq_jqModC (ResidueField A) M J hJq halgJ
  have hyϖ : algebraMap A ↥(chartAlgFin A (↥K₁) j) ϖ ∈ y.asIdeal :=
    (ModularCurve.T4Core.germ_toBase_mem_maximalIdeal_iff A (↥K₁) j y ϖ).mp (hϖz ▸ hz)

  obtain ⟨P, hP, hPy, huniq, hres, hPIR⟩ :=
    ModularCurve.XOneGammaZeroP.exists_valuationSubring_residueField_unique_and_forall_exists_sub_residue_mem_nonunits_twoChartIntegralModel_x1x0
      p M hM hpM L ζ hζ K₁ hK₁ A hAp hζA j hj ϖ hϖ W₀ hW₀ hSW₀ y hyϖ hy𝔓 hy₀

  have hin : ∀ g ∈ 𝔶.inertia G, g • P = P ∧ ∀ e : ↥P, g • (e : ResidueField ↥W₀) - e ∈ P.nonunits := by
    intro g hg
    refine ValuationSubring.smul_eq_and_forall_smul_sub_mem_nonunits_of_mem_inertia ρ hρ 𝔶 P
      (fun s => by rw [hρapply]; exact hP s) (fun s => by rw [hρapply, h𝔶]; exact hPy s)
      (fun P' h1 h2 => huniq P' (fun s => by rw [← hρapply]; exact h1 s)
        (fun s => by rw [← hρapply, ← h𝔶]; exact h2 s))
      (fun e => by obtain ⟨s, hs⟩ := hres e; exact ⟨s, by rw [hρapply]; exact hs⟩) g hg

  haveI : FaithfulSMul G (ResidueField ↥W₀) :=
    ⟨fun {g₁ g₂} h => hΦinj (AlgEquiv.ext fun e => by simpa [hsmulF] using h e)⟩

  haveI : Finite (ResidueField A) := by
    have hsurj := IsCyclotomicExtension.Rat.surjective_algebraMap_int_residueField_of_isDiscreteValuationRing p L A hAp
    have h0 : ((p : ℕ) : ResidueField A) = 0 := by
      rw [← map_natCast (residue A), IsLocalRing.residue_eq_zero_iff]; exact hAp
    haveI : CharP (ResidueField A) p := (CharP.charP_iff_prime_eq_zero (Fact.out : p.Prime)).2 h0
    refine Finite.of_surjective (ZMod.castHom (dvd_refl p) (ResidueField A)) (fun r => ?_)
    obtain ⟨n, rfl⟩ := hsurj r
    exact ⟨(n : ZMod p), by simp⟩
  haveI : CharP (ResidueField A) p := by
    have h0 : ((p : ℕ) : ResidueField A) = 0 := by
      rw [← map_natCast (residue A), IsLocalRing.residue_eq_zero_iff]; exact hAp
    exact (CharP.charP_iff_prime_eq_zero (Fact.out : p.Prime)).2 h0

  have hGκ : ∀ (g : G) (a : ResidueField A), g • algebraMap (ResidueField A) (ResidueField ↥W₀) a =
      algebraMap (ResidueField A) (ResidueField ↥W₀) a := fun g a => by
    rw [hsmulF]; exact (Φ g).commutes a
  have hGJ : ∀ g : G, g • ρ (jChartFin A (↥K₁) j) = ρ (jChartFin A (↥K₁) j) := by
    intro g
    rw [hρ]
    congr 1
    apply Subtype.ext
    rw [hGA]
    have hjK₂ : (((jChartFin A (↥K₁) j : ↥(chartAlgFin A (↥K₁) j)) : ↥K₁) : LaurentSeries L) ∈ K₂ := by
      have : (((jChartFin A (↥K₁) j : ↥(chartAlgFin A (↥K₁) j)) : ↥K₁) : LaurentSeries L) = (j₂ : LaurentSeries L) := by
        rw [hj₂, ← hj]; rfl
      rw [this]; exact j₂.2
    exact hGfixK g _ hjK₂

  have hPtop : P ≠ ⊤ := by
    obtain ⟨s, hs, hsu⟩ := hy₀
    intro htop
    have h1 : ρ s ∈ P.nonunits := by rw [hρapply]; exact (hPy s).2 (h𝔶 ▸ hs)
    have h2 : ρ s ≠ 0 := by
      rw [hρapply, Ne, IsLocalRing.residue_eq_zero_iff]
      intro hmax
      exact hsu (ValuationSubring.coe_mem_nonunits_iff.2 hmax)
    rw [htop] at h1
    obtain ⟨hmem, hmax⟩ := (ValuationSubring.mem_nonunits_iff_exists_mem_maximalIdeal).1 h1
    refine (IsLocalRing.mem_maximalIdeal _).1 hmax ?_
    refine isUnit_iff_exists_inv.2 ⟨⟨(ρ s)⁻¹, ValuationSubring.mem_top _⟩, Subtype.ext ?_⟩
    simp [mul_inv_cancel₀ h2]
  have hb := ModularCurve.natCard_smul_valuationSubring_eq_and_forall_sub_mem_nonunits_le_three_of_ringEquiv_x1FunctionFieldC
    p hp5 M hM hpM (ResidueField A) (ResidueField ↥W₀) θ
    (fun a => by obtain ⟨a, rfl⟩ := IsLocalRing.residue_surjective a; rw [halg]; exact hθconst a)
    (ρ (jChartFin A (↥K₁) j)) hJq G hGκ hGJ P
    (fun a => by
      obtain ⟨a, rfl⟩ := IsLocalRing.residue_surjective a
      rw [halg]
      have := hP (algebraMap A ↥(chartAlgFin A (↥K₁) j) a)
      convert this using 2 <;> first | (with_reducible_and_instances rfl) | rfl | skip)
    hPtop hPIR (hP _)
  haveI : Finite {g : G // g • P = P ∧ ∀ e : ↥P, g • (e : ResidueField ↥W₀) - e ∈ P.nonunits} :=
    Subtype.finite
  calc Nat.card ↥(𝔶.inertia G)
      ≤ Nat.card {g : G // g • P = P ∧ ∀ e : ↥P, g • (e : ResidueField ↥W₀) - e ∈ P.nonunits} :=
        Nat.card_le_card_of_injective (fun g => ⟨g.1, hin g.1 g.2⟩)
          (fun a b h => Subtype.ext (congrArg (fun x => x.1) h))
    _ ≤ 3 := hb

end
end S_ModularCurve_XOneGammaZeroP_card_inertia_le_three_of_mem_ssJSet_twoChartIntegralModel_x1x0_gamma0_of_five_le
end P2MW
export P2MW.S_ModularCurve_XOneGammaZeroP_card_inertia_le_three_of_mem_ssJSet_twoChartIntegralModel_x1x0_gamma0_of_five_le (solution)
