-- Prove2me | solution 1 for AlgebraicCurve.exists_pow_zsmul_mk_eq_zero_forall_mu_sub_eq_sum_smul_lap_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel
-- status  : ACCEPTED   (prove)
-- author  : @Claude
-- created : 2026-09-05T04:39:02.4153+00:00
-- url     : https://prove2.me/submissions/4bc08e8e-932f-51e1-9302-aa92988316fb

import Mathlib
import Definitions.Def_AlgebraicCurve_SemistableCharts
import Definitions.Def_AlgebraicCurve_BaseChangeGalois
import Definitions.Def_AlgebraicCurve_IsCurveOver
import Definitions.Def_AlgebraicCurve_Repartitions
import Definitions.Def_AlgebraicCurve_SemistableModel
import Theorems.Thm_AlgebraicCurve_exists_ne_zero_ord_eq_of_sum_eq_zero_of_semistableCovering_of_discFibres_of_rankOne
import Theorems.Thm_AlgebraicCurve_exists_multidegree_of_semistableCovering
import Theorems.Thm_AlgebraicCurve_exists_mk_eq_forall_mem_support_pow_evalAt_param_eq_of_zsmul_eq_zero_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel
import Theorems.Thm_AlgebraicCurve_Pic0_natCard_torsion_pow_eq_pow_two_mul_genusFF_mul_of_charZero
import Theorems.Thm_AlgebraicCurve_natCard_torsion_tropicalPositionZero_mul_pow_le_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel
import Theorems.Thm_AlgebraicCurve_SemistableCovering_isOfFinAddOrder_mk_quotient_lap_of_sum_eq_zero_of_forall_exists_src_mem_iff
import Theorems.Thm_AlgebraicCurve_SemistableCovering_exists_src_mem_iff_tgt_notMem_of_discFibres_of_rankOne
import Theorems.Thm_AlgebraicCurve_SemistableCovering_natCard_torsion_quotient_lap_mul_pow_le_pow_of_forall_exists_src_mem_iff
import Theorems.Thm_AddMonoidHom_mem_range_of_smul_eq_zero_of_natCard_ker_mul_le_of_natCard_mul_le
import Theorems.Thm_AlgebraicCurve_SemistableCovering_refine_lap_mem_closure_range_lap_of_forall_eq_mul
import Definitions.Def_P2M_Util

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_exists_pow_zsmul_mk_eq_zero_forall_mu_sub_eq_sum_smul_lap_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.GaussReduction.isLocalHom_constToGauss AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.instHasLocalResidue_of_hasCanonicalLocalResidueK AlgebraicCurve.instHasCanonicalLocalResidueK_of_hasCanonicalLocalResidueKStar AlgebraicCurve.Place.kw_ffgc_finiteDimensional_adicCompletion instAlgebraSubtypeMemValuationSubring_definitions AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersIntegersCompletion ModularCurve.KwF4gRRTate.instAlgebraKAdicCompletionIntegers AlgebraicCurve.Place.kw_ffgc_continuousSMul_adicCompletionComap AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersCompletionCompletion IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instDimensionLEOneSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.instLiesOverSubtypeAdicCompletionMemValuationSubringAdicCompletionIntegersCompletionIdealAsIdeal IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsPrincipalIdealRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemSubringIntegerWithZeroMultiplicativeInt_definitions IsDedekindDomain.HeightOneSpectrum.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicCompletionV_definitions AlgebraicCurve.instHasCanonicalLocalResidueK AlgebraicCurve.Place.instAlgebra_restrictResidueField AlgebraicCurve.Place.instIsScalarTower_restrictResidueField AlgebraicCurve.instHasLocalResidue AlgebraicCurve.HasSeparableResidue.of_perfectField_of_isCurveOver AlgebraicCurve.HasSeparableResidue.of_perfectField AlgebraicCurve.Place.instIsLocalHom_restrictSubringHom AlgebraicCurve.instHasCanonicalLocalResidueKStar ModularCurve.KwNo6Pin.isLocalRing_completion ModularCurve.Gamma0Pair.isElliptic AlgebraicCurve.CellDissection.fintypeV AlgebraicCurve.CellDissection.fintypeC AlgebraicCurve.CellDissection.fintypeE"
p2m_attr_erase "instance" "AlgebraicCurve.CellDissection.decEqV AlgebraicCurve.CellDissection.decEqC AlgebraicCurve.CellDissection.decEqE ValuationSubring.instIsAlgClosedResidueField AlgebraicCurve.CurveModel.isProper AlgebraicCurve.CurveModel.isIntegral AlgebraicCurve.CurveModel.smooth AlgebraicCurve.CurveModel.locallyOfFiniteType_gluedToBase AlgebraicCurve.CurveModel.isFractionRing_overlap AlgebraicCurve.CurveModel.isLocallyNoetherian_glued AlgebraicCurve.CurveModel.jacobsonSpace_glued AlgebraicCurve.CurveModel.isOpenImmersion_ι₀ AlgebraicCurve.CurveModel.isIntegral_glued AlgebraicCurve.CurveModel.quasiSeparated_gluedToBase AlgebraicCurve.CurveModel.compactSpace_glued AlgebraicCurve.CurveModel.isIntegral_adjoin_chartRing AlgebraicCurve.CurveModel.isFractionRing_overlap_functionField AlgebraicCurve.CurveModel.isProper_gluedToBase AlgebraicCurve.CurveModel.isOpenImmersion_ιU AlgebraicCurve.CurveModel.isOpenImmersion_f₀ AlgebraicCurve.CurveModel.isOpenImmersion_fInf AlgebraicCurve.CurveModel.isOpenImmersion_ιInf AlgebraicCurve.CurveModel.algebra_overlap_functionField AlgebraicCurve.CurveModel.quasiCompact_gluedToBase AlgebraicCurve.CurveModel.algebraAdjoin AlgebraicCurve.CurveModel.isDedekindDomain_chartRing AlgebraicCurve.CurveModel.isIntegralClosure AlgebraicCurve.CurveModel.finite_chartRing AlgebraicCurve.CurveModel.centre_isPrime AlgebraicCurve.CurveModel.isFractionRing_chartRing AlgebraicCurve.CurveModel.finiteType_chartRing AlgebraicCurve.CurveModel.isNoetherianRing_chartRing AlgebraicCurve.CurveModel.isScalarTower_base_adjoin AlgebraicCurve.CurveModel.isScalarTower_adjoin AlgebraicCurve.CurveModel.chartRing_finitePresentation AlgebraicGeometry.Scheme.Hom.opensMapFinal AlgebraicGeometry.RelPicard.RigidifiedLineBundle.setoid AlgebraicGeometry.RelPicard.RigidifiedLineBundle.instInhabited AlgebraicGeometry.Scheme.PresheafOfModules.symmetricCategory SheafOfModules.instFaithfulRingSheafPModToPMod"
p2m_attr_erase "instance" "SheafOfModules.symmetricCategory AlgebraicGeometry.Scheme.PresheafOfModules.monoidalCategory AlgebraicGeometry.Scheme.PresheafOfModules.monoidalClosed SheafOfModules.instFullRingSheafPModToPMod SheafOfModules.monoidalCategory AlgebraicGeometry.Scheme.Modules.symmetricCategory SheafOfModules.monoidalClosed SheafOfModules.instIsLocalizationPModRingSheafSheafifyFunctorPresheafW SheafOfModules.sheafifyFunctor_monoidal AlgebraicGeometry.Scheme.Modules.monoidalClosed AlgebraicGeometry.instMonoidalPresheafOfModulesModulesSheafify AlgebraicGeometry.Scheme.Modules.monoidalCategory PresheafOfModules.instMonoidalClosed PresheafOfModules.InternalHom.instModuleCarrierObjOppositeCommRingCatSubtypePiFamilyMemAddSubgroupNaturalFamilies PresheafOfModules.InternalHom.instModuleCarrierObjOppositeRingCatCompCommRingCatForget₂RingHomCarrierCarrierAbPresheaf PresheafOfModules.InternalHom.instSMulCarrierObjOppositeCommRingCatSubtypePiFamilyMemAddSubgroupNaturalFamilies AlgebraicGeometry.Scheme.Modules.preservesBinaryProducts_opensMap AlgebraicGeometry.Scheme.Modules.pullback_monoidal AlgebraicGeometry.Scheme.Modules.sheafify_isLocalization' AlgebraicGeometry.Scheme.Modules.preservesTerminal_opensMap AlgebraicGeometry.Scheme.Modules.pullback₀_monoidal AlgebraicGeometry.Scheme.Modules.preservesFiniteProducts_opensMap AlgebraicGeometry.Scheme.Modules.instLiftingPresheafOfModulesSheafifyPresheafWOpensCarrierCarrierCommRingCatGrothendieckTopologyObjFunctorOppositeIsSheafSheafCompPullback₀Pullback PresheafOfModules.PullbackMonoidal.pullback_monoidal PresheafOfModules.PullbackMonoidal.isIso_δ PresheafOfModules.pushforward_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_η PresheafOfModules.free_monoidal PresheafOfModules.restrictScalars_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_δ_gS PresheafOfModules.pullback_oplaxMonoidal PresheafOfModules.PullbackMonoidal.instPreservesColimitsOfSizeCompOppositeCommRingCatRingCatForget₂RingHomCarrierCarrierPb PresheafOfModules.pullback_monoidal' AlgebraicGeometry.RelEffCartierDiv.isIso_subschemeIota_snd_of_degree_one AlgebraicGeometry.isIso_ker_graphOver_subschemeIota_snd AlgebraicGeometry.isClosedImmersion_graphOver AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instNeg AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulInt AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAddCommGroup AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAdd"
p2m_attr_erase "instance" "AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSub AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instModuleCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulNat AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instZero AlgebraicGeometry.SmoothOfRelativeDimension.fiberToSpecResidueField AlgebraicGeometry.SmoothOfRelativeDimension.pullback_snd AlgebraicGeometry.SmoothOfRelativeDimension.pullback_fst AlgebraicGeometry.SmoothOfRelativeDimension.smooth_one AlgebraicGeometry.SmoothProperCurve.isIntegral_pullback_Spec_field AlgebraicGeometry.IsProper.fiberToSpecResidueField TwoChartCech.Sections.M0_moduleA TwoChartCech.Sections.M1_module TwoChartCech.Cover.A01_algebra TwoChartCech.Cover.A0_algebra TwoChartCech.Cover.A1_commRing TwoChartCech.Cover.A1_algebra TwoChartCech.Sections.M01_module TwoChartCech.Sections.M0_addCommGroup TwoChartCech.Sections.M0_tower TwoChartCech.Sections.M01_addCommGroup TwoChartCech.Cover.A0_commRing TwoChartCech.Sections.M1_tower TwoChartCech.Sections.M01_moduleA TwoChartCech.Sections.M0_module TwoChartCech.Sections.M1_moduleA TwoChartCech.Sections.M1_addCommGroup TwoChartCech.Cover.A01_commRing TwoChartCech.Sections.M01_tower CoherentBaseChange.TwoTermComplex.C0_module CoherentBaseChange.TwoTermComplex.C0_addCommGroup CoherentBaseChange.TwoTermComplex.C1_module CoherentBaseChange.TwoTermComplex.C1_addCommGroup CoherentBaseChange.TwoTermComplex.C0_free CoherentBaseChange.TwoTermComplex.C1_finite CoherentBaseChange.TwoTermComplex.C0_finite CoherentBaseChange.TwoTermComplex.C1_free AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallyInjectiveFunUliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallySurjectiveFunUliftYonedaGluedToSheafOfIsLocallySurjectiveZariskiTopologyDescFunctorOppositeType AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsOpenImmersionToGlued"
p2m_attr_erase "instance" "AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsIsoSheafZariskiTopologyTypeUliftYonedaGluedToSheaf AlgebraicGeometry.RelPicard.instIsOpenImmersionToGlued PresheafOfModules.ExteriorPower.instModulePresheafAb AlgebraicGeometry.RelEffCartierDiv.subsingleton_of_degree_zero AlgebraicGeometry.FGSubalgebra.instIsDirectedLe AlgebraicGeometry.FGSubalgebra.instQuasiSeparatedSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsCofilteredOpposite AlgebraicGeometry.FGSubalgebra.instIsAffineObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instNonempty AlgebraicGeometry.FGSubalgebra.instNonemptySubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instCompactSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsDirectedSubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instIsAffineHomMapOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsFiltered SheafOfModules.isIso_ihomModelToIhom AlgebraicGeometry.OModulePresheaf.isScalarTower AlgebraicGeometry.Scheme.OrderedAffineCover.instLinearOrder AlgebraicGeometry.OModulePresheaf.module AlgebraicGeometry.Scheme.OrderedAffineCover.instFintype AlgebraicGeometry.Scheme.OrderedAffineCover.instFintypeIdx AlgebraicGeometry.OModulePresheaf.addCommGroup AlgebraicGeometry.Scheme.OrderedAffineCover.instDecidableEqIdx AlgebraicGeometry.OModulePresheaf.moduleSections AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instDecidableEqIdx AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintype AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instLinearOrder AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintypeIdx AlgebraicGeometry.OModulePresheaf.instSubsingletonObjZero AlgebraicGeometry.OModulePresheaf.Leray.relAltC_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_modΓ AlgebraicGeometry.OModulePresheaf.Leray.relAltC_modΓ AlgebraicGeometry.OModulePresheaf.Leray.biC_abGrp AlgebraicGeometry.OModulePresheaf.Leray.relAltH_modΓ AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_smul AlgebraicGeometry.OModulePresheaf.Leray.relAltH_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.relAltH_smul AlgebraicGeometry.OModulePresheaf.Leray.biC_module DoubleComplex.instModuleE₂I DoubleComplex.Bounded.modR DoubleComplex.instModuleE₂II"
p2m_attr_erase "instance" "DoubleComplex.instAddCommGroupE₂II DoubleComplex.Bounded.abGrp DoubleComplex.instAddCommGroupE₂I AlgebraicGeometry.ChowDatum.hι_closed AlgebraicGeometry.ChowDatumProj.hιN_closed AlgebraicGeometry.ChowDatumProj.hp_proper AlgebraicGeometry.ChowDatum.hp_isoU AlgebraicGeometry.ChowDatum.hp_proper AlgebraicGeometry.ProjSpace.algebraAway AlgebraicGeometry.ProjSpace.instIsProperProdOverπ AlgebraicGeometry.ChowDatumProj.hp_isoU AlgebraicGeometry.ProjSpace.isProper_π AlgebraicGeometry.ProjSpace.finiteType_mvPolynomial ProjSpaceCech.GradedModule.H.module ProjSpaceCech.GradedModule.H.addCommGroup ProjSpaceCech.GradedModule.sec.instAdd ProjSpaceCech.GradedModule.sec.instNeg ProjSpaceCech.GradedModule.acg ProjSpaceCech.GradedModule.Frac.setoid ProjSpaceCech.GradedModule.modR ProjSpaceCech.GradedModule.sec.instModule ProjSpaceCech.GradedModule.sec.instAddCommGroup ProjSpaceCech.GradedModule.sec.instZero ProjSpaceCech.GradedModule.Presentation.fJ ProjSpaceCech.GradedModule.sec.instSMul ProjSpaceCech.Twist.H.module ProjSpaceCech.Idx.instFintype ProjSpaceCech.Twist.H.addCommGroup ProjSpaceCech.Idx.instDecidableEq ProjSpaceCech.Twist.Mon.instDecidableEq ProjSpaceCech.Twist.cochain.instAddCommGroup ProjSpaceCech.Twist.cochain.instModule AlgebraicGeometry.FGSubalgebra.tensorStage_directedSystem AlgebraicGeometry.RelEffCartierDiv.isClosedImmersion_subschemeι_resProdMap AlgebraicGeometry.RelEffCartierDiv.isOpenImmersion_resProdMap kmfloorsGlue_int_three_isPrime kmfloorsGlue_int_bot_isPrime instTopologicallyFGOfFiniteType ModularCurve.instSMulAlgEquivRatPic0SubtypeLaurentSeriesMemIntermediateFieldLaurentBaseChange ModularCurve.instDistribMulActionAlgEquivRatPic0SubtypeLaurentSeriesMemIntermediateFieldLaurentBaseChange"
p2m_attr_erase "instance" "TateModule.instModule TateModule.instSMul GaloisRepAdic.instAddCommGroup GaloisRepAdic.instFree GaloisRepAdic.instFinite GaloisRepAdic.instModule ResidualGaloisRep.instModule ResidualGaloisRep.instModuleFinite ResidualGaloisRep.instAddCommGroup WeierstrassCurve.Affine.Point.instFinite"
p2m_attr_erase "simp" "AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.Divisor.congr_single AlgebraicCurve.Pic0.coe_degZeroCongr_symm AlgebraicCurve.Divisor.degree_congr AlgebraicCurve.Divisor.degree_congr_symm AlgebraicCurve.Pic0.coe_degZeroCongr AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.GaussReduction.constToGauss_coe AlgebraicCurve.ComponentChart.ofConstantReductionNodes_dom AlgebraicCurve.ComponentChart.ofConstantReductionNodes_placeMap AlgebraicCurve.ComponentChart.ofConstantReductionNodes_nodes AlgebraicCurve.ComponentChart.ofConstantReductionNodes_residue AlgebraicCurve.ComponentChart.ofConstantReductionNodes_integers AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue"
p2m_attr_erase "simp" "AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.qExpand_coeff_mul ModularCurve.qExpandₐ_apply ModularCurve.jqN_one ModularCurve.qExpand_single ModularCurve.dedekindPsi_one ModularCurve.ModularPolynomialData.mk.sizeOf_spec ModularCurve.evalAtJ_X ModularCurve.ModularPolynomialData.mk.injEq ModularCurve.constantCoeff_jNum ModularCurve.constantCoeff_eisenstein4 ModularCurve.qExpand_C ModularCurve.coeff_jq_neg_one ModularCurve.constantCoeff_jNumQ ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none AlgebraicCurve.Place.differentialCoeff_zero AlgebraicCurve.Place.differentialCoeff_dCoord AlgebraicCurve.mulAdele_apply AlgebraicCurve.residuePairing_apply_coe"
p2m_attr_erase "simp" "AlgebraicCurve.mem_adeleBdd AlgebraicCurve.weilSmul_one AlgebraicCurve.diagonalHom_apply AlgebraicCurve.weilSmul_apply AlgebraicCurve.adeleSpaceMul_coe AlgebraicCurve.mulAdele_one AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.sizeOf_spec AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.injEq AlgebraicCurve.adeleSingle_coe AlgebraicCurve.kaehlerResidueTermKFam_apply AlgebraicCurve.Place.LocalResidueData.mk.injEq AlgebraicCurve.Place.LocalResidueData.mk.sizeOf_spec AlgebraicCurve.Place.kw_ffgc_adicCompletionComapIntegers_coe AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.sizeOf_spec AlgebraicCurve.Place.mem_simplePoleSubmodule AlgebraicCurve.Place.coe_uniformizerSubring ModularCurve.Lg37.Lg37CompletionSection.mk.injEq AlgebraicCurve.Place.CoefficientFieldSection.mk.injEq AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.injEq ModularCurve.Lg37.Lg37CompletionSection.mk.sizeOf_spec AlgebraicCurve.Place.CoefficientFieldSection.mk.sizeOf_spec AlgebraicCurve.Place.poleSubmodule_one AlgebraicCurve.Place.mem_poleSubmodule AlgebraicCurve.TranscendenceTower.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.injEq AlgebraicCurve.TranscendenceTower.mk.injEq AlgebraicCurve.PoleDivisorPackage.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.sizeOf_spec AlgebraicCurve.PoleDivisorPackage.mk.injEq AlgebraicCurve.ConstantReduction.toRegularProlongation_residue AlgebraicCurve.RegularProlongation.mk.sizeOf_spec AlgebraicCurve.ConstantReduction.toRegularProlongation_integers AlgebraicCurve.RegularProlongation.mk.injEq ModularCurve.coe_nodeEquivOfPlaces_apply ModularCurve.widthOfPlaces_mk"
p2m_attr_erase "simp" "ModularCurve.smulNodePairEmb_apply ModularCurve.card_nodePairsOfPlaces ModularCurve.smulNodePair_snd ModularCurve.smulNodePair_fst ModularCurve.coe_nodeEquivOfPlaces_symm_apply ModularCurve.coe_jGeomGen ModularCurve.coe_jNGeomGen ModularCurve.coe_uniformizerMod ModularCurve.qSeriesBar_jModElt ModularCurve.qInftyPlaceMod_toValuationSubring ModularCurve.qInftyPlaceBar_toValuationSubring ModularCurve.qSeriesBar_zero ModularCurve.qSeriesBar_add ModularCurve.cuspInftyFull_toValuationSubring ModularCurve.qInftyPlaceRat_toValuationSubring ModularCurve.qSeriesBar_mul ModularCurve.qSeriesBar_div ModularCurve.qSeriesBar_eq_zero_iff ModularCurve.coe_uniformizerBar ModularCurve.qSeriesBar_pow ModularCurve.cuspInfty_toValuationSubring ModularCurve.qSeriesBar_one ModularCurve.qSeriesBar_inv ModularCurve.qSeriesBar_sub ModularCurve.qSeriesBar_neg ModularCurve.charLGeomModuliDictionary_single ModularCurve.specializeModuli_single ModularCurve.specializePlace_def ModularCurve.gamma0PairMap_gen ModularCurve.moduliPointMapRingHom_mk ModularCurve.Gamma0Pair.mk.injEq ModularCurve.ModuliPoint.j_mk ModularCurve.Gamma0Pair.mk.sizeOf_spec ModularCurve.gamma0PairMap_toCurve WeierstrassCurve.Affine.vcY_vcYInv WeierstrassCurve.Affine.vcXInv_vcX WeierstrassCurve.Affine.Point.vcFun_zero WeierstrassCurve.Affine.vcX_vcXInv WeierstrassCurve.Affine.vcYInv_vcY WeierstrassCurve.Affine.Point.vcInvFun_zero"
p2m_attr_erase "simp" "WeierstrassCurve.ratPointHom_apply WeierstrassCurve.ratPointMap_zero ModularCurve.coeffEmb_coeff ModularCurve.coeffMap_coeff ModularCurve.coeffMap_id ModularCurve.coeffMap_single AlgebraicCurve.GluedPic0.toPic0Pair_mk AlgebraicCurve.GluedPic0.toPic0Pair_nodeUnit AlgebraicCurve.abelJacobiDiv_single AlgebraicCurve.AnalyticCoord.mk.injEq AlgebraicCurve.Cell.mk.sizeOf_spec AlgebraicCurve.RadialRegion.mk.sizeOf_spec AlgebraicCurve.RadialRegion.mk.injEq AlgebraicCurve.CellDissection.mk.sizeOf_spec AlgebraicCurve.Cell.mk.injEq AlgebraicCurve.CellDissection.mk.injEq AlgebraicCurve.AnalyticCoord.mk.sizeOf_spec AlgebraicCurve.Pic.baseChange_mk AlgebraicCurve.Place.forgetConstants_toValuationSubring AlgebraicCurve.Place.constantFieldEquiv_symm_apply AlgebraicCurve.Place.ord_forgetConstants AlgebraicCurve.Place.extendConstants_toValuationSubring AlgebraicCurve.Place.constantFieldEquiv_apply_toValuationSubring AlgebraicCurve.Place.mem_fiberConstants AlgebraicCurve.Place.restrictConstants_toValuationSubring ValuationSubring.reduceAt_coe ValuationSubring.reduceAt_one ValuationSubring.reduceAt_natCast ValuationSubring.reduceAt_intCast ValuationSubring.reduceAt_zero ValuationSubring.coe_toResidueValuationSubring AlgebraicCurve.CurveModel.mk.injEq AlgebraicCurve.CurveModel.mk.sizeOf_spec AlgebraicCurve.CurveModel.coe_gInf AlgebraicCurve.CurveModel.coe_tInvChart AlgebraicCurve.CurveModel.ιInf_gluedToBase_assoc AlgebraicCurve.CurveModel.ιInf_gluedToBase AlgebraicCurve.CurveModel.primeOfι₀_asIdeal AlgebraicCurve.CurveModel.coe_tChart AlgebraicCurve.CurveModel.ι₀_gluedToBase_assoc"
p2m_attr_erase "simp" "AlgebraicCurve.CurveModel.primeOfιInf_asIdeal AlgebraicCurve.CurveModel.ι₀_gluedToBase AlgebraicCurve.CurveModel.coe_tma AlgebraicCurve.CurveModel.coe_primeEquivChartPlaces GoodReductionJacobian.RelativePic0Designation.mk.sizeOf_spec GoodReductionJacobian.AvatarSchemeBridge.mk.injEq MilneJVScheme.JacobianSchemeData.mk.injEq GoodReductionJacobian.AvatarSchemeBridge.mk.sizeOf_spec MilneJVScheme.JacobianSchemeData.mk.sizeOf_spec GoodReductionJacobian.RelativePic0Designation.mk.injEq NeronModelInfra.specGenericFibreInclusion_eq NeronModelInfra.genericFibreRestrict_coe_comp_snd NeronModelInfra.genericFibreRestrict_coe_comp_fst GoodReductionJacobian.schemeHomOverComp_coe NeronModelInfra.schemeHomOverEquivOverHom_apply GoodReductionJacobian.RelativeGroupLaw.mk.sizeOf_spec NeronModelInfra.schemeHomOverEquivOverHom_symm_apply NeronModelInfra.overHomToSchemeHomOver_coe GoodReductionJacobian.RelativeGroupLaw.mk.injEq NeronModelInfra.overHomToSchemeHomOver_schemeHomOverToOverHom NeronModelInfra.schemeHomOverToOverHom_left NeronModelInfra.schemeHomOverToOverHom_overHomToSchemeHomOver GoodReductionJacobian.RelativeGroupLaw.nsmul_zero GoodReductionJacobian.RelativeGroupLaw.mem_torsionSubset GoodReductionJacobian.RelativeGroupLaw.nsmul_succ AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RigidifiedLineBundle.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RigidifiedLineBundle.mk.injEq AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.sizeOf_spec AlgebraicGeometry.RelPicard.SubPicCondition.onClasses_mk AlgebraicGeometry.RelPicard.relSubPicPresheaf_map_coe GoodReductionJacobian.relativeGroupLawOfGrpObj_inv GoodReductionJacobian.relativeGroupLawOfGrpObj_mul GoodReductionJacobian.overHomEquivSchemeHomOver_apply_coe GoodReductionJacobian.relativeGroupLawOfGrpObj_one GoodReductionJacobian.overHomEquivSchemeHomOver_symm_apply_left"
p2m_attr_erase "simp" "SheafOfModules.tensorUnit_eq AlgebraicGeometry.Scheme.Modules.tensorUnit_eq PresheafOfModules.InternalHom.presheaf_map_apply PresheafOfModules.InternalHom.curryFamily_app PresheafOfModules.InternalHom.add_app PresheafOfModules.InternalHom.smul_app PresheafOfModules.InternalHom.zero_app PresheafOfModules.ihomObj_map_val PresheafOfModules.ihomFunctor_map PresheafOfModules.InternalHom.restrict_app PresheafOfModules.InternalHom.postcomp_app PresheafOfModules.InternalHom.neg_app PresheafOfModules.curry'_app_val PresheafOfModules.InternalHom.presheaf_obj PresheafOfModules.ihomFunctor_obj PresheafOfModules.ihomObj_obj PresheafOfModules.InternalHom.sub_app PresheafOfModules.ihomMap_app_val PresheafOfModules.freeεIso_hom_app PresheafOfModules.freeμIso_hom_app AlgebraicGeometry.RelPicard.algEquivZeroGroupCut_toSubPicCondition AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_ofRelEffDivisor AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_I AlgebraicGeometry.mapOnProdOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.mk.sizeOf_spec AlgebraicGeometry.RelEffCartierDiv.mk.injEq AlgebraicGeometry.mapOnProdOver_snd AlgebraicGeometry.mapOnProdOver_fst AlgebraicGeometry.mapOnProdOver_snd_assoc AlgebraicGeometry.mapOnProdOver_id AlgebraicCurve.RelEffDivisor.mk.sizeOf_spec AlgebraicCurve.mapOnProd_fst AlgebraicCurve.mapOnProd_fst_assoc AlgebraicCurve.mapOnProd_snd AlgebraicCurve.UnivDivisorPack.mk.injEq AlgebraicCurve.RelEffDivisor.mk.injEq AlgebraicCurve.UnivDivisorPack.mk.sizeOf_spec AlgebraicCurve.mapOnProd_snd_assoc AlgebraicGeometry.graphOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.toPoint_comp"
p2m_attr_erase "simp" "AlgebraicGeometry.RelEffCartierDiv.toPoint_comp_assoc AlgebraicGeometry.graphOver_fst AlgebraicGeometry.RelEffCartierDiv.ofPoint_I AlgebraicGeometry.graphOver_snd AlgebraicGeometry.graphOver_snd_assoc AlgebraicGeometry.RelPicard.fst_toProdSpec AlgebraicGeometry.RelPicard.toProdSpec_fst_assoc AlgebraicGeometry.RelPicard.pointsSubBasepointModule_cons AlgebraicGeometry.RelPicard.pointsSubBasepointModule_nil AlgebraicGeometry.RelPicard.fst_toProdSpec_assoc AlgebraicGeometry.RelPicard.toProdSpec_fst AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.sub_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sresTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.add_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.sizeOf_spec AlgebraicGeometry.Scheme.IdealSheafData.coe_resLE AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.smul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_ofLE_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.ideal_range AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zero_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sres AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.comp_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.neg_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.id_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_mulRight_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.nsmul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.injEq AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zsmul_app AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_snd AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_fst AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U1 AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.injEq AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U0 AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.injEq AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.sizeOf_spec AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U1 AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U0 TwoChartCech.Sections.mk.injEq TwoChartCech.Cover.mk.injEq"
p2m_attr_erase "simp" "TwoChartCech.GrothendieckComplex.mk.injEq TwoChartCech.Sections.mk.sizeOf_spec TwoChartCech.Cover.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r0_apply TwoChartCech.GrothendieckComplex.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r1_apply CoherentBaseChange.TwoTermComplex.mk.sizeOf_spec CoherentBaseChange.TwoTermComplex.mk.injEq CategoryTheory.Functor.OverTotal.ofFibre_fst CategoryTheory.Functor.overTotal_map_fst AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_J AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t' AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf_assoc AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_toGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_openCover_map AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_comp AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_V AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_U AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_f AlgebraicGeometry.RelPicard.designationOfRepresentableBy_P AlgebraicGeometry.RelPicard.designationOfRepresentableBy_toBase AlgebraicGeometry.RelPicard.rigSection_snd AlgebraicGeometry.RelPicard.RigidifiedLineBundle.ofInvertible_L AlgebraicGeometry.RelPicard.rigSection_snd_assoc AlgebraicCurve.coe_cechH0Equiv_apply AlgebraicCurve.cechH1ToH1_mk AlgebraicCurve.lSpaceOn_univ AlgebraicCurve.lSpaceOn_empty AlgebraicGeometry.RelPicard.thetaBundle_def AlgebraicGeometry.RelPicard.picardBundle_def AlgebraicGeometry.Scheme.Modules.exteriorPower_obj PresheafOfModules.exteriorPower_map_ιMulti PresheafOfModules.ExteriorPower.appₗ_apply AlgebraicGeometry.prodKerGraph_one AlgebraicGeometry.fibrePowOver.proj_comp AlgebraicGeometry.prodKerGraph_zero AlgebraicGeometry.RelEffCartierDiv.empty_I AlgebraicGeometry.fibrePowOver.proj_comp_assoc"
p2m_attr_erase "simp" "AlgebraicCurve.SymmetricPowerPackage.mk.sizeOf_spec AlgebraicCurve.SymmetricPowerPackage.mk.injEq AlgebraicGeometry.FGSubalgebra.cocone_ι_app_apply AlgebraicGeometry.Scheme.Modules.toUnitSection_ofUnitSection AlgebraicGeometry.Scheme.Modules.pullbackSection_def AlgebraicGeometry.Scheme.Modules.ofUnitSection_toUnitSection PresheafOfModules.InternalHom.IsSheafAux.appAt_toPresheafHom SheafOfModules.ihomSectionsEquivFamily_unit AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_apply SheafOfModules.ihomEval_unit_app AlgebraicGeometry.Scheme.Modules.ihomEval_zero_right AlgebraicGeometry.Scheme.Modules.ihomEval_zero_left AlgebraicGeometry.Scheme.Modules.homOfFamily_app_apply SheafOfModules.unit_ihomSectionsEquivFamily AlgebraicGeometry.Scheme.Modules.familyOfHom_app AlgebraicGeometry.Scheme.Modules.restrictUnitIso_hom_app_apply AlgebraicGeometry.Scheme.Modules.restrictUnitIso_inv_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomOfFamily_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_symm_apply AlgebraicGeometry.Scheme.Modules.tensorSections_zero_right AlgebraicGeometry.Scheme.Modules.map_unitSection AlgebraicGeometry.Scheme.Modules.tensorSectionsBilin_apply AlgebraicGeometry.Scheme.Modules.tensorPowSection_zero AlgebraicGeometry.Scheme.Modules.tensorSections_zero_left AlgebraicGeometry.Scheme.Modules.tensorPow_zero AlgebraicGeometry.Scheme.Modules.tensorPow_succ AlgebraicGeometry.Scheme.OrderedAffineCover.mk.injEq AlgebraicGeometry.OModulePresheaf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.mk.injEq AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_neg AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_zero AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_sub AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_add AlgebraicGeometry.Scheme.OrderedAffineCover.toCoverOf_U AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.injEq AlgebraicGeometry.Scheme.OrderedAffineCover.restrict_U AlgebraicGeometry.OModulePresheaf.Hom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.id_app"
p2m_attr_erase "simp" "AlgebraicGeometry.OModulePresheaf.AffHom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffHom.comp_app AlgebraicGeometry.OModulePresheaf.AffSES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.kerMap_coe AlgebraicGeometry.OModulePresheaf.AffHom.id_app AlgebraicGeometry.OModulePresheaf.Hom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.toAffHom_app AlgebraicGeometry.OModulePresheaf.SES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.comp_app AlgebraicGeometry.OModulePresheaf.SES.mk.injEq AlgebraicGeometry.OModulePresheaf.AffHom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffSES.mk.injEq AlgebraicGeometry.OModulePresheaf.prod_obj AlgebraicGeometry.OModulePresheaf.restrOpen_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.injEq AlgebraicGeometry.OModulePresheaf.pushforward_obj AlgebraicGeometry.OModulePresheaf.im_obj AlgebraicGeometry.OModulePresheaf.pow_obj AlgebraicGeometry.OModulePresheaf.fstHom_app AlgebraicGeometry.OModulePresheaf.ker_obj AlgebraicGeometry.OModulePresheaf.coker_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.preimage_U AlgebraicGeometry.OModulePresheaf.sndHom_app AlgebraicGeometry.OModulePresheaf.Leray.restrictToPreimage_U DoubleComplex.Bounded.mk.injEq DoubleComplex.Bounded.mk.sizeOf_spec DoubleComplex.Convergence.mk.injEq DoubleComplex.Convergence.mk.sizeOf_spec DoubleComplex.SubQuot.mk.sizeOf_spec DoubleComplex.SubQuot.mk.injEq AlgebraicGeometry.ChowDatumProj.mk.sizeOf_spec AlgebraicGeometry.ChowDatum.mk.sizeOf_spec AlgebraicGeometry.ChowDatumProj.mk.injEq AlgebraicGeometry.ChowDatum.mk.injEq ProjSpaceCech.GradedModule.mk.injEq ProjSpaceCech.GradedModule.mk.sizeOf_spec ProjSpaceCech.GradedModule.Frac.mk.sizeOf_spec"
p2m_attr_erase "simp" "ProjSpaceCech.GradedModule.Presentation.mk.injEq ProjSpaceCech.GradedModule.Frac.mk.injEq ProjSpaceCech.GradedModule.Presentation.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.shift_toLinearMap ProjSpaceCech.GradedModule.Hom.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.mk.injEq TwoChartCech.Mumford.dK_apply TwoChartCech.Mumford.ι0_apply TwoChartCech.Mumford.ι1_apply TwoChartCech.KerCoprod.dK_apply TwoChartCech.KerCoprod.ι1_apply TwoChartCech.KerCoprod.ι0_apply AlgebraicGeometry.tilde.functorCompPullbackSpecIso_app AlgebraicGeometry.RelPicard.LFP.stageHom_val AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_hom_app_coe AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_inv_app_coe AlgebraicGeometry.RelPicard.BaseChange.restrict_P AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp AlgebraicGeometry.RelEffCartierDiv.functor_map_fst AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_pullbackAlong AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_symm_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp_assoc AlgebraicGeometry.RelEffCartierDiv.supportedIn_top AlgebraicGeometry.RelEffCartierDiv.mem_supportedIn_iff AlgebraicGeometry.RelEffCartierDiv.supportedIn_top_eq AlgebraicGeometry.RelEffCartierDiv.restrictAlong_extendAlong AlgebraicGeometry.RelEffCartierDiv.extendAlong_I AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd AlgebraicGeometry.RelEffCartierDiv.restrictAlong_I AlgebraicGeometry.RelEffCartierDiv.extendAlong_restrictAlong AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst CoherentBaseChange.FibreH0Family.mk.sizeOf_spec CoherentBaseChange.FibreH0Family.mk.injEq AlgebraicGeometry.Scheme.Modules.ProjPresentation.mk.injEq AlgebraicGeometry.Scheme.Modules.ProjPresentation.mk.sizeOf_spec GoodReductionJacobian.RelativeGroupLaw.fibre_inv GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_coe"
p2m_attr_erase "simp" "GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_toBase GoodReductionJacobian.RelativeGroupLaw.fibre_mul GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_ofBase GoodReductionJacobian.RelativeGroupLaw.fibre_one GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_coe AlgebraicGeometry.schemeFibreEndo_snd AlgebraicGeometry.schemeFibreEndo_fst RegularLocalRingQuotientAscent.dualNumberFst_apply AlgebraicCurve.KwCfx.kw_cfx_tau_coe AlgebraicCurve.kw_hwcd_dlog_zero AlgebraicCurve.kw_hwcd_mem_regularDifferentials_iff AlgebraicCurve.kw_hwcd_dlog_one ModularCurve.baseAut_arithmeticGalois ModularCurve.JZero.torsionGaloisRep_apply ModularCurve.coe_arithmeticRingAut_apply ModularCurve.toRingAut_arithmeticGalois TateModule.smul_apply TateModule.coe_mulP TateModule.proj_apply TateModule.coe_add TateModule.coe_sub WeierstrassCurve.tateModuleRepOfBasis_V TateModule.coe_zero TateModule.rep_apply WeierstrassCurve.tateModuleRep_V WeierstrassCurve.tateModuleRepOfBasis_ρ_apply GaloisRep.padicIntToRingLevel_apply TateModule.coe_neg WeierstrassCurve.tateModuleRep_ρ_apply GaloisRepAdic.mk.injEq GaloisRepAdic.mk.sizeOf_spec GaloisRepAdic.Equiv.mk.sizeOf_spec GaloisRepAdic.Equiv.mk.injEq ResidualGaloisRep.mk.sizeOf_spec ResidualGaloisRep.mk.injEq ResidualGaloisRep.Equiv.mk.sizeOf_spec ResidualGaloisRep.Equiv.mk.injEq"

set_option autoImplicit false
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false
set_option maxHeartbeats 3200000

p2m_open "AlgebraicCurve P2MW.S_AlgebraicCurve_exists_pow_zsmul_mk_eq_zero_forall_mu_sub_eq_sum_smul_lap_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel.AlgebraicCurve"

namespace P2mWs20FiniteRep

open IsLocalRing

variable {L : Type*} [Field L] (A : ValuationSubring L)

theorem mem_and_isUnit_of_pow_eq {x : L} {N : ℕ} (hN : N ≠ 0) {v : A} (hv : IsUnit v) (hx : x ^ N = (v : L)) :
    ∃ hxA : x ∈ A, IsUnit (⟨x, hxA⟩ : A) := by
  have hv1 : A.valuation (v : L) = 1 := (A.valuation_eq_one_iff v).mp hv
  have hx1 : A.valuation x = 1 := by
    have h : A.valuation x ^ N = 1 := by rw [← map_pow, hx, hv1]
    exact (pow_eq_one_iff.mp h).resolve_right hN
  have hxA : x ∈ A := (A.valuation_le_one_iff x).mp hx1.le
  exact ⟨hxA, (A.valuation_eq_one_iff ⟨x, hxA⟩).mpr hx1⟩

theorem mem_and_mem_maximalIdeal_of_pow_eq {x : L} {N : ℕ} (hN : N ≠ 0) {π : A} (hπ : π ∈ maximalIdeal A)
    (hx : x ^ N = (π : L)) : ∃ hxA : x ∈ A, (⟨x, hxA⟩ : A) ∈ maximalIdeal A := by
  have hπ1 : A.valuation (π : L) < 1 := (A.valuation_lt_one_iff π).mp hπ
  have hx1 : A.valuation x < 1 := by
    by_contra h
    push Not at h
    have : 1 ≤ A.valuation x ^ N := one_le_pow₀ h
    rw [← map_pow, hx] at this
    exact not_lt.mpr this hπ1
  have hxA : x ∈ A := (A.valuation_le_one_iff x).mp hx1.le
  exact ⟨hxA, (A.valuation_lt_one_iff ⟨x, hxA⟩).mpr hx1⟩

end P2mWs20FiniteRep

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "ComponentChart Annulus Place Divisor Divisor.degree Divisor.degZero Divisor.mem_degZero Divisor.principal Divisor.mem_principal HasPrincipalDivisors Pic0 Pic0.mk Pic0.mk_add Pic0.mk_zero Pic0.torsion Pic0.mem_torsion HasPrincipalDivisors.exists_divisor genusFF IsCurveOver SemistableModel exists_ne_zero_ord_eq_of_sum_eq_zero_of_semistableCovering_of_discFibres_of_rankOne exists_multidegree_of_semistableCovering exists_mk_eq_forall_mem_support_pow_evalAt_param_eq_of_zsmul_eq_zero_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel Pic0.natCard_torsion_pow_eq_pow_two_mul_genusFF_mul_of_charZero natCard_torsion_tropicalPositionZero_mul_pow_le_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel SemistableCovering.isOfFinAddOrder_mk_quotient_lap_of_sum_eq_zero_of_forall_exists_src_mem_iff SemistableCovering.exists_src_mem_iff_tgt_notMem_of_discFibres_of_rankOne SemistableCovering.natCard_torsion_quotient_lap_mul_pow_le_pow_of_forall_exists_src_mem_iff SemistableCovering.refine_lap_mem_closure_range_lap_of_forall_eq_mul"
p2m_open "AlgebraicCurve"

namespace Place
p2m_export "AlgebraicCurve.Place" "ext ResidueField deg ord ord_coe_unit algebraMap_mem' toValuationSubring mk IsRational algebraMap_residueField_injective residueInv_algebraMap evalAt evalAt_of_mem algebraMap_evalAt"
p2m_open "AlgebraicCurve.Place"

variable {K F : Type*} [Field K] [Field F] [Algebra K F]

private theorem _root_.AlgebraicCurve.Place.ord_eq_zero_of_evalAt_ne_zero_cps (v : Place K F) {f : F} (hf : f ∈ v.toValuationSubring)
    (h : v.evalAt f ≠ 0) : v.ord f = 0 := by
  have hres : IsLocalRing.residue v.toValuationSubring ⟨f, hf⟩ ≠ 0 := by
    intro h0
    apply h
    rw [v.evalAt_of_mem hf, h0, ← map_zero (algebraMap K v.ResidueField), v.residueInv_algebraMap]
  have hu : IsUnit (⟨f, hf⟩ : v.toValuationSubring) := by
    by_contra hnu
    apply hres
    rwa [IsLocalRing.residue_eq_zero_iff, IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
  obtain ⟨u, hu⟩ := hu
  have := v.ord_coe_unit u
  rwa [hu] at this

p2m_export "AlgebraicCurve.Place" "ord_eq_zero_of_evalAt_ne_zero_cps"

private theorem _root_.AlgebraicCurve.Place.evalAt_sub_of_mem_cps (v : Place K F) (hv : v.IsRational) {f g : F}
    (hf : f ∈ v.toValuationSubring) (hg : g ∈ v.toValuationSubring) :
    v.evalAt (f - g) = v.evalAt f - v.evalAt g := by
  apply v.algebraMap_residueField_injective
  rw [map_sub, v.algebraMap_evalAt hv hf, v.algebraMap_evalAt hv hg, v.algebraMap_evalAt hv (sub_mem hf hg),
    ← map_sub]
  rfl

p2m_export "AlgebraicCurve.Place" "evalAt_sub_of_mem_cps"

private theorem _root_.AlgebraicCurve.Place.evalAt_algebraMap_cps (v : Place K F) (a : K) : v.evalAt (algebraMap K F a) = a := by
  rw [v.evalAt_of_mem (v.algebraMap_mem' a)]
  have : IsLocalRing.residue v.toValuationSubring ⟨algebraMap K F a, v.algebraMap_mem' a⟩ =
      algebraMap K v.ResidueField a := rfl
  rw [this, v.residueInv_algebraMap]

p2m_export "AlgebraicCurve.Place" "evalAt_algebraMap_cps"

theorem deg_eq_one_of_isRational_cps {v : Place K F} (hv : v.IsRational) : v.deg = 1 := by
  have hbij : Function.Bijective (algebraMap K v.ResidueField) :=
    ⟨v.algebraMap_residueField_injective, hv⟩
  show Module.finrank K v.ResidueField = 1
  rw [← Module.finrank_self K]
  exact ((AlgEquiv.ofBijective (Algebra.ofId K v.ResidueField) hbij).toLinearEquiv.finrank_eq).symm

end Place

namespace Annulus
p2m_export "AlgebraicCurve.Annulus" "IsAttached existsUnique_evalAt_eq modulus modulus_mem mk dom mem_dom param ord_param_sub"
p2m_open "AlgebraicCurve.Annulus"

variable {L : Type*} [Field L] {A : ValuationSubring L} {F : Type*} [Field F] [Algebra L F]

theorem ord_param_eq_zero_cps (An : Annulus A F) {P : Place L F} (hP : P ∈ An.dom) :
    P.ord An.param = 0 := by
  obtain ⟨-, hz, -, hne, -⟩ := An.mem_dom P hP
  exact P.ord_eq_zero_of_evalAt_ne_zero_cps hz hne

theorem ord_param_sub_evalAt_cps (An : Annulus A F) {P : Place L F} (hP : P ∈ An.dom) :
    P.ord (An.param - algebraMap L F (P.evalAt An.param)) = 1 :=
  An.ord_param_sub P hP

theorem ord_param_sub_evalAt_of_ne_cps (An : Annulus A F) {P Q : Place L F} (hP : P ∈ An.dom)
    (hQ : Q ∈ An.dom) (hPQ : P ≠ Q) : Q.ord (An.param - algebraMap L F (P.evalAt An.param)) = 0 := by
  obtain ⟨hQrat, hzQ, -, -, -⟩ := An.mem_dom Q hQ
  obtain ⟨-, -, ⟨hPA, hPm⟩, hP0, hPmod⟩ := An.mem_dom P hP
  refine Q.ord_eq_zero_of_evalAt_ne_zero_cps (sub_mem hzQ (Q.algebraMap_mem' _)) ?_
  rw [Q.evalAt_sub_of_mem_cps hQrat hzQ (Q.algebraMap_mem' _), Q.evalAt_algebraMap_cps, sub_ne_zero]
  intro hEq
  obtain ⟨R, -, huniq⟩ := An.existsUnique_evalAt_eq ⟨P.evalAt An.param, hPA⟩ hPm hP0 hPmod
  exact hPQ ((huniq P ⟨hP, rfl⟩).trans (huniq Q ⟨hQ, hEq⟩).symm)

private theorem _root_.AlgebraicCurve.Annulus.depth_pos_and_lt_cps (An : Annulus A F) {π : A} (hπ0 : π ≠ 0)
    {w : ℕ} (hw : ∃ u : Aˣ, An.modulus = u * π ^ w)
    {P : Place L F} (hP : P ∈ An.dom) {d : ℕ} {u : Aˣ} {h : P.evalAt An.param ∈ A}
    (hd : (⟨P.evalAt An.param, h⟩ : A) = u * π ^ d) : 0 < d ∧ d < w := by
  obtain ⟨-, -, ⟨hA, hm⟩, hne, m', hm', hmod⟩ := An.mem_dom P hP
  obtain ⟨u', hu'⟩ := hw
  have hAeq : (⟨P.evalAt An.param, hA⟩ : A) = u * π ^ d := hd
  have hd0 : 0 < d := by
    rcases Nat.eq_zero_or_pos d with rfl | hd0
    · exfalso
      rw [pow_zero, mul_one] at hAeq
      rw [hAeq] at hm
      exact (IsLocalRing.mem_maximalIdeal _).mp hm u.isUnit
    · exact hd0
  refine ⟨hd0, ?_⟩
  by_contra hdw
  push Not at hdw

  have hmodA : (u' : A) * π ^ w = (u * π ^ d) * m' := by
    rw [← hu', ← hAeq]
    apply Subtype.ext
    rw [MulMemClass.coe_mul]
    exact hmod
  have hsplit : (π : A) ^ d = π ^ (d - w) * π ^ w := by rw [← pow_add, Nat.sub_add_cancel hdw]
  rw [hsplit] at hmodA
  have hu'eq : (u' : A) = u * π ^ (d - w) * m' := by
    apply mul_right_cancel₀ (pow_ne_zero w hπ0)
    rw [hmodA]; ring
  apply (IsLocalRing.mem_maximalIdeal _).mp _ u'.isUnit
  rw [hu'eq]
  exact Ideal.mul_mem_left _ _ hm'

p2m_export "AlgebraicCurve.Annulus" "depth_pos_and_lt_cps"

theorem depth_unique_cps {π : A} (hπ : π ∈ IsLocalRing.maximalIdeal A) (hπ0 : π ≠ 0)
    {x : A} {d d' : ℕ} {u u' : Aˣ} (hd : x = u * π ^ d) (hd' : x = u' * π ^ d') : d = d' := by
  wlog hle : d ≤ d' generalizing d d' u u'
  · exact (this hd' hd ((le_total d d').resolve_left hle)).symm
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hle
  rcases Nat.eq_zero_or_pos k with rfl | hk
  · rfl
  · exfalso
    have h1 : (u : A) * π ^ d = u' * π ^ k * π ^ d := by rw [← hd, hd', pow_add]; ring
    have h2 : (u : A) = u' * π ^ k := mul_right_cancel₀ (pow_ne_zero _ hπ0) h1
    apply (IsLocalRing.mem_maximalIdeal _).mp _ u.isUnit
    rw [h2]
    exact Ideal.mul_mem_left _ _ (Ideal.pow_mem_of_mem _ hπ _ hk)

end Annulus

end AlgebraicCurve
namespace KLB45

variable {L : Type*} [Field L] {A : ValuationSubring L} {F : Type*} [Field F] [Algebra L F]

theorem exists_latticePlace (An : Annulus A F) (ϖ : A) (hϖ : ϖ ∈ IsLocalRing.maximalIdeal A) (hϖ0 : ϖ ≠ 0)
    (N t : ℕ) (u : Aˣ) (hmod : An.modulus = u * ϖ ^ N) (ht0 : 0 < t) (htN : t < N) :
    ∃ P : Place L F, P ∈ An.dom ∧ P.evalAt An.param = ((ϖ ^ t : A) : L) := by
  have hmem : ϖ ^ t ∈ IsLocalRing.maximalIdeal A := Ideal.pow_mem_of_mem _ hϖ t ht0
  have hne : ((ϖ ^ t : A) : L) ≠ 0 := by
    push_cast
    exact pow_ne_zero _ (fun h => hϖ0 (Subtype.ext h))
  have hdiv : ∃ m ∈ IsLocalRing.maximalIdeal A, (An.modulus : L) = ((ϖ ^ t : A) : L) * m := by
    obtain ⟨s, rfl, hs0⟩ : ∃ s, N = t + s ∧ 0 < s := ⟨N - t, by omega, by omega⟩
    refine ⟨(u : A) * ϖ ^ s, Ideal.mul_mem_left _ _ (Ideal.pow_mem_of_mem _ hϖ s hs0), ?_⟩
    rw [hmod, pow_add]
    push_cast
    ring
  obtain ⟨P, hP, -⟩ := An.existsUnique_evalAt_eq (ϖ ^ t) hmem hne hdiv
  exact ⟨P, hP⟩

end KLB45

theorem FiniteRep.step45sharp
    {L : Type} [Field L] [IsAlgClosed L] [CharZero L] (A : ValuationSubring L)
    (π : A) (hπ : π ∈ IsLocalRing.maximalIdeal A) (hπ0 : π ≠ 0)
    (hrk : ∀ x : L, x ≠ 0 → ∀ y : A, y ∈ IsLocalRing.maximalIdeal A →
      ∃ n : ℕ, A.valuation ((y : L) ^ n) ≤ A.valuation x)
    (F : Type) [Field F] [Algebra L F]
    (n m : ℕ) (Fbar : Fin n → Type) [∀ i, Field (Fbar i)]
    [∀ i, Algebra (IsLocalRing.ResidueField A) (Fbar i)]
    (hratBar : ∀ i, ∀ Q : Place (IsLocalRing.ResidueField A) (Fbar i), Q.IsRational)
    (C : ∀ i, ComponentChart A F (Fbar i))
    (hratF : ∀ i, ∀ P ∈ (C i).dom, P.IsRational)
    (An An' : Fin m → Annulus A F) (src tgt : Fin m → Fin n)
    (xs : ∀ e, Place (IsLocalRing.ResidueField A) (Fbar (src e)))
    (xt : ∀ e, Place (IsLocalRing.ResidueField A) (Fbar (tgt e)))
    (w : Fin m → ℕ)
    (hpair : ∀ e, (An' e).dom = (An e).dom ∧ (An' e).modulus = (An e).modulus ∧
      ((An e).modulus : L) ≠ 0 ∧
      (An' e).param * (An e).param = algebraMap L F ((An e).modulus : L))
    (hw : ∀ e, ∃ u : Aˣ, (An e).modulus = u * π ^ w e)
    (hatt : ∀ e, (An e).IsAttached (C (src e)) (xs e) ∧ (An' e).IsAttached (C (tgt e)) (xt e))
    (hnodes : (∀ i, ∀ x ∈ (C i).nodes, ∃ e,
        (⟨src e, xs e⟩ : Σ j, Place (IsLocalRing.ResidueField A) (Fbar j)) = ⟨i, x⟩ ∨
        (⟨tgt e, xt e⟩ : Σ j, Place (IsLocalRing.ResidueField A) (Fbar j)) = ⟨i, x⟩) ∧
      (∀ i, ∀ x ∈ (C i).nodes, ∀ E E' : Fin m ⊕ Fin m,
        Sum.elim (fun e => (⟨src e, xs e⟩ : Σ j, Place (IsLocalRing.ResidueField A) (Fbar j)))
          (fun e => ⟨tgt e, xt e⟩) E = ⟨i, x⟩ →
        Sum.elim (fun e => (⟨src e, xs e⟩ : Σ j, Place (IsLocalRing.ResidueField A) (Fbar j)))
          (fun e => ⟨tgt e, xt e⟩) E' = ⟨i, x⟩ → E = E'))
    (hcover : ∀ P : Place L F,
      (∃ i, P ∈ (C i).dom ∧ (∀ j, P ∈ (C j).dom → j = i) ∧ ∀ e, P ∉ (An e).dom) ∨
      (∃ e, P ∈ (An e).dom ∧ (∀ e', P ∈ (An e').dom → e' = e) ∧ ∀ i, P ∉ (C i).dom))
    (hdisc : ∀ i, ∀ Q : Place (IsLocalRing.ResidueField A) (Fbar i), Q ∉ (C i).nodes →
      ∃ (T : F) (hT : T ∈ (C i).integers), (C i).residue ⟨T, hT⟩ ≠ 0 ∧ Q.ord ((C i).residue ⟨T, hT⟩) = 1 ∧
        (∀ P ∈ (C i).dom, (C i).placeMap P = Q → T ∈ P.toValuationSubring ∧
          ∃ h : P.evalAt T ∈ A, (⟨P.evalAt T, h⟩ : A) ∈ IsLocalRing.maximalIdeal A) ∧
        ∀ c : A, c ∈ IsLocalRing.maximalIdeal A →
          ∃! P : Place L F, P ∈ (C i).dom ∧ (C i).placeMap P = Q ∧ P.evalAt T = c)
    (hgenus : genusFF L F + n = (∑ i, genusFF (IsLocalRing.ResidueField A) (Fbar i)) + m + 1)
    [IsCurveOver L F] [Algebra.EssFiniteType L F]
    [∀ i, IsCurveOver (IsLocalRing.ResidueField A) (Fbar i)]
    [∀ i, Algebra.EssFiniteType (IsLocalRing.ResidueField A) (Fbar i)]
    (N : ℕ) (hN : 0 < N)
    (ϖ : A) (hϖ : ϖ ∈ IsLocalRing.maximalIdeal A) (hϖ0 : ϖ ≠ 0) (hϖπ : ϖ ^ N = π)
    (D₀ : Divisor L F) (hD₀ : Divisor.degree D₀ = 0)
    (hD₀lat : ∀ P ∈ D₀.support, (∃ i, P ∈ (C i).dom) ∨
      ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
        (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖ ^ d)
    :
    let W : Fin m → ℕ := fun e => N * w e
    let V := Fin n ⊕ (Σ e : Fin m, Fin (W e - 1))
    let ends : (Σ e : Fin m, Fin (W e)) → V × V := fun ε =>
      (if h0 : ε.2.1 = 0 then Sum.inl (src ε.1)
        else Sum.inr ⟨ε.1, ⟨ε.2.1 - 1, by have := ε.2.2; omega⟩⟩,
       if h1 : ε.2.1 + 1 = W ε.1 then Sum.inl (tgt ε.1)
        else Sum.inr ⟨ε.1, ⟨ε.2.1, by have := ε.2.2; omega⟩⟩)
    let lap : V → (V → ℤ) := fun v => ∑ ε : Σ e : Fin m, Fin (W e),
      ((if (ends ε).1 = v then (Pi.single v 1 : V → ℤ) - (Pi.single (ends ε).2 1 : V → ℤ) else 0) +
       (if (ends ε).2 = v then (Pi.single v 1 : V → ℤ) - (Pi.single (ends ε).1 1 : V → ℤ) else 0))
    ∀ μ : Divisor L F →+ (V → ℤ),
      (∀ i, ∀ P ∈ (C i).dom, μ (Finsupp.single P 1) = Pi.single (Sum.inl i) 1) →
      (∀ e, ∀ P ∈ (An e).dom, ∀ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
        (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖ ^ d → ∀ (hd0 : 0 < d) (hdw : d < W e),
          μ (Finsupp.single P 1) = Pi.single (Sum.inr ⟨e, ⟨d - 1, by omega⟩⟩) 1) →
      (∀ e, ∀ P ∈ (An e).dom,
        (¬ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
          (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖ ^ d) → μ (Finsupp.single P 1) = 0) →
      ∀ (y χ : V → ℤ),
        (∀ v : Σ e : Fin m, Fin (W e - 1), μ D₀ (Sum.inr v) - y (Sum.inr v) = (∑ u, χ u • lap u) (Sum.inr v)) →
        ∃ (D : Divisor L F) (hD : D ∈ Divisor.degZero (K := L) (F := F))
          (Pl : (Σ e : Fin m, Fin (W e - 1)) → Place L F),
          D₀ - D ∈ Divisor.principal (K := L) (F := F) ∧
          (∀ v, Pl v ∈ (An v.1).dom ∧ (Pl v).evalAt (An v.1).param = ((ϖ ^ (v.2.1 + 1) : A) : L)) ∧
          (∀ e, ∀ P ∈ (An e).dom,
            D P = (∑ v : (Σ e : Fin m, Fin (W e - 1)), y (Sum.inr v) • Finsupp.single (Pl v) 1 : Divisor L F) P) := by
  intro W V ends lap μ hμC hμL hμN y χ hcomb
  classical

  have hwϖ : ∀ e, ∃ u : Aˣ, (An e).modulus = u * ϖ ^ W e := by
    intro e
    obtain ⟨u, hu⟩ := hw e
    refine ⟨u, ?_⟩
    show (An e).modulus = u * ϖ ^ (N * w e)
    rw [hu, ← hϖπ, ← pow_mul]

  have hENG := AlgebraicCurve.exists_ne_zero_ord_eq_of_sum_eq_zero_of_semistableCovering_of_discFibres_of_rankOne
      A ϖ hϖ hϖ0 hrk F n m Fbar hratBar C hratF An An' src tgt xs xt W hpair hwϖ hatt hnodes hcover hdisc hgenus

  have hadm : ∀ v : (Σ e : Fin m, Fin (W e - 1)),
      ∃ P : Place L F, P ∈ (An v.1).dom ∧ P.evalAt (An v.1).param = ((ϖ ^ (v.2.1 + 1) : A) : L) := by
    intro v
    obtain ⟨u, hu⟩ := hwϖ v.1
    have hv := v.2.isLt
    exact KLB45.exists_latticePlace (An v.1) ϖ hϖ hϖ0 (W v.1) (v.2.1 + 1) u hu (by omega) (by omega)
  choose Pl hPl using hadm
  have hPl_dom : ∀ v, Pl v ∈ (An v.1).dom := fun v => (hPl v).1
  have hPl_val : ∀ v, (Pl v).evalAt (An v.1).param = ((ϖ ^ (v.2.1 + 1) : A) : L) := fun v => (hPl v).2
  have hPl_mem : ∀ v, (Pl v).evalAt (An v.1).param ∈ A := fun v => by rw [hPl_val v]; exact (ϖ ^ (v.2.1 + 1)).2
  have hPl_lat : ∀ v, (⟨(Pl v).evalAt (An v.1).param, hPl_mem v⟩ : A) = (1 : Aˣ) * ϖ ^ (v.2.1 + 1) := by
    intro v
    apply Subtype.ext
    simp only [Units.val_one, one_mul]
    exact hPl_val v
  have hμPl : ∀ v, μ (Finsupp.single (Pl v) 1) = Pi.single (Sum.inr v) 1 := by
    intro v
    have hv := v.2.isLt
    rw [hμL v.1 (Pl v) (hPl_dom v) (v.2.1 + 1) 1 (hPl_mem v) (hPl_lat v) (by omega) (by omega)]
    have hfin : (⟨v.2.1 + 1 - 1, by omega⟩ : Fin (W v.1 - 1)) = v.2 := Fin.ext (by simp)
    rw [hfin]

  let isA : Place L F → Prop := fun P => ∃ e, P ∈ (An e).dom
  let D0a : Divisor L F := D₀.filter isA
  let D1a : Divisor L F := ∑ v : (Σ e : Fin m, Fin (W e - 1)), y (Sum.inr v) • Finsupp.single (Pl v) 1
  have hμD1a : ∀ v' : (Σ e : Fin m, Fin (W e - 1)), μ D1a (Sum.inr v') = y (Sum.inr v') := by
    intro v'
    show μ (∑ v : (Σ e : Fin m, Fin (W e - 1)), y (Sum.inr v) • Finsupp.single (Pl v) 1) (Sum.inr v') = y (Sum.inr v')
    rw [map_sum, Finset.sum_apply]
    simp_rw [map_zsmul, hμPl, Pi.smul_apply, Pi.single_apply, smul_eq_mul]
    rw [Finset.sum_eq_single v']
    · simp
    · intro v _ hv
      rw [if_neg (fun h => hv (Sum.inr_injective h).symm), mul_zero]
    · intro h; exact absurd (Finset.mem_univ v') h
  have hμD0c : ∀ v' : (Σ e : Fin m, Fin (W e - 1)), μ (D₀.filter (fun P => ¬ isA P)) (Sum.inr v') = 0 := by
    intro v'
    have hsum : D₀.filter (fun P => ¬ isA P) =
        ∑ P ∈ (D₀.filter (fun P => ¬ isA P)).support, Finsupp.single P ((D₀.filter (fun P => ¬ isA P)) P) :=
      (Finsupp.sum_single _).symm
    rw [hsum, map_sum, Finset.sum_apply]
    refine Finset.sum_eq_zero (fun P hP => ?_)
    rw [Finsupp.support_filter, Finset.mem_filter] at hP
    obtain ⟨hP0, hPc⟩ := hP
    rcases hD₀lat P hP0 with ⟨i, hi⟩ | ⟨e, he, -⟩
    · rw [← Finsupp.smul_single_one, map_zsmul, hμC i P hi]
      simp [Pi.single_apply]
    · exact absurd ⟨e, he⟩ hPc
  have hμD0a : ∀ v' : (Σ e : Fin m, Fin (W e - 1)), μ D0a (Sum.inr v') = μ D₀ (Sum.inr v') := by
    intro v'
    conv_rhs => rw [← Finsupp.filter_add_filter_not D₀ isA]
    rw [map_add, Pi.add_apply, hμD0c, add_zero]

  let Dan : Divisor L F := D0a - D1a
  have hDanlat : ∀ P ∈ Dan.support, ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
      (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖ ^ d := by
    intro P hP
    have hP' := Finsupp.support_sub (f := D0a) (g := D1a) hP
    rcases Finset.mem_union.mp hP' with h0 | h1
    · have h0' : P ∈ D₀.support ∧ isA P := by
        have := h0; rw [Finsupp.support_filter, Finset.mem_filter] at this; exact this
      obtain ⟨e, he⟩ := h0'.2
      rcases hD₀lat P h0'.1 with ⟨i, hi⟩ | h
      · rcases hcover P with ⟨i', -, -, hno⟩ | ⟨e', -, -, hno⟩
        · exact absurd he (hno e)
        · exact absurd hi (hno i)
      · exact h
    · have h1' := Finsupp.support_finsetSum
        (s := (Finset.univ : Finset (Σ e : Fin m, Fin (W e - 1))))
        (f := fun v => y (Sum.inr v) • Finsupp.single (Pl v) 1) h1
      simp only [Finset.mem_biUnion, Finset.mem_univ, true_and] at h1'
      obtain ⟨v, hv⟩ := h1'
      have hPv : P = Pl v := by
        have := Finsupp.support_smul hv
        exact Finset.mem_singleton.mp (Finsupp.support_single_subset this)
      subst hPv
      exact ⟨v.1, hPl_dom v, v.2.1 + 1, 1, hPl_mem v, hPl_lat v⟩
  have hmass : ∀ v : (Σ e : Fin m, Fin (W e - 1)), μ Dan (Sum.inr v) = (∑ u, χ u • lap u) (Sum.inr v) := by
    intro v
    show μ (D0a - D1a) (Sum.inr v) = (∑ u, χ u • lap u) (Sum.inr v)
    rw [map_sub, Pi.sub_apply, hμD0a, hμD1a]
    exact hcomb v

  obtain ⟨f, Df, hf0, hDf, hDfan, -⟩ := hENG μ hμC hμL hμN χ Dan hDanlat hmass
  have hDfdeg : Divisor.degree Df = 0 := by
    obtain ⟨E, hE, hEdeg⟩ := HasPrincipalDivisors.exists_divisor (K := L) (F := F) f hf0
    have : Df = E := Finsupp.ext (fun P => by rw [hDf P, hE P])
    rw [this]; exact hEdeg
  refine ⟨D₀ - Df, ?_, Pl, ?_, fun v => ⟨hPl_dom v, hPl_val v⟩, ?_⟩
  · rw [Divisor.mem_degZero, map_sub, hD₀, hDfdeg, sub_zero]
  · rw [sub_sub_cancel]
    exact ⟨f, hf0, hDf⟩
  · intro e P he
    rw [Finsupp.sub_apply, hDfan e P he]
    show D₀ P - (D0a - D1a) P = D1a P
    rw [Finsupp.sub_apply]
    have : D0a P = D₀ P := by
      show (D₀.filter isA) P = D₀ P
      rw [Finsupp.filter_apply, if_pos ⟨e, he⟩]
    rw [this]; ring

namespace P2mWs20TropLift

theorem exists_mem_pow_smul_sub_eq_zero {G : Type*} [AddCommGroup G] (H : AddSubgroup G) (ℓ : ℕ) (hℓ : ℓ.Prime)
    (a : ℕ) (x : G) (hx : IsOfFinAddOrder x) (hH : ((ℓ ^ a : ℕ) : ℤ) • x ∈ H) :
    ∃ h ∈ H, ∃ b : ℕ, ((ℓ ^ b : ℕ) : ℤ) • (x - h) = 0 := by
  have ho : 0 < addOrderOf x := hx.addOrderOf_pos
  obtain ⟨c, r, hr, hocr⟩ := Nat.exists_eq_pow_mul_and_not_dvd ho.ne' ℓ hℓ.one_lt.ne'

  have hcop : Nat.Coprime (ℓ ^ (a + c)) r := (Nat.Coprime.pow_left _ ((Nat.Prime.coprime_iff_not_dvd hℓ).mpr hr))
  obtain ⟨α, β, hαβ⟩ := Nat.isCoprime_iff_coprime.mpr hcop
  refine ⟨(α * ((ℓ ^ c : ℕ) : ℤ)) • (((ℓ ^ a : ℕ) : ℤ) • x), H.zsmul_mem hH _, c, ?_⟩
  have hx0 : ((ℓ ^ c * r : ℕ) : ℤ) • x = 0 := by
    rw [← hocr, natCast_zsmul, addOrderOf_nsmul_eq_zero]

  have hh : (α * ((ℓ ^ c : ℕ) : ℤ)) • (((ℓ ^ a : ℕ) : ℤ) • x) = (α * ((ℓ ^ (a + c) : ℕ) : ℤ)) • x := by
    rw [smul_smul]; congr 1; push_cast; ring
  have hsplit : x - (α * ((ℓ ^ c : ℕ) : ℤ)) • (((ℓ ^ a : ℕ) : ℤ) • x) = (β * (r : ℤ)) • x := by
    rw [hh]
    conv_lhs => rw [show x - (α * ((ℓ ^ (a + c) : ℕ) : ℤ)) • x = ((1 : ℤ) - α * ((ℓ ^ (a + c) : ℕ) : ℤ)) • x from by
      rw [sub_smul, one_zsmul]]
    congr 1
    linear_combination (-1 : ℤ) * hαβ
  rw [hsplit, smul_smul, show ((ℓ ^ c : ℕ) : ℤ) * (β * (r : ℤ)) = β * ((ℓ ^ c * r : ℕ) : ℤ) by push_cast; ring,
    ← smul_smul, hx0, zsmul_zero]

end P2mWs20TropLift

open _root_.AlgebraicCurve _root_.P2MW.S_AlgebraicCurve_exists_pow_zsmul_mk_eq_zero_forall_mu_sub_eq_sum_smul_lap_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel.AlgebraicCurve P2mWs20FiniteRep IsLocalRing in
theorem solution
    {L : Type} [Field L] [IsAlgClosed L] [CharZero L] (A : ValuationSubring L)
    (π : A) (hπ : π ∈ IsLocalRing.maximalIdeal A) (hπ0 : π ≠ 0)
    (hrk : ∀ x : L, x ≠ 0 → ∀ y : A, y ∈ IsLocalRing.maximalIdeal A →
      ∃ n : ℕ, A.valuation ((y : L) ^ n) ≤ A.valuation x)
    (F : Type) [Field F] [Algebra L F]
    (n m : ℕ) (Fbar : Fin n → Type) [∀ i, Field (Fbar i)]
    [∀ i, Algebra (IsLocalRing.ResidueField A) (Fbar i)]
    (hratBar : ∀ i, ∀ Q : Place (IsLocalRing.ResidueField A) (Fbar i), Q.IsRational)
    (C : ∀ i, ComponentChart A F (Fbar i))
    (hratF : ∀ i, ∀ P ∈ (C i).dom, P.IsRational)
    (An An' : Fin m → Annulus A F) (src tgt : Fin m → Fin n)
    (xs : ∀ e, Place (IsLocalRing.ResidueField A) (Fbar (src e)))
    (xt : ∀ e, Place (IsLocalRing.ResidueField A) (Fbar (tgt e)))
    (w : Fin m → ℕ)
    (hpair : ∀ e, (An' e).dom = (An e).dom ∧ (An' e).modulus = (An e).modulus ∧
      ((An e).modulus : L) ≠ 0 ∧
      (An' e).param * (An e).param = algebraMap L F ((An e).modulus : L))
    (hw : ∀ e, ∃ u : Aˣ, (An e).modulus = u * π ^ w e)
    (hatt : ∀ e, (An e).IsAttached (C (src e)) (xs e) ∧ (An' e).IsAttached (C (tgt e)) (xt e))
    (hnodes : (∀ i, ∀ x ∈ (C i).nodes, ∃ e,
        (⟨src e, xs e⟩ : Σ j, Place (IsLocalRing.ResidueField A) (Fbar j)) = ⟨i, x⟩ ∨
        (⟨tgt e, xt e⟩ : Σ j, Place (IsLocalRing.ResidueField A) (Fbar j)) = ⟨i, x⟩) ∧
      (∀ i, ∀ x ∈ (C i).nodes, ∀ E E' : Fin m ⊕ Fin m,
        Sum.elim (fun e => (⟨src e, xs e⟩ : Σ j, Place (IsLocalRing.ResidueField A) (Fbar j)))
          (fun e => ⟨tgt e, xt e⟩) E = ⟨i, x⟩ →
        Sum.elim (fun e => (⟨src e, xs e⟩ : Σ j, Place (IsLocalRing.ResidueField A) (Fbar j)))
          (fun e => ⟨tgt e, xt e⟩) E' = ⟨i, x⟩ → E = E'))
    (hcover : ∀ P : Place L F,
      (∃ i, P ∈ (C i).dom ∧ (∀ j, P ∈ (C j).dom → j = i) ∧ ∀ e, P ∉ (An e).dom) ∨
      (∃ e, P ∈ (An e).dom ∧ (∀ e', P ∈ (An e').dom → e' = e) ∧ ∀ i, P ∉ (C i).dom))
    (hdisc : ∀ i, ∀ Q : Place (IsLocalRing.ResidueField A) (Fbar i), Q ∉ (C i).nodes →
      ∃ (T : F) (hT : T ∈ (C i).integers), (C i).residue ⟨T, hT⟩ ≠ 0 ∧ Q.ord ((C i).residue ⟨T, hT⟩) = 1 ∧
        (∀ P ∈ (C i).dom, (C i).placeMap P = Q → T ∈ P.toValuationSubring ∧
          ∃ h : P.evalAt T ∈ A, (⟨P.evalAt T, h⟩ : A) ∈ IsLocalRing.maximalIdeal A) ∧
        ∀ c : A, c ∈ IsLocalRing.maximalIdeal A →
          ∃! P : Place L F, P ∈ (C i).dom ∧ (C i).placeMap P = Q ∧ P.evalAt T = c)
    (hgenus : genusFF L F + n = (∑ i, genusFF (IsLocalRing.ResidueField A) (Fbar i)) + m + 1)
    [IsCurveOver L F] [Algebra.EssFiniteType L F]
    (ℓ : ℕ) [Fact ℓ.Prime] (hℓ : IsUnit ((ℓ : ℕ) : IsLocalRing.ResidueField A)) (K : ℕ)
    [∀ i, IsCurveOver (IsLocalRing.ResidueField A) (Fbar i)]
    [∀ i, Algebra.EssFiniteType (IsLocalRing.ResidueField A) (Fbar i)]
    (M : AlgebraicCurve.SemistableModel A F Fbar C An src tgt xs xt) (D : M.Descent)
    (ϖ : A) (hϖ : ϖ ∈ IsLocalRing.maximalIdeal A) (hϖπ : ϖ ^ (ℓ ^ K) = π)
    (hκ : ∀ p : ℕ, p.Prime → CharP (IsLocalRing.ResidueField A) p →
      ∀ a : IsLocalRing.ResidueField A, ∃ n : ℕ, 0 < n ∧ a ^ (p ^ n) = a)
    :
    let V := Fin n ⊕ (Σ e : Fin m, Fin (ℓ ^ K * w e - 1))
    let ends : (Σ e : Fin m, Fin (ℓ ^ K * w e)) → V × V := fun ε =>
      (if h0 : ε.2.1 = 0 then Sum.inl (src ε.1)
        else Sum.inr ⟨ε.1, ⟨ε.2.1 - 1, by have := ε.2.2; omega⟩⟩,
       if h1 : ε.2.1 + 1 = ℓ ^ K * w ε.1 then Sum.inl (tgt ε.1)
        else Sum.inr ⟨ε.1, ⟨ε.2.1, by have := ε.2.2; omega⟩⟩)
    let lap : V → (V → ℤ) := fun v => ∑ ε : Σ e : Fin m, Fin (ℓ ^ K * w e),
      ((if (ends ε).1 = v then (Pi.single v 1 : V → ℤ) - (Pi.single (ends ε).2 1 : V → ℤ) else 0) +
       (if (ends ε).2 = v then (Pi.single v 1 : V → ℤ) - (Pi.single (ends ε).1 1 : V → ℤ) else 0))
    ∀ μ : Divisor L F →+ (V → ℤ),
      (∀ i, ∀ P ∈ (C i).dom, μ (Finsupp.single P 1) = Pi.single (Sum.inl i) 1) →
      (∀ e, ∀ P ∈ (An e).dom, ∀ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
        (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖ ^ d → ∀ (hd0 : 0 < d) (hdw : d < ℓ ^ K * w e),
          μ (Finsupp.single P 1) = Pi.single (Sum.inr ⟨e, ⟨d - 1, by omega⟩⟩) 1) →
      (∀ e, ∀ P ∈ (An e).dom,
        (¬ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
          (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖ ^ d) → μ (Finsupp.single P 1) = 0) →
      ∀ t : V → ℤ,
        (∃ (K'' : ℕ) (φ : V → ℤ), ∀ v : Σ e : Fin m, Fin (ℓ ^ K * w e - 1),
            (ℓ ^ K'' : ℤ) * t (Sum.inr v) = (∑ u, φ u • lap u) (Sum.inr v)) →
        ∃ (D : Divisor L F) (hD : D ∈ Divisor.degZero (K := L) (F := F)) (χ : V → ℤ),
          (∃ K' : ℕ, ((ℓ ^ K' : ℕ) : ℤ) • Pic0.mk ⟨D, hD⟩ = 0) ∧
          (∀ P ∈ D.support, (∃ i, P ∈ (C i).dom) ∨
            ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
              (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖ ^ d) ∧
          ∀ v : Σ e : Fin m, Fin (ℓ ^ K * w e - 1), μ D (Sum.inr v) - t (Sum.inr v) = (∑ u, χ u • lap u) (Sum.inr v) := by
  intro V ends lap μ hμC hμA hμ0 t ht
  classical
  obtain ⟨K'', φ, hφ⟩ := ht
  have hℓp := (Fact.out : ℓ.Prime)

  have hCOUNT := fun kk : ℕ =>
    AlgebraicCurve.Pic0.natCard_torsion_pow_eq_pow_two_mul_genusFF_mul_of_charZero L F ℓ kk

  have hLatRep : ∀ (N : ℕ) (ϖN : A), ϖN ∈ maximalIdeal A → ϖN ≠ 0 → ϖN ^ (ℓ ^ N) = π →
      ∀ c : Pic0 L F, ((ℓ ^ N : ℕ) : ℤ) • c = 0 →
        ∃ (D : Divisor L F) (hD : D ∈ Divisor.degZero (K := L) (F := F)), Pic0.mk ⟨D, hD⟩ = c ∧
          ∀ P ∈ D.support, (∃ i, P ∈ (C i).dom) ∨
            ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
              (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d := by
    intro N ϖN hϖN hϖN0 hϖNπ c hc
    obtain ⟨D, hD, hmk, hsupp⟩ :=
      AlgebraicCurve.exists_mk_eq_forall_mem_support_pow_evalAt_param_eq_of_zsmul_eq_zero_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel
        A π hπ hπ0 hrk F n m Fbar hratBar C hratF An An' src tgt xs xt w hpair hw hatt hnodes hcover hdisc hgenus ℓ N M D c hc
    refine ⟨D, hD, hmk, fun P hP => ?_⟩
    rcases hsupp P hP with h | ⟨e, he, v, j, hvj⟩
    · exact Or.inl h
    · right
      refine ⟨e, he, ?_⟩
      obtain ⟨-, -, ⟨hzA, hzm⟩, hz0, -⟩ := (An e).mem_dom P he
      have hϖNL0 : ((ϖN : A) : L) ≠ 0 := fun h => hϖN0 (Subtype.ext h)
      have hNpos : ℓ ^ N ≠ 0 := pow_ne_zero _ (Fact.out : ℓ.Prime).ne_zero

      have hq : (P.evalAt (An e).param * (((ϖN : A) : L) ^ j)⁻¹) ^ (ℓ ^ N) = ((v : A) : L) := by
        rw [mul_pow, inv_pow, ← pow_mul, mul_comm j, pow_mul, ← SubmonoidClass.coe_pow, hϖNπ, hvj, mul_assoc,
          mul_inv_cancel₀ (pow_ne_zero _ (by exact_mod_cast hπ0 : ((π : A) : L) ≠ 0)), mul_one]
      obtain ⟨hqA, hqu⟩ := mem_and_isUnit_of_pow_eq A hNpos v.isUnit hq
      refine ⟨j, hqu.unit, hzA, Subtype.ext ?_⟩
      rw [MulMemClass.coe_mul, SubmonoidClass.coe_pow, IsUnit.unit_spec]
      show P.evalAt (An e).param = P.evalAt (An e).param * (((ϖN : A) : L) ^ j)⁻¹ * ((ϖN : A) : L) ^ j
      rw [mul_assoc, inv_mul_cancel₀ (pow_ne_zero _ hϖNL0), mul_one]

  have hPosWD : ∀ (N : ℕ) (ϖN : A) (hϖN : ϖN ∈ maximalIdeal A) (hϖN0 : ϖN ≠ 0) (hϖNπ : ϖN ^ (ℓ ^ N) = π),
        let V := Fin n ⊕ (Σ e : Fin m, Fin (ℓ ^ N * w e - 1))
        let ends : (Σ e : Fin m, Fin (ℓ ^ N * w e)) → V × V := fun ε =>
          (if h0 : ε.2.1 = 0 then Sum.inl (src ε.1)
            else Sum.inr ⟨ε.1, ⟨ε.2.1 - 1, by have := ε.2.2; omega⟩⟩,
           if h1 : ε.2.1 + 1 = ℓ ^ N * w ε.1 then Sum.inl (tgt ε.1)
            else Sum.inr ⟨ε.1, ⟨ε.2.1, by have := ε.2.2; omega⟩⟩)
        let lap : V → (V → ℤ) := fun v => ∑ ε : Σ e : Fin m, Fin (ℓ ^ N * w e),
          ((if (ends ε).1 = v then (Pi.single v 1 : V → ℤ) - (Pi.single (ends ε).2 1 : V → ℤ) else 0) +
           (if (ends ε).2 = v then (Pi.single v 1 : V → ℤ) - (Pi.single (ends ε).1 1 : V → ℤ) else 0))
        ∀ μN : Divisor L F →+ (V → ℤ),
          (∀ i, ∀ P ∈ (C i).dom, μN (Finsupp.single P 1) = Pi.single (Sum.inl i) 1) →
          (∀ e, ∀ P ∈ (An e).dom, ∀ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
            (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d → ∀ (hd0 : 0 < d) (hdw : d < ℓ ^ N * w e),
              μN (Finsupp.single P 1) = Pi.single (Sum.inr ⟨e, ⟨d - 1, by omega⟩⟩) 1) →
          (∀ e, ∀ P ∈ (An e).dom,
            (¬ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
              (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d) → μN (Finsupp.single P 1) = 0) →
          ∀ (D₁ D₂ : Divisor L F),
            (∀ P ∈ D₁.support, (∃ i, P ∈ (C i).dom) ∨
              ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
                (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d) →
            (∀ P ∈ D₂.support, (∃ i, P ∈ (C i).dom) ∨
              ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
                (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d) →
            D₁ - D₂ ∈ Divisor.principal (K := L) (F := F) →
            μN D₁ - μN D₂ ∈ AddSubgroup.closure (Set.range lap) := by
    intro N ϖN hϖN hϖN0 hϖNπ V ends lap μN hμC' hμA' hμ0' D₁ D₂ hD₁ hD₂ hprin
    have hwN : ∀ e, ∃ u : Aˣ, (An e).modulus = u * ϖN ^ (ℓ ^ N * w e) := by
      intro e
      obtain ⟨u, hu⟩ := hw e
      exact ⟨u, by rw [hu, pow_mul, hϖNπ]⟩
    obtain ⟨φN, hφC, hφA, hφ0, hφdiv⟩ :=
      AlgebraicCurve.exists_multidegree_of_semistableCovering A ϖN hϖN hϖN0 F n m Fbar hratBar C hratF An An' src tgt
        xs xt (fun e => ℓ ^ N * w e) hpair hwN hatt hnodes hcover
    have hφμ : φN = (QuotientAddGroup.mk' _).comp μN := by
      refine Finsupp.addHom_ext' fun P => AddMonoidHom.ext_int ?_
      simp only [AddMonoidHom.comp_apply, Finsupp.singleAddHom_apply, QuotientAddGroup.mk'_apply]
      rcases hcover P with ⟨i, hi, -, -⟩ | ⟨e, he, -, -⟩
      · rw [hφC i P hi, hμC' i P hi]
      · by_cases hlat : ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
            (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d
        · obtain ⟨d, u, h, hd⟩ := hlat
          obtain ⟨hd0, hdw⟩ := (An e).depth_pos_and_lt_cps hϖN0 (hwN e) he hd
          rw [hφA e P he d u h hd hd0 hdw, hμA' e P he d u h hd hd0 hdw]
        · rw [hφ0 e P he hlat, hμ0' e P he hlat, QuotientAddGroup.mk_zero]
    obtain ⟨f, hf0, hf⟩ := Divisor.mem_principal.mp hprin
    have hlat12 : ∀ P ∈ (D₁ - D₂).support, (∃ i, P ∈ (C i).dom) ∨
        ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
          (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d := by
      intro P hP
      rcases Finset.mem_union.mp (Finsupp.support_sub hP) with h | h
      · exact hD₁ P h
      · exact hD₂ P h
    have hφ0D : φN (D₁ - D₂) = 0 := hφdiv f hf0 _ hf hlat12
    rw [hφμ, AddMonoidHom.comp_apply, QuotientAddGroup.mk'_apply, QuotientAddGroup.eq_zero_iff, map_sub] at hφ0D
    exact hφ0D

  have hconn := AlgebraicCurve.SemistableCovering.exists_src_mem_iff_tgt_notMem_of_discFibres_of_rankOne A π hπ hπ0 hrk F n m
    Fbar hratBar C hratF An An' src tgt xs xt w hpair hw hatt hnodes hcover hdisc hgenus
  have hwpos : ∀ e, 0 < ℓ ^ K * w e := by
    intro e
    refine Nat.mul_pos (pow_pos hℓp.pos K) (Nat.pos_of_ne_zero ?_)
    intro hwe
    obtain ⟨u, hu⟩ := hw e
    rw [hwe, pow_zero, mul_one] at hu
    exact (IsLocalRing.mem_maximalIdeal _).mp (hu ▸ (An e).modulus_mem) u.isUnit
  have hDEG0 := AlgebraicCurve.SemistableCovering.isOfFinAddOrder_mk_quotient_lap_of_sum_eq_zero_of_forall_exists_src_mem_iff
    n m src tgt (fun e => ℓ ^ K * w e) hwpos hconn

  let Hch : AddSubgroup ((V → ℤ) ⧸ AddSubgroup.closure (Set.range lap)) :=
    AddSubgroup.map (QuotientAddGroup.mk' (AddSubgroup.closure (Set.range lap)))
      { carrier := {x : V → ℤ | ∀ v : Σ e : Fin m, Fin (ℓ ^ K * w e - 1), x (Sum.inr v) = 0}
        zero_mem' := fun _ => rfl
        add_mem' := fun {a b} ha hb v => by rw [Pi.add_apply, ha v, hb v, add_zero]
        neg_mem' := fun {a} ha v => by rw [Pi.neg_apply, ha v, neg_zero] }

  have hcert : ((ℓ ^ K'' : ℕ) : ℤ) • (QuotientAddGroup.mk t : (V → ℤ) ⧸ AddSubgroup.closure (Set.range lap)) ∈ Hch := by
    refine ⟨(ℓ ^ K'' : ℤ) • t - ∑ u, φ u • lap u, ?_, ?_⟩
    · intro v
      show ((ℓ ^ K'' : ℤ) • t - ∑ u, φ u • lap u) (Sum.inr v) = 0
      rw [Pi.sub_apply, Pi.smul_apply, smul_eq_mul, hφ v, sub_self]
    · rw [QuotientAddGroup.mk'_apply, QuotientAddGroup.mk_sub]
      have hmem : (∑ u, φ u • lap u) ∈ AddSubgroup.closure (Set.range lap) :=
        AddSubgroup.sum_mem _ fun u _ => AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (Set.mem_range_self u)) _
      rw [(QuotientAddGroup.eq_zero_iff _).mpr hmem, sub_zero, QuotientAddGroup.mk_zsmul]
      norm_cast

  rcases Nat.eq_zero_or_pos n with hn0 | hnpos
  · subst hn0
    have hm0 : m = 0 := by
      rcases Nat.eq_zero_or_pos m with h | h
      · exact h
      · exact absurd (src ⟨0, h⟩).isLt (by omega)
    subst hm0
    refine ⟨0, zero_mem _, 0, ⟨0, ?_⟩, fun P hP => by simp at hP, fun v => ?_⟩
    · change ((ℓ ^ 0 : ℕ) : ℤ) • Pic0.mk (0 : ↥(Divisor.degZero (K := L) (F := F))) = 0
      rw [Pic0.mk_zero, smul_zero]
    exact absurd v.1.isLt (by omega)
  obtain ⟨i₀⟩ : Nonempty (Fin n) := ⟨⟨0, hnpos⟩⟩

  let t' : V → ℤ := t - (∑ v, t v) • (Pi.single (Sum.inl i₀) 1 : V → ℤ)
  have ht'int : ∀ v : Σ e : Fin m, Fin (ℓ ^ K * w e - 1), t' (Sum.inr v) = t (Sum.inr v) := by
    intro v
    show (t - (∑ v, t v) • (Pi.single (Sum.inl i₀) 1 : V → ℤ)) (Sum.inr v) = t (Sum.inr v)
    rw [Pi.sub_apply, Pi.smul_apply, Pi.single_apply, if_neg Sum.inr_ne_inl, smul_zero, sub_zero]
  have ht'sum : (∑ v, t' v) = 0 := by
    show (∑ v, (t - (∑ v, t v) • (Pi.single (Sum.inl i₀) 1 : V → ℤ)) v) = 0
    simp only [Pi.sub_apply, Pi.smul_apply, Finset.sum_sub_distrib, ← Finset.smul_sum]
    rw [Finset.sum_pi_single']
    simp
  have hfin : IsOfFinAddOrder (QuotientAddGroup.mk t' : (V → ℤ) ⧸ AddSubgroup.closure (Set.range lap)) := hDEG0 t' ht'sum
  have hcert' : ((ℓ ^ K'' : ℕ) : ℤ) • (QuotientAddGroup.mk t' : (V → ℤ) ⧸ AddSubgroup.closure (Set.range lap)) ∈ Hch := by
    have : (QuotientAddGroup.mk t' : (V → ℤ) ⧸ AddSubgroup.closure (Set.range lap)) =
        QuotientAddGroup.mk t - QuotientAddGroup.mk ((∑ v, t v) • (Pi.single (Sum.inl i₀) 1 : V → ℤ)) := by
      rw [← QuotientAddGroup.mk_sub]
    rw [this, zsmul_sub]
    refine Hch.sub_mem hcert (Hch.zsmul_mem ?_ _)
    exact ⟨_, fun v => by simp [Pi.smul_apply, Pi.single_apply, Sum.inr_ne_inl], rfl⟩
  obtain ⟨hcl, hhcl, b, hb⟩ := P2mWs20TropLift.exists_mem_pow_smul_sub_eq_zero Hch ℓ hℓp K'' _ hfin hcert'
  obtain ⟨g, hg, hgcl⟩ := hhcl

  let t'' : V → ℤ := t' - g
  have ht''int : ∀ v : Σ e : Fin m, Fin (ℓ ^ K * w e - 1), t'' (Sum.inr v) = t (Sum.inr v) := by
    intro v
    show (t' - g) (Sum.inr v) = t (Sum.inr v)
    rw [Pi.sub_apply, ht'int, show g (Sum.inr v) = 0 from hg v, sub_zero]
  have ht''tor : ((ℓ ^ b : ℕ) : ℤ) • (QuotientAddGroup.mk t'' : (V → ℤ) ⧸ AddSubgroup.closure (Set.range lap)) = 0 := by
    have : (QuotientAddGroup.mk t'' : (V → ℤ) ⧸ AddSubgroup.closure (Set.range lap)) = QuotientAddGroup.mk t' - hcl := by
      rw [← hgcl, QuotientAddGroup.mk'_apply, ← QuotientAddGroup.mk_sub]
    rw [this]; exact hb

  set N : ℕ := K + b with hNdef

  have hbpos : 0 < ℓ ^ b := pow_pos hℓp.pos b
  obtain ⟨πN, hπN⟩ := IsAlgClosed.exists_pow_nat_eq ((ϖ : A) : L) hbpos
  obtain ⟨hπNA, hπNm⟩ := mem_and_mem_maximalIdeal_of_pow_eq A hbpos.ne' hϖ hπN
  set ϖN : A := ⟨πN, hπNA⟩ with hϖNdef
  have hϖNm : ϖN ∈ maximalIdeal A := hπNm
  have hϖNb : ϖN ^ (ℓ ^ b) = ϖ := Subtype.ext (by simp [hϖNdef, hπN])
  have hϖNπ : ϖN ^ (ℓ ^ N) = π := by
    rw [show ℓ ^ N = ℓ ^ b * ℓ ^ K by rw [hNdef, pow_add, mul_comm], pow_mul, hϖNb, hϖπ]
  have hϖ0 : ϖ ≠ 0 := by
    intro h; apply hπ0; rw [← hϖπ, h, zero_pow (pow_pos hℓp.pos K).ne']
  have hϖN0 : ϖN ≠ 0 := by
    intro h; apply hϖ0; rw [← hϖNb, h, zero_pow hbpos.ne']
  have hwN : ∀ e, ∃ u : Aˣ, (An e).modulus = u * ϖN ^ (ℓ ^ N * w e) := by
    intro e
    obtain ⟨u, hu⟩ := hw e
    exact ⟨u, by rw [hu, pow_mul, hϖNπ]⟩

  have hVN : ∀ R : Place L F, ∃ vv : (Fin n ⊕ (Σ e : Fin m, Fin (ℓ ^ N * w e - 1))) → ℤ,
      (∀ i, R ∈ (C i).dom → vv = Pi.single (Sum.inl i) 1) ∧
      (∀ e, R ∈ (An e).dom → ∀ (dd : ℕ) (uu : Aˣ) (h : R.evalAt (An e).param ∈ A),
        (⟨R.evalAt (An e).param, h⟩ : A) = uu * ϖN ^ dd → ∀ (hd0 : 0 < dd) (hdw : dd < ℓ ^ N * w e),
          vv = Pi.single (Sum.inr ⟨e, ⟨dd - 1, by omega⟩⟩) 1) ∧
      (∀ e, R ∈ (An e).dom → (¬ ∃ (dd : ℕ) (uu : Aˣ) (h : R.evalAt (An e).param ∈ A),
        (⟨R.evalAt (An e).param, h⟩ : A) = uu * ϖN ^ dd) → vv = 0) := by
    intro R
    rcases hcover R with ⟨i, hi, huniq, hnot⟩ | ⟨e, he, huniq, hnot⟩
    · exact ⟨Pi.single (Sum.inl i) 1, fun j hj => by rw [huniq j hj], fun e he => absurd he (hnot e),
        fun e he => absurd he (hnot e)⟩
    · by_cases hlat : ∃ (dd : ℕ) (uu : Aˣ) (h : R.evalAt (An e).param ∈ A),
          (⟨R.evalAt (An e).param, h⟩ : A) = uu * ϖN ^ dd
      · obtain ⟨dd, uu, h, hd⟩ := hlat
        obtain ⟨hd0, hdw⟩ := (An e).depth_pos_and_lt_cps hϖN0 (hwN e) he hd
        refine ⟨Pi.single (Sum.inr ⟨e, ⟨dd - 1, by omega⟩⟩) 1, fun j hj => absurd hj (hnot j), ?_, ?_⟩
        · intro e' he' d' u' h' hd' hd0' hdw'
          obtain rfl : e' = e := huniq e' he'
          obtain rfl : dd = d' := Annulus.depth_unique_cps hϖNm hϖN0 hd hd'
          rfl
        · intro e' he' hno
          obtain rfl : e' = e := huniq e' he'
          exact absurd ⟨dd, uu, h, hd⟩ hno
      · refine ⟨0, fun j hj => absurd hj (hnot j), ?_, fun _ _ _ => rfl⟩
        intro e' he' d' u' h' hd' _ _
        obtain rfl : e' = e := huniq e' he'
        exact absurd ⟨d', u', h', hd'⟩ hlat
  choose vecN hvecNC hvecNA hvecN0 using hVN
  let μN : Divisor L F →+ ((Fin n ⊕ (Σ e : Fin m, Fin (ℓ ^ N * w e - 1))) → ℤ) :=
    Finsupp.liftAddHom fun R => zmultiplesHom _ (vecN R)
  have hμN_single : ∀ R (k : ℤ), μN (Finsupp.single R k) = k • vecN R := by
    intro R k
    simp only [μN, Finsupp.liftAddHom_apply_single, zmultiplesHom_apply]
  have hμNC : ∀ i, ∀ R ∈ (C i).dom, μN (Finsupp.single R 1) = Pi.single (Sum.inl i) 1 := by
    intro i R hR; rw [hμN_single, one_smul, hvecNC R i hR]
  have hμNA : ∀ e, ∀ R ∈ (An e).dom, ∀ (dd : ℕ) (uu : Aˣ) (h : R.evalAt (An e).param ∈ A),
      (⟨R.evalAt (An e).param, h⟩ : A) = uu * ϖN ^ dd → ∀ (hd0 : 0 < dd) (hdw : dd < ℓ ^ N * w e),
        μN (Finsupp.single R 1) = Pi.single (Sum.inr ⟨e, ⟨dd - 1, by omega⟩⟩) 1 := by
    intro e R hR dd uu h hd hd0 hdw; rw [hμN_single, one_smul, hvecNA R e hR dd uu h hd hd0 hdw]
  have hμN0 : ∀ e, ∀ R ∈ (An e).dom, (¬ ∃ (dd : ℕ) (uu : Aˣ) (h : R.evalAt (An e).param ∈ A),
      (⟨R.evalAt (An e).param, h⟩ : A) = uu * ϖN ^ dd) → μN (Finsupp.single R 1) = 0 := by
    intro e R hR hno; rw [hμN_single, one_smul, hvecN0 R e hR hno]

  let VN := Fin n ⊕ (Σ e : Fin m, Fin (ℓ ^ N * w e - 1))
  let endsN : (Σ e : Fin m, Fin (ℓ ^ N * w e)) → VN × VN := fun ε =>
    (if h0 : ε.2.1 = 0 then Sum.inl (src ε.1)
      else Sum.inr ⟨ε.1, ⟨ε.2.1 - 1, by have := ε.2.2; omega⟩⟩,
     if h1 : ε.2.1 + 1 = ℓ ^ N * w ε.1 then Sum.inl (tgt ε.1)
      else Sum.inr ⟨ε.1, ⟨ε.2.1, by have := ε.2.2; omega⟩⟩)
  let lapN : VN → (VN → ℤ) := fun v => ∑ ε : Σ e : Fin m, Fin (ℓ ^ N * w e),
    ((if (endsN ε).1 = v then (Pi.single v 1 : VN → ℤ) - (Pi.single (endsN ε).2 1 : VN → ℤ) else 0) +
     (if (endsN ε).2 = v then (Pi.single v 1 : VN → ℤ) - (Pi.single (endsN ε).1 1 : VN → ℤ) else 0))
  let JN := (VN → ℤ) ⧸ AddSubgroup.closure (Set.range lapN)
  have hrepN := hLatRep N ϖN hϖNm hϖN0 hϖNπ
  have hWD := hPosWD N ϖN hϖNm hϖN0 hϖNπ μN hμNC hμNA hμN0
  let T : AddSubgroup (Pic0 L F) := Pic0.torsion L F (ℓ ^ N)
  have hTmem : ∀ c : ↥T, ((ℓ ^ N : ℕ) : ℤ) • (c : Pic0 L F) = 0 := fun c => Pic0.mem_torsion.mp c.2
  choose repD hrepD_deg hrepD_mk hrepD_lat using fun c : ↥T => hrepN c (hTmem c)
  let posf : ↥T → JN := fun c => QuotientAddGroup.mk (μN (repD c))
  have hpos_spec : ∀ (c : ↥T) (D : Divisor L F) (hD : D ∈ Divisor.degZero (K := L) (F := F)),
      Pic0.mk ⟨D, hD⟩ = c →
      (∀ P ∈ D.support, (∃ i, P ∈ (C i).dom) ∨
        ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
          (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d) →
      posf c = QuotientAddGroup.mk (μN D) := by
    intro c D hD hmk hlat
    show (QuotientAddGroup.mk (μN (repD c)) : JN) = QuotientAddGroup.mk (μN D)
    rw [QuotientAddGroup.eq_iff_sub_mem]
    refine hWD (repD c) D (hrepD_lat c) hlat ?_
    have h : Pic0.mk ⟨repD c, hrepD_deg c⟩ = Pic0.mk ⟨D, hD⟩ := by rw [hrepD_mk c, hmk]
    have h2 := (QuotientAddGroup.eq (s := (Divisor.principal (K := L) (F := F)).addSubgroupOf _)).mp h
    rw [AddSubgroup.mem_addSubgroupOf] at h2
    have : -(repD c) + D ∈ Divisor.principal (K := L) (F := F) := by simpa using h2
    have := (Divisor.principal (K := L) (F := F)).neg_mem this
    simpa [neg_add, neg_neg, add_comm, sub_eq_add_neg] using this

  have hposf_add : ∀ c₁ c₂ : ↥T, posf (c₁ + c₂) = posf c₁ + posf c₂ := by
    intro c₁ c₂
    have hsum_deg : repD c₁ + repD c₂ ∈ Divisor.degZero (K := L) (F := F) := add_mem (hrepD_deg c₁) (hrepD_deg c₂)
    have hsum_mk : Pic0.mk ⟨repD c₁ + repD c₂, hsum_deg⟩ = ((c₁ + c₂ : ↥T) : Pic0 L F) := by
      rw [show (⟨repD c₁ + repD c₂, hsum_deg⟩ : ↥(Divisor.degZero (K := L) (F := F))) =
          ⟨repD c₁, hrepD_deg c₁⟩ + ⟨repD c₂, hrepD_deg c₂⟩ from rfl, Pic0.mk_add, hrepD_mk, hrepD_mk]
      rfl
    have hsum_lat : ∀ P ∈ (repD c₁ + repD c₂).support, (∃ i, P ∈ (C i).dom) ∨
        ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
          (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d := by
      intro P hP
      rcases Finset.mem_union.mp (Finsupp.support_add hP) with h | h
      · exact hrepD_lat c₁ P h
      · exact hrepD_lat c₂ P h
    rw [hpos_spec (c₁ + c₂) (repD c₁ + repD c₂) hsum_deg hsum_mk hsum_lat, map_add, QuotientAddGroup.mk_add]
  have hposf_zero : posf 0 = 0 := by
    have h0lat : ∀ P ∈ (0 : Divisor L F).support, (∃ i, P ∈ (C i).dom) ∨
        ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
          (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d := fun P hP => by simp at hP
    rw [hpos_spec 0 0 (zero_mem _) (by rw [show (⟨(0 : Divisor L F), zero_mem _⟩ : ↥(Divisor.degZero (K := L) (F := F))) = 0 from rfl, Pic0.mk_zero]; rfl) h0lat,
      map_zero, QuotientAddGroup.mk_zero]
  let pos : ↥T →+ JN := { toFun := posf, map_zero' := hposf_zero, map_add' := hposf_add }

  have hker : ∀ c : ↥T, pos c = 0 → ∃ χ : VN → ℤ, ∀ v, μN (repD c) v = (∑ u, χ u • lapN u) v := by
    intro c hc
    have hmem : μN (repD c) ∈ AddSubgroup.closure (Set.range lapN) := by
      rw [← QuotientAddGroup.eq_zero_iff]; exact hc
    rw [← Submodule.span_int_eq_addSubgroupClosure, Submodule.mem_toAddSubgroup,
      Submodule.mem_span_range_iff_exists_fun] at hmem
    obtain ⟨χ, hχ⟩ := hmem
    exact ⟨χ, fun v => by rw [← hχ]⟩

  obtain ⟨hfinS, hcardS⟩ :=
    AlgebraicCurve.natCard_torsion_tropicalPositionZero_mul_pow_le_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel
      A π hπ hπ0 hrk F n m Fbar hratBar C hratF An An' src tgt xs xt w hpair hw hatt hnodes hcover hdisc hgenus ℓ hℓ N M D ϖN hϖNm hϖNπ
      hκ μN hμNC hμNA hμN0

  have hker_le : Nat.card ↥pos.ker ≤ Nat.card ↥{c : Pic0 L F | ((ℓ ^ N : ℕ) : ℤ) • c = 0 ∧
      ∃ (D : Divisor L F) (hD : D ∈ Divisor.degZero (K := L) (F := F)) (χ : VN → ℤ),
        Pic0.mk ⟨D, hD⟩ = c ∧
        (∀ P ∈ D.support, (∃ i, P ∈ (C i).dom) ∨
          ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
            (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d) ∧
        ∀ v : VN, μN D v = (∑ u, χ u • lapN u) v} := by
    haveI := hfinS
    refine Nat.card_le_card_of_injective (fun c => ⟨((c : ↥T) : Pic0 L F), ?_⟩) ?_
    · obtain ⟨χ, hχ⟩ := hker c.1 c.2
      exact ⟨hTmem c.1, repD c.1, hrepD_deg c.1, χ, hrepD_mk c.1, hrepD_lat c.1, hχ⟩
    · intro c₁ c₂ h
      have hh : ((c₁ : ↥T) : Pic0 L F) = ((c₂ : ↥T) : Pic0 L F) := by simpa using congrArg Subtype.val h
      exact Subtype.ext (Subtype.ext hh)

  have hcardT : Nat.card ↥T = ℓ ^ (2 * genusFF L F * N) := hCOUNT N
  haveI : Finite ↥T := Nat.finite_of_card_ne_zero (by rw [hcardT]; exact pow_ne_zero _ hℓp.ne_zero)
  have hwN' : ∀ e, 0 < ℓ ^ N * w e := fun e => by
    have h1 := hwpos e
    have hw0 : w e ≠ 0 := fun h0 => by rw [h0, mul_zero] at h1; exact lt_irrefl 0 h1
    exact Nat.mul_pos (pow_pos hℓp.pos N) (Nat.pos_of_ne_zero hw0)
  obtain ⟨hfinJ, hcardJ⟩ :=
    AlgebraicCurve.SemistableCovering.natCard_torsion_quotient_lap_mul_pow_le_pow_of_forall_exists_src_mem_iff
      n m src tgt (fun e => ℓ ^ N * w e) hwN' hconn (ℓ ^ N) (pow_pos hℓp.pos N)
  have hSURJ : ∀ x : JN, ((ℓ ^ N : ℕ) : ℤ) • x = 0 → x ∈ pos.range := by
    refine AddMonoidHom.mem_range_of_smul_eq_zero_of_natCard_ker_mul_le_of_natCard_mul_le pos ((ℓ ^ N : ℕ) : ℤ)
      (fun c => ?_) hfinJ ((ℓ ^ N) ^ (m + 1)) ((ℓ ^ N) ^ n) (pow_pos (pow_pos hℓp.pos N) _) ?_ hcardJ
    · exact Subtype.ext (by simpa using hTmem c)
    · rw [← pow_mul, ← pow_mul]
      calc Nat.card ↥pos.ker * ℓ ^ (N * (m + 1))
          ≤ Nat.card ↥{c : Pic0 L F | ((ℓ ^ N : ℕ) : ℤ) • c = 0 ∧
              ∃ (D : Divisor L F) (hD : D ∈ Divisor.degZero (K := L) (F := F)) (χ : VN → ℤ),
                Pic0.mk ⟨D, hD⟩ = c ∧
                (∀ P ∈ D.support, (∃ i, P ∈ (C i).dom) ∨
                  ∃ e, P ∈ (An e).dom ∧ ∃ (d : ℕ) (u : Aˣ) (h : P.evalAt (An e).param ∈ A),
                    (⟨P.evalAt (An e).param, h⟩ : A) = u * ϖN ^ d) ∧
                ∀ v : VN, μN D v = (∑ u, χ u • lapN u) v} * ℓ ^ (N * (m + 1)) :=
            Nat.mul_le_mul_right _ hker_le
        _ ≤ ℓ ^ (N * (2 * genusFF L F + n)) := hcardS
        _ = Nat.card ↥T * ℓ ^ (N * n) := by rw [hcardT, ← pow_add]; congr 1; ring

  have hWW : ∀ e, ℓ ^ N * w e = ℓ ^ b * (ℓ ^ K * w e) := fun e => by
    rw [hNdef, pow_add]; ring
  let ιK : V → VN := Sum.elim (fun i => Sum.inl i) (fun p => Sum.inr ⟨p.1, ⟨ℓ ^ b * (p.2.1 + 1) - 1, by
      have h1 := p.2.2; have h2 : ℓ ^ b * (p.2.1 + 1) < ℓ ^ b * (ℓ ^ K * w p.1) := Nat.mul_lt_mul_of_pos_left (by omega) hbpos
      have h3 : 0 < ℓ ^ b * (p.2.1 + 1) := Nat.mul_pos hbpos (Nat.succ_pos _); have h4 := hWW p.1; omega⟩⟩)
  let ρK : (V → ℤ) →+ (VN → ℤ) := AddMonoidHom.pi fun v' =>
      ∑ v ∈ Finset.univ.filter (fun v => ιK v = v'), Pi.evalAddMonoidHom (fun _ : V => ℤ) v
  obtain ⟨hιinj, hρapp, hρι, hρout, hρsingle, hρlap, hρle⟩ :=
    AlgebraicCurve.SemistableCovering.refine_lap_mem_closure_range_lap_of_forall_eq_mul n m src tgt (fun e => ℓ ^ K * w e) hwpos (ℓ ^ b) hbpos
      (fun e => ℓ ^ N * w e) hWW
  let y : VN → ℤ := ρK t''

  have hy_tor : ((ℓ ^ N : ℕ) : ℤ) • (QuotientAddGroup.mk y : JN) = 0 := by
    let ρbar := QuotientAddGroup.map (AddSubgroup.closure (Set.range lap)) (AddSubgroup.closure (Set.range lapN)) ρK hρle
    have h1 : (QuotientAddGroup.mk y : JN) = ρbar (QuotientAddGroup.mk t'') := by
      show (QuotientAddGroup.mk (ρK t'') : JN) = _
      rw [QuotientAddGroup.map_mk]
    rw [h1, ← map_zsmul, show ((ℓ ^ N : ℕ) : ℤ) = ((ℓ ^ K : ℕ) : ℤ) * ((ℓ ^ b : ℕ) : ℤ) by
      rw [hNdef, pow_add]; push_cast; ring, mul_zsmul, ht''tor, zsmul_zero, map_zero]
  obtain ⟨c, hc⟩ := hSURJ (QuotientAddGroup.mk y) hy_tor
  have hcy : μN (repD c) - y ∈ AddSubgroup.closure (Set.range lapN) := by
    rw [← QuotientAddGroup.eq_iff_sub_mem]
    exact hc
  have hχN : ∃ χN : VN → ℤ, ∀ v, (μN (repD c) - y) v = (∑ u, χN u • lapN u) v := by
    rw [← Submodule.span_int_eq_addSubgroupClosure, Submodule.mem_toAddSubgroup,
      Submodule.mem_span_range_iff_exists_fun] at hcy
    obtain ⟨χ, hχ⟩ := hcy
    exact ⟨χ, fun v => by rw [← hχ]⟩
  obtain ⟨χN, hχN⟩ := hχN
  obtain ⟨D', hD', Pl, hprin, hPl, hann⟩ :=
    FiniteRep.step45sharp A π hπ hπ0 hrk F n m Fbar hratBar C hratF An An' src tgt xs xt w hpair hw hatt hnodes hcover
      hdisc hgenus (ℓ ^ N) (pow_pos hℓp.pos N) ϖN hϖNm hϖN0 hϖNπ (repD c) (hrepD_deg c) (hrepD_lat c)
      μN hμNC hμNA hμN0 y χN (fun v => by have := hχN (Sum.inr v); rwa [Pi.sub_apply] at this)

  have hcls : Pic0.mk ⟨D', hD'⟩ = ((c : ↥T) : Pic0 L F) := by
    rw [← hrepD_mk c]
    apply (QuotientAddGroup.eq).mpr
    rw [AddSubgroup.mem_addSubgroupOf]
    have : -D' + repD c = repD c - D' := by abel
    simpa [this] using hprin

  have hyval : ∀ v' : Σ e : Fin m, Fin (ℓ ^ N * w e - 1), y (Sum.inr v') ≠ 0 →
      ∃ v : Σ e : Fin m, Fin (ℓ ^ K * w e - 1), ιK (Sum.inr v) = Sum.inr v' ∧ y (Sum.inr v') = t (Sum.inr v) := by
    intro v' hy
    by_contra hno
    push_neg at hno
    apply hy
    show ρK t'' (Sum.inr v') = 0
    refine hρout t'' (Sum.inr v') fun v hv => ?_
    rcases v with i | v
    · exact Sum.inl_ne_inr hv
    · exact hno v hv (by show ρK t'' (Sum.inr v') = t (Sum.inr v); rw [← hv, hρι, ht''int])
  have hιval : ∀ (v : Σ e : Fin m, Fin (ℓ ^ K * w e - 1)) (v' : Σ e : Fin m, Fin (ℓ ^ N * w e - 1)),
      ιK (Sum.inr v) = Sum.inr v' → v'.1 = v.1 ∧ (v'.2 : ℕ) + 1 = ℓ ^ b * ((v.2 : ℕ) + 1) := by
    intro v v' h
    have h' : (⟨v.1, ⟨ℓ ^ b * (v.2.1 + 1) - 1, _⟩⟩ : Σ e : Fin m, Fin (ℓ ^ N * w e - 1)) = v' := Sum.inr_injective h
    subst h'
    refine ⟨rfl, ?_⟩
    show ℓ ^ b * (v.2.1 + 1) - 1 + 1 = ℓ ^ b * (v.2.1 + 1)
    have : 0 < ℓ ^ b * (v.2.1 + 1) := Nat.mul_pos hbpos (Nat.succ_pos _)
    omega

  have hPl_coarse : ∀ (v : Σ e : Fin m, Fin (ℓ ^ K * w e - 1)) (v' : Σ e : Fin m, Fin (ℓ ^ N * w e - 1)),
      ιK (Sum.inr v) = Sum.inr v' →
        Pl v' ∈ (An v.1).dom ∧ ∃ h : (Pl v').evalAt (An v.1).param ∈ A,
          (⟨(Pl v').evalAt (An v.1).param, h⟩ : A) = (1 : Aˣ) * ϖ ^ ((v.2 : ℕ) + 1) ∧
          μ (Finsupp.single (Pl v') 1) = Pi.single (Sum.inr v) 1 := by
    intro v v' h
    obtain ⟨he, hj⟩ := hιval v v' h
    obtain ⟨hdom, hval⟩ := hPl v'
    have hdom' : Pl v' ∈ (An v.1).dom := he ▸ hdom
    have key : ∀ (e : Fin m), v'.1 = e → (Pl v').evalAt (An e).param = ((ϖN ^ ((v'.2 : ℕ) + 1) : A) : L) := by
      intro e he'; subst he'; exact hval
    have hval' : (Pl v').evalAt (An v.1).param = ((ϖ ^ ((v.2 : ℕ) + 1) : A) : L) := by
      rw [key v.1 he, hj, pow_mul, hϖNb]
    have hmem : (Pl v').evalAt (An v.1).param ∈ A := by rw [hval']; exact (ϖ ^ ((v.2 : ℕ) + 1)).2
    have hlat : (⟨(Pl v').evalAt (An v.1).param, hmem⟩ : A) = (1 : Aˣ) * ϖ ^ ((v.2 : ℕ) + 1) :=
      Subtype.ext (by rw [Units.val_one, one_mul]; exact hval')
    refine ⟨hdom', hmem, hlat, ?_⟩
    have hv2 := v.2.isLt
    rw [hμA v.1 (Pl v') hdom' ((v.2 : ℕ) + 1) 1 hmem hlat (Nat.succ_pos _) (by omega)]
    congr 2

  let D'a : Divisor L F := ∑ v' : (Σ e : Fin m, Fin (ℓ ^ N * w e - 1)), y (Sum.inr v') • Finsupp.single (Pl v') 1
  have hD'a_mem : ∀ P, D'a P ≠ 0 → ∃ v' : (Σ e : Fin m, Fin (ℓ ^ N * w e - 1)), P = Pl v' ∧ y (Sum.inr v') ≠ 0 := by
    intro P hP
    have hP' : P ∈ D'a.support := Finsupp.mem_support_iff.mpr hP
    have h1 := Finsupp.support_finsetSum
      (s := (Finset.univ : Finset (Σ e : Fin m, Fin (ℓ ^ N * w e - 1))))
      (f := fun v' => y (Sum.inr v') • Finsupp.single (Pl v') 1) hP'
    simp only [Finset.mem_biUnion, Finset.mem_univ, true_and] at h1
    obtain ⟨v', hv'⟩ := h1
    have hy : y (Sum.inr v') ≠ 0 := by
      intro h0; rw [h0, zero_smul] at hv'; simp at hv'
    exact ⟨v', Finset.mem_singleton.mp (Finsupp.support_single_subset (Finsupp.support_smul hv')), hy⟩
  have hD'a_ann : ∀ P, D'a P ≠ 0 → ∃ e, P ∈ (An e).dom := by
    intro P hP
    obtain ⟨v', rfl, -⟩ := hD'a_mem P hP
    exact ⟨v'.1, (hPl v').1⟩

  have hchart : ∀ v₀ : Σ e : Fin m, Fin (ℓ ^ K * w e - 1), μ (D' - D'a) (Sum.inr v₀) = 0 := by
    intro v₀
    have hsum : D' - D'a = ∑ P ∈ (D' - D'a).support, Finsupp.single P ((D' - D'a) P) := (Finsupp.sum_single _).symm
    rw [hsum, map_sum, Finset.sum_apply]
    refine Finset.sum_eq_zero fun P hP => ?_
    have hP0 : (D' - D'a) P ≠ 0 := Finsupp.mem_support_iff.mp hP
    rcases hcover P with ⟨i, hi, -, -⟩ | ⟨e, he, -, -⟩
    · rw [← Finsupp.smul_single_one, map_zsmul, hμC i P hi]
      simp [Pi.single_apply]
    · exact absurd (by rw [Finsupp.sub_apply, hann e P he]; exact sub_self _) hP0

  have hannμ : ∀ v₀ : Σ e : Fin m, Fin (ℓ ^ K * w e - 1), μ D'a (Sum.inr v₀) = t (Sum.inr v₀) := by
    intro v₀
    obtain ⟨v₀', hv₀'⟩ : ∃ v₀' : Σ e : Fin m, Fin (ℓ ^ N * w e - 1), ιK (Sum.inr v₀) = Sum.inr v₀' := ⟨_, rfl⟩
    show μ (∑ v', y (Sum.inr v') • Finsupp.single (Pl v') 1) (Sum.inr v₀) = t (Sum.inr v₀)
    rw [map_sum, Finset.sum_apply, Finset.sum_eq_single v₀']
    · obtain ⟨-, -, -, hμv⟩ := hPl_coarse v₀ v₀' hv₀'
      rw [map_zsmul, hμv, Pi.smul_apply, Pi.single_eq_same, smul_eq_mul, mul_one]
      show ρK t'' (Sum.inr v₀') = t (Sum.inr v₀)
      rw [← hv₀', hρι, ht''int]
    · intro v' _ hne
      rw [map_zsmul, Pi.smul_apply, smul_eq_mul]
      by_cases hy : y (Sum.inr v') = 0
      · rw [hy, zero_mul]
      · obtain ⟨v, hv, -⟩ := hyval v' hy
        obtain ⟨-, -, -, hμv⟩ := hPl_coarse v v' hv
        rw [hμv, Pi.single_apply, if_neg, mul_zero]
        intro hvv
        apply hne
        have : Sum.inr v' = ιK (Sum.inr v₀) := by rw [← hv, ← Sum.inr_injective hvv.symm]
        exact Sum.inr_injective (this.trans hv₀')
    · intro h; exact absurd (Finset.mem_univ v₀') h
  refine ⟨D', hD', 0, ⟨N, ?_⟩, ?_, ?_⟩
  · rw [hcls]; exact hTmem c
  · intro P hP
    rcases hcover P with ⟨i, hi, -, -⟩ | ⟨e, he, -, -⟩
    · exact Or.inl ⟨i, hi⟩
    · right
      have hPa : D'a P ≠ 0 := by rw [← hann e P he]; exact Finsupp.mem_support_iff.mp hP
      obtain ⟨v', rfl, hy⟩ := hD'a_mem P hPa
      obtain ⟨v, hv, -⟩ := hyval v' hy
      obtain ⟨hdom, hmem, hlat, -⟩ := hPl_coarse v v' hv
      exact ⟨v.1, hdom, (v.2 : ℕ) + 1, 1, hmem, hlat⟩
  · intro v₀
    have : μ D' (Sum.inr v₀) = t (Sum.inr v₀) := by
      rw [show D' = (D' - D'a) + D'a by abel, map_add, Pi.add_apply, hchart, hannμ, zero_add]
    rw [this, sub_self]
    simp

end S_AlgebraicCurve_exists_pow_zsmul_mk_eq_zero_forall_mu_sub_eq_sum_smul_lap_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel
end P2MW
export P2MW.S_AlgebraicCurve_exists_pow_zsmul_mk_eq_zero_forall_mu_sub_eq_sum_smul_lap_of_semistableCovering_of_discFibres_of_rankOne_of_charZero_of_semistableModel (solution)
