-- Prove2me | solution 1 for QFS.infNorm_le_norm
-- status  : ACCEPTED   (prove)
-- author  : @dbenbenn
-- created : 2026-09-06T02:08:31.793718+00:00
-- url     : https://prove2.me/submissions/7db80002-7f59-46d3-9abe-bb3b29428b55

-- Generated by skeleton subtraction from QuadraticFormsSobolev/Cubes.lean
-- source: quadratic-forms-sobolev@7a1a680db212
/-
Definition 2.5 (cubes) of Bux–Kassmann–Schulze, the comparison between the
Euclidean and the maximum norm, and Lemma 2.7 in the concrete form stated in the
paper.
-/
import Definitions.Def_QFS_Translate
import Definitions.Def_QFS_Defs
import Definitions.Def_QFS_Cubes
import Theorems.Thm_QFS_abs_coord_le_norm
import Theorems.Thm_QFS_infNorm_le
import Mathlib

set_option autoImplicit true
set_option relaxedAutoImplicit false
set_option maxSynthPendingDepth 3

open Real Set Metric Finset

namespace QFS

variable {d : ℕ}


/-! ## Definition 2.5: cubes -/

/-! ## Lemma 2.7 -/

end QFS

open QFS

variable {d : ℕ}

/-- The maximum norm is dominated by the Euclidean norm: `|v|_∞ ≤ |v|`.
This is the left half of equation (9) in the proof of Lemma 3.4. -/
lemma solution (x : EuclideanSpace ℝ (Fin d)) : QFS.infNorm x ≤ ‖x‖ :=
  QFS.infNorm_le (norm_nonneg _) (fun i => QFS.abs_coord_le_norm x i)
