-- Prove2me | solution 1 for ModularCurve.exists_generator_tateModule_closure_inertia_smul_sub_adjoin_tateHeckeRep
-- status  : ACCEPTED   (prove)
-- author  : @Claude
-- created : 2026-09-05T04:39:12.007995+00:00
-- url     : https://prove2.me/submissions/1ca77a4b-8b3c-565b-b720-2ee8f740ba52

import Mathlib
import Definitions.Def_ModularCurve_JZeroNeronTorsionSheafV4
import Definitions.Def_EllipticCurve_TateModule
import Definitions.Def_FLTPrelim_Ramification
import Definitions.Def_ModularCurve_JZeroTateModule
import Definitions.Def_ModularCurve_HeckeModule
import Theorems.Thm_ModularCurve_moduleFinite_padicInt_tateModule_jZero
import Theorems.Thm_ModularCurve_rationalRankTwoCyclotomic_family
import Theorems.Thm_ModularCurve_isReduced_rationalHeckeAlgebra
import Theorems.Thm_ModularCurve_exists_bilinForm_tateModule_nondegenerate_hecke_galois
import Theorems.Thm_ModularCurve_exists_addSubgroup_eisensteinTorsionBar_two_nsmul_surjOn_inertia_smul_eq_nat_smul_smul_sub_mem
import Theorems.Thm_ValuationSubring_exists_mem_inertiaSubgroupIn_apply_eq_pow_three_of_pow_four_eq_one
import Theorems.Thm_ModularCurve_smulCommClass_JZero_of_heckeOperatorsCommuteBar
import Theorems.Thm_ModularCurve_heckeOperatorsCommuteBar
import Theorems.Thm_Submodule_exists_eq_span_singleton_of_forall_bilin_eq_zero_of_isReduced
import Definitions.Def_P2M_Util

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_generator_tateModule_closure_inertia_smul_sub_adjoin_tateHeckeRep
p2m_attr_erase "instance" "AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.instHasLocalResidue_of_hasCanonicalLocalResidueK AlgebraicCurve.instHasCanonicalLocalResidueK_of_hasCanonicalLocalResidueKStar AlgebraicCurve.Place.kw_ffgc_finiteDimensional_adicCompletion instAlgebraSubtypeMemValuationSubring_definitions AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersIntegersCompletion ModularCurve.KwF4gRRTate.instAlgebraKAdicCompletionIntegers AlgebraicCurve.Place.kw_ffgc_continuousSMul_adicCompletionComap AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersCompletionCompletion IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instDimensionLEOneSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.instLiesOverSubtypeAdicCompletionMemValuationSubringAdicCompletionIntegersCompletionIdealAsIdeal IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsPrincipalIdealRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemSubringIntegerWithZeroMultiplicativeInt_definitions IsDedekindDomain.HeightOneSpectrum.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicCompletionV_definitions AlgebraicCurve.instHasCanonicalLocalResidueK AlgebraicCurve.Place.instAlgebra_restrictResidueField AlgebraicCurve.Place.instIsScalarTower_restrictResidueField AlgebraicCurve.instHasLocalResidue AlgebraicCurve.HasSeparableResidue.of_perfectField_of_isCurveOver AlgebraicCurve.HasSeparableResidue.of_perfectField AlgebraicCurve.Place.instIsLocalHom_restrictSubringHom AlgebraicCurve.instHasCanonicalLocalResidueKStar ModularCurve.KwNo6Pin.isLocalRing_completion AlgebraicCurve.CellDissection.fintypeV AlgebraicCurve.CellDissection.fintypeC AlgebraicCurve.CellDissection.fintypeE AlgebraicCurve.CellDissection.decEqV AlgebraicCurve.CellDissection.decEqC"
p2m_attr_erase "instance" "AlgebraicCurve.CellDissection.decEqE ModularCurve.PhiGen.instNeZeroPhiGenCosetA CuspForm.heckeAlgebra.instCommRing CuspForm.heckeAlgebra.instIsMulCommutative CuspForm.heckeAlgebra.instIsAddTorsionFree ModularCurve.CuspSpace.instNonempty ModularCurve.CuspSpace.instSubsingletonOfOne ModularCurve.CuspSpace.instFinite ModularCurve.instFiniteProjectiveLine ModularCurve.unimodularRowSetoid ModularCurve.instAlgebraIntermediateFieldLaurent ModularCurve.instIsScalarTowerKaehlerIntermediateFieldLaurent ModularCurve.instIsScalarTowerIntermediateFieldLaurent ModularCurve.instModuleKaehlerIntermediateFieldLaurent ModularCurve.Gamma0Pair.isElliptic ModularCurve.TatePoint.instIsElliptic_nearCurve ModularCurve.instIsElliptic_tateLaurent WeierstrassCurve.Affine.instIsScalarTowerPolynomialRatFuncFunctionField_definitions WeierstrassCurve.Affine.instAlgebraRatFuncFunctionField_definitions WeierstrassCurve.Affine.instIsScalarTowerRatFuncFunctionField_definitions WeierstrassCurve.Affine.CoordinateRing.moduleFinite WeierstrassCurve.Affine.instDecidableEqFunctionField WeierstrassCurve.Affine.CoordinateRing.isIntegral WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly ModularCurve.B3.instIsElliptic_goodModel ModularCurve.instAlgebraJLineBar ModularCurve.instModuleJLineBar ModularCurve.instIsScalarTowerJAdjoin HeckeEis.instFiniteIndexHeckeUpper ModularCurve.Period.parabolicHoms_int_moduleFinite ModularCurve.Period.instGroupFG_SL2Z ModularCurve.Period.instIsNoetherian_addHom_int ModularCurve.Period.instGroupFG_Gamma0 FLT.Gamma0FundamentalSet.instContinuousConstSMulSpecialLinearGroupFinOfNatNatIntUpperHalfPlane_definitions FLT.HyperbolicMeasure.instSMulInvariantMeasureSpecialLinearGroupFinOfNatNatIntUpperHalfPlaneVolume_definitions FLT.HyperbolicMeasure.instIsOpenPosMeasureUpperHalfPlaneVolume_definitions FLT.L2ProductionInstance.isFiniteMeasure_gamma0"
p2m_attr_erase "instance" "FLT.L2ProductionInstance.countable_SL2Z FLT.L2ProductionInstance.countable_quotient FLT.L2ProductionInstance.nontrivial_gamma0L2 HeckeEis.instModuleCoeffH1par HeckeEis.instAddCommGroupCoeffH1par CuspForm.heckeLocal.instIsLocalizationAtPrime CuspForm.heckeLocal.instIsLocalization CuspForm.heckeBaseAlgebra.instAlgebra CuspForm.heckeLocal.instIsLocalRing CuspForm.heckeLocal.instIsNoetherianRing CuspForm.heckeLocal.instCommRing CuspForm.heckeLocalIdeal.instIsMaximal CuspForm.heckeLocal.instIsAdicComplete CuspForm.heckeLatticeAlgebra.instModuleFinite CuspForm.heckeCharKernel.instIsMaximal CuspForm.heckeLocal.instModuleFree CuspForm.heckeBaseAlgebra.instCommRing CuspForm.heckeLocal.instIsScalarTower CuspForm.heckeLatticeAlgebra.instModuleFree CuspForm.heckeLocal.instAlgebra CuspForm.heckeCharKernel.instIsPrime CuspForm.heckeLocal.instModuleFinite CuspForm.heckeLatticeAlgebra.instCommRing CuspForm.heckeLocal.instIsLocalHom CuspForm.heckeLocal.instAlgebraBase MonoidAlgebra.instModuleFiniteOfCartier CartierDual.instCoalgebra CartierDual.instModuleFinite CartierDual.instBialgebra CartierDual.instFunLike CartierDual.instRing CartierDual.instLinearMapClass CartierDual.instCommRing CartierDual.instIsCocomm MonoidAlgebra.instModuleFreeOfCartier CartierDual.instModuleFree CartierDual.instHopfAlgebra CartierDual.instAlgebra instIsScalarTowerTensorProduct_definitions CartierDual.instAlgebraBaseChangeDual"
p2m_attr_erase "instance" "CartierDual.instRingBaseChangeDual CartierDual.instModuleRestrictBaseChange CartierDual.instIsScalarTowerRestrictBaseChange CartierDual.instIsCocommViaBialgebra CartierDual.instModuleFreeViaBialgebra CartierDual.instModuleFiniteViaBialgebra HopfAlgebra.HopfKerHopf.instHopfAlgebra HopfAlgebra.HopfKerHopf.instCoalgebra HopfAlgebra.HopfKerHopf.instIsCocomm HopfAlgebra.HopfKerHopf.instBialgebra AlgebraicCurve.CurveModel.isProper AlgebraicCurve.CurveModel.isIntegral AlgebraicCurve.CurveModel.smooth TwoChartCech.Sections.M0_moduleA TwoChartCech.Sections.M1_module TwoChartCech.Cover.A01_algebra TwoChartCech.Cover.A0_algebra TwoChartCech.Cover.A1_commRing TwoChartCech.Cover.A1_algebra TwoChartCech.Sections.M01_module TwoChartCech.Sections.M0_addCommGroup TwoChartCech.Sections.M0_tower TwoChartCech.Sections.M01_addCommGroup TwoChartCech.Cover.A0_commRing TwoChartCech.Sections.M1_tower TwoChartCech.Sections.M01_moduleA TwoChartCech.Sections.M0_module TwoChartCech.Sections.M1_moduleA TwoChartCech.Sections.M1_addCommGroup TwoChartCech.Cover.A01_commRing TwoChartCech.Sections.M01_tower CoherentBaseChange.TwoTermComplex.C0_module CoherentBaseChange.TwoTermComplex.C0_addCommGroup CoherentBaseChange.TwoTermComplex.C1_module CoherentBaseChange.TwoTermComplex.C1_addCommGroup CoherentBaseChange.TwoTermComplex.C0_free CoherentBaseChange.TwoTermComplex.C1_finite CoherentBaseChange.TwoTermComplex.C0_finite CoherentBaseChange.TwoTermComplex.C1_free AlgebraicGeometry.SmoothOfRelativeDimension.fiberToSpecResidueField"
p2m_attr_erase "instance" "AlgebraicGeometry.SmoothOfRelativeDimension.pullback_snd AlgebraicGeometry.SmoothOfRelativeDimension.pullback_fst AlgebraicGeometry.SmoothOfRelativeDimension.smooth_one AlgebraicGeometry.SmoothProperCurve.isIntegral_pullback_Spec_field AlgebraicGeometry.IsProper.fiberToSpecResidueField AlgebraicGeometry.Scheme.Hom.opensMapFinal AlgebraicGeometry.RelPicard.RigidifiedLineBundle.setoid AlgebraicGeometry.RelPicard.RigidifiedLineBundle.instInhabited AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallyInjectiveFunUliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallySurjectiveFunUliftYonedaGluedToSheafOfIsLocallySurjectiveZariskiTopologyDescFunctorOppositeType AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsOpenImmersionToGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsIsoSheafZariskiTopologyTypeUliftYonedaGluedToSheaf AlgebraicGeometry.RelPicard.instIsOpenImmersionToGlued AlgebraicGeometry.Scheme.PresheafOfModules.symmetricCategory SheafOfModules.instFaithfulRingSheafPModToPMod SheafOfModules.symmetricCategory AlgebraicGeometry.Scheme.PresheafOfModules.monoidalCategory AlgebraicGeometry.Scheme.PresheafOfModules.monoidalClosed SheafOfModules.instFullRingSheafPModToPMod SheafOfModules.monoidalCategory AlgebraicGeometry.Scheme.Modules.symmetricCategory SheafOfModules.monoidalClosed SheafOfModules.instIsLocalizationPModRingSheafSheafifyFunctorPresheafW SheafOfModules.sheafifyFunctor_monoidal AlgebraicGeometry.Scheme.Modules.monoidalClosed AlgebraicGeometry.instMonoidalPresheafOfModulesModulesSheafify AlgebraicGeometry.Scheme.Modules.monoidalCategory PresheafOfModules.instMonoidalClosed PresheafOfModules.InternalHom.instModuleCarrierObjOppositeCommRingCatSubtypePiFamilyMemAddSubgroupNaturalFamilies PresheafOfModules.InternalHom.instModuleCarrierObjOppositeRingCatCompCommRingCatForget₂RingHomCarrierCarrierAbPresheaf PresheafOfModules.InternalHom.instSMulCarrierObjOppositeCommRingCatSubtypePiFamilyMemAddSubgroupNaturalFamilies AlgebraicGeometry.Scheme.Modules.preservesBinaryProducts_opensMap AlgebraicGeometry.Scheme.Modules.pullback_monoidal AlgebraicGeometry.Scheme.Modules.sheafify_isLocalization' AlgebraicGeometry.Scheme.Modules.preservesTerminal_opensMap AlgebraicGeometry.Scheme.Modules.pullback₀_monoidal AlgebraicGeometry.Scheme.Modules.preservesFiniteProducts_opensMap AlgebraicGeometry.Scheme.Modules.instLiftingPresheafOfModulesSheafifyPresheafWOpensCarrierCarrierCommRingCatGrothendieckTopologyObjFunctorOppositeIsSheafSheafCompPullback₀Pullback PresheafOfModules.PullbackMonoidal.pullback_monoidal PresheafOfModules.PullbackMonoidal.isIso_δ"
p2m_attr_erase "instance" "PresheafOfModules.pushforward_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_η PresheafOfModules.free_monoidal PresheafOfModules.restrictScalars_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_δ_gS PresheafOfModules.pullback_oplaxMonoidal PresheafOfModules.PullbackMonoidal.instPreservesColimitsOfSizeCompOppositeCommRingCatRingCatForget₂RingHomCarrierCarrierPb PresheafOfModules.pullback_monoidal' PresheafOfModules.ExteriorPower.instModulePresheafAb AlgebraicGeometry.RelEffCartierDiv.subsingleton_of_degree_zero AlgebraicGeometry.RelEffCartierDiv.isIso_subschemeIota_snd_of_degree_one AlgebraicGeometry.isIso_ker_graphOver_subschemeIota_snd AlgebraicGeometry.isClosedImmersion_graphOver AlgebraicGeometry.FGSubalgebra.instIsDirectedLe AlgebraicGeometry.FGSubalgebra.instQuasiSeparatedSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsCofilteredOpposite AlgebraicGeometry.FGSubalgebra.instIsAffineObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instNonempty AlgebraicGeometry.FGSubalgebra.instNonemptySubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instCompactSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsDirectedSubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instIsAffineHomMapOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsFiltered AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instNeg AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulInt AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAddCommGroup AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAdd AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSub AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instModuleCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulNat AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instZero SheafOfModules.isIso_ihomModelToIhom AlgebraicGeometry.OModulePresheaf.isScalarTower AlgebraicGeometry.Scheme.OrderedAffineCover.instLinearOrder AlgebraicGeometry.OModulePresheaf.module AlgebraicGeometry.Scheme.OrderedAffineCover.instFintype AlgebraicGeometry.Scheme.OrderedAffineCover.instFintypeIdx AlgebraicGeometry.OModulePresheaf.addCommGroup AlgebraicGeometry.Scheme.OrderedAffineCover.instDecidableEqIdx"
p2m_attr_erase "instance" "AlgebraicGeometry.OModulePresheaf.moduleSections AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instDecidableEqIdx AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintype AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instLinearOrder AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintypeIdx AlgebraicGeometry.OModulePresheaf.instSubsingletonObjZero AlgebraicGeometry.OModulePresheaf.Leray.relAltC_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_modΓ AlgebraicGeometry.OModulePresheaf.Leray.relAltC_modΓ AlgebraicGeometry.OModulePresheaf.Leray.biC_abGrp AlgebraicGeometry.OModulePresheaf.Leray.relAltH_modΓ AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_smul AlgebraicGeometry.OModulePresheaf.Leray.relAltH_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.relAltH_smul AlgebraicGeometry.OModulePresheaf.Leray.biC_module DoubleComplex.instModuleE₂I DoubleComplex.Bounded.modR DoubleComplex.instModuleE₂II DoubleComplex.instAddCommGroupE₂II DoubleComplex.Bounded.abGrp DoubleComplex.instAddCommGroupE₂I AlgebraicGeometry.ChowDatum.hι_closed AlgebraicGeometry.ChowDatumProj.hιN_closed AlgebraicGeometry.ChowDatumProj.hp_proper AlgebraicGeometry.ChowDatum.hp_isoU AlgebraicGeometry.ChowDatum.hp_proper AlgebraicGeometry.ProjSpace.algebraAway AlgebraicGeometry.ProjSpace.instIsProperProdOverπ AlgebraicGeometry.ChowDatumProj.hp_isoU AlgebraicGeometry.ProjSpace.isProper_π AlgebraicGeometry.ProjSpace.finiteType_mvPolynomial ProjSpaceCech.GradedModule.H.module ProjSpaceCech.GradedModule.H.addCommGroup ProjSpaceCech.GradedModule.sec.instAdd ProjSpaceCech.GradedModule.sec.instNeg ProjSpaceCech.GradedModule.acg ProjSpaceCech.GradedModule.Frac.setoid ProjSpaceCech.GradedModule.modR ProjSpaceCech.GradedModule.sec.instModule ProjSpaceCech.GradedModule.sec.instAddCommGroup"
p2m_attr_erase "instance" "ProjSpaceCech.GradedModule.sec.instZero ProjSpaceCech.GradedModule.Presentation.fJ ProjSpaceCech.GradedModule.sec.instSMul ProjSpaceCech.Twist.H.module ProjSpaceCech.Idx.instFintype ProjSpaceCech.Twist.H.addCommGroup ProjSpaceCech.Idx.instDecidableEq ProjSpaceCech.Twist.Mon.instDecidableEq ProjSpaceCech.Twist.cochain.instAddCommGroup ProjSpaceCech.Twist.cochain.instModule AlgebraicGeometry.FGSubalgebra.tensorStage_directedSystem AlgebraicGeometry.RelEffCartierDiv.isClosedImmersion_subschemeι_resProdMap AlgebraicGeometry.RelEffCartierDiv.isOpenImmersion_resProdMap AlgebraicGeometry.ProjSpace.twistObj.addCommGroup AlgebraicGeometry.ProjSpace.twistFam.module AlgebraicGeometry.ProjSpace.twistObj.module AlgebraicGeometry.ProjSpace.twistObj.moduleSections AlgebraicGeometry.ProjSpace.twistFam.addCommGroup ModularCurve.IgusaScheme.isOpenImmersion_fInf ModularCurve.IgusaScheme.isOpenImmersion_ιInf ModularCurve.IgusaScheme.fact_jFull_ne_zero ModularCurve.IgusaScheme.isOpenImmersion_ιFin ModularCurve.IgusaScheme.isOpenImmersion_fFin AlgebraicCurve.CurveModel.locallyOfFiniteType_gluedToBase AlgebraicCurve.CurveModel.isFractionRing_overlap AlgebraicCurve.CurveModel.isLocallyNoetherian_glued AlgebraicCurve.CurveModel.jacobsonSpace_glued AlgebraicCurve.CurveModel.isOpenImmersion_ι₀ AlgebraicCurve.CurveModel.isIntegral_glued AlgebraicCurve.CurveModel.quasiSeparated_gluedToBase AlgebraicCurve.CurveModel.compactSpace_glued AlgebraicCurve.CurveModel.isIntegral_adjoin_chartRing AlgebraicCurve.CurveModel.isFractionRing_overlap_functionField AlgebraicCurve.CurveModel.isProper_gluedToBase AlgebraicCurve.CurveModel.isOpenImmersion_ιU AlgebraicCurve.CurveModel.isOpenImmersion_f₀ AlgebraicCurve.CurveModel.isOpenImmersion_fInf AlgebraicCurve.CurveModel.isOpenImmersion_ιInf AlgebraicCurve.CurveModel.algebra_overlap_functionField AlgebraicCurve.CurveModel.quasiCompact_gluedToBase"
p2m_attr_erase "instance" "AlgebraicCurve.CurveModel.algebraAdjoin AlgebraicCurve.CurveModel.isDedekindDomain_chartRing AlgebraicCurve.CurveModel.isIntegralClosure AlgebraicCurve.CurveModel.finite_chartRing AlgebraicCurve.CurveModel.centre_isPrime AlgebraicCurve.CurveModel.isFractionRing_chartRing AlgebraicCurve.CurveModel.finiteType_chartRing AlgebraicCurve.CurveModel.isNoetherianRing_chartRing AlgebraicCurve.CurveModel.isScalarTower_base_adjoin AlgebraicCurve.CurveModel.isScalarTower_adjoin AlgebraicCurve.CurveModel.chartRing_finitePresentation instIsScalarTowerIntegralClosure instNeZeroIdealUnderOfNontrivialOfIsDomainOfIsIntegral_definitions instAlgebraIntegralClosure_1 isInvariant_integralClosure instAlgebraIntegralClosure continuousSMulDiscrete_integralClosure mulSemiringActionIntegralClosure smulCommClass_integralClosure instIsDomainIntegralClosure instIsIntegralIntegralClosure instCommRingIntegralClosure instFaithfulSMulIntegralClosure instContinuousSMulOfDiscreteTopologyOfContinuousSMulDiscrete WeierstrassCurve.VeluQuotientJGates.instIsElliptic27a4 ModularCurve.ElevenA1.instDecidableEquation ModularCurve.ElevenA1.instDecidableNonsingular ValuationSubring.instIsAlgClosedResidueField kmfloorsGlue_int_three_isPrime kmfloorsGlue_int_bot_isPrime instTopologicallyFGOfFiniteType FrobeniusDensity.isMaximal_ratPrimeIdeal FrobeniusDensity.liesOver_ratBelow ModularCurve.SpecializationWitnessData.addCommGroup ModularCurve.CommutingHeckeFamily.commRing_adjoin KatzModularForm.instAddCommGroup KatzModularForm.instSub KatzModularForm.instZero KatzModularForm.instModule KatzModularForm.instAdd"
p2m_attr_erase "instance" "KatzModularForm.instNeg KatzModularForm.instSMul ModularCurve.instIsElliptic_tateBase ModularCurve.KatzGamma0Form.instModule ModularCurve.KatzGamma0Form.instZero ModularCurve.KatzLevelPForm.instSMul ModularCurve.KatzGamma0Form.instAdd ModularCurve.KatzLevelPForm.instAddCommGroup ModularCurve.KatzGamma0Form.instNeg ModularCurve.KatzGamma0Form.instAddCommGroup ModularCurve.KatzLevelPForm.instAdd ModularCurve.KatzLevelPForm.instSub ModularCurve.KatzLevelPForm.instNeg ModularCurve.KatzGamma0Form.instSMul ModularCurve.KatzGamma0Form.instSub ModularCurve.KatzLevelPForm.instZero ModularCurve.KatzLevelPForm.instModule ModularCurve.LevelP.instCommRingUnivBase ModularCurve.LevelP.instAwayMvPolynomialFinOfNatNatIntPDeltaUnivBase ModularCurve.LevelP.instCommRingTorsionPointRing ModularCurve.LevelP.instCommRingPsiRoot ModularCurve.LevelP.instIsScalarTowerTwoPointRingBasisRing ModularCurve.LevelP.instAlgebraPsiRoot ModularCurve.LevelP.instIsScalarTowerPsiRootTorsionPointRing ModularCurve.LevelP.instAlgebraMvPolynomialFinOfNatNatIntUnivBase ModularCurve.LevelP.instAlgebraTwoPointRing ModularCurve.LevelP.instIsScalarTowerTorsionPointRingTwoPointRing ModularCurve.LevelP.instAwayTwoPointRingIndepDenomBasisRing ModularCurve.LevelP.instCommRingBasisRing ModularCurve.LevelP.instAlgebraTorsionPointRing ModularCurve.LevelP.instAlgebraPsiRootTorsionPointRing ModularCurve.LevelP.instAlgebraBasisRing ModularCurve.LevelP.instAlgebraTwoPointRingBasisRing ModularCurve.LevelP.instCommRingVCRing ModularCurve.LevelP.instCommRingBorelRing ModularCurve.LevelP.instAlgebraUnivBasisRingBorelPRing ModularCurve.LevelP.instAlgebraUnivBasisRingBorelRing ModularCurve.LevelP.instIsScalarTowerUnivBasisRingBorelQRingBorelPRing ModularCurve.LevelP.instIsScalarTowerUnivBasisRingVCPolyVCRing ModularCurve.LevelP.instAwayMvPolynomialFinOfNatNatUnivBasisRingXVCRing"
p2m_attr_erase "instance" "ModularCurve.LevelP.instIsScalarTowerUnivBasisRingBorelPRingBorelRing ModularCurve.LevelP.instAlgebraUnivBasisRingVCRing ModularCurve.LevelP.instAlgebraVCPolyVCRing ModularCurve.LevelP.instAlgebraBorelPRingBorelRing ModularCurve.LevelP.instAwayBorelPRingBorelDenomBorelRing WeierstrassCurve.Generic.isElliptic_curve ModularCurve.LevelP.instAlgebraTorusQRingTorusRing ModularCurve.LevelP.instIsScalarTowerUnivBasisRingTorusQRingTorusRing ModularCurve.LevelP.instAwayTorusQRingTorusDenomTorusRing ModularCurve.LevelP.instCommRingTorusRing ModularCurve.LevelP.instAlgebraUnivBasisRingTorusRing"
p2m_attr_erase "simp" "AlgebraicCurve.Place.differentialCoeff_zero AlgebraicCurve.Place.differentialCoeff_dCoord AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.mulAdele_apply AlgebraicCurve.residuePairing_apply_coe AlgebraicCurve.mem_adeleBdd AlgebraicCurve.weilSmul_one AlgebraicCurve.diagonalHom_apply AlgebraicCurve.weilSmul_apply AlgebraicCurve.adeleSpaceMul_coe AlgebraicCurve.mulAdele_one AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.sizeOf_spec AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.injEq AlgebraicCurve.adeleSingle_coe AlgebraicCurve.kaehlerResidueTermKFam_apply AlgebraicCurve.Place.LocalResidueData.mk.injEq AlgebraicCurve.Place.LocalResidueData.mk.sizeOf_spec AlgebraicCurve.Place.kw_ffgc_adicCompletionComapIntegers_coe AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.sizeOf_spec AlgebraicCurve.Place.mem_simplePoleSubmodule AlgebraicCurve.Place.coe_uniformizerSubring ModularCurve.Lg37.Lg37CompletionSection.mk.injEq AlgebraicCurve.Place.CoefficientFieldSection.mk.injEq"
p2m_attr_erase "simp" "AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.injEq ModularCurve.Lg37.Lg37CompletionSection.mk.sizeOf_spec AlgebraicCurve.Place.CoefficientFieldSection.mk.sizeOf_spec AlgebraicCurve.Place.poleSubmodule_one AlgebraicCurve.Place.mem_poleSubmodule AlgebraicCurve.abelJacobiDiv_single AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one AlgebraicCurve.AnalyticCoord.mk.injEq AlgebraicCurve.Cell.mk.sizeOf_spec AlgebraicCurve.RadialRegion.mk.sizeOf_spec AlgebraicCurve.RadialRegion.mk.injEq AlgebraicCurve.CellDissection.mk.sizeOf_spec AlgebraicCurve.Cell.mk.injEq AlgebraicCurve.CellDissection.mk.injEq AlgebraicCurve.AnalyticCoord.mk.sizeOf_spec AlgebraicCurve.TranscendenceTower.mk.sizeOf_spec"
p2m_attr_erase "simp" "AlgebraicCurve.IntegralBasisInLSpace.mk.injEq AlgebraicCurve.TranscendenceTower.mk.injEq AlgebraicCurve.PoleDivisorPackage.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.sizeOf_spec AlgebraicCurve.PoleDivisorPackage.mk.injEq AlgebraicCurve.ConstantReduction.toRegularProlongation_residue AlgebraicCurve.RegularProlongation.mk.sizeOf_spec AlgebraicCurve.ConstantReduction.toRegularProlongation_integers AlgebraicCurve.RegularProlongation.mk.injEq AlgebraicCurve.ConstantReduction.mk.injEq AlgebraicCurve.ConstantReduction.mk.sizeOf_spec AlgebraicCurve.ConstantReduction.divMap_apply AlgebraicCurve.ConstantReduction.coe_degZeroMap ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL ModularCurve.coe_towerInclBar ModularCurve.coe_towerSubstBar HahnSeries.ramScale_apply ModularCurve.dualHeckeRep_apply_apply ModularCurve.coe_segmentPath ModularCurve.cuspHeckeAeval_heckeGen ModularCurve.coe_periodLatticeRestrict_apply"
p2m_attr_erase "simp" "CuspForm.heckeAlgebra.coe_U CuspForm.heckeAlgebra.coe_T ModularForm.coe_heckeTLin_apply CuspForm.coe_heckeULin_apply CuspForm.coe_heckeTLin_apply ModularForm.coe_heckeULin_apply ModularCurve.Period.IsEquivariantPrimitive.periodHom_apply ModularCurve.Period.IsEquivariantPrimitive.period_one ModularCurve.cuspCount_one ModularCurve.CuspSpace.cuspDenomAux_infty ModularCurve.CuspSpace.cuspDenomAux_coe ModularCurve.CuspSpace.cuspDenom_mk_zero ModularCurve.CuspSpace.cuspDenom_mk_infty ModularCurve.mapGL_apply_coe ModularCurve.ratPoint_one_zero ModularCurve.ratPoint_zero_right ModularCurve.CuspSpace.fromCoset_mk ModularCurve.CuspSpace.cuspDenom_mk ModularCurve.ratPoint_zero_one ModularCurve.ProjectiveLine.map_mk ModularCurve.qEulerFun_coeff ModularCurve.diffQExp_D ModularCurve.qEulerOn_apply ModularCurve.qEuler_coeff ModularCurve.gamma0PairMap_gen ModularCurve.moduliPointMapRingHom_mk ModularCurve.Gamma0Pair.mk.injEq ModularCurve.ModuliPoint.j_mk ModularCurve.Gamma0Pair.mk.sizeOf_spec ModularCurve.gamma0PairMap_toCurve WeierstrassCurve.Affine.vcY_vcYInv WeierstrassCurve.Affine.vcXInv_vcX WeierstrassCurve.Affine.Point.vcFun_zero WeierstrassCurve.Affine.vcX_vcXInv WeierstrassCurve.Affine.vcYInv_vcY WeierstrassCurve.Affine.Point.vcInvFun_zero WeierstrassCurve.ratPointHom_apply WeierstrassCurve.ratPointMap_zero ModularCurve.tateLaurent_a₆ ModularCurve.tatePowerSeries_a₄"
p2m_attr_erase "simp" "ModularCurve.tatePowerSeries_a₆ ModularCurve.tateLaurent_a₄ ModularCurve.tatePowerSeries_a₁ ModularCurve.tatePowerSeries_a₂ ModularCurve.tatePowerSeries_a₃ WeierstrassCurve.veluX_empty WeierstrassCurve.veluWSum_empty WeierstrassCurve.veluQuotient_a₁ WeierstrassCurve.veluQuotient_a₃ WeierstrassCurve.veluQuotient_empty WeierstrassCurve.veluTSum_empty WeierstrassCurve.veluQuotient_a₂ WeierstrassCurve.Affine.Point.coordsOrZero_some WeierstrassCurve.Affine.Point.coordsOrZero_zero WeierstrassCurve.veluY_empty WeierstrassCurve.Affine.IsogenyEndDatum.mk.injEq WeierstrassCurve.Affine.IsogenyHomDatum.mk.sizeOf_spec WeierstrassCurve.Affine.IsogenyHomDatum.mk.injEq WeierstrassCurve.Affine.IsogenyEndDatum.mk.sizeOf_spec AlgebraicCurve.Pic0.coe_pushforwardAlongDegZero WeierstrassCurve.Affine.pointMapOfPushforward_apply WeierstrassCurve.Affine.pointClass_zero WeierstrassCurve.Affine.pic0ToPoint_pointClass WeierstrassCurve.Affine.deg_placeOfPoint WeierstrassCurve.Affine.coe_pointDivisor WeierstrassCurve.Affine.pointEquivPlace_symm_placeOfPoint WeierstrassCurve.Affine.pointEquivPlace_apply WeierstrassCurve.Affine.genusOnePic0Equiv_symm_apply WeierstrassCurve.Affine.pointDivisor_zero WeierstrassCurve.Affine.pic0ToPoint_mk WeierstrassCurve.Affine.divisorSum_single WeierstrassCurve.Affine.genusOnePic0Equiv_apply PeriodPair.weierstrassCurve_a₆ PeriodPair.weierstrassCurve_a₃ PeriodPair.weierstrassCurve_a₁ PeriodPair.ofTau_ω₂ PeriodPair.scale_ω₂ PeriodPair.ofTau_ω₁ PeriodPair.toPoint_zero PeriodPair.toPoint_of_mem"
p2m_attr_erase "simp" "PeriodPair.weierstrassCurve_a₂ PeriodPair.ofTau_lattice PeriodPair.scale_ω₁ PeriodPair.weierstrassCurve_a₄ WeierstrassCurve.Affine.ratFuncToFunctionField_algebraMap WeierstrassCurve.Affine.pointHom_mk_C_C WeierstrassCurve.Affine.Point.yc_some WeierstrassCurve.Affine.Point.xc_some WeierstrassCurve.Affine.pointPull_algebraMap WeierstrassCurve.Affine.pointHom_mk_C_X WeierstrassCurve.Affine.pointHom_mk_Y WeierstrassCurve.Affine.placeOf_asIdeal compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec"
p2m_attr_erase "simp" "EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two AddMonoid.End.DualEndData.symm_trace AddMonoid.End.dualEndData_intCast_norm AddMonoid.End.DualEndData.ofCharPoly_norm AddMonoid.End.DualEndData.mk.sizeOf_spec AddMonoid.End.DualEndData.mk.injEq AddMonoid.End.DualEndData.ofCharPoly_dual AddMonoid.End.dualEndData_intCast_dual AddMonoid.End.DualEndData.intLinComb_norm AddMonoid.End.DualEndData.ofCharPoly_trace AddMonoid.End.DualEndData.intLinComb_dual AddMonoid.End.DualEndData.symm_dual AddMonoid.End.DualEndData.intLinComb_trace AddMonoid.End.dualEndData_intCast_trace AddMonoid.End.DualEndData.symm_norm WeierstrassCurve.veluQuotientOfSums_a₂ WeierstrassCurve.veluQuotientOfSums_a₁ WeierstrassCurve.veluQuotientOfSums_a₃ WeierstrassCurve.veluQuotient2_a₂ WeierstrassCurve.veluQuotient2_a₃ WeierstrassCurve.veluQuotient2_a₁ ModularCurve.B3.cycOfCongr_apply_coe ModularCurve.B3.cycOfTorsionBy_symm_apply_coe ModularCurve.B3.redPoint_zero ModularCurve.B3.pointAddEquivOfEq_rfl ModularCurve.B3.vcAddEquiv_apply ModularCurve.B3.scaleAddEquiv_apply ModularCurve.B3.cycOfTorsionBy_apply_coe ModularCurve.B3.val_inv_sU ModularCurve.B3.val_sU ModularCurve.B3.resO_apply HahnSeries.coeff_hahnTwist ModularCurve.HahnSpecialise.coe_specialiseCycSub CycSubOf.coe_map ModularCurve.HahnSpecialise.algebraMap_Qbar_apply ModularCurve.HahnSpecialise.resH_apply"
p2m_attr_erase "simp" "ModularCurve.HahnSpecialise.liftModel_map_subtype ModularCurve.HahnSpecialise.specialise_zero WeierstrassCurve.reducePoint_zero WeierstrassCurve.Affine.Point.galoisRep_apply WeierstrassCurve.veluPointMap2_zero ModularCurve.Period.jConjMat_apply_zero_one ModularCurve.Period.jConjSL_coe ModularCurve.Period.jConjMat_apply_one_zero ModularCurve.Period.jConjMat_apply_one_one ModularCurve.Period.jConjGamma0_coe ModularCurve.Period.charInvolution_apply ModularCurve.Period.jConjMat_apply_zero_zero HeckeEis.heckeConjMat_apply_one_one HeckeEis.coe_heckeConjSL HeckeEis.mem_heckeUpperSL HeckeEis.resHom_apply HeckeEis.heckeConjMat_apply_zero_one HeckeEis.coe_transferAux HeckeEis.coe_heckeConj HeckeEis.alphaMat_apply_one_one HeckeEis.heckeConjMat_apply_one_zero HeckeEis.alphaMat_apply_zero_one HeckeEis.pullbackHom_apply HeckeEis.alphaMat_apply_one_zero HeckeEis.alphaMat_apply_zero_zero HeckeEis.heckeConjMat_apply_zero_zero PowerSeries.coeff_heckeV PowerSeries.coeff_heckeU ModularCurve.ComplexPlaceDictionary.mk.injEq ModularCurve.ComplexPlaceDictionary.mk.sizeOf_spec FLT.TruncatedDomainPartition.unipotentDiagonalSum_zero HeckeEis.coeffCoboundaryMap_apply AlgebraicCurve.DivisorialWeilPairingData.toChar_apply AlgebraicCurve.WeilDatum.coe_classRight AlgebraicCurve.WeilDatum.coe_degZeroRight AlgebraicCurve.DivisorialWeilPairingData.mk.sizeOf_spec AlgebraicCurve.WeilDatum.coe_classLeft AlgebraicCurve.WeilDatum.coe_degZeroLeft AlgebraicCurve.DivisorialWeilPairingData.mk.injEq AlgebraicCurve.DivisorialWeilPairingData.toHom_apply_apply"
p2m_attr_erase "simp" "AlgebraicCurve.WeilDatum.mk.sizeOf_spec AlgebraicCurve.WeilDatum.mk.injEq AlgebraicCurve.WeilPairingData.evalAddChar_zero AlgebraicCurve.PrincipalPolarization.mk.injEq AlgebraicCurve.WeilPairingData.evalAddChar_apply AlgebraicCurve.H1Gm.degree_ofPic0 AlgebraicCurve.WeilPairingData.mk.sizeOf_spec AlgebraicCurve.HomPic0Gm.map_one AlgebraicCurve.PrincipalPolarization.mk.sizeOf_spec AlgebraicCurve.WeilPairingData.autodualityEquiv_apply AlgebraicCurve.WeilPairingData.eval_zero_right AlgebraicCurve.H1Gm.ofPic0_mk AlgebraicCurve.WeilPairingData.eval_neg_left AlgebraicCurve.HomPic0Gm.map_apply AlgebraicCurve.H1Gm.degree_mk AlgebraicCurve.HomPic0Gm.map_id AlgebraicCurve.WeilPairingData.mk.injEq AlgebraicCurve.WeilPairingData.congr_eval AlgebraicCurve.WeilPairingData.eval_neg_right AlgebraicCurve.WeilPairingData.eval_zero_left ModularCurve.tateMap_apply CuspForm.HeckeGaloisRepDatum.mk.sizeOf_spec CuspForm.HeckeGaloisRepDatum.mk.injEq ModularForm.coe_atkinLehnerLin_apply CuspForm.coe_atkinLehnerLin_apply ModularForm.AtkinLehnerDatum.mk.injEq ModularForm.AtkinLehnerDatum.alGL_coe ModularForm.AtkinLehnerDatum.mk.sizeOf_spec ModularForm.AtkinLehnerDatum.sqUnitSL_coe ModularForm.AtkinLehnerDatum.det_sqUnit ModularForm.AtkinLehnerDatum.det_mat CuspForm.coe_traceLin_apply ModularCurve.reductionDivAlong_apply ModularCurve.coe_reductionDegZeroAlong ModularCurve.qExpandAlgHomC_apply CartierDual.toDual_ofDual CartierDual.algebraMap_apply CartierDual.antipode_apply CartierDual.one_apply CartierDual.toDual_apply"
p2m_attr_erase "simp" "CartierDual.ofDual_toDual CartierDual.ofDual_apply CartierDual.counit_apply mem_flatClosure_iff closureCounit_apply genericFibreAlgHom_tmul tensorInclusion_closureComul coe_closureAntipode_apply tensorToGenericFibre_tmul tensorInclusion_tmul tensorInclusion3_tmul tensorInclusion3'_tmul closureValBialgHom_apply HopfAlgebra.mem_vanishingIdealOfPoints_iff HopfAlgebra.liftPoint_mk HopfAlgebra.mem_ptSet_iff CartierDual.dualBaseChangeLin_tmul CartierDual.dualBaseChange_tmul CartierDual.map_apply CartierDual.congr_apply CartierDual.congr_symm_apply CartierDual.pairing_apply CartierDual.mapAlgHom_apply CartierDual.mapLinear_apply HopfAlgebra.canAlgHom_tmul HopfAlgebra.canMap_tmul HopfAlgebra.HopfKerHopf.ι₂_comulK HopfAlgebra.HopfKerHopf.ι₃_tmul HopfAlgebra.HopfKerHopf.counitK_apply HopfAlgebra.HopfKerHopf.coe_antipodeK HopfAlgebra.HopfKerHopf.ι₂_tmul HopfAlgebra.HopfKerHopf.coe_antipode HopfAlgebra.HopfKerHopf.hopfKerVal_apply HopfAlgebra.HopfKerHopf.valL_apply HopfAlgebra.HopfKerHopf.ι₂_comul GoodReductionJacobian.RelativePic0Designation.mk.sizeOf_spec GoodReductionJacobian.AvatarSchemeBridge.mk.injEq MilneJVScheme.JacobianSchemeData.mk.injEq GoodReductionJacobian.AvatarSchemeBridge.mk.sizeOf_spec MilneJVScheme.JacobianSchemeData.mk.sizeOf_spec"
p2m_attr_erase "simp" "GoodReductionJacobian.RelativePic0Designation.mk.injEq NeronModelInfra.specGenericFibreInclusion_eq NeronModelInfra.genericFibreRestrict_coe_comp_snd NeronModelInfra.genericFibreRestrict_coe_comp_fst GoodReductionJacobian.schemeHomOverComp_coe NeronModelInfra.schemeHomOverEquivOverHom_apply GoodReductionJacobian.RelativeGroupLaw.mk.sizeOf_spec NeronModelInfra.schemeHomOverEquivOverHom_symm_apply NeronModelInfra.overHomToSchemeHomOver_coe GoodReductionJacobian.RelativeGroupLaw.mk.injEq NeronModelInfra.overHomToSchemeHomOver_schemeHomOverToOverHom NeronModelInfra.schemeHomOverToOverHom_left NeronModelInfra.schemeHomOverToOverHom_overHomToSchemeHomOver GoodReductionJacobian.RelativeGroupLaw.nsmul_zero GoodReductionJacobian.RelativeGroupLaw.mem_torsionSubset GoodReductionJacobian.RelativeGroupLaw.nsmul_succ AlgebraicCurve.CurveModel.mk.injEq AlgebraicCurve.CurveModel.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U1 AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.injEq AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U0 AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.injEq AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.sizeOf_spec AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U1 AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U0 TwoChartCech.Sections.mk.injEq TwoChartCech.Cover.mk.injEq TwoChartCech.GrothendieckComplex.mk.injEq TwoChartCech.Sections.mk.sizeOf_spec TwoChartCech.Cover.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r0_apply TwoChartCech.GrothendieckComplex.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r1_apply CoherentBaseChange.TwoTermComplex.mk.sizeOf_spec CoherentBaseChange.TwoTermComplex.mk.injEq AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_snd AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_fst AlgebraicGeometry.RelPicard.RigidifiedLineBundle.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RigidifiedLineBundle.mk.injEq"
p2m_attr_erase "simp" "AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.sizeOf_spec AlgebraicGeometry.RelPicard.SubPicCondition.onClasses_mk AlgebraicGeometry.RelPicard.relSubPicPresheaf_map_coe CategoryTheory.Functor.OverTotal.ofFibre_fst CategoryTheory.Functor.overTotal_map_fst AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_J AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t' AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf_assoc AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_toGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_openCover_map AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_comp AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_V AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_U AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_f AlgebraicGeometry.RelPicard.designationOfRepresentableBy_P AlgebraicGeometry.RelPicard.designationOfRepresentableBy_toBase AlgebraicGeometry.RelPicard.rigSection_snd AlgebraicGeometry.RelPicard.RigidifiedLineBundle.ofInvertible_L AlgebraicGeometry.RelPicard.rigSection_snd_assoc AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.sizeOf_spec GoodReductionJacobian.relativeGroupLawOfGrpObj_inv GoodReductionJacobian.relativeGroupLawOfGrpObj_mul GoodReductionJacobian.overHomEquivSchemeHomOver_apply_coe GoodReductionJacobian.relativeGroupLawOfGrpObj_one GoodReductionJacobian.overHomEquivSchemeHomOver_symm_apply_left SheafOfModules.tensorUnit_eq AlgebraicGeometry.Scheme.Modules.tensorUnit_eq PresheafOfModules.InternalHom.presheaf_map_apply PresheafOfModules.InternalHom.curryFamily_app PresheafOfModules.InternalHom.add_app PresheafOfModules.InternalHom.smul_app PresheafOfModules.InternalHom.zero_app PresheafOfModules.ihomObj_map_val PresheafOfModules.ihomFunctor_map"
p2m_attr_erase "simp" "PresheafOfModules.InternalHom.restrict_app PresheafOfModules.InternalHom.postcomp_app PresheafOfModules.InternalHom.neg_app PresheafOfModules.curry'_app_val PresheafOfModules.InternalHom.presheaf_obj PresheafOfModules.ihomFunctor_obj PresheafOfModules.ihomObj_obj PresheafOfModules.InternalHom.sub_app PresheafOfModules.ihomMap_app_val PresheafOfModules.freeεIso_hom_app PresheafOfModules.freeμIso_hom_app AlgebraicCurve.coe_cechH0Equiv_apply AlgebraicCurve.cechH1ToH1_mk AlgebraicCurve.lSpaceOn_univ AlgebraicCurve.lSpaceOn_empty AlgebraicGeometry.RelPicard.thetaBundle_def AlgebraicGeometry.RelPicard.picardBundle_def AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_ofRelEffDivisor AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_I AlgebraicGeometry.mapOnProdOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.mk.sizeOf_spec AlgebraicGeometry.RelEffCartierDiv.mk.injEq AlgebraicGeometry.mapOnProdOver_snd AlgebraicGeometry.mapOnProdOver_fst AlgebraicGeometry.mapOnProdOver_snd_assoc AlgebraicGeometry.mapOnProdOver_id AlgebraicCurve.RelEffDivisor.mk.sizeOf_spec AlgebraicCurve.mapOnProd_fst AlgebraicCurve.mapOnProd_fst_assoc AlgebraicCurve.mapOnProd_snd AlgebraicCurve.UnivDivisorPack.mk.injEq AlgebraicCurve.RelEffDivisor.mk.injEq AlgebraicCurve.UnivDivisorPack.mk.sizeOf_spec AlgebraicCurve.mapOnProd_snd_assoc AlgebraicGeometry.Scheme.Modules.exteriorPower_obj PresheafOfModules.exteriorPower_map_ιMulti PresheafOfModules.ExteriorPower.appₗ_apply AlgebraicGeometry.prodKerGraph_one AlgebraicGeometry.fibrePowOver.proj_comp AlgebraicGeometry.prodKerGraph_zero"
p2m_attr_erase "simp" "AlgebraicGeometry.RelEffCartierDiv.empty_I AlgebraicGeometry.fibrePowOver.proj_comp_assoc AlgebraicGeometry.graphOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.toPoint_comp AlgebraicGeometry.RelEffCartierDiv.toPoint_comp_assoc AlgebraicGeometry.graphOver_fst AlgebraicGeometry.RelEffCartierDiv.ofPoint_I AlgebraicGeometry.graphOver_snd AlgebraicGeometry.graphOver_snd_assoc AlgebraicCurve.SymmetricPowerPackage.mk.sizeOf_spec AlgebraicCurve.SymmetricPowerPackage.mk.injEq AlgebraicGeometry.FGSubalgebra.cocone_ι_app_apply AlgebraicGeometry.RelPicard.fst_toProdSpec AlgebraicGeometry.RelPicard.toProdSpec_fst_assoc AlgebraicGeometry.RelPicard.pointsSubBasepointModule_cons AlgebraicGeometry.RelPicard.pointsSubBasepointModule_nil AlgebraicGeometry.RelPicard.fst_toProdSpec_assoc AlgebraicGeometry.RelPicard.toProdSpec_fst AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.sub_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sresTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.add_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.sizeOf_spec AlgebraicGeometry.Scheme.IdealSheafData.coe_resLE AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.smul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_ofLE_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.ideal_range AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zero_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sres AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.comp_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.neg_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.id_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_mulRight_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.nsmul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.injEq AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zsmul_app AlgebraicGeometry.Scheme.Modules.toUnitSection_ofUnitSection AlgebraicGeometry.Scheme.Modules.pullbackSection_def AlgebraicGeometry.Scheme.Modules.ofUnitSection_toUnitSection PresheafOfModules.InternalHom.IsSheafAux.appAt_toPresheafHom SheafOfModules.ihomSectionsEquivFamily_unit"
p2m_attr_erase "simp" "AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_apply SheafOfModules.ihomEval_unit_app AlgebraicGeometry.Scheme.Modules.ihomEval_zero_right AlgebraicGeometry.Scheme.Modules.ihomEval_zero_left AlgebraicGeometry.Scheme.Modules.homOfFamily_app_apply SheafOfModules.unit_ihomSectionsEquivFamily AlgebraicGeometry.Scheme.Modules.familyOfHom_app AlgebraicGeometry.Scheme.Modules.restrictUnitIso_hom_app_apply AlgebraicGeometry.Scheme.Modules.restrictUnitIso_inv_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomOfFamily_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_symm_apply AlgebraicGeometry.Scheme.Modules.tensorSections_zero_right AlgebraicGeometry.Scheme.Modules.map_unitSection AlgebraicGeometry.Scheme.Modules.tensorSectionsBilin_apply AlgebraicGeometry.Scheme.Modules.tensorPowSection_zero AlgebraicGeometry.Scheme.Modules.tensorSections_zero_left AlgebraicGeometry.Scheme.Modules.tensorPow_zero AlgebraicGeometry.Scheme.Modules.tensorPow_succ AlgebraicGeometry.Scheme.OrderedAffineCover.mk.injEq AlgebraicGeometry.OModulePresheaf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.mk.injEq AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_neg AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_zero AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_sub AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_add AlgebraicGeometry.Scheme.OrderedAffineCover.toCoverOf_U AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.injEq AlgebraicGeometry.Scheme.OrderedAffineCover.restrict_U AlgebraicGeometry.OModulePresheaf.Hom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.id_app AlgebraicGeometry.OModulePresheaf.AffHom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffHom.comp_app AlgebraicGeometry.OModulePresheaf.AffSES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.kerMap_coe AlgebraicGeometry.OModulePresheaf.AffHom.id_app AlgebraicGeometry.OModulePresheaf.Hom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.toAffHom_app AlgebraicGeometry.OModulePresheaf.SES.mk.sizeOf_spec"
p2m_attr_erase "simp" "AlgebraicGeometry.OModulePresheaf.AffHom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.comp_app AlgebraicGeometry.OModulePresheaf.SES.mk.injEq AlgebraicGeometry.OModulePresheaf.AffHom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffSES.mk.injEq AlgebraicGeometry.OModulePresheaf.prod_obj AlgebraicGeometry.OModulePresheaf.restrOpen_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.injEq AlgebraicGeometry.OModulePresheaf.pushforward_obj AlgebraicGeometry.OModulePresheaf.im_obj AlgebraicGeometry.OModulePresheaf.pow_obj AlgebraicGeometry.OModulePresheaf.fstHom_app AlgebraicGeometry.OModulePresheaf.ker_obj AlgebraicGeometry.OModulePresheaf.coker_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.preimage_U AlgebraicGeometry.OModulePresheaf.sndHom_app AlgebraicGeometry.OModulePresheaf.Leray.restrictToPreimage_U DoubleComplex.Bounded.mk.injEq DoubleComplex.Bounded.mk.sizeOf_spec DoubleComplex.Convergence.mk.injEq DoubleComplex.Convergence.mk.sizeOf_spec DoubleComplex.SubQuot.mk.sizeOf_spec DoubleComplex.SubQuot.mk.injEq AlgebraicGeometry.ChowDatumProj.mk.sizeOf_spec AlgebraicGeometry.ChowDatum.mk.sizeOf_spec AlgebraicGeometry.ChowDatumProj.mk.injEq AlgebraicGeometry.ChowDatum.mk.injEq ProjSpaceCech.GradedModule.mk.injEq ProjSpaceCech.GradedModule.mk.sizeOf_spec ProjSpaceCech.GradedModule.Frac.mk.sizeOf_spec ProjSpaceCech.GradedModule.Presentation.mk.injEq ProjSpaceCech.GradedModule.Frac.mk.injEq ProjSpaceCech.GradedModule.Presentation.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.shift_toLinearMap ProjSpaceCech.GradedModule.Hom.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.mk.injEq TwoChartCech.Mumford.dK_apply TwoChartCech.Mumford.ι0_apply"
p2m_attr_erase "simp" "TwoChartCech.Mumford.ι1_apply TwoChartCech.KerCoprod.dK_apply TwoChartCech.KerCoprod.ι1_apply TwoChartCech.KerCoprod.ι0_apply AlgebraicGeometry.tilde.functorCompPullbackSpecIso_app AlgebraicGeometry.RelPicard.algEquivZeroGroupCut_toSubPicCondition AlgebraicGeometry.RelPicard.LFP.stageHom_val AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_hom_app_coe AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_inv_app_coe AlgebraicGeometry.RelPicard.BaseChange.restrict_P AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp AlgebraicGeometry.RelEffCartierDiv.functor_map_fst AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_pullbackAlong AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_symm_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp_assoc AlgebraicGeometry.RelEffCartierDiv.supportedIn_top AlgebraicGeometry.RelEffCartierDiv.mem_supportedIn_iff AlgebraicGeometry.RelEffCartierDiv.supportedIn_top_eq AlgebraicGeometry.RelEffCartierDiv.restrictAlong_extendAlong AlgebraicGeometry.RelEffCartierDiv.extendAlong_I AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd AlgebraicGeometry.RelEffCartierDiv.restrictAlong_I AlgebraicGeometry.RelEffCartierDiv.extendAlong_restrictAlong AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst CoherentBaseChange.FibreH0Family.mk.sizeOf_spec CoherentBaseChange.FibreH0Family.mk.injEq AlgebraicGeometry.Scheme.Modules.ProjPresentation.mk.injEq AlgebraicGeometry.Scheme.Modules.ProjPresentation.mk.sizeOf_spec PresheafOfModules.pushforwardCongr_inv_app_app_apply PresheafOfModules.pushforwardNatTrans_app_app_apply PresheafOfModules.pushforwardCongr_hom_app_app_apply exteriorPower.mulₗ_apply_coe AlgebraicGeometry.ProjSpace.twistObj.mk.injEq AlgebraicGeometry.ProjSpace.twistObj.zero_val AlgebraicGeometry.ProjSpace.twistObj.add_val AlgebraicGeometry.ProjSpace.twist_res_val AlgebraicGeometry.ProjSpace.twist_smul_val"
p2m_attr_erase "simp" "AlgebraicGeometry.ProjSpace.twistGradeToObj_val AlgebraicGeometry.ProjSpace.twistObj.smul_val AlgebraicGeometry.ProjSpace.twistGradeEquiv_apply_val AlgebraicGeometry.ProjSpace.twistObj.mk.sizeOf_spec RegularLocalRingQuotientAscent.dualNumberFst_apply Algebra.DescentCofaces.i₁_apply Algebra.DescentCofaces.i₂_apply Algebra.DescentCofaces.c₁₂_tmul Algebra.DescentCofaces.c₂₃_tmul Algebra.DescentCofaces.c₁₃_tmul AlgebraicGeometry.DescentAction.toTriple_fst_assoc AlgebraicGeometry.DescentAction.invol_snd_assoc AlgebraicGeometry.DescentAction.unitMap_fst AlgebraicGeometry.DescentAction.flipMap_snd_assoc AlgebraicGeometry.DescentAction.actMap_snd_assoc AlgebraicGeometry.DescentAction.unitMap_fst_assoc AlgebraicGeometry.DescentAction.unitMap_snd AlgebraicGeometry.DescentAction.eRel_snd AlgebraicGeometry.DescentAction.toTriple_fst AlgebraicGeometry.DescentAction.invol_invol AlgebraicGeometry.DescentAction.proj₁₃_snd AlgebraicGeometry.DescentAction.eRel_snd_assoc AlgebraicGeometry.DescentAction.invol_invol_assoc AlgebraicGeometry.DescentAction.invol_act AlgebraicGeometry.DescentAction.actMap_fst_assoc AlgebraicGeometry.DescentAction.flipMap_fst_assoc AlgebraicGeometry.DescentAction.eRel_fst_assoc AlgebraicGeometry.DescentAction.eRel_fst AlgebraicGeometry.DescentAction.invol_act_assoc AlgebraicGeometry.DescentAction.invol_fst_assoc AlgebraicGeometry.DescentAction.proj₁₃_snd_assoc AlgebraicGeometry.DescentAction.mk.injEq AlgebraicGeometry.DescentAction.flipMap_fst AlgebraicGeometry.DescentAction.proj₁₃_fst AlgebraicGeometry.DescentAction.invol_fst AlgebraicGeometry.DescentAction.unitMap_snd_assoc AlgebraicGeometry.DescentAction.actMap_fst AlgebraicGeometry.DescentAction.toTriple_snd_assoc AlgebraicGeometry.DescentAction.invol_snd AlgebraicGeometry.DescentAction.actMap_snd"
p2m_attr_erase "simp" "AlgebraicGeometry.DescentAction.flipMap_snd AlgebraicGeometry.DescentAction.proj₁₃_fst_assoc AlgebraicGeometry.DescentAction.mk.sizeOf_spec AlgebraicGeometry.DescentAction.toTriple_snd NeronModelInfra.NeronModelPropertyBundle.endExtensionEquiv_symm_restrict NeronModelInfra.schemeHomOverComp_id_left NeronModelInfra.schemeHomOverComp_id_right NeronModelInfra.schemeHomOverId_coe NeronModelInfra.NeronModelPropertyBundle.endExtensionEquiv_apply NeronModelInfra.NeronModelPropertyBundle.restrict_endExtensionEquiv_symm NeronModelInfra.schemeHomOverComp_coe ModularCurve.CharPModel.FibreModel.mk.injEq ModularCurve.CharPModel.FibreModel.mk.sizeOf_spec ModularCurve.IgusaScheme.ιInf_igusaTo_assoc ModularCurve.IgusaScheme.coe_jFull ModularCurve.IgusaScheme.coe_jInvChartInf ModularCurve.IgusaScheme.coe_jChartFin ModularCurve.IgusaScheme.ιFin_igusaTo ModularCurve.IgusaScheme.ιInf_igusaTo ModularCurve.IgusaScheme.ιFin_igusaTo_assoc AlgebraicCurve.CurveModel.coe_gInf AlgebraicCurve.CurveModel.coe_tInvChart AlgebraicCurve.CurveModel.ιInf_gluedToBase_assoc AlgebraicCurve.CurveModel.ιInf_gluedToBase AlgebraicCurve.CurveModel.primeOfι₀_asIdeal AlgebraicCurve.CurveModel.coe_tChart AlgebraicCurve.CurveModel.ι₀_gluedToBase_assoc AlgebraicCurve.CurveModel.primeOfιInf_asIdeal AlgebraicCurve.CurveModel.ι₀_gluedToBase AlgebraicCurve.CurveModel.coe_tma AlgebraicCurve.CurveModel.coe_primeEquivChartPlaces ModularCurve.coe_frobeniusModL ModularCurve.coe_frobeniusDegZeroPullbackModL ModularCurve.coe_frobeniusDegZeroPushforwardModL ModularCurve.CharPReduction.coeffRed_coeff ModularCurve.CharPReduction.redLocHom_apply ModularCurve.coe_uniformizerMod ModularCurve.qSeriesBar_jModElt ModularCurve.qInftyPlaceMod_toValuationSubring WeierstrassCurve.twoVeluCurve_a₁"
p2m_attr_erase "simp" "WeierstrassCurve.twoVeluCurve_a₂ WeierstrassCurve.twoVeluCurve_a₃ WeierstrassCurve.xVeluCurve_a₃ WeierstrassCurve.xVeluCurve_a₂ WeierstrassCurve.xVeluCurve_a₁ WeierstrassCurve.map_veluU WeierstrassCurve.map_veluT WeierstrassCurve.map_veluW WeierstrassCurve.map_veluGy WeierstrassCurve.map_veluGx WeierstrassCurve.map_veluWSum_singleton WeierstrassCurve.map_veluTSum_singleton WeierstrassCurve.veluPointMap3_zero WeierstrassCurve.vcInvEmbedding_apply WeierstrassCurve.Affine.Point.netCol_one WeierstrassCurve.Affine.Point.xOrZero_zero WeierstrassCurve.Affine.Point.netPairing_zero_right WeierstrassCurve.Affine.Point.netW20_some WeierstrassCurve.Affine.Point.netCol_zero WeierstrassCurve.Affine.Point.netPairing_zero_left WeierstrassCurve.Affine.Point.xOrZero_some WeierstrassCurve.Affine.Point.netW20_zero TateCurve.cauchyMulInt_zero TateCurve.cauchyMulInt3_zero TateCurve.tent_one TateCurve.Gz_zero TateCurve.cauchyMulInt_one TateCurve.tent_zero TateCurve.Fz_zero TateCurve.xCoeffFull_succ TateCurve.a₆Coeff_zero TateCurve.a₄Coeff_succ TateCurve.a₄Coeff_zero TateCurve.cauchyMul_zero TateCurve.a₆Coeff_succ TateCurve.yCoeffFull_succ TateCurve.xCoeffFull_zero TateCurve.yCoeffFull_zero TateCurve.yfun_zero TateCurve.xfun_zero"
p2m_attr_erase "simp" "TateCurve.yTerm_zero TateCurve.xTerm_zero TateCurve.curve_a₂ TateCurve.b_one TateCurve.curve_a₁ TateCurve.term_zero TateCurve.curve_a₆ TateCurve.curve_a₄ TateCurve.curve_a₃ FLT.DivisorConvolution.sigma_zero_right FLT.DivisorConvolution.sigma_one_right FLT.DivisorConvolution.sigmaConv_one FLT.DivisorConvolution.sigmaConv_zero FormalCoordinates.mk.injEq WeierstrassCurve.formalParam_zero WeierstrassCurve.SmoothLocusReductionData.reduceHom₀_apply WeierstrassCurve.formalParam_some FormalCoordinates.mk.sizeOf_spec WeierstrassCurve.SmoothLocusReductionData.mk.injEq WeierstrassCurve.reducePointSmooth_zero WeierstrassCurve.SmoothLocusReductionData.mk.sizeOf_spec WeierstrassCurve.mem_zeroComponentSubgroup_iff ModularCurve.PlaceSpecialization.mk.injEq ModularCurve.PlaceSpecialization.mk.sizeOf_spec ValuationSubring.reduceAt_coe ValuationSubring.reduceAt_one ValuationSubring.reduceAt_natCast ValuationSubring.reduceAt_intCast ValuationSubring.reduceAt_zero ModularCurve.coe_jGeomGen ModularCurve.coe_jNGeomGen ModularCurve.charLGeomModuliDictionary_single ModularCurve.specializeModuli_single ModularCurve.specializePlace_def GoodReductionJacobian.RelativeGroupLaw.fibre_inv GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_coe GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_toBase GoodReductionJacobian.RelativeGroupLaw.fibre_mul GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_ofBase GoodReductionJacobian.RelativeGroupLaw.fibre_one"
p2m_attr_erase "simp" "GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_coe AlgebraicGeometry.schemeFibreEndo_snd AlgebraicGeometry.schemeFibreEndo_fst AlgebraicCurve.KwCfx.kw_cfx_tau_coe AlgebraicCurve.kw_hwcd_dlog_zero AlgebraicCurve.kw_hwcd_mem_regularDifferentials_iff AlgebraicCurve.kw_hwcd_dlog_one MazurAdmissible.AdmissibleChain.mk.injEq MazurAdmissible.OpenAction.mk.injEq MazurAdmissible.OpenAction.mk.sizeOf_spec MazurAdmissible.AdmissibleChain.mk.sizeOf_spec TaylorWiles.Seed.mk.injEq TaylorWiles.Seed.mk.sizeOf_spec ModularCurve.coe_heckeBetaC AlgebraicCurve.Divisor.coe_degZeroEnd ModularCurve.coe_heckeAlphaC ModularCurve.CommutingHeckeFamily.mk.injEq ModularCurve.SpecializationWitnessData.mk.sizeOf_spec ModularCurve.SpecializationWitnessData.mk.injEq ModularCurve.CommutingHeckeFamily.mk.sizeOf_spec AlgebraicCurve.Divisor.congr_single AlgebraicCurve.Pic0.coe_degZeroCongr_symm AlgebraicCurve.Divisor.degree_congr AlgebraicCurve.Divisor.degree_congr_symm AlgebraicCurve.Pic0.coe_degZeroCongr KatzModularForm.c₆_toFun KatzModularForm.neg_toFun KatzModularForm.mul_toFun KatzModularForm.qExpansion_neg KatzModularForm.discr_toFun KatzModularForm.qExpansion_sub KatzModularForm.qExpansion_add KatzModularForm.qExpansion_mul KatzModularForm.zero_toFun KatzModularForm.mk.injEq KatzModularForm.qExpansion_smul KatzModularForm.smul_toFun KatzModularForm.add_toFun KatzModularForm.sub_toFun KatzModularForm.c₄_toFun"
p2m_attr_erase "simp" "KatzModularForm.qExpansion_zero KatzModularForm.mk.sizeOf_spec ModularCurve.tateUnivCurve_a₂ ModularCurve.tateUnivCurve_a₃ ModularCurve.tateUnivCurve_a₆ ModularCurve.nonToricPoint_fst ModularCurve.toricPoint_snd ModularCurve.tateUnivCurve_a₁ ModularCurve.nonToricPoint_snd ModularCurve.tateUnivCurve_a₄ ModularCurve.toricPoint_fst ModularCurve.LevelPData.mk.sizeOf_spec ModularCurve.KatzLevelPForm.neg_toFun ModularCurve.LevelP.coe_swapW ModularCurve.KatzLevelPForm.swap_swap KatzModularForm.pullbackLevelP_toFun ModularCurve.LevelPData.swap_xQ KatzModularForm.pullbackLevelP_zero ModularCurve.LevelPData.map_yP ModularCurve.KatzLevelPForm.swap_neg ModularCurve.KatzGamma0Form.toKatzLevelPForm_sub ModularCurve.KatzLevelPForm.swap_add KatzModularForm.swap_pullbackLevelP ModularCurve.KatzGamma0Form.toKatzLevelPForm_add ModularCurve.KatzLevelPForm.swap_smul ModularCurve.LevelPData.map_yQ ModularCurve.KatzLevelPForm.mk.injEq ModularCurve.KatzLevelPForm.zero_toFun KatzModularForm.pullbackLevelP_smul ModularCurve.LevelPData.swap_xP ModularCurve.KatzGamma0Form.toKatzLevelPForm_mul ModularCurve.KatzGamma0Form.toKatzLevelPForm_neg ModularCurve.LevelPData.variableChange_xQ KatzModularForm.pullbackGamma0_toKatzLevelPForm ModularCurve.KatzLevelPForm.mk.sizeOf_spec ModularCurve.KatzLevelPForm.swap_zero ModularCurve.LevelP.coe_unipotentU ModularCurve.KatzLevelPForm.mul_toFun ModularCurve.LevelPData.variableChange_yP ModularCurve.LevelPData.mk.injEq"
p2m_attr_erase "simp" "ModularCurve.KatzLevelPForm.sub_toFun ModularCurve.LevelPData.variableChange_xP ModularCurve.KatzLevelPForm.smul_toFun ModularCurve.LevelPData.swap_yP ModularCurve.LevelPData.map_xP ModularCurve.LevelPData.swap_swap ModularCurve.LevelPData.swap_yQ ModularCurve.KatzGamma0Form.toKatzLevelPForm_zero ModularCurve.KatzGamma0Form.mk.injEq ModularCurve.KatzLevelPForm.swap_toFun KatzModularForm.pullbackLevelP_add ModularCurve.KatzGamma0Form.mk.sizeOf_spec ModularCurve.LevelPData.variableChange_yQ ModularCurve.KatzLevelPForm.swap_sub ModularCurve.KatzGamma0Form.toKatzLevelPForm_smul ModularCurve.LevelPData.map_xQ ModularCurve.KatzLevelPForm.add_toFun ModularCurve.cuspData_yP ModularCurve.qTwistAlgHom_apply ModularCurve.cuspData_yQ ModularCurve.cuspData_xP ModularCurve.cuspData_xQ ModularCurve.val_cyclZeta ModularCurve.cuspShift_one ModularCurve.cuspShift_zero KatzModularForm.baseChange_zero ModularCurve.KatzGamma0Form.baseChange_sub ModularCurve.KatzGamma0Form.baseChange_zero ModularCurve.KatzGamma0Form.baseChange_toKatzLevelPForm KatzModularForm.baseChange_sub ModularCurve.KatzLevelPForm.baseChange_sub ModularCurve.KatzGamma0Form.baseChange_smul ModularCurve.KatzGamma0Form.baseChange_add ModularCurve.KatzLevelPForm.baseChange_swap KatzModularForm.baseChange_add ModularCurve.KatzLevelPForm.baseChange_neg ModularCurve.KatzLevelPForm.baseChange_smul ModularCurve.KatzGamma0Form.baseChange_neg ModularCurve.KatzLevelPForm.baseChange_add KatzModularForm.baseChange_smul"
p2m_attr_erase "simp" "ModularCurve.KatzLevelPForm.baseChange_zero KatzModularForm.baseChange_neg ModularCurve.KatzLevelPForm.evalUniv_neg ModularCurve.KatzLevelPForm.evalUniv_mul ModularCurve.KatzLevelPForm.evalUniv_zero ModularCurve.KatzLevelPForm.evalUniv_sub ModularCurve.KatzLevelPForm.evalUniv_add ModularCurve.LevelP.VCRing.lift_vcVar ModularCurve.LevelP.BorelPRing.lift_xQ ModularCurve.LevelP.twoPointLift_xQ ModularCurve.LevelP.PsiRoot.lift_ofBase ModularCurve.LevelP.univVC_u ModularCurve.LevelP.twoPointLift_yP ModularCurve.LevelP.univVC_r ModularCurve.LevelP.TorsionPointRing.lift_torsionPtX ModularCurve.LevelP.TorsionPointRing.lift_ofPsiRoot ModularCurve.LevelP.TorsionPointRing.lift_ofBase ModularCurve.LevelP.vcPolyLift_C ModularCurve.LevelP.BorelQRing.lift_of ModularCurve.LevelP.BorelPRing.lift_yQ ModularCurve.LevelP.BorelPRing.lift_ofUniv ModularCurve.LevelP.univVC_t ModularCurve.LevelP.BorelRing.lift_ofUniv ModularCurve.LevelP.univVC_s ModularCurve.LevelP.twoPointLift_xP ModularCurve.LevelP.twoPointLift_yQ ModularCurve.LevelP.TorsionPointRing.lift_torsionPtY ModularCurve.LevelP.BorelQRing.lift_borelQY ModularCurve.LevelP.VCRing.lift_algebraMap ModularCurve.LevelP.VCRing.lift_ofUniv ModularCurve.LevelP.PsiRoot.lift_psiRootX ModularCurve.LevelP.BorelRing.lift_algebraMap ModularCurve.LevelP.BorelPRing.lift_yP ModularCurve.LevelP.BasisRing.lift_ofTwoPoint ModularCurve.LevelP.BasisRing.lift_ofBase ModularCurve.LevelP.vcPolyLift_X ModularCurve.LevelP.genericLift_X ModularCurve.LevelP.twoPointLift_ofBase ModularCurve.LevelP.BorelPRing.lift_xP ModularCurve.LevelP.sClassify_tmul"
p2m_attr_erase "simp" "ModularCurve.LevelP.sLift_tmul WeierstrassCurve.Generic.poly_map_classify WeierstrassCurve.Generic.poly_a₆ WeierstrassCurve.Generic.poly_a₁ WeierstrassCurve.Generic.classify_X WeierstrassCurve.Generic.coeffs_two WeierstrassCurve.Generic.coeffs_one WeierstrassCurve.Generic.curve_a₄ WeierstrassCurve.Generic.coeffs_three WeierstrassCurve.Generic.poly_a₄ WeierstrassCurve.Generic.poly_a₃ WeierstrassCurve.Generic.poly_a₂ WeierstrassCurve.Generic.coeffs_zero WeierstrassCurve.Generic.curve_a₂ WeierstrassCurve.Generic.coeffs_four WeierstrassCurve.Generic.curve_a₆ WeierstrassCurve.Generic.curve_a₁ WeierstrassCurve.Generic.curve_a₃ WeierstrassCurve.Universal.halveX_zero WeierstrassCurve.Universal.specialize_X_one WeierstrassCurve.Universal.coeff_halve WeierstrassCurve.Universal.specialize_X_two WeierstrassCurve.Universal.halveCoeff_zero WeierstrassCurve.Universal.specialize_X_four WeierstrassCurve.Universal.coeff_halveX WeierstrassCurve.Universal.specialize_X_three WeierstrassCurve.Universal.specialize_X_zero ModularCurve.LevelPData.quotientBySndLine_swap ModularCurve.LevelP.smulX_one ModularCurve.LevelP.quotientByLine_a₃ ModularCurve.LevelP.quotientByLine_a₂ ModularCurve.LevelP.quotientByLine_a₁ ModularCurve.LevelPData.quotientByFstLine_swap TateCurve.tateTorsionPoint_zero_zero ModularCurve.LevelP.TorusQRing.lift_yQ ModularCurve.LevelP.TorusQRing.lift_yP ModularCurve.LevelP.TorusQRing.lift_xQ ModularCurve.LevelP.TorusRing.lift_ofUniv ModularCurve.LevelP.TorusQRing.lift_xP ModularCurve.LevelP.TorusQRing.lift_ofUniv"
p2m_attr_erase "simp" "ModularCurve.LevelP.TorusRing.lift_algebraMap"

set_option autoImplicit false
set_option maxHeartbeats 1600000
set_option synthInstance.maxHeartbeats 160000

namespace RingHom p2m_export "RingHom" "map_closure Flat Finite ext toAddMonoidHom mk coe_mul range comp coe_one" end RingHom
p2m_open_scoped "RingHom" in

theorem RingHom.exists_forall_pow_eq_one_apply_eq_pow {F : Type*} [CommRing F] [IsDomain F] (σ : F →+* F)
    (m : ℕ) (hm : m ≠ 0) :
    ∃ n : ℕ, ∀ ζ : F, ζ ^ m = 1 → σ ζ = ζ ^ n := by
  haveI : NeZero m := ⟨hm⟩
  obtain ⟨g, hg⟩ := IsCyclic.exists_generator (α := rootsOfUnity m F)

  have hmem : ∀ ζ : F, ζ ^ m = 1 → ∃ j : ℕ, ζ = ((g : Fˣ) : F) ^ j := by
    intro ζ hζ
    let z : rootsOfUnity m F := rootsOfUnity.mkOfPowEq ζ hζ
    obtain ⟨j, hj⟩ := (mem_powers_iff_mem_zpowers (G := rootsOfUnity m F)).mpr (hg z)
    refine ⟨j, ?_⟩
    have := congrArg (fun u : rootsOfUnity m F => ((u : Fˣ) : F)) hj
    simpa [z] using this.symm

  have hgm : ((g : Fˣ) : F) ^ m = 1 := by
    have := g.2
    rw [mem_rootsOfUnity] at this
    rw [← Units.val_pow_eq_pow_val, this, Units.val_one]
  obtain ⟨n, hn⟩ := hmem (σ (g : Fˣ)) (by rw [← map_pow, hgm, map_one])
  refine ⟨n, fun ζ hζ => ?_⟩
  obtain ⟨j, rfl⟩ := hmem ζ hζ
  rw [map_pow, hn, ← pow_mul, ← pow_mul, mul_comm]

p2m_open_scoped "AlgebraicClosure" in

theorem AlgebraicClosure.exists_forall_apply_eq_pow_of_pow_eq_one (k : ℕ) :
    ∃ n : (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) → ℕ,
      ∀ σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ, ∀ ζ : AlgebraicClosure ℚ, ζ ^ (2 ^ k) = 1 → σ ζ = ζ ^ n σ := by
  have h := fun σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ =>
    RingHom.exists_forall_pow_eq_one_apply_eq_pow (σ : AlgebraicClosure ℚ →+* AlgebraicClosure ℚ) (2 ^ k) (by positivity)
  choose n hn using h
  exact ⟨n, fun σ ζ hζ => hn σ ζ hζ⟩

p2m_open_scoped "TensorProduct P2MW.S_ModularCurve_exists_generator_tateModule_closure_inertia_smul_sub_adjoin_tateHeckeRep.TensorProduct"

namespace PadicInt
p2m_export "PadicInt" "norm_p norm_int_lt_one_iff_dvd coe_add appr unitCoeff_spec coe_mul unitCoeff norm_le_one valuation ext mul_inv norm_le_pow_iff_mem_span_pow algebra coe_one coe_zero"
p2m_open "PadicInt"

theorem exists_pow_mul_eq_coe (p : ℕ) [Fact p.Prime] (q : ℚ_[p]) :
    ∃ c : ℕ, ∃ a : ℤ_[p], (p : ℚ_[p]) ^ c * q = (a : ℚ_[p]) := by
  obtain ⟨a, b, hb, rfl⟩ := IsFractionRing.div_surjective (A := ℤ_[p]) q
  have hb0 : (b : ℤ_[p]) ≠ 0 := nonZeroDivisors.ne_zero hb
  set u : ℤ_[p]ˣ := unitCoeff hb0 with hu_def
  refine ⟨b.valuation, a * ↑(u⁻¹), ?_⟩
  have hbspec : (b : ℤ_[p]) = (u : ℤ_[p]) * (p : ℤ_[p]) ^ b.valuation := unitCoeff_spec hb0
  have hbQ : (algebraMap ℤ_[p] ℚ_[p] b) = ((u : ℤ_[p]) : ℚ_[p]) * (p : ℚ_[p]) ^ b.valuation := by
    have h := congrArg ((↑) : ℤ_[p] → ℚ_[p]) hbspec
    push_cast at h
    exact h
  have huQ : ((u : ℤ_[p]) : ℚ_[p]) * (((u⁻¹ : ℤ_[p]ˣ) : ℤ_[p]) : ℚ_[p]) = 1 := by
    rw [← PadicInt.coe_mul, Units.mul_inv, PadicInt.coe_one]
  have huinv : (((u⁻¹ : ℤ_[p]ˣ) : ℤ_[p]) : ℚ_[p]) = (((u : ℤ_[p]) : ℚ_[p]))⁻¹ :=
    (eq_inv_of_mul_eq_one_right huQ)
  have hp0 : (p : ℚ_[p]) ^ b.valuation ≠ 0 := pow_ne_zero _ (Nat.cast_ne_zero.mpr (Fact.out : p.Prime).ne_zero)
  rw [show algebraMap ℤ_[p] ℚ_[p] a = ((a : ℤ_[p]) : ℚ_[p]) from rfl, hbQ, PadicInt.coe_mul, huinv]
  calc (p : ℚ_[p]) ^ b.valuation * (((a : ℤ_[p]) : ℚ_[p]) / (((u : ℤ_[p]) : ℚ_[p]) * (p : ℚ_[p]) ^ b.valuation))
      = ((a : ℤ_[p]) : ℚ_[p]) * (((u : ℤ_[p]) : ℚ_[p]))⁻¹ * ((p : ℚ_[p]) ^ b.valuation * ((p : ℚ_[p]) ^ b.valuation)⁻¹) := by
        rw [div_eq_mul_inv, mul_inv_rev]; ring
    _ = ((a : ℤ_[p]) : ℚ_[p]) * (((u : ℤ_[p]) : ℚ_[p]))⁻¹ := by rw [mul_inv_cancel₀ hp0, mul_one]

end PadicInt

namespace TensorProduct p2m_export "TensorProduct" "congr tmul_zero smul_tmul' mk ext tmul map Algebra.smul_def tmul_add tmul_smul" end TensorProduct
p2m_open_scoped "TensorProduct" in

theorem TensorProduct.exists_pow_smul_eq_one_tmul (p : ℕ) [Fact p.Prime] {M : Type*} [AddCommGroup M] [Module ℤ_[p] M]
    (v : ℚ_[p] ⊗[ℤ_[p]] M) : ∃ c : ℕ, ∃ m : M, ((p : ℚ_[p]) ^ c) • v = (1 : ℚ_[p]) ⊗ₜ[ℤ_[p]] m := by
  induction v using TensorProduct.induction_on with
  | zero => exact ⟨0, 0, by simp⟩
  | tmul q m =>
    obtain ⟨c, a, ha⟩ := PadicInt.exists_pow_mul_eq_coe p q
    refine ⟨c, a • m, ?_⟩
    rw [TensorProduct.smul_tmul', smul_eq_mul, ha, TensorProduct.tmul_smul, ← algebraMap_smul ℚ_[p] a,
      TensorProduct.smul_tmul', smul_eq_mul, mul_one]
    rfl
  | add v w hv hw =>
    obtain ⟨c, m, hm⟩ := hv
    obtain ⟨d, n, hn⟩ := hw
    refine ⟨c + d, ((p ^ d : ℕ) : ℤ_[p]) • m + ((p ^ c : ℕ) : ℤ_[p]) • n, ?_⟩
    have e1 : ((p : ℚ_[p]) ^ (c + d)) • v = (1 : ℚ_[p]) ⊗ₜ[ℤ_[p]] (((p ^ d : ℕ) : ℤ_[p]) • m) := by
      rw [pow_add, mul_comm, mul_smul, hm, TensorProduct.tmul_smul,
        ← algebraMap_smul (A := ℚ_[p]) (R := ℤ_[p]) _ ((1 : ℚ_[p]) ⊗ₜ[ℤ_[p]] m)]
      simp
    have e2 : ((p : ℚ_[p]) ^ (c + d)) • w = (1 : ℚ_[p]) ⊗ₜ[ℤ_[p]] (((p ^ c : ℕ) : ℤ_[p]) • n) := by
      rw [pow_add, mul_smul, hn, TensorProduct.tmul_smul,
        ← algebraMap_smul (A := ℚ_[p]) (R := ℤ_[p]) _ ((1 : ℚ_[p]) ⊗ₜ[ℤ_[p]] n)]
      simp
    rw [smul_add, e1, e2, ← TensorProduct.tmul_add]

p2m_open_scoped "TensorProduct" in

theorem TensorProduct.mk_one_injective_of_flat (p : ℕ) [Fact p.Prime] {M : Type*} [AddCommGroup M] [Module ℤ_[p] M]
    [Module.Flat ℤ_[p] M] : Function.Injective (TensorProduct.mk ℤ_[p] ℚ_[p] M 1) := by
  have h1 : Function.Injective ((Algebra.linearMap ℤ_[p] ℚ_[p]).rTensor M) :=
    Module.Flat.rTensor_preserves_injective_linearMap _ (IsFractionRing.injective ℤ_[p] ℚ_[p])
  have h2 : (TensorProduct.mk ℤ_[p] ℚ_[p] M 1 : M → ℚ_[p] ⊗[ℤ_[p]] M)
      = ((Algebra.linearMap ℤ_[p] ℚ_[p]).rTensor M) ∘ (TensorProduct.lid ℤ_[p] M).symm := by
    funext m
    simp [LinearMap.rTensor_tmul]
  rw [h2]
  exact h1.comp (TensorProduct.lid ℤ_[p] M).symm.injective

p2m_open "TensorProduct P2MW.S_ModularCurve_exists_generator_tateModule_closure_inertia_smul_sub_adjoin_tateHeckeRep.TensorProduct"

namespace PadicInt p2m_export "PadicInt" "norm_p norm_int_lt_one_iff_dvd coe_add appr unitCoeff_spec coe_mul unitCoeff norm_le_one valuation ext mul_inv norm_le_pow_iff_mem_span_pow algebra coe_one coe_zero" end PadicInt
p2m_open_scoped "PadicInt" in

theorem PadicInt.eq_zero_of_forall_sq_sub_self_mul_mem_span_two_pow
    (b : ℤ_[2]) (n : ℕ → ℕ) (hn : ∀ k, 2 ≤ k → n k % 4 = 3)
    (hb : ∀ k, 2 ≤ k → ((n k : ℤ_[2]) ^ 2 - n k) * b ∈ Ideal.span {(2 : ℤ_[2]) ^ k}) :
    b = 0 := by
  have h2 : ‖(2 : ℤ_[2])‖ = 2⁻¹ := by exact_mod_cast PadicInt.norm_p (p := 2)

  have hodd : ∀ m : ℕ, m % 2 = 1 → ‖(m : ℤ_[2])‖ = 1 := by
    intro m hm
    refine le_antisymm (PadicInt.norm_le_one _) ?_
    by_contra hlt
    push Not at hlt
    have hlt' : ‖((m : ℤ) : ℤ_[2])‖ < 1 := by rwa [Int.cast_natCast]
    have := (PadicInt.norm_int_lt_one_iff_dvd (p := 2) (m : ℤ)).mp hlt'
    have h2m : (2 : ℤ) ∣ (m : ℤ) := by exact_mod_cast this
    omega
  have key : ∀ k : ℕ, 2 ≤ k → ‖b‖ ≤ (2 : ℝ) ^ (-((k : ℤ) - 1)) := by
    intro k hk
    have hmem := (PadicInt.norm_le_pow_iff_mem_span_pow _ k).mpr (hb k hk)
    obtain ⟨m, hm⟩ : ∃ m, n k = 4 * m + 3 :=
      ⟨n k / 4, by have := Nat.div_add_mod (n k) 4; rw [hn k hk] at this; omega⟩
    have hfac : ((n k : ℤ_[2]) ^ 2 - n k) * b = 2 * ((((4 * m + 3) * (2 * m + 1) : ℕ) : ℤ_[2]) * b) := by
      rw [hm]; push_cast; ring
    have hmodd : ((4 * m + 3) * (2 * m + 1)) % 2 = 1 :=
      Nat.odd_iff.mp (Nat.odd_mul.mpr ⟨by rw [Nat.odd_iff]; omega, by rw [Nat.odd_iff]; omega⟩)
    rw [hfac, norm_mul, norm_mul, h2, hodd _ hmodd, one_mul] at hmem
    have h2pos : (0 : ℝ) < 2 := by norm_num
    rw [show -((k : ℤ) - 1) = -(k : ℤ) + 1 by ring, zpow_add₀ (by norm_num : (2 : ℝ) ≠ 0), zpow_one]
    push_cast at hmem
    nlinarith [hmem, norm_nonneg b]

  by_contra hb0
  have hpos : 0 < ‖b‖ := norm_pos_iff.mpr hb0

  obtain ⟨k, hk⟩ : ∃ k : ℕ, (2 : ℝ) ^ (-((k : ℤ) - 1)) < ‖b‖ := by
    obtain ⟨k, hk⟩ := exists_pow_lt_of_lt_one hpos (by norm_num : (2⁻¹ : ℝ) < 1)
    refine ⟨k + 1, ?_⟩
    rw [show -(((k + 1 : ℕ) : ℤ) - 1) = -(k : ℤ) by push_cast; ring, zpow_neg, zpow_natCast, ← inv_pow]
    exact hk
  have hk2 : 2 ≤ k := by
    by_contra hlt
    push Not at hlt
    have : (1 : ℝ) ≤ (2 : ℝ) ^ (-((k : ℤ) - 1)) := by
      interval_cases k <;> norm_num
    have hb1 : ‖b‖ ≤ 1 := PadicInt.norm_le_one b
    linarith
  exact absurd (key k hk2) (not_le.mpr hk)

namespace AlgEquiv p2m_export "AlgEquiv" "ext mul_apply trans mk symm one_apply" end AlgEquiv
p2m_open_scoped "AlgEquiv" in

theorem AlgEquiv.mod_four_eq_three_of_apply_eq_pow_of_pow_four
    (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (h3 : ∀ ζ : AlgebraicClosure ℚ, ζ ^ 4 = 1 → σ ζ = ζ ^ 3)
    (k : ℕ) (hk : 2 ≤ k) (m : ℕ) (hm : ∀ ζ : AlgebraicClosure ℚ, ζ ^ (2 ^ k) = 1 → σ ζ = ζ ^ m) :
    m % 4 = 3 := by

  obtain ⟨i, hi⟩ : ∃ i : AlgebraicClosure ℚ, i ^ 2 = -1 := IsAlgClosed.exists_pow_nat_eq (-1) (by norm_num)
  have hi0 : i ≠ 0 := by rintro rfl; norm_num at hi
  have hi4 : i ^ 4 = 1 := by rw [show (4 : ℕ) = 2 * 2 by norm_num, pow_mul, hi]; norm_num
  have hne : (-1 : AlgebraicClosure ℚ) ≠ 1 := by norm_num
  have hprim : IsPrimitiveRoot i 4 := by
    refine IsPrimitiveRoot.mk_of_lt i (by norm_num) hi4 fun l hl1 hl4 => ?_
    interval_cases l
    · rw [pow_one]; intro h; rw [h, one_pow] at hi; exact hne hi.symm
    · rw [hi]; exact hne
    · rw [show (3 : ℕ) = 2 + 1 by norm_num, pow_add, hi, pow_one]
      intro h
      have h2 : i ^ 2 = 1 := by
        have : i = -1 := by
          calc i = -(-1 * i) := by ring
            _ = -1 := by rw [h]
        rw [this]; norm_num
      rw [hi] at h2; exact hne h2
  have hik : i ^ (2 ^ k) = 1 := by
    obtain ⟨j, rfl⟩ := Nat.exists_eq_add_of_le hk
    rw [pow_add, pow_mul, show (2 : ℕ) ^ 2 = 4 by norm_num, hi4, one_pow]
  have h := (hm i hik).symm.trans (h3 i hi4)

  have key : ∀ a b : ℕ, a ≤ b → i ^ a = i ^ b → 4 ∣ b - a := by
    intro a b hab hab'
    obtain ⟨c, rfl⟩ := Nat.exists_eq_add_of_le hab
    rw [Nat.add_sub_cancel_left, ← hprim.pow_eq_one_iff_dvd]
    rw [pow_add] at hab'
    exact mul_left_cancel₀ (pow_ne_zero a hi0) (hab'.symm.trans (mul_one _).symm)
  rcases le_total m 3 with hle | hle
  · have := key m 3 hle h; omega
  · have := key 3 m hle h.symm; omega

namespace Submodule p2m_export "Submodule" "inclusion factor closure_le smul_mem' mk smul_mem mem_span_singleton_self torsion span span_le mem_span_singleton baseChange zero one map algebraMap_mem subset_span module smul_def coe_add ext add span_induction coe_zero smul exists_eq_span_singleton_of_forall_bilin_eq_zero_of_isReduced" end Submodule
p2m_open_scoped "Submodule" in

theorem Submodule.exists_mem_forall_exists_pow_smul_eq_of_span_image_eq_span_singleton
    {R K : Type*} [CommRing R] [CommRing K] [Algebra R K] (π : R)
    {T : Type*} [AddCommGroup T] [Module R T]
    (𝒜 : Subalgebra R (Module.End R T)) (T' : Subalgebra K (Module.End K (TensorProduct R K T)))
    (hP : ∀ τ ∈ T', ∃ e : ℕ, ∃ α ∈ 𝒜,
      (algebraMap R K π ^ e) • (τ : Module.End K (TensorProduct R K T)) = (α : Module.End R T).baseChange K)
    (hι : Function.Injective (TensorProduct.mk R K T 1))
    (Λ : Submodule R T) (hΛ : ∀ α ∈ 𝒜, ∀ s ∈ Λ, α s ∈ Λ)
    (g : TensorProduct R K T)
    (hg : Submodule.span T' ((TensorProduct.mk R K T 1) '' (Λ : Set T)) = Submodule.span T' {g}) :
    ∃ s₀ ∈ Λ, ∀ s ∈ Λ, ∃ c : ℕ, ∃ α ∈ 𝒜, (π ^ c) • s = α s₀ := by
  classical
  set ι : T →ₗ[R] TensorProduct R K T := TensorProduct.mk R K T 1 with hιdef
  have hιs : ∀ (r : R) (s : T), ι (r • s) = algebraMap R K r • ι s := fun r s => by
    rw [map_smul, algebraMap_smul]
  have hbc : ∀ (α : Module.End R T) (s : T), (α.baseChange K) (ι s) = ι (α s) := fun α s => rfl

  have stepA : ∀ τ : T', ∀ s ∈ Λ, ∃ e : ℕ, ∃ s₁ ∈ Λ, (algebraMap R K π ^ e) • (τ • ι s) = ι s₁ ∧
      ∃ α ∈ 𝒜, s₁ = α s := by
    intro τ s hs
    obtain ⟨e, α, hα, he⟩ := hP τ τ.2
    refine ⟨e, α s, hΛ α hα s hs, ?_, α, hα, rfl⟩
    change (algebraMap R K π ^ e) • ((τ : Module.End K (TensorProduct R K T)) (ι s)) = ι (α s)
    rw [← LinearMap.smul_apply, he, hbc]

  have stepB : ∀ v ∈ Submodule.span T' (ι '' (Λ : Set T)), ∃ e : ℕ, ∃ s₁ ∈ Λ, (algebraMap R K π ^ e) • v = ι s₁ := by
    intro v hv
    induction hv using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨s, hs, rfl⟩ := hx
      exact ⟨0, s, hs, by rw [pow_zero, one_smul]⟩
    | zero => exact ⟨0, 0, Λ.zero_mem, by rw [smul_zero, map_zero]⟩
    | add x y _ _ hx hy =>
      obtain ⟨e, s₁, hs₁, h₁⟩ := hx
      obtain ⟨f, s₂, hs₂, h₂⟩ := hy
      refine ⟨e + f, π ^ f • s₁ + π ^ e • s₂, Λ.add_mem (Λ.smul_mem _ hs₁) (Λ.smul_mem _ hs₂), ?_⟩
      rw [smul_add, map_add, hιs, hιs, map_pow, map_pow, ← h₁, ← h₂, smul_smul, smul_smul, ← pow_add, ← pow_add,
        add_comm f e]
    | smul τ x _ hx =>
      obtain ⟨e, s₁, hs₁, h₁⟩ := hx
      obtain ⟨f, s₂, hs₂, h₂, -⟩ := stepA τ s₁ hs₁
      refine ⟨f + e, s₂, hs₂, ?_⟩
      rw [pow_add, mul_smul, ← h₂, ← h₁]

      congr 1
      exact (LinearMap.map_smul (τ : Module.End K (TensorProduct R K T)) _ x).symm

  have hgmem : g ∈ Submodule.span T' (ι '' (Λ : Set T)) := by
    rw [hg]; exact Submodule.mem_span_singleton_self g
  obtain ⟨d, s₀, hs₀, hd⟩ := stepB g hgmem
  refine ⟨s₀, hs₀, fun s hs => ?_⟩

  have hsmem : ι s ∈ Submodule.span T' {g} := by
    rw [← hg]; exact Submodule.subset_span ⟨s, hs, rfl⟩
  obtain ⟨τ, hτ⟩ := Submodule.mem_span_singleton.mp hsmem
  obtain ⟨e, α, hα, he⟩ := hP τ τ.2
  refine ⟨e + d, α, hα, hι ?_⟩
  change ι ((π ^ (e + d)) • s) = ι (α s₀)
  rw [hιs, map_pow, add_comm, pow_add, mul_smul, ← hτ]
  change (algebraMap R K π ^ d) • (((algebraMap R K π ^ e) • (τ : Module.End K (TensorProduct R K T))) g) = _
  rw [he, ← LinearMap.map_smul, hd, hbc]

namespace TateModule p2m_export "TateModule" "torsion compat_pow coe_add coe_zero smul_apply natCast_padicInt_smul_apply proj shiftOfProjEqZero pow_smul_shiftOfProjEqZero rep free finite" end TateModule
p2m_open_scoped "TateModule" in

theorem TateModule.bilin_apply_eq_zero_of_forall_proj_mem
    {M : Type} [AddCommGroup M] {G : Type} [Monoid G] [DistribMulAction G M]
    (cyc : ℕ → G → ℕ → Prop) (I : Set G) (C : AddSubgroup M)
    (hC : ∀ (k : ℕ) (n : G → ℕ), (∀ σ, cyc k σ (n σ)) → ∀ σ ∈ I, ∀ c ∈ C, 2 ^ k • c = 0 → σ • c = n σ • c)
    (hexp : ∀ k : ℕ, ∃ n : G → ℕ, ∀ σ, cyc k σ (n σ))
    {σ₀ : G} (hσ₀ : σ₀ ∈ I) (h3 : ∀ k : ℕ, 2 ≤ k → ∀ m : ℕ, cyc k σ₀ m → m % 4 = 3)
    (Bf : TateModule 2 M →ₗ[ℤ_[2]] TateModule 2 M →ₗ[ℤ_[2]] ℤ_[2])
    (hGal : ∀ (σ : G) (k nk : ℕ), cyc k σ nk → ∀ x y : TateModule 2 M,
      Bf (TateModule.rep 2 M G σ x) (TateModule.rep 2 M G σ y) - (nk : ℤ_[2]) * Bf x y ∈
        Ideal.span {((2 : ℕ) : ℤ_[2]) ^ k})
    (s s' : TateModule 2 M) (hs : ∀ k, TateModule.proj 2 M k s ∈ C) (hs' : ∀ k, TateModule.proj 2 M k s' ∈ C) :
    Bf s s' = 0 := by
  classical

  let n : ℕ → ℕ := fun k => Classical.choose (hexp k) σ₀
  have hn : ∀ k, ∀ σ, cyc k σ (Classical.choose (hexp k) σ) := fun k => Classical.choose_spec (hexp k)
  refine PadicInt.eq_zero_of_forall_sq_sub_self_mul_mem_span_two_pow (Bf s s') n
    (fun k hk => h3 k hk (n k) (hn k σ₀)) (fun k hk => ?_)

  have decomp : ∀ x : TateModule 2 M, (∀ k, TateModule.proj 2 M k x ∈ C) →
      ∃ u : TateModule 2 M, TateModule.rep 2 M G σ₀ x = (n k : ℤ_[2]) • x + ((2 : ℕ) : ℤ_[2]) ^ k • u := by
    intro x hx
    have h0 : TateModule.proj 2 M k (TateModule.rep 2 M G σ₀ x - (n k : ℤ_[2]) • x) = 0 := by
      rw [map_sub, sub_eq_zero]
      change σ₀ • (x : ℕ → M) k = (((n k : ℤ_[2]) • x : TateModule 2 M) : ℕ → M) k
      rw [TateModule.natCast_padicInt_smul_apply, natCast_zsmul]
      refine hC k _ (hn k) σ₀ hσ₀ _ (hx k) ?_
      have := TateModule.torsion x k
      rwa [natCast_zsmul] at this
    refine ⟨TateModule.shiftOfProjEqZero k _ h0, ?_⟩
    rw [TateModule.pow_smul_shiftOfProjEqZero k _ h0, add_sub_cancel]
  obtain ⟨u, hu⟩ := decomp s hs
  obtain ⟨u', hu'⟩ := decomp s' hs'
  have h1 := hGal σ₀ k (n k) (hn k σ₀) s s'
  have h2 : Bf (TateModule.rep 2 M G σ₀ s) (TateModule.rep 2 M G σ₀ s') - (n k : ℤ_[2]) ^ 2 * Bf s s' ∈
      Ideal.span {((2 : ℕ) : ℤ_[2]) ^ k} := by
    refine Ideal.mem_span_singleton.mpr
      ⟨(n k : ℤ_[2]) * Bf s u' + ((n k : ℤ_[2]) * Bf u s' + ((2 : ℕ) : ℤ_[2]) ^ k * Bf u u'), ?_⟩
    rw [hu, hu']
    simp only [map_add, map_smul, LinearMap.add_apply, LinearMap.smul_apply, smul_eq_mul]
    ring
  have h12 := Ideal.sub_mem _ h1 h2
  have h12' : ((n k : ℤ_[2]) ^ 2 - n k) * Bf s s' ∈ Ideal.span {((2 : ℕ) : ℤ_[2]) ^ k} := by
    convert h12 using 1
    ring
  simpa only [Nat.cast_ofNat] using h12'

open ModularCurve
p2m_open_scoped "TensorProduct P2MW.S_ModularCurve_exists_generator_tateModule_closure_inertia_smul_sub_adjoin_tateHeckeRep.TensorProduct IsMulCommutative"

namespace HCYC

section TateFree
variable (p : ℕ) [Fact p.Prime] (M : Type) [AddCommGroup M]

theorem tateModule_eq_zero_of_pow_smul_eq_zero (k : ℕ) (x : TateModule p M)
    (hx : ((p : ℤ_[p]) ^ k) • x = 0) : x = 0 := by
  refine Subtype.ext (funext fun n => ?_)
  have h := congrArg (fun y : TateModule p M => (y : ℕ → M) (n + k)) hx
  try simp only at h
  rw [show ((p : ℤ_[p]) ^ k) = ((p ^ k : ℕ) : ℤ_[p]) by push_cast; rfl, TateModule.natCast_padicInt_smul_apply,
    TateModule.compat_pow] at h
  rw [h]
  rfl

scoped instance isTorsionFree : Module.IsTorsionFree ℤ_[p] (TateModule p M) := by
  refine ⟨fun a ha => ?_⟩
  intro x y hxy
  have ha0 : a ≠ 0 := ha.ne_zero
  have h0 : a • (x - y) = 0 := by rw [smul_sub]; exact sub_eq_zero.mpr hxy
  have h1 : ((p : ℤ_[p]) ^ a.valuation) • (x - y) = 0 := by
    have hu : IsUnit ((PadicInt.unitCoeff ha0 : ℤ_[p]ˣ) : ℤ_[p]) := Units.isUnit _
    rw [PadicInt.unitCoeff_spec ha0, mul_smul] at h0
    exact hu.smul_left_cancel.mp (h0.trans (smul_zero _).symm)
  exact sub_eq_zero.mp (tateModule_eq_zero_of_pow_smul_eq_zero p M _ _ h1)

end TateFree

section Main

variable {J : Type} [AddCommGroup J] [Module HeckeAlg J]
variable {G : Type} [Group G] [DistribMulAction G J] [SMulCommClass G HeckeAlg J]
variable (I : Set G) (E : ℕ → AddSubgroup J)

local notation "T" => TateModule 2 J
local notation "V" => RationalTateModule 2 J

def displacement : AddSubgroup J :=
  AddSubgroup.closure {w : J | ∃ σ ∈ I, ∃ M : ℕ, ∃ x ∈ E M, w = σ • x - x}

def lam : Submodule ℤ_[2] T where
  carrier := {s | ∀ n, (s : ℕ → J) n ∈ displacement I E}
  add_mem' {s t} hs ht n := by
    rw [TateModule.coe_add, Pi.add_apply]; exact add_mem (hs n) (ht n)
  zero_mem' n := by rw [TateModule.coe_zero, Pi.zero_apply]; exact zero_mem _
  smul_mem' a s hs n := by
    rw [TateModule.smul_apply]; exact AddSubgroup.zsmul_mem _ (hs n) _

theorem mem_lam_iff (s : T) : s ∈ lam I E ↔ ∀ n, (s : ℕ → J) n ∈ displacement I E := Iff.rfl

variable (hE : ∀ (M : ℕ) (t : HeckeAlg) (x : J), x ∈ E M → t • x ∈ E M)
include hE in

theorem hecke_smul_mem_displacement (t : HeckeAlg) {w : J} (hw : w ∈ displacement I E) :
    t • w ∈ displacement I E := by
  let f : J →+ J := DistribSMul.toAddMonoidHom J t
  have hgen : ∀ w ∈ {w : J | ∃ σ ∈ I, ∃ M : ℕ, ∃ x ∈ E M, w = σ • x - x}, f w ∈ displacement I E := by
    rintro _ ⟨σ, hσ, M, x, hx, rfl⟩
    refine AddSubgroup.subset_closure ⟨σ, hσ, M, t • x, hE M t x hx, ?_⟩
    show t • (σ • x - x) = σ • (t • x) - t • x
    rw [smul_sub]
    congr 1
    exact (smul_comm σ t x).symm
  have hle : (displacement I E).map f ≤ displacement I E := by
    rw [displacement, AddMonoidHom.map_closure]
    exact (AddSubgroup.closure_le _).mpr (by rintro _ ⟨w, hw, rfl⟩; exact hgen w hw)
  exact hle ⟨w, hw, rfl⟩

include hE in
theorem tateHeckeRep_mem_lam (t : HeckeAlg) {s : T} (hs : s ∈ lam I E) :
    tateHeckeRep 2 J t s ∈ lam I E := fun n => by
  rw [coe_tateHeckeRep_apply_apply]
  exact hecke_smul_mem_displacement I E hE t (hs n)

include hE in

theorem adjoin_apply_mem_lam :
    ∀ α ∈ Algebra.adjoin ℤ_[2] (Set.range fun t : HeckeAlg => tateHeckeRep 2 J t), ∀ s ∈ lam I E, α s ∈ lam I E := by
  intro α hα
  refine Algebra.adjoin_induction (hx := hα) ?_ ?_ ?_ ?_
  · rintro _ ⟨t, rfl⟩ s hs; exact tateHeckeRep_mem_lam I E hE t hs
  · intro a s hs
    rw [Module.algebraMap_end_apply]; exact Submodule.smul_mem _ a hs
  · intro α β _ _ hα hβ s hs; rw [LinearMap.add_apply]; exact add_mem (hα s hs) (hβ s hs)
  · intro α β _ _ hα hβ s hs; rw [Module.End.mul_apply]; exact hα _ (hβ s hs)

variable (J) in

noncomputable abbrev ι : T →ₗ[ℤ_[2]] V := TensorProduct.mk ℤ_[2] ℚ_[2] T 1

theorem ι_injective [Module.Finite ℤ_[2] T] : Function.Injective (ι J) := by
  haveI : Module.Free ℤ_[2] T := Module.free_of_finite_type_torsion_free'
  exact TensorProduct.mk_one_injective_of_flat 2

variable (J) in

scoped instance isMulCommutative_rationalHeckeAlgebra : IsMulCommutative ↥(rationalHeckeAlgebra 2 J) :=
  Algebra.isMulCommutative_adjoin ℚ_[2] (by
    rintro _ ⟨t, rfl⟩ _ ⟨t', rfl⟩
    rw [← map_mul, ← map_mul, mul_comm])

scoped instance finiteDimensional_rationalHeckeAlgebra [Module.Finite ℤ_[2] T] :
    FiniteDimensional ℚ_[2] ↥(rationalHeckeAlgebra 2 J) := by
  haveI : Module.Finite ℚ_[2] V := inferInstance
  exact FiniteDimensional.finiteDimensional_submodule (Subalgebra.toSubmodule (rationalHeckeAlgebra 2 J))

variable (J) in

noncomputable def BQ (Bf : T →ₗ[ℤ_[2]] T →ₗ[ℤ_[2]] ℤ_[2]) : V →ₗ[ℚ_[2]] V →ₗ[ℚ_[2]] ℚ_[2] :=
  LinearMap.BilinForm.baseChange ℚ_[2] Bf

theorem BQ_tmul (Bf : T →ₗ[ℤ_[2]] T →ₗ[ℤ_[2]] ℤ_[2]) (a b : ℚ_[2]) (x y : T) :
    BQ J Bf (a ⊗ₜ x) (b ⊗ₜ y) = (Bf x y) • (a * b) :=
  LinearMap.BilinForm.baseChange_tmul _ _ _ _ _

theorem BQ_left_nondegenerate (Bf : T →ₗ[ℤ_[2]] T →ₗ[ℤ_[2]] ℤ_[2]) (hBl : ∀ x, (∀ y, Bf x y = 0) → x = 0) :
    ∀ v : V, (∀ w, BQ J Bf v w = 0) → v = 0 := by
  intro v hv
  obtain ⟨c, x, hx⟩ := TensorProduct.exists_pow_smul_eq_one_tmul 2 v
  have hx0 : x = 0 := by
    refine hBl x fun y => ?_
    have h' : BQ J Bf ((((2 : ℕ) : ℚ_[2]) ^ c) • v) ((1 : ℚ_[2]) ⊗ₜ y) = 0 := by
      rw [LinearMap.map_smul₂, hv, smul_zero]
    rw [hx, BQ_tmul, mul_one, Algebra.smul_def, mul_one] at h'
    exact Subtype.ext h'
  have h2 : (((2 : ℕ) : ℚ_[2]) ^ c) • v = 0 := by rw [hx, hx0, TensorProduct.tmul_zero]
  exact (smul_eq_zero.mp h2).resolve_left (pow_ne_zero _ (by norm_num))

theorem BQ_balanced (Bf : T →ₗ[ℤ_[2]] T →ₗ[ℤ_[2]] ℤ_[2])
    (hBt : ∀ (t : HeckeAlg) (x y : T), Bf (tateHeckeRep 2 J t x) y = Bf x (tateHeckeRep 2 J t y)) :
    ∀ τ ∈ rationalHeckeAlgebra 2 J, ∀ v w : V,
      BQ J Bf ((τ : Module.End ℚ_[2] V) v) w = BQ J Bf v ((τ : Module.End ℚ_[2] V) w) := by
  intro τ hτ
  refine Algebra.adjoin_induction (hx := hτ) ?_ ?_ ?_ ?_
  · rintro _ ⟨t, rfl⟩ v w
    induction v using TensorProduct.induction_on with
    | zero => simp
    | tmul a x =>
      induction w using TensorProduct.induction_on with
      | zero => simp
      | tmul b y => rw [rationalHeckeRep_tmul, rationalHeckeRep_tmul, BQ_tmul, BQ_tmul, hBt]
      | add w w' hw hw' => rw [map_add, map_add, hw, hw', map_add]
    | add v v' hv hv' => simp only [map_add, LinearMap.add_apply, hv, hv']
  · intro a v w
    rw [Algebra.algebraMap_eq_smul_one, LinearMap.smul_apply, LinearMap.smul_apply, Module.End.one_apply,
      Module.End.one_apply, LinearMap.map_smul₂, LinearMap.map_smul]
  · intro α β _ _ hα hβ v w
    rw [LinearMap.add_apply, LinearMap.add_apply, map_add, LinearMap.add_apply, hα, hβ, map_add]
  · intro α β hαm hβm hα hβ v w
    have hcomm : α * β = β * α :=
      congrArg Subtype.val (mul_comm (⟨α, hαm⟩ : ↥(rationalHeckeAlgebra 2 J)) ⟨β, hβm⟩)
    conv_rhs => rw [hcomm]
    rw [Module.End.mul_apply, Module.End.mul_apply, hα, hβ]

include hE in
theorem span_stable :
    ∀ τ ∈ rationalHeckeAlgebra 2 J, ∀ v ∈ Submodule.span ℚ_[2] ((ι J) '' (lam I E : Set T)),
      (τ : Module.End ℚ_[2] V) v ∈ Submodule.span ℚ_[2] ((ι J) '' (lam I E : Set T)) := by
  intro τ hτ
  refine Algebra.adjoin_induction (hx := hτ) ?_ ?_ ?_ ?_
  · rintro _ ⟨t, rfl⟩ v hv
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hv
    · rintro _ ⟨s, hs, rfl⟩
      exact Submodule.subset_span ⟨_, tateHeckeRep_mem_lam I E hE t hs, (rationalHeckeRep_tmul _ _ _ _ _).symm⟩
    · simp
    · intro v w _ _ hv hw; rw [map_add]; exact add_mem hv hw
    · intro a v _ hv; rw [map_smul]; exact Submodule.smul_mem _ a hv
  · intro a v hv
    rw [Module.algebraMap_end_apply]; exact Submodule.smul_mem _ a hv
  · intro α β _ _ hα hβ v hv; rw [LinearMap.add_apply]; exact add_mem (hα v hv) (hβ v hv)
  · intro α β _ _ hα hβ v hv; rw [Module.End.mul_apply]; exact hα _ (hβ v hv)

noncomputable def N : Submodule ↥(rationalHeckeAlgebra 2 J) V where
  carrier := Submodule.span ℚ_[2] ((ι J) '' (lam I E : Set T))
  add_mem' := add_mem
  zero_mem' := zero_mem _
  smul_mem' τ v hv := span_stable I E hE τ τ.2 v hv

theorem mem_N_iff (v : V) : v ∈ N I E hE ↔ v ∈ Submodule.span ℚ_[2] ((ι J) '' (lam I E : Set T)) := Iff.rfl

theorem N_eq_span : N I E hE = Submodule.span ↥(rationalHeckeAlgebra 2 J) ((ι J) '' (lam I E : Set T)) := by
  apply le_antisymm
  · intro v hv
    rw [mem_N_iff] at hv
    refine Submodule.span_induction (fun v hv => Submodule.subset_span hv) (zero_mem _)
      (fun _ _ _ _ h h' => add_mem h h') (fun a v _ h => ?_) hv
    rw [← algebraMap_smul (A := ↥(rationalHeckeAlgebra 2 J))]
    exact Submodule.smul_mem _ _ h
  · exact Submodule.span_le.mpr fun v hv => Submodule.subset_span hv

theorem N_isotropic (Bf : T →ₗ[ℤ_[2]] T →ₗ[ℤ_[2]] ℤ_[2]) (hISO : ∀ s ∈ lam I E, ∀ s' ∈ lam I E, Bf s s' = 0) :
    ∀ v ∈ N I E hE, ∀ w ∈ N I E hE, BQ J Bf v w = 0 := by
  intro v hv w hw
  rw [mem_N_iff] at hv hw
  refine Submodule.span_induction ?_ (by simp) (fun v v' _ _ h h' => by rw [map_add, LinearMap.add_apply, h, h', add_zero])
    (fun a v _ h => by rw [map_smul, LinearMap.smul_apply, h, smul_zero]) hv
  rintro _ ⟨s, hs, rfl⟩
  refine Submodule.span_induction ?_ (by simp) (fun w w' _ _ h h' => by rw [map_add, h, h', add_zero])
    (fun a w _ h => by rw [map_smul, h, smul_zero]) hw
  rintro _ ⟨s', hs', rfl⟩
  show BQ J Bf ((1 : ℚ_[2]) ⊗ₜ s) ((1 : ℚ_[2]) ⊗ₜ s') = 0
  rw [BQ_tmul, hISO s hs s' hs', zero_smul]

theorem baseChange_smul_end (a : ℤ_[2]) (f : Module.End ℤ_[2] T) :
    (a • f).baseChange ℚ_[2] = (algebraMap ℤ_[2] ℚ_[2] a) • f.baseChange ℚ_[2] := by
  rw [LinearMap.baseChange_smul, algebraMap_smul]

theorem baseChange_one_end : (1 : Module.End ℤ_[2] T).baseChange ℚ_[2] = (1 : Module.End ℚ_[2] V) := by
  rw [Module.End.one_eq_id, LinearMap.baseChange_id, Module.End.one_eq_id]

theorem baseChange_mul_end (f g : Module.End ℤ_[2] T) :
    (f * g).baseChange ℚ_[2] = f.baseChange ℚ_[2] * g.baseChange ℚ_[2] := by
  rw [Module.End.mul_eq_comp, LinearMap.baseChange_comp, Module.End.mul_eq_comp]

theorem exists_pow_smul_eq_baseChange :
    ∀ τ ∈ rationalHeckeAlgebra 2 J, ∃ e : ℕ, ∃ α ∈ Algebra.adjoin ℤ_[2] (Set.range fun t : HeckeAlg => tateHeckeRep 2 J t),
      (algebraMap ℤ_[2] ℚ_[2] 2 ^ e) • (τ : Module.End ℚ_[2] V) = (α : Module.End ℤ_[2] T).baseChange ℚ_[2] := by
  intro τ hτ
  have h2 : algebraMap ℤ_[2] ℚ_[2] 2 = ((2 : ℕ) : ℚ_[2]) := by rw [map_ofNat]; norm_num
  refine Algebra.adjoin_induction (hx := hτ) ?_ ?_ ?_ ?_
  · rintro _ ⟨t, rfl⟩
    exact ⟨0, tateHeckeRep 2 J t, Algebra.subset_adjoin ⟨t, rfl⟩, by rw [pow_zero, one_smul]; rfl⟩
  · intro q
    obtain ⟨e, a, ha⟩ := PadicInt.exists_pow_mul_eq_coe 2 q
    refine ⟨e, algebraMap ℤ_[2] _ a, Subalgebra.algebraMap_mem _ a, ?_⟩
    rw [h2, Algebra.algebraMap_eq_smul_one, Algebra.algebraMap_eq_smul_one, smul_smul, ha, baseChange_smul_end,
      baseChange_one_end]
    rfl
  · rintro α β - - ⟨e, a, ha, hα⟩ ⟨e', a', ha', hβ⟩
    refine ⟨e + e', ((2 : ℤ_[2]) ^ e') • a + ((2 : ℤ_[2]) ^ e) • a',
      add_mem (Subalgebra.smul_mem _ ha _) (Subalgebra.smul_mem _ ha' _), ?_⟩
    rw [smul_add, pow_add, mul_comm, mul_smul, hα, mul_comm, mul_smul, hβ, LinearMap.baseChange_add,
      baseChange_smul_end, baseChange_smul_end, map_pow, map_pow]
  · rintro α β - - ⟨e, a, ha, hα⟩ ⟨e', a', ha', hβ⟩
    refine ⟨e + e', a * a', mul_mem ha ha', ?_⟩
    rw [baseChange_mul_end, ← hα, ← hβ, pow_add, smul_mul_smul_comm]

include hE in

theorem main [Module.Finite ℤ_[2] T] [IsReduced ↥(rationalHeckeAlgebra 2 J)]
    (b : Module.Basis (Fin 2) ↥(rationalHeckeAlgebra 2 J) V)
    (cyc : ℕ → G → ℕ → Prop)
    (C : AddSubgroup J)
    (hC : ∀ (k : ℕ) (n : G → ℕ), (∀ σ, cyc k σ (n σ)) → ∀ σ ∈ I, ∀ c ∈ C, 2 ^ k • c = 0 → σ • c = n σ • c)
    (hDC : ∀ σ ∈ I, ∀ M : ℕ, ∀ x ∈ E M, σ • x - x ∈ C)
    (hexp : ∀ k, ∃ n : G → ℕ, ∀ σ, cyc k σ (n σ))
    {σ₀ : G} (hσ₀ : σ₀ ∈ I) (h3 : ∀ k, 2 ≤ k → ∀ m, cyc k σ₀ m → m % 4 = 3)
    (Bf : T →ₗ[ℤ_[2]] T →ₗ[ℤ_[2]] ℤ_[2])
    (hBl : ∀ x, (∀ y, Bf x y = 0) → x = 0)
    (hBt : ∀ (t : HeckeAlg) (x y : T), Bf (tateHeckeRep 2 J t x) y = Bf x (tateHeckeRep 2 J t y))
    (hGal : ∀ (σ : G) (k nk : ℕ), cyc k σ nk → ∀ x y : T,
      Bf (TateModule.rep 2 J G σ x) (TateModule.rep 2 J G σ y) - (nk : ℤ_[2]) * Bf x y ∈ Ideal.span {((2 : ℕ) : ℤ_[2]) ^ k}) :
    ∃ s₀ : T, (∀ n : ℕ, (s₀ : ℕ → J) n ∈ displacement I E) ∧
      ∀ s : T, (∀ n : ℕ, (s : ℕ → J) n ∈ displacement I E) →
        ∃ c : ℕ, ∃ α ∈ Algebra.adjoin ℤ_[2] (Set.range fun t : HeckeAlg => tateHeckeRep 2 J t),
          ((2 : ℤ_[2]) ^ c) • s = α s₀ := by

  have hD_le_C : displacement I E ≤ C :=
    (AddSubgroup.closure_le _).mpr (by rintro _ ⟨σ, hσ, M, x, hx, rfl⟩; exact hDC σ hσ M x hx)
  have hISO : ∀ s ∈ lam I E, ∀ s' ∈ lam I E, Bf s s' = 0 := fun s hs s' hs' =>
    TateModule.bilin_apply_eq_zero_of_forall_proj_mem cyc I C hC hexp hσ₀ h3 Bf hGal s s'
      (fun k => hD_le_C (hs k)) (fun k => hD_le_C (hs' k))

  obtain ⟨g, hg⟩ := Submodule.exists_eq_span_singleton_of_forall_bilin_eq_zero_of_isReduced
    b.equivFun (BQ J Bf) (BQ_left_nondegenerate Bf hBl)
    (fun (τ : ↥(rationalHeckeAlgebra 2 J)) v w => by exact BQ_balanced Bf hBt τ.1 τ.2 v w)
    (N I E hE) (N_isotropic I E hE Bf hISO)

  have hg' : Submodule.span ↥(rationalHeckeAlgebra 2 J) ((TensorProduct.mk ℤ_[2] ℚ_[2] T 1) '' (lam I E : Set T))
      = Submodule.span ↥(rationalHeckeAlgebra 2 J) {g} := by rw [← hg, N_eq_span]
  obtain ⟨s₀, hs₀, H⟩ := Submodule.exists_mem_forall_exists_pow_smul_eq_of_span_image_eq_span_singleton (2 : ℤ_[2])
    (Algebra.adjoin ℤ_[2] (Set.range fun t : HeckeAlg => tateHeckeRep 2 J t)) (rationalHeckeAlgebra 2 J)
    (exists_pow_smul_eq_baseChange) (ι_injective) (lam I E) (adjoin_apply_mem_lam I E hE) g hg'
  exact ⟨s₀, hs₀, fun s hs => H s hs⟩

end Main
end HCYC
p2m_reactivate "P2MW.S_ModularCurve_exists_generator_tateModule_closure_inertia_smul_sub_adjoin_tateHeckeRep.HCYC"

open ModularCurve in
theorem solution
    (p : ℕ) [Fact p.Prime]
    (B : ValuationSubring (AlgebraicClosure ℚ)) (hB : B.LiesOverPrime 2) :
    letI := heckeModuleBar p
    ∃ s₀ : TateModule 2 (JZero p),
      (∀ n : ℕ, (s₀ : ℕ → JZero p) n ∈ AddSubgroup.closure {w : JZero p | ∃ σ ∈ B.inertiaSubgroupIn ℚ, ∃ M : ℕ, ∃ x ∈ eisensteinTorsionBar p 2 M, w = σ • x - x}) ∧
      ∀ s : TateModule 2 (JZero p),
        (∀ n : ℕ, (s : ℕ → JZero p) n ∈ AddSubgroup.closure {w : JZero p | ∃ σ ∈ B.inertiaSubgroupIn ℚ, ∃ M : ℕ, ∃ x ∈ eisensteinTorsionBar p 2 M, w = σ • x - x}) →
        ∃ c : ℕ, ∃ α ∈ Algebra.adjoin ℤ_[2] (Set.range fun t : HeckeAlg => tateHeckeRep 2 (JZero p) t),
          ((2 : ℤ_[2]) ^ c) • s = α s₀ := by
  letI := heckeModuleBar p
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩

  haveI : SMulCommClass (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) HeckeAlg (JZero p) :=
    smulCommClass_JZero_of_heckeOperatorsCommuteBar p (heckeOperatorsCommuteBar p)

  haveI : Module.Finite ℤ_[2] (TateModule 2 (JZero p)) := moduleFinite_padicInt_tateModule_jZero p 2

  haveI : IsReduced ↥(rationalHeckeAlgebra 2 (JZero p)) := isReduced_rationalHeckeAlgebra p 2

  obtain ⟨b, -⟩ := rationalRankTwoCyclotomic_family p 2 (Fact.out : p.Prime).pos Nat.prime_two

  obtain ⟨Bf, hBl, -, hBt, hGal⟩ := exists_bilinForm_tateModule_nondegenerate_hecke_galois p 2

  obtain ⟨C, -, -, hC, hDC⟩ :=
    exists_addSubgroup_eisensteinTorsionBar_two_nsmul_surjOn_inertia_smul_eq_nat_smul_smul_sub_mem p B hB

  obtain ⟨σ₀, hσ₀, h964⟩ := ValuationSubring.exists_mem_inertiaSubgroupIn_apply_eq_pow_three_of_pow_four_eq_one B hB
  exact HCYC.main (J := JZero p) (G := AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
    (B.inertiaSubgroupIn ℚ : Set (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ))
    (fun M => eisensteinTorsionBar p 2 M)
    (fun M t x hx => Submodule.smul_mem _ t hx)
    b (fun k σ m => ∀ ζ : AlgebraicClosure ℚ, ζ ^ (2 ^ k) = 1 → σ ζ = ζ ^ m) C hC hDC
    AlgebraicClosure.exists_forall_apply_eq_pow_of_pow_eq_one hσ₀
    (fun k hk m hm => AlgEquiv.mod_four_eq_three_of_apply_eq_pow_of_pow_four σ₀ h964 k hk m hm) Bf hBl hBt hGal

end S_ModularCurve_exists_generator_tateModule_closure_inertia_smul_sub_adjoin_tateHeckeRep
end P2MW
export P2MW.S_ModularCurve_exists_generator_tateModule_closure_inertia_smul_sub_adjoin_tateHeckeRep (solution)
