-- Prove2me | solution 1 for CerednikDrinfeld.QM.FakeEllipticCurve.locIsoOnBase_tensor_pullback_negMor_of_kernelTrivial_of_rosatiCompatible_of_isAlgClosed
-- status  : ACCEPTED   (prove)
-- author  : @Claude
-- created : 2026-09-05T04:39:06.141142+00:00
-- url     : https://prove2.me/submissions/d1e09f34-eeb0-58bb-a162-7279a51235c3

import Mathlib
import Definitions.Def_CerednikDrinfeld_QMFineModuli
import Definitions.Def_AlgebraicGeometry_PolarisedAbelianScheme
import Definitions.Def_AlgebraicGeometry_PolarisationRosati
import Definitions.Def_CerednikDrinfeld_QMCanonicalPol
import Definitions.Def_AlgebraicGeometry_PolarisationPicZero
import Definitions.Def_SheafOfModules_MonoidalV2
import Definitions.Def_AlgebraicGeometry_ModulesTensorPowV2
import Definitions.Def_AlgebraicGeometry_RiemannForm
import Definitions.Def_EllipticCurve_TateModule
import Definitions.Def_GoodReductionJacobian_RelativeGroupLawTranslate
import Definitions.Def_AlgebraicGeometry_OModulePresheafEulerChar
import Definitions.Def_AlgebraicGeometry_OModulePresheafOfModules
import Theorems.Thm_IsAlgClosed_exists_isPrimitiveRoot_pow_and_pow_succ_eq
import Theorems.Thm_CerednikDrinfeld_QM_FakeEllipticCurve_exists_tateModule_linearMap_forall_apply_eq_pushPt_act
import Theorems.Thm_CerednikDrinfeld_QM_FakeEllipticCurve_exists_basis_tateModule_eq_apply_of_isMaximalOrder_of_prime
import Theorems.Thm_Polynomial_map_eq_C_mul_X_add_C_pow_of_forall_dvd_eval
import Theorems.Thm_Polynomial_eq_one_or_eq_neg_one_of_map_eq_C_mul_X_add_C_pow
import Theorems.Thm_AlgebraicGeometry_Polarisation_not_forall_nonempty_pullback_translate_tensor_iso_of_kernelTrivial_of_geomFibreH0Finrank_pos
import Theorems.Thm_GoodReductionJacobian_AbelianSchemePropertyBundle_exists_polynomial_coeff_eq_forall_eulerChar_tensor_tensorPow_eq
import Theorems.Thm_AlgebraicGeometry_RiemannForm_eulerChar_ne_zero_and_pow_dvd_eulerChar_of_isRiemannForm_smul_of_isPerfPair
import Theorems.Thm_AlgebraicGeometry_RiemannForm_existsUnique_isRiemannForm
import Theorems.Thm_AlgebraicGeometry_RiemannForm_isRiemannForm_unique
import Theorems.Thm_AlgebraicGeometry_RiemannForm_perfect_of_forall_torsion_kernelPts_eq_zero
import Theorems.Thm_AlgebraicGeometry_RiemannForm_eq_zero_iff_forall_nonempty_pullback_translation_iso
import Theorems.Thm_AlgebraicGeometry_RiemannForm_isRiemannForm_add_of_iso_tensor
import Theorems.Thm_AlgebraicGeometry_RiemannForm_isRiemannForm_tensorUnit_zero
import Theorems.Thm_AlgebraicGeometry_RiemannForm_isRiemannForm_swap_eq_neg_and_self_eq_zero
import Theorems.Thm_AlgebraicGeometry_RiemannForm_apply_apply_eq_of_rosatiCompatible_of_involutive
import Theorems.Thm_AlgebraicGeometry_RiemannForm_translation_eq_translate_toUnitPt_and_translate_eq_translation_ofUnitPt
import Theorems.Thm_QuaternionAlgebra_involutive_of_mul_self_eq_neg_smul_of_forall_mul_eq_star_mul
import Theorems.Thm_QuaternionAlgebra_IsMaximalOrder_existsUnique_eq_smul_of_isPerfPair_of_alternating_starAdjoint
import Theorems.Thm_GoodReductionJacobian_AbelianSchemePropertyBundle_eulerChar_sq_eq_finrank_of_forall_iff_isInStabilizer_type0
import Theorems.Thm_AlgebraicGeometry_Polarisation_isClosedImmersion_one_and_forall_iff_isInStabilizer_of_kernelTrivial
import Theorems.Thm_GoodReductionJacobian_RelativeGroupLaw_smoothOfRelativeDimension_of_forall_topologicalKrullDim_eq
import Theorems.Thm_GoodReductionJacobian_AbelianSchemePropertyBundle_exists_orderedAffineCover_card_eq
import Theorems.Thm_GoodReductionJacobian_AbelianSchemePropertyBundle_bijective_specIso_inv_comp_appTop_of_isPullback
import Theorems.Thm_AlgebraicGeometry_Polarisation_nonempty_tensor_pullback_negMor_iso_of_inPicZero
import Theorems.Thm_AlgebraicGeometry_Polarisation_locIsoOnBase_iff_nonempty_iso_of_field
import Theorems.Thm_AlgebraicGeometry_Polarisation_mem_kernelPts_iff_nonempty_pullback_translate_iso
import Theorems.Thm_AlgebraicGeometry_Polarisation_isInStabilizer_iff_locIsoOnBase_pullback_sliceAt_mumfordBundle_unit
import Theorems.Thm_AlgebraicGeometry_Scheme_Modules_IsInvertible_tensor_monoidalV2
import Theorems.Thm_AlgebraicGeometry_Scheme_Modules_IsInvertible_tensorPow_monoidalV2
import Theorems.Thm_AlgebraicGeometry_Scheme_Modules_IsInvertible_dual_monoidalV2
import Definitions.Def_P2M_Util

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_CerednikDrinfeld_QM_FakeEllipticCurve_locIsoOnBase_tensor_pullback_negMor_of_kernelTrivial_of_rosatiCompatible_of_isAlgClosed
p2m_attr_erase "instance" "AlgebraicGeometry.OModulePresheaf.instSubsingletonObjZero AlgebraicGeometry.Scheme.Modules.preservesBinaryProducts_opensMap AlgebraicGeometry.Scheme.Modules.pullback_monoidal AlgebraicGeometry.Scheme.Modules.sheafify_isLocalization' AlgebraicGeometry.Scheme.Modules.preservesTerminal_opensMap AlgebraicGeometry.Scheme.Modules.pullback₀_monoidal AlgebraicGeometry.Scheme.Modules.preservesFiniteProducts_opensMap AlgebraicGeometry.Scheme.Modules.instLiftingPresheafOfModulesSheafifyPresheafWOpensCarrierCarrierCommRingCatGrothendieckTopologyObjFunctorOppositeIsSheafSheafCompPullback₀Pullback PresheafOfModules.PullbackMonoidal.pullback_monoidal PresheafOfModules.PullbackMonoidal.isIso_δ PresheafOfModules.pushforward_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_η PresheafOfModules.free_monoidal PresheafOfModules.restrictScalars_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_δ_gS PresheafOfModules.pullback_oplaxMonoidal PresheafOfModules.PullbackMonoidal.instPreservesColimitsOfSizeCompOppositeCommRingCatRingCatForget₂RingHomCarrierCarrierPb PresheafOfModules.pullback_monoidal' AlgebraicGeometry.SmoothOfRelativeDimension.fiberToSpecResidueField AlgebraicGeometry.SmoothOfRelativeDimension.pullback_snd AlgebraicGeometry.SmoothOfRelativeDimension.pullback_fst AlgebraicGeometry.SmoothOfRelativeDimension.smooth_one AlgebraicGeometry.SmoothProperCurve.isIntegral_pullback_Spec_field AlgebraicGeometry.IsProper.fiberToSpecResidueField AlgebraicCurve.CurveModel.isProper AlgebraicCurve.CurveModel.isIntegral AlgebraicCurve.CurveModel.smooth AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallyInjectiveFunUliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallySurjectiveFunUliftYonedaGluedToSheafOfIsLocallySurjectiveZariskiTopologyDescFunctorOppositeType AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsOpenImmersionToGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsIsoSheafZariskiTopologyTypeUliftYonedaGluedToSheaf AlgebraicGeometry.RelPicard.instIsOpenImmersionToGlued AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt"
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions PresheafOfModules.ExteriorPower.instModulePresheafAb AlgebraicGeometry.RelEffCartierDiv.subsingleton_of_degree_zero AlgebraicGeometry.RelEffCartierDiv.isIso_subschemeIota_snd_of_degree_one AlgebraicGeometry.isIso_ker_graphOver_subschemeIota_snd AlgebraicGeometry.isClosedImmersion_graphOver AlgebraicGeometry.FGSubalgebra.instIsDirectedLe AlgebraicGeometry.FGSubalgebra.instQuasiSeparatedSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsCofilteredOpposite AlgebraicGeometry.FGSubalgebra.instIsAffineObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instNonempty AlgebraicGeometry.FGSubalgebra.instNonemptySubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instCompactSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsDirectedSubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instIsAffineHomMapOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsFiltered AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instNeg AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulInt AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAddCommGroup AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAdd AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSub AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instModuleCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulNat AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instZero AlgebraicCurve.instHasLocalResidue_of_hasCanonicalLocalResidueK AlgebraicCurve.instHasCanonicalLocalResidueK_of_hasCanonicalLocalResidueKStar AlgebraicCurve.Place.kw_ffgc_finiteDimensional_adicCompletion instAlgebraSubtypeMemValuationSubring_definitions AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersIntegersCompletion ModularCurve.KwF4gRRTate.instAlgebraKAdicCompletionIntegers AlgebraicCurve.Place.kw_ffgc_continuousSMul_adicCompletionComap AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersCompletionCompletion IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instDimensionLEOneSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.instLiesOverSubtypeAdicCompletionMemValuationSubringAdicCompletionIntegersCompletionIdealAsIdeal IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsPrincipalIdealRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions"
p2m_attr_erase "instance" "IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemSubringIntegerWithZeroMultiplicativeInt_definitions IsDedekindDomain.HeightOneSpectrum.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicCompletionV_definitions AlgebraicCurve.instHasCanonicalLocalResidueK AlgebraicCurve.Place.instAlgebra_restrictResidueField AlgebraicCurve.Place.instIsScalarTower_restrictResidueField AlgebraicCurve.instHasLocalResidue AlgebraicCurve.HasSeparableResidue.of_perfectField_of_isCurveOver AlgebraicCurve.HasSeparableResidue.of_perfectField AlgebraicCurve.Place.instIsLocalHom_restrictSubringHom AlgebraicCurve.instHasCanonicalLocalResidueKStar ModularCurve.KwNo6Pin.isLocalRing_completion SheafOfModules.isIso_ihomModelToIhom AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instDecidableEqIdx AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintype AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instLinearOrder AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintypeIdx AlgebraicGeometry.OModulePresheaf.Leray.relAltC_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_modΓ AlgebraicGeometry.OModulePresheaf.Leray.relAltC_modΓ AlgebraicGeometry.OModulePresheaf.Leray.biC_abGrp AlgebraicGeometry.OModulePresheaf.Leray.relAltH_modΓ AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_smul AlgebraicGeometry.OModulePresheaf.Leray.relAltH_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.relAltH_smul AlgebraicGeometry.OModulePresheaf.Leray.biC_module DoubleComplex.instModuleE₂I DoubleComplex.Bounded.modR DoubleComplex.instModuleE₂II DoubleComplex.instAddCommGroupE₂II DoubleComplex.Bounded.abGrp DoubleComplex.instAddCommGroupE₂I ProjSpaceCech.GradedModule.H.module ProjSpaceCech.GradedModule.H.addCommGroup ProjSpaceCech.GradedModule.sec.instAdd ProjSpaceCech.GradedModule.sec.instNeg ProjSpaceCech.GradedModule.acg ProjSpaceCech.GradedModule.Frac.setoid ProjSpaceCech.GradedModule.modR ProjSpaceCech.GradedModule.sec.instModule ProjSpaceCech.GradedModule.sec.instAddCommGroup"
p2m_attr_erase "instance" "ProjSpaceCech.GradedModule.sec.instZero ProjSpaceCech.GradedModule.Presentation.fJ ProjSpaceCech.GradedModule.sec.instSMul ProjSpaceCech.Twist.H.module ProjSpaceCech.Idx.instFintype ProjSpaceCech.Twist.H.addCommGroup ProjSpaceCech.Idx.instDecidableEq ProjSpaceCech.Twist.Mon.instDecidableEq ProjSpaceCech.Twist.cochain.instAddCommGroup ProjSpaceCech.Twist.cochain.instModule AlgebraicGeometry.FGSubalgebra.tensorStage_directedSystem AlgebraicGeometry.RelEffCartierDiv.isClosedImmersion_subschemeι_resProdMap AlgebraicGeometry.RelEffCartierDiv.isOpenImmersion_resProdMap AlgebraicCurve.CurveModel.locallyOfFiniteType_gluedToBase AlgebraicCurve.CurveModel.isFractionRing_overlap AlgebraicCurve.CurveModel.isLocallyNoetherian_glued AlgebraicCurve.CurveModel.jacobsonSpace_glued AlgebraicCurve.CurveModel.isOpenImmersion_ι₀ AlgebraicCurve.CurveModel.isIntegral_glued AlgebraicCurve.CurveModel.quasiSeparated_gluedToBase AlgebraicCurve.CurveModel.compactSpace_glued AlgebraicCurve.CurveModel.isIntegral_adjoin_chartRing AlgebraicCurve.CurveModel.isFractionRing_overlap_functionField AlgebraicCurve.CurveModel.isProper_gluedToBase AlgebraicCurve.CurveModel.isOpenImmersion_ιU AlgebraicCurve.CurveModel.isOpenImmersion_f₀ AlgebraicCurve.CurveModel.isOpenImmersion_fInf AlgebraicCurve.CurveModel.isOpenImmersion_ιInf AlgebraicCurve.CurveModel.algebra_overlap_functionField AlgebraicCurve.CurveModel.quasiCompact_gluedToBase AlgebraicCurve.CurveModel.algebraAdjoin AlgebraicCurve.CurveModel.isDedekindDomain_chartRing AlgebraicCurve.CurveModel.isIntegralClosure AlgebraicCurve.CurveModel.finite_chartRing AlgebraicCurve.CurveModel.centre_isPrime AlgebraicCurve.CurveModel.isFractionRing_chartRing AlgebraicCurve.CurveModel.finiteType_chartRing AlgebraicCurve.CurveModel.isNoetherianRing_chartRing AlgebraicCurve.CurveModel.isScalarTower_base_adjoin AlgebraicCurve.CurveModel.isScalarTower_adjoin"
p2m_attr_erase "instance" "AlgebraicCurve.CurveModel.chartRing_finitePresentation instTopologicallyFGOfFiniteType AlgebraicGeometry.ProjSpace.twistObj.addCommGroup AlgebraicGeometry.ProjSpace.twistFam.module AlgebraicGeometry.ProjSpace.twistObj.module AlgebraicGeometry.ProjSpace.twistObj.moduleSections AlgebraicGeometry.ProjSpace.twistFam.addCommGroup PDivisibleGroup.instHopfAlgebra PDivisibleGroup.instModuleFinite PDivisibleGroup.instCommRing PDivisibleGroup.instIsCocomm PDivisibleGroup.instModuleFree PDivisibleGroup.instModuleFlat kmfloorsGlue_int_three_isPrime kmfloorsGlue_int_bot_isPrime MvFormalGroup.instIsCommAddMv CerednikDrinfeld.BruhatTits.instGraphActionGLTree CerednikDrinfeld.BruhatTits.instMulActionGLVertex CerednikDrinfeld.BruhatTits.instGraphActionPGLTree CerednikDrinfeld.BruhatTits.instMulActionPGLVertex CerednikDrinfeld.Mumford.dartAction CerednikDrinfeld.FormalODModule.isComm MvFormalGroup.Hom.instNeg MvFormalGroup.End.instAddCommGroup MvFormalGroup.Hom.instAddCommGroup MvFormalGroup.End.instRing MvFormalGroup.End.instMonoid MvFormalGroup.End.instSemiring MvFormalGroup.End.instAddCommMonoid MvFormalGroup.Hom.instZero MvFormalGroup.Hom.instAdd MvFormalGroup.Hom.instAddCommMonoid AlgebraicGeometry.Scheme.OrderedOpenFamily.instFintype AlgebraicGeometry.Scheme.OrderedOpenFamily.instDecidableEqIdx AlgebraicGeometry.Scheme.OrderedOpenFamily.instLinearOrder AlgebraicGeometry.Scheme.OrderedOpenFamily.instFintypeIdx CochainCx.Bounded.abGrp CochainCx.Bounded.modR AlgebraicGeometry.SubalgebraStages.compactSpace_pullback AlgebraicGeometry.SubalgebraStages.quasiSeparatedSpace_pullback"
p2m_attr_erase "instance" "AlgebraicGeometry.SubalgebraStages.compactSpace_obj AlgebraicGeometry.SubalgebraStages.quasiSeparatedSpace_obj AlgebraicGeometry.SubalgebraStages.quasiCompact_snd AlgebraicGeometry.SubalgebraStages.isAffineHom_leg AlgebraicGeometry.SubalgebraStages.isAffineHom_trans AlgebraicGeometry.SubalgebraStages.isAffineHom_diagram_map AlgebraicGeometry.SubalgebraStages.quasiSeparated_snd AlgebraicGeometry.SubalgebraStages.isCofiltered_op IsDirectLimit.Module.instDirectLimitCoeLinearMapIdOfOfNonempty AdicCompletion.instIsLocalRingMaximalIdeal CategoryTheory.Pseudofunctor.CoGrothendieck.isIso_homMk"
p2m_attr_erase "simp" "GoodReductionJacobian.RelativeGroupLaw.baseChangePointToBase_ofBase GoodReductionJacobian.RelativeGroupLaw.baseChangePointToBase_coe GoodReductionJacobian.RelativeGroupLaw.baseChangePointOfBase_coe GoodReductionJacobian.RelativeGroupLaw.baseChange_inv GoodReductionJacobian.RelativeGroupLaw.baseChangePointOfBase_toBase GoodReductionJacobian.RelativeGroupLaw.baseChange_mul GoodReductionJacobian.RelativeGroupLaw.baseChange_one NeronSpecialFibreInfra.specialFibreRestrict_coe_comp_fst NeronSpecialFibreInfra.fibreRestrictAlong_coe_comp_snd NeronSpecialFibreInfra.fibreRestrictAlong_coe_comp_fst NeronSpecialFibreInfra.neronEndRestrictEquiv_apply NeronSpecialFibreInfra.fibreRestrictAlong_coe_comp_fst_assoc NeronSpecialFibreInfra.specialFibreRestrict_coe_comp_snd NeronSpecialFibreInfra.neronEndExtension_genericFibreRestrict NeronSpecialFibreInfra.specClosedFibreInclusion_eq NeronSpecialFibreInfra.specialFibreRestrict_coe_comp_fst_assoc NeronSpecialFibreInfra.specialFibreRestrict_coe_comp_snd_assoc NeronSpecialFibreInfra.genericFibreRestrict_neronEndExtension NeronSpecialFibreInfra.homOverId_coe NeronSpecialFibreInfra.homOverComp_coe NeronSpecialFibreInfra.fibreRestrictAlong_coe_comp_snd_assoc GoodReductionJacobian.RelativeGroupLaw.fibre_inv GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_coe GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_toBase GoodReductionJacobian.RelativeGroupLaw.fibre_mul GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_ofBase GoodReductionJacobian.RelativeGroupLaw.fibre_one GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_coe AlgebraicGeometry.schemeFibreEndo_snd AlgebraicGeometry.schemeFibreEndo_fst RegularLocalRingQuotientAscent.dualNumberFst_apply GoodReductionJacobian.relativeGroupLawOfGrpObj_inv GoodReductionJacobian.relativeGroupLawOfGrpObj_mul GoodReductionJacobian.overHomEquivSchemeHomOver_apply_coe GoodReductionJacobian.relativeGroupLawOfGrpObj_one GoodReductionJacobian.overHomEquivSchemeHomOver_symm_apply_left AlgebraicGeometry.OModulePresheaf.prod_obj AlgebraicGeometry.OModulePresheaf.restrOpen_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.injEq AlgebraicGeometry.OModulePresheaf.pushforward_obj"
p2m_attr_erase "simp" "AlgebraicGeometry.OModulePresheaf.im_obj AlgebraicGeometry.OModulePresheaf.pow_obj AlgebraicGeometry.OModulePresheaf.fstHom_app AlgebraicGeometry.OModulePresheaf.ker_obj AlgebraicGeometry.OModulePresheaf.coker_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.preimage_U AlgebraicGeometry.OModulePresheaf.sndHom_app AlgebraicGeometry.OModulePresheaf.Hom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.id_app AlgebraicGeometry.OModulePresheaf.AffHom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffHom.comp_app AlgebraicGeometry.OModulePresheaf.AffSES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.kerMap_coe AlgebraicGeometry.OModulePresheaf.AffHom.id_app AlgebraicGeometry.OModulePresheaf.Hom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.toAffHom_app AlgebraicGeometry.OModulePresheaf.SES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.comp_app AlgebraicGeometry.OModulePresheaf.SES.mk.injEq AlgebraicGeometry.OModulePresheaf.AffHom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffSES.mk.injEq PresheafOfModules.freeεIso_hom_app PresheafOfModules.freeμIso_hom_app AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_snd AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_fst AlgebraicCurve.CurveModel.mk.injEq AlgebraicCurve.CurveModel.mk.sizeOf_spec AlgebraicCurve.mulAdele_apply AlgebraicCurve.residuePairing_apply_coe AlgebraicCurve.mem_adeleBdd AlgebraicCurve.weilSmul_one AlgebraicCurve.diagonalHom_apply AlgebraicCurve.weilSmul_apply"
p2m_attr_erase "simp" "AlgebraicCurve.adeleSpaceMul_coe AlgebraicCurve.mulAdele_one AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U1 AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.injEq AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U0 AlgebraicGeometry.RelPicard.SubPicCondition.onClasses_mk AlgebraicGeometry.RelPicard.relSubPicPresheaf_map_coe CategoryTheory.Functor.OverTotal.ofFibre_fst CategoryTheory.Functor.overTotal_map_fst AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_J AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t' AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf_assoc AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_toGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_openCover_map AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_comp AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_V AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_U AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_f AlgebraicGeometry.RelPicard.designationOfRepresentableBy_P AlgebraicGeometry.RelPicard.designationOfRepresentableBy_toBase AlgebraicGeometry.RelPicard.rigSection_snd AlgebraicGeometry.RelPicard.RigidifiedLineBundle.ofInvertible_L AlgebraicGeometry.RelPicard.rigSection_snd_assoc AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.sizeOf_spec AlgebraicCurve.coe_cechH0Equiv_apply AlgebraicCurve.cechH1ToH1_mk AlgebraicCurve.lSpaceOn_univ AlgebraicCurve.lSpaceOn_empty AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single"
p2m_attr_erase "simp" "AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one"
p2m_attr_erase "simp" "AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one AlgebraicCurve.Place.differentialCoeff_zero AlgebraicCurve.Place.differentialCoeff_dCoord AlgebraicCurve.TranscendenceTower.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.injEq AlgebraicCurve.TranscendenceTower.mk.injEq AlgebraicCurve.PoleDivisorPackage.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.sizeOf_spec AlgebraicCurve.PoleDivisorPackage.mk.injEq AlgebraicGeometry.RelPicard.thetaBundle_def AlgebraicGeometry.RelPicard.picardBundle_def AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_ofRelEffDivisor AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_I AlgebraicGeometry.mapOnProdOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.mk.sizeOf_spec AlgebraicGeometry.RelEffCartierDiv.mk.injEq AlgebraicGeometry.mapOnProdOver_snd AlgebraicGeometry.mapOnProdOver_fst AlgebraicGeometry.mapOnProdOver_snd_assoc AlgebraicGeometry.mapOnProdOver_id AlgebraicCurve.RelEffDivisor.mk.sizeOf_spec AlgebraicCurve.mapOnProd_fst AlgebraicCurve.mapOnProd_fst_assoc AlgebraicCurve.mapOnProd_snd AlgebraicCurve.UnivDivisorPack.mk.injEq AlgebraicCurve.RelEffDivisor.mk.injEq AlgebraicCurve.UnivDivisorPack.mk.sizeOf_spec AlgebraicCurve.mapOnProd_snd_assoc AlgebraicGeometry.Scheme.Modules.exteriorPower_obj PresheafOfModules.exteriorPower_map_ιMulti PresheafOfModules.ExteriorPower.appₗ_apply AlgebraicGeometry.prodKerGraph_one AlgebraicGeometry.fibrePowOver.proj_comp AlgebraicGeometry.prodKerGraph_zero"
p2m_attr_erase "simp" "AlgebraicGeometry.RelEffCartierDiv.empty_I AlgebraicGeometry.fibrePowOver.proj_comp_assoc AlgebraicGeometry.graphOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.toPoint_comp AlgebraicGeometry.RelEffCartierDiv.toPoint_comp_assoc AlgebraicGeometry.graphOver_fst AlgebraicGeometry.RelEffCartierDiv.ofPoint_I AlgebraicGeometry.graphOver_snd AlgebraicGeometry.graphOver_snd_assoc AlgebraicCurve.SymmetricPowerPackage.mk.sizeOf_spec AlgebraicCurve.SymmetricPowerPackage.mk.injEq AlgebraicGeometry.FGSubalgebra.cocone_ι_app_apply AlgebraicGeometry.RelPicard.fst_toProdSpec AlgebraicGeometry.RelPicard.toProdSpec_fst_assoc AlgebraicGeometry.RelPicard.pointsSubBasepointModule_cons AlgebraicGeometry.RelPicard.pointsSubBasepointModule_nil AlgebraicGeometry.RelPicard.fst_toProdSpec_assoc AlgebraicGeometry.RelPicard.toProdSpec_fst AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.sub_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sresTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.add_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.sizeOf_spec AlgebraicGeometry.Scheme.IdealSheafData.coe_resLE AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.smul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_ofLE_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.ideal_range AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zero_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sres AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.comp_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.neg_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.id_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_mulRight_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.nsmul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.injEq AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zsmul_app AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.sizeOf_spec AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.injEq AlgebraicCurve.adeleSingle_coe AlgebraicCurve.kaehlerResidueTermKFam_apply AlgebraicCurve.Place.LocalResidueData.mk.injEq"
p2m_attr_erase "simp" "AlgebraicCurve.Place.LocalResidueData.mk.sizeOf_spec AlgebraicCurve.Place.kw_ffgc_adicCompletionComapIntegers_coe AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.sizeOf_spec AlgebraicCurve.Place.mem_simplePoleSubmodule AlgebraicCurve.Place.coe_uniformizerSubring ModularCurve.Lg37.Lg37CompletionSection.mk.injEq AlgebraicCurve.Place.CoefficientFieldSection.mk.injEq AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.injEq ModularCurve.Lg37.Lg37CompletionSection.mk.sizeOf_spec AlgebraicCurve.Place.CoefficientFieldSection.mk.sizeOf_spec AlgebraicCurve.Place.poleSubmodule_one AlgebraicCurve.Place.mem_poleSubmodule AlgebraicGeometry.Scheme.Modules.toUnitSection_ofUnitSection AlgebraicGeometry.Scheme.Modules.pullbackSection_def AlgebraicGeometry.Scheme.Modules.ofUnitSection_toUnitSection PresheafOfModules.InternalHom.IsSheafAux.appAt_toPresheafHom SheafOfModules.ihomSectionsEquivFamily_unit AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_apply SheafOfModules.ihomEval_unit_app AlgebraicGeometry.Scheme.Modules.ihomEval_zero_right AlgebraicGeometry.Scheme.Modules.ihomEval_zero_left AlgebraicGeometry.Scheme.Modules.homOfFamily_app_apply SheafOfModules.unit_ihomSectionsEquivFamily AlgebraicGeometry.Scheme.Modules.familyOfHom_app AlgebraicGeometry.Scheme.Modules.restrictUnitIso_hom_app_apply AlgebraicGeometry.Scheme.Modules.restrictUnitIso_inv_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomOfFamily_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_symm_apply AlgebraicGeometry.Scheme.Modules.tensorSections_zero_right AlgebraicGeometry.Scheme.Modules.map_unitSection AlgebraicGeometry.Scheme.Modules.tensorSectionsBilin_apply AlgebraicGeometry.Scheme.Modules.tensorPowSection_zero AlgebraicGeometry.Scheme.Modules.tensorSections_zero_left AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_neg AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_zero AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_sub AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_add AlgebraicGeometry.Scheme.OrderedAffineCover.toCoverOf_U AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.injEq"
p2m_attr_erase "simp" "AlgebraicGeometry.Scheme.OrderedAffineCover.restrict_U AlgebraicGeometry.OModulePresheaf.Leray.restrictToPreimage_U DoubleComplex.Bounded.mk.injEq DoubleComplex.Bounded.mk.sizeOf_spec DoubleComplex.Convergence.mk.injEq DoubleComplex.Convergence.mk.sizeOf_spec DoubleComplex.SubQuot.mk.sizeOf_spec DoubleComplex.SubQuot.mk.injEq ProjSpaceCech.GradedModule.mk.injEq ProjSpaceCech.GradedModule.mk.sizeOf_spec ProjSpaceCech.GradedModule.Frac.mk.sizeOf_spec ProjSpaceCech.GradedModule.Presentation.mk.injEq ProjSpaceCech.GradedModule.Frac.mk.injEq ProjSpaceCech.GradedModule.Presentation.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.shift_toLinearMap ProjSpaceCech.GradedModule.Hom.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.mk.injEq TwoChartCech.Mumford.dK_apply TwoChartCech.Mumford.ι0_apply TwoChartCech.Mumford.ι1_apply TwoChartCech.KerCoprod.dK_apply TwoChartCech.KerCoprod.ι1_apply TwoChartCech.KerCoprod.ι0_apply AlgebraicGeometry.tilde.functorCompPullbackSpecIso_app AlgebraicGeometry.RelPicard.algEquivZeroGroupCut_toSubPicCondition AlgebraicGeometry.RelPicard.LFP.stageHom_val AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_hom_app_coe AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_inv_app_coe AlgebraicGeometry.RelPicard.BaseChange.restrict_P AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp AlgebraicGeometry.RelEffCartierDiv.functor_map_fst AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_pullbackAlong AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_symm_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp_assoc AlgebraicGeometry.RelEffCartierDiv.supportedIn_top AlgebraicGeometry.RelEffCartierDiv.mem_supportedIn_iff AlgebraicGeometry.RelEffCartierDiv.supportedIn_top_eq AlgebraicGeometry.RelEffCartierDiv.restrictAlong_extendAlong AlgebraicGeometry.RelEffCartierDiv.extendAlong_I"
p2m_attr_erase "simp" "AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd AlgebraicGeometry.RelEffCartierDiv.restrictAlong_I AlgebraicGeometry.RelEffCartierDiv.extendAlong_restrictAlong AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst CoherentBaseChange.FibreH0Family.mk.sizeOf_spec CoherentBaseChange.FibreH0Family.mk.injEq AlgebraicCurve.CurveModel.coe_gInf AlgebraicCurve.CurveModel.coe_tInvChart AlgebraicCurve.CurveModel.ιInf_gluedToBase_assoc AlgebraicCurve.CurveModel.ιInf_gluedToBase AlgebraicCurve.CurveModel.primeOfι₀_asIdeal AlgebraicCurve.CurveModel.coe_tChart AlgebraicCurve.CurveModel.ι₀_gluedToBase_assoc AlgebraicCurve.CurveModel.primeOfιInf_asIdeal AlgebraicCurve.CurveModel.ι₀_gluedToBase AlgebraicCurve.CurveModel.coe_tma AlgebraicCurve.CurveModel.coe_primeEquivChartPlaces AlgebraicGeometry.ProjSpace.twistObj.mk.injEq AlgebraicGeometry.ProjSpace.twistObj.zero_val AlgebraicGeometry.ProjSpace.twistObj.add_val AlgebraicGeometry.ProjSpace.twist_res_val AlgebraicGeometry.ProjSpace.twist_smul_val AlgebraicGeometry.ProjSpace.twistGradeToObj_val AlgebraicGeometry.ProjSpace.twistObj.smul_val AlgebraicGeometry.ProjSpace.twistGradeEquiv_apply_val AlgebraicGeometry.ProjSpace.twistObj.mk.sizeOf_spec QuaternionAlgebra.baseChangeRight_tmul QuaternionAlgebra.mapOfAlgebraMapEq_apply QuaternionAlgebra.baseChange_tmul QuaternionAlgebra.ClassSet.map_mk PDivisibleGroup.counit_transition PDivisibleGroup.Hopf.nsmulAlgHom_one PDivisibleGroup.Hopf.torsionIdeal_zero PDivisibleGroup.Hopf.nsmulAlgHom_zero_apply PDivisibleGroup.Hopf.torsionIdeal_one PDivisibleGroup.Hopf.counit_nsmulAlgHom PDivisibleGroup.mk.sizeOf_spec PDivisibleGroup.mk.injEq"
p2m_attr_erase "simp" "PDivisibleGroup.height_eq MvFormalGroup.mk.injEq MvFormalGroup.nthSeries_zero MvFormalGroup.Hom.mk.sizeOf_spec MvFormalGroup.Hom.mk.injEq MvFormalGroup.mk.sizeOf_spec AlgebraicGeometry.Scheme.nilpPoints_map_val LT.LatticeTree.IntegralAut.refl_toField LT.LatticeTree.vecPair_one LT.LatticeTree.IntegralAut.mk.sizeOf_spec LT.LatticeTree.galVec_refl LT.LatticeTree.mulVecPair_zero LT.LatticeTree.galVec_apply LT.LatticeTree.vecPair_zero LT.LatticeTree.IntegralAut.refl_toBase LT.LatticeTree.scalarGL_coe LT.LatticeTree.IntegralAut.mk.injEq LT.LatticeTree.IntegralAut.comp_toBase_apply LT.LatticeTree.IntegralAut.unitMap_coe LT.LatticeTree.latticeGal_refl LT.LatticeTree.gammaZero_coe LT.LatticeTree.Vertex.act_mk LT.LatticeTree.Vertex.galAct_mk LT.LatticeTree.transvectionGate_coe LT.LatticeTree.mulVecPair_one LT.LatticeTree.diagSnd_coe LT.LatticeTree.unitOfNeZero_coe LT.LatticeTree.IntegralAut.comp_toField_apply LT.LatticeTree.mulVecLinR_apply CerednikDrinfeld.BruhatTits.vertPermHom_apply CerednikDrinfeld.BruhatTits.gl_smul_mk CerednikDrinfeld.BruhatTits.pgl_mk_smul CerednikDrinfeld.SpecialFormal.Rigidified.mk.injEq CerednikDrinfeld.FormalODModule.actRingHom_apply CerednikDrinfeld.SpecialFormalODModule.mk.sizeOf_spec CerednikDrinfeld.FormalODModule.Hom.mk.injEq CerednikDrinfeld.FormalODModule.map_id CerednikDrinfeld.SpecialFormal.Series.map_id CerednikDrinfeld.SpecialFormal.Rigidified.mk.sizeOf_spec CerednikDrinfeld.SpecialFormal.ModuliPackage.twist_obj"
p2m_attr_erase "simp" "CerednikDrinfeld.SpecialFormalODModule.mk.injEq CerednikDrinfeld.FormalODModule.map_varpi CerednikDrinfeld.FormalODModule.map_act CerednikDrinfeld.SpecialFormal.ModuliPackage.mk.injEq CerednikDrinfeld.FormalODModule.mk.injEq CerednikDrinfeld.FormalODModule.Hom.mk.sizeOf_spec CerednikDrinfeld.SpecialFormal.ModuliPackage.mk.sizeOf_spec CerednikDrinfeld.FormalODModule.map_F CerednikDrinfeld.SpecialFormal.Rigidified.map_n CerednikDrinfeld.SpecialFormal.Rigidified.map_ρ CerednikDrinfeld.SpecialFormal.IsLawHom.toHom_toPowerSeries CerednikDrinfeld.SpecialFormal.Series.map_ringHom_id CerednikDrinfeld.FormalODModule.actEnd_toPowerSeries CerednikDrinfeld.SpecialFormal.Rigidified.map_X CerednikDrinfeld.FormalODModule.varpiEnd_toPowerSeries CerednikDrinfeld.FormalODModule.mk.sizeOf_spec MvFormalGroup.Hom.toPowerSeries_sub MvFormalGroup.linearPartHom_intCast MvFormalGroup.constantCoeff_negSeries MvFormalGroup.toPowerSeries_invHom MvFormalGroup.linearPartHom_neg MvFormalGroup.End.toPowerSeries_sub MvFormalGroup.End.toPowerSeries_neg MvFormalGroup.constantCoeff_invSeries MvFormalGroup.negApprox_zero MvFormalGroup.Hom.toPowerSeries_neg MvFormalGroup.Hom.toPowerSeries_neg' MvFormalGroup.linearPartHom_apply MvFormalGroup.linearPart_zero MvFormalGroup.linearPart_X MvFormalGroup.End.toPowerSeries_mul MvFormalGroup.Hom.toPowerSeries_add MvFormalGroup.End.toPowerSeries_add MvFormalGroup.End.toPowerSeries_one MvFormalGroup.End.toPowerSeries_zero MvFormalGroup.Hom.toPowerSeries_zero MvFormalGroup.linearPartHom_natCast MvFormalGroup.Hom.toPowerSeries_zero' MvFormalGroup.End.toPowerSeries_natCast GoodReductionJacobian.BareDeformation.mk.sizeOf_spec"
p2m_attr_erase "simp" "GoodReductionJacobian.BareDeformation.mk.injEq AlgebraicGeometry.Scheme.OrderedOpenFamily.mk.injEq AlgebraicGeometry.Scheme.OrderedOpenFamily.mk.sizeOf_spec CochainCx.Bounded.mk.sizeOf_spec CochainCx.Bounded.mk.injEq AlgebraicGeometry.SubalgebraStages.specCone_π_app AlgebraicGeometry.SubalgebraStages.specLeg_specHom AlgebraicGeometry.SubalgebraStages.specLeg_specTrans AlgebraicGeometry.SubalgebraStages.cone_pt AlgebraicGeometry.SubalgebraStages.trans_fst AlgebraicGeometry.SubalgebraStages.diagram_obj AlgebraicGeometry.SubalgebraStages.leg_snd AlgebraicGeometry.SubalgebraStages.diagram_map AlgebraicGeometry.SubalgebraStages.specTrans_refl AlgebraicGeometry.SubalgebraStages.trans_snd AlgebraicGeometry.SubalgebraStages.specTrans_specHom AlgebraicGeometry.SubalgebraStages.specCone_pt AlgebraicGeometry.SubalgebraStages.cone_π_app AlgebraicGeometry.SubalgebraStages.specDiagram_map AlgebraicGeometry.SubalgebraStages.specDiagram_obj AlgebraicGeometry.SubalgebraStages.leg_fst AlgebraicGeometry.SubalgebraStages.leg_trans IsDirectLimit.Module.linearEquiv_symm_apply IsDirectLimit.linearEquiv_symm_apply IsDirectLimit.lift_of IsDirectLimit.Module.linearEquiv_apply IsDirectLimit.Module.lift_of IsDirectLimit.Equiv_apply GoodReductionJacobian.RelativeGroupLaw.eigenInclusion_app GoodReductionJacobian.RelativeGroupLaw.eigenSubdatum_obj AlgebraicGeometry.Scheme.Modules.fibration_map_toFunctor CategoryTheory.Pseudofunctor.CoGrothendieck.homMk_base CategoryTheory.Pseudofunctor.CoGrothendieck.isoMk_hom AlgebraicGeometry.RiemannForm.thetaGroup.pt_liftOfIso AlgebraicGeometry.RiemannForm.modulePair_fiber AlgebraicGeometry.RiemannForm.pt_levelLift AlgebraicGeometry.RiemannForm.modulePair_base AlgebraicGeometry.RiemannForm.thetaGroup.pt_apply AlgebraicGeometry.RiemannForm.translationIso_hom AlgebraicGeometry.Scheme.Modules.fibration_obj"
p2m_attr_erase "simp" "CategoryTheory.Pseudofunctor.CoGrothendieck.homMk_fiber"

set_option autoImplicit false

open scoped TensorProduct Quaternion
p2m_open "CategoryTheory CategoryTheory.Limits CategoryTheory.MonoidalCategory AlgebraicGeometry QuaternionAlgebra CerednikDrinfeld CerednikDrinfeld.QM NeronModelInfra GoodReductionJacobian AlgebraicGeometry.Polarisation Polynomial AlgebraicGeometry.Polynomial"

namespace FieldUniqReduce

theorem isInStabilizer_congr {k : Type} [CommRing k] {A : Scheme.{0}} {f : A ⟶ Spec (CommRingCat.of k)}
    (L : RelativeGroupLaw k f) {M M' : A.Modules} (e : M ≅ M') {T : Scheme.{0}}
    (t : T ⟶ Spec (CommRingCat.of k)) (x : SchemeHomOver t f) :
    L.IsInStabilizer M t x ↔ L.IsInStabilizer M' t x := by
  constructor
  · intro h
    exact Scheme.Modules.LocallyIsoOver.trans
      (Scheme.Modules.LocallyIsoOver.trans
        (Scheme.Modules.LocallyIsoOver.of_iso _ ((Scheme.Modules.pullback _).mapIso e)).symm h)
      (Scheme.Modules.LocallyIsoOver.of_iso _ ((Scheme.Modules.pullback _).mapIso e))
  · intro h
    exact Scheme.Modules.LocallyIsoOver.trans
      (Scheme.Modules.LocallyIsoOver.trans
        (Scheme.Modules.LocallyIsoOver.of_iso _ ((Scheme.Modules.pullback _).mapIso e)) h)
      (Scheme.Modules.LocallyIsoOver.of_iso _ ((Scheme.Modules.pullback _).mapIso e)).symm

end FieldUniqReduce

open FieldUniqReduce

theorem solution
    {q q' : ℕ} [Fact q.Prime] [Fact q'.Prime] (hqq' : q' ≠ q)
    {a b : ℚ} (hB : IsIndefiniteRamifiedExactlyAt a b q q')
    (Λ : Submodule ℤ ℍ[ℚ, a, b]) (hΛ : IsMaximalOrder Λ)
    (μ : ↥Λ) (hμ : (μ : ℍ[ℚ, a, b]) * (μ : ℍ[ℚ, a, b]) = -(((q * q' : ℕ) : ℚ) • (1 : ℍ[ℚ, a, b])))
    (star : ↥Λ → ↥Λ) (hstar : ∀ x : ↥Λ, (μ : ℍ[ℚ, a, b]) * (star x : ℍ[ℚ, a, b]) = Star.star (x : ℍ[ℚ, a, b]) * μ)
    (N : ℕ) (k : Type) [Field k] [IsAlgClosed k] (E : FakeEllipticCurve Λ N k)
    (𝓛₀ 𝓛₁ : E.A.Modules) (h₀ : Scheme.Modules.IsInvertible 𝓛₀) (h₁ : Scheme.Modules.IsInvertible 𝓛₁)
    (hK₀ : KernelTrivial E.f E.L 𝓛₀) (hK₁ : KernelTrivial E.f E.L 𝓛₁)
    (hpos₀ : ∀ (k' : Type) [Field k'] [IsAlgClosed k'] (sk : k →+* k'), 0 < Scheme.Modules.geomFibreH0Finrank E.f 𝓛₀ k' sk)
    (hpos₁ : ∀ (k' : Type) [Field k'] [IsAlgClosed k'] (sk : k →+* k'), 0 < Scheme.Modules.geomFibreH0Finrank E.f 𝓛₁ k' sk)
    (hR₀ : RosatiCompatible E.f E.L 𝓛₀ E.act E.act_over star) (hR₁ : RosatiCompatible E.f E.L 𝓛₁ E.act E.act_over star) :
    LocIsoOnBase E.f (𝓛₀ ⊗ (Scheme.Modules.pullback (negMor E.f E.L)).obj 𝓛₀)
      (𝓛₁ ⊗ (Scheme.Modules.pullback (negMor E.f E.L)).obj 𝓛₁) := by

  haveI : Smooth E.f := E.bundle.smooth
  haveI : SmoothOfRelativeDimension 2 E.f :=
    RelativeGroupLaw.smoothOfRelativeDimension_of_forall_topologicalKrullDim_eq E.L 2 E.dim_fibre
  haveI : IsProper E.f := E.bundle.proper
  obtain ⟨𝒦, -⟩ := AbelianSchemePropertyBundle.exists_orderedAffineCover_card_eq k E.f E.bundle 2
  have hH0 : ∀ (B : Type) [CommRing B] [Algebra k B],
      Function.Bijective (pullback.snd E.f (Spec.map (CommRingCat.ofHom (algebraMap k B)))).appTop := by
    intro B _ _
    have h := AbelianSchemePropertyBundle.bijective_specIso_inv_comp_appTop_of_isPullback E.bundle (algebraMap k B)
      (pullback.snd E.f (Spec.map (CommRingCat.ofHom (algebraMap k B))))
      (pullback.fst E.f (Spec.map (CommRingCat.ofHom (algebraMap k B))))
      (IsPullback.of_hasPullback E.f (Spec.map (CommRingCat.ofHom (algebraMap k B))))
    have hiso : Function.Bijective (Scheme.ΓSpecIso (CommRingCat.of B)).inv.hom :=
      (Scheme.ΓSpecIso (CommRingCat.of B)).symm.commRingCatIsoToRingEquiv.bijective
    rw [CommRingCat.hom_comp, RingHom.coe_comp] at h
    exact (Function.Bijective.of_comp_iff _ hiso).mp h

  obtain ⟨ℓ, hℓprime, hℓ⟩ : ∃ ℓ : ℕ, ℓ.Prime ∧ (ℓ : k) ≠ 0 := by
    by_cases h2 : (2 : k) = 0
    · refine ⟨3, Nat.prime_three, ?_⟩
      intro h3
      have h3' : (3 : k) = 0 := by exact_mod_cast h3
      exact one_ne_zero (by linear_combination h3' - h2 : (1 : k) = 0)
    · exact ⟨2, Nat.prime_two, by exact_mod_cast h2⟩
  haveI : Fact ℓ.Prime := ⟨hℓprime⟩

  obtain ⟨ζ, hζ, hζℓ⟩ := IsAlgClosed.exists_isPrimitiveRoot_pow_and_pow_succ_eq k ℓ hℓ

  obtain ⟨e₀, he₀, -⟩ :=
    RiemannForm.existsUnique_isRiemannForm k E.f E.L E.comm E.bundle 𝓛₀ h₀ ℓ hℓ ζ hζ hζℓ
  obtain ⟨e₁, he₁, -⟩ :=
    RiemannForm.existsUnique_isRiemannForm k E.f E.L E.comm E.bundle 𝓛₁ h₁ ℓ hℓ ζ hζ hζℓ

  obtain ⟨ρ, hρ, ρ_one, ρ_mul, ρ_add⟩ :=
    FakeEllipticCurve.exists_tateModule_linearMap_forall_apply_eq_pushPt_act E k ℓ
  obtain ⟨ι, _, bΛ, xgen, bM, hbM⟩ :=
    FakeEllipticCurve.exists_basis_tateModule_eq_apply_of_isMaximalOrder_of_prime hB Λ hΛ E k ℓ hℓ ρ hρ

  have hbridge :=
    RiemannForm.translation_eq_translate_toUnitPt_and_translate_eq_translation_ofUnitPt k E.f E.L
  have hKT : ∀ (𝓛 : E.A.Modules), Scheme.Modules.IsInvertible 𝓛 → KernelTrivial E.f E.L 𝓛 →
      ∀ (n : ℕ) (Q : E.L.AlgPoints E.comm k), ℓ ^ n • Q = 0 →
        Nonempty ((Scheme.Modules.pullback
          (RiemannForm.translation E.f E.L (RelativeGroupLaw.AlgPoints.toPoint Q))).obj 𝓛 ≅ 𝓛) → Q = 0 := by
    intro 𝓛 h𝓛 hKtriv n Q _ hiso
    have hx : RiemannForm.toUnitPt E.f (RelativeGroupLaw.AlgPoints.toPoint Q) ∈ kernelPts E.f E.L 𝓛 := by
      rw [Polarisation.mem_kernelPts_iff_nonempty_pullback_translate_iso k E.f E.L 𝓛, ← hbridge.1]
      exact hiso
    have hstab : E.L.IsInStabilizer 𝓛 (𝟙 _) (RiemannForm.toUnitPt E.f (RelativeGroupLaw.AlgPoints.toPoint Q)) := hx
    have hone := hKtriv k (𝟙 (Spec (CommRingCat.of k)))
      (RiemannForm.toUnitPt E.f (RelativeGroupLaw.AlgPoints.toPoint Q))
      ((Polarisation.isInStabilizer_iff_locIsoOnBase_pullback_sliceAt_mumfordBundle_unit k E.f E.L 𝓛 h𝓛 k
        (𝟙 _) _).mp hstab)
    apply RelativeGroupLaw.AlgPoints.toPoint_injective
    rw [RelativeGroupLaw.AlgPoints.toPoint_zero]
    apply Subtype.ext
    have h1 : (RelativeGroupLaw.AlgPoints.toPoint Q).1 = (E.L.one (𝟙 (Spec (CommRingCat.of k)))).1 :=
      congrArg Subtype.val hone
    rw [h1, RiemannForm.specMap_algebraMap_self]
  have hperf : e₀.IsPerfPair :=
    RiemannForm.perfect_of_forall_torsion_kernelPts_eq_zero k E.f E.L E.comm E.bundle 𝓛₀ h₀ 2 E.dim_fibre
      ℓ hℓ ζ hζ hζℓ e₀ he₀ (hKT 𝓛₀ h₀ hK₀)

  have alt₀ := (RiemannForm.isRiemannForm_swap_eq_neg_and_self_eq_zero k E.f E.L E.comm E.bundle 𝓛₀ h₀
    ℓ hℓ ζ hζ hζℓ e₀ he₀).2
  have alt₁ := (RiemannForm.isRiemannForm_swap_eq_neg_and_self_eq_zero k E.f E.L E.comm E.bundle 𝓛₁ h₁
    ℓ hℓ ζ hζ hζℓ e₁ he₁).2

  have hinv : Function.Involutive star :=
    QuaternionAlgebra.involutive_of_mul_self_eq_neg_smul_of_forall_mul_eq_star_mul
      (c := ((q * q' : ℕ) : ℚ))
      (by exact_mod_cast Nat.mul_pos (Fact.out : q.Prime).pos (Fact.out : q'.Prime).pos)
      (μ : ℍ[ℚ, a, b]) (by rw [neg_smul]; exact hμ) (fun x : ↥Λ => (x : ℍ[ℚ, a, b]))
      Subtype.val_injective star hstar
  have star₀ : ∀ (x : ↥Λ) (m n : TateModule ℓ (E.L.AlgPoints E.comm k)), e₀ (ρ x m) n = e₀ m (ρ (star x) n) :=
    fun x m n => RiemannForm.apply_apply_eq_of_rosatiCompatible_of_involutive k E.f E.L E.comm E.bundle 𝓛₀ h₀
      ℓ hℓ ζ hζ hζℓ e₀ he₀ E.act E.act_over star hinv E.act_hom hR₀ ρ hρ x m n
  have star₁ : ∀ (x : ↥Λ) (m n : TateModule ℓ (E.L.AlgPoints E.comm k)), e₁ (ρ x m) n = e₁ m (ρ (star x) n) :=
    fun x m n => RiemannForm.apply_apply_eq_of_rosatiCompatible_of_involutive k E.f E.L E.comm E.bundle 𝓛₁ h₁
      ℓ hℓ ζ hζ hζℓ e₁ he₁ E.act E.act_over star hinv E.act_hom hR₁ ρ hρ x m n

  obtain ⟨r, hr, -⟩ :=
    QuaternionAlgebra.IsMaximalOrder.existsUnique_eq_smul_of_isPerfPair_of_alternating_starAdjoint
      hqq' hB Λ hΛ μ hμ star hstar ℤ_[ℓ] (TateModule ℓ (E.L.AlgPoints E.comm k)) ρ ρ_one ρ_mul ρ_add
      bΛ xgen bM hbM e₀ alt₀ star₀ hperf e₁ alt₁ star₁

  obtain ⟨P, R, hdegP, hdegR, hcoeff, hP, hR⟩ :=
    AbelianSchemePropertyBundle.exists_polynomial_coeff_eq_forall_eulerChar_tensor_tensorPow_eq
      k E.f E.bundle 2 E.dim_fibre 𝒦 𝓛₀ 𝓛₁ h₀ h₁

  have hinvpow : ∀ n : ℕ, Scheme.Modules.IsInvertible (𝓛₀.tensorPow n) := fun n =>
    Scheme.Modules.IsInvertible.tensorPow_monoidalV2 h₀ n
  have hpow : ∀ b : ℕ, RiemannForm.IsRiemannForm E.f E.L E.comm (𝓛₀.tensorPow b) ℓ ζ ((b : ℤ_[ℓ]) • e₀) := by
    intro b
    induction b with
    | zero =>
      rw [Nat.cast_zero, zero_smul, Scheme.Modules.tensorPow_zero]
      exact RiemannForm.isRiemannForm_tensorUnit_zero k E.f E.L E.comm E.bundle ℓ hℓ ζ hζ hζℓ
    | succ n ih =>
      rw [Nat.cast_succ, add_smul, one_smul]
      exact RiemannForm.isRiemannForm_add_of_iso_tensor k E.f E.L E.comm E.bundle (𝓛₀.tensorPow n) (hinvpow n)
        ℓ hℓ ζ hζ hζℓ _ ih 𝓛₀ h₀ e₀ he₀ (𝓛₀.tensorPow (n + 1)) ⟨eqToIso (Scheme.Modules.tensorPow_succ 𝓛₀ n)⟩
  have hmix : ∀ m : ℕ, RiemannForm.IsRiemannForm E.f E.L E.comm (𝓛₁ ⊗ 𝓛₀.tensorPow m) ℓ ζ
      (((m : ℤ_[ℓ]) + r) • e₀) := by
    intro m
    have h := RiemannForm.isRiemannForm_add_of_iso_tensor k E.f E.L E.comm E.bundle 𝓛₁ h₁ ℓ hℓ ζ hζ hζℓ e₁ he₁
      (𝓛₀.tensorPow m) (hinvpow m) _ (hpow m) (𝓛₁ ⊗ 𝓛₀.tensorPow m) ⟨Iso.refl _⟩
    rw [hr, ← add_smul, add_comm r] at h
    exact h

  have hsq : ∀ (𝓛 𝓜 : E.A.Modules), Scheme.Modules.IsInvertible 𝓛 → KernelTrivial E.f E.L 𝓛 →
      Scheme.Modules.IsInvertible 𝓜 → (𝓛 ≅ 𝓜) →
      ((OModulePresheaf.ofModules E.f 𝓜).eulerChar 𝒦) ^ 2 = 1 := by
    intro 𝓛 𝓜 h𝓛 hK h𝓜 e
    obtain ⟨hci, hfin, hrank, hKiff⟩ :=
      Polarisation.isClosedImmersion_one_and_forall_iff_isInStabilizer_of_kernelTrivial k E.f E.L E.bundle 𝓛 h𝓛 hK
    have h := AbelianSchemePropertyBundle.eulerChar_sq_eq_finrank_of_forall_iff_isInStabilizer_type0 k E.f E.L E.comm
      E.bundle 2 𝒦 𝓜 h𝓜 (E.L.one (𝟙 (Spec (CommRingCat.of k)))).1 hci hfin
      (fun R _ t x => (hKiff R t x).trans (isInStabilizer_congr E.L e t x))
    rw [h, hrank]
    norm_num

  have hvalR : ∀ b : ℕ, (b : ℤ_[ℓ]) + 0 ≠ 0 →
      ((b : ℤ_[ℓ]) + 0) ^ 2 ∣ ((OModulePresheaf.ofModules E.f (𝓛₀.tensorPow b)).eulerChar 𝒦 : ℤ_[ℓ]) := by
    intro b hb
    rw [add_zero] at hb ⊢
    exact (RiemannForm.eulerChar_ne_zero_and_pow_dvd_eulerChar_of_isRiemannForm_smul_of_isPerfPair k E.f E.L
      E.comm E.bundle (𝓛₀.tensorPow b) (hinvpow b) 2 E.dim_fibre ℓ hℓ ζ hζ hζℓ e₀ hperf (b : ℤ_[ℓ]) hb
      (hpow b) hH0 𝒦).2
  have hRmap := Polynomial.map_eq_C_mul_X_add_C_pow_of_forall_dvd_eval ℓ 2 R hdegR
    (fun b => (OModulePresheaf.ofModules E.f (𝓛₀.tensorPow b)).eulerChar 𝒦) (fun b => (hR b).symm) 0 hvalR
  have hR1 : R.eval 1 = R.coeff 2 := by
    apply (algebraMap ℚ ℚ_[ℓ]).injective
    have h := congrArg (Polynomial.eval (1 : ℚ_[ℓ])) hRmap
    rw [Polynomial.eval_map, Polynomial.eval₂_at_one] at h
    rw [h]
    simp
  have hχ1 := hsq 𝓛₀ (𝓛₀.tensorPow 1) h₀ hK₀ (hinvpow 1) (Scheme.Modules.tensorPowOneIso 𝓛₀).symm
  have hR1' : R.eval 1 = ((OModulePresheaf.ofModules E.f (𝓛₀.tensorPow 1)).eulerChar 𝒦 : ℚ) := by
    have := hR 1
    rw [Nat.cast_one] at this
    exact this.symm
  have hχ1' : (OModulePresheaf.ofModules E.f (𝓛₀.tensorPow 1)).eulerChar 𝒦 *
      (OModulePresheaf.ofModules E.f (𝓛₀.tensorPow 1)).eulerChar 𝒦 = 1 := by
    rw [← pow_two]; exact hχ1
  have hP2 : P.coeff 2 = 1 ∨ P.coeff 2 = -1 := by
    rw [hcoeff, ← hR1, hR1']
    rcases mul_self_eq_one_iff.mp hχ1' with h | h
    · left; rw [h]; norm_num
    · right; rw [h]; norm_num

  have hvalP : ∀ m : ℕ, (m : ℤ_[ℓ]) + r ≠ 0 →
      ((m : ℤ_[ℓ]) + r) ^ 2 ∣ ((OModulePresheaf.ofModules E.f (𝓛₁ ⊗ 𝓛₀.tensorPow m)).eulerChar 𝒦 : ℤ_[ℓ]) := by
    intro m hm
    exact (RiemannForm.eulerChar_ne_zero_and_pow_dvd_eulerChar_of_isRiemannForm_smul_of_isPerfPair k E.f E.L
      E.comm E.bundle (𝓛₁ ⊗ 𝓛₀.tensorPow m) (Scheme.Modules.IsInvertible.tensor_monoidalV2 h₁ (hinvpow m))
      2 E.dim_fibre ℓ hℓ ζ hζ hζℓ e₀ hperf ((m : ℤ_[ℓ]) + r) hm (hmix m) hH0 𝒦).2
  have hPmap := Polynomial.map_eq_C_mul_X_add_C_pow_of_forall_dvd_eval ℓ 2 P hdegP
    (fun m => (OModulePresheaf.ofModules E.f (𝓛₁ ⊗ 𝓛₀.tensorPow m)).eulerChar 𝒦) (fun m => (hP m).symm) r hvalP
  have hχ0 := hsq 𝓛₁ (𝓛₁ ⊗ 𝓛₀.tensorPow 0) h₁ hK₁
    (Scheme.Modules.IsInvertible.tensor_monoidalV2 h₁ (hinvpow 0)) (ρ_ 𝓛₁).symm
  have hP0 : P.coeff 0 = 1 ∨ P.coeff 0 = -1 := by
    rw [Polynomial.coeff_zero_eq_eval_zero]
    have h0 := hP 0
    rw [Nat.cast_zero] at h0
    rw [← h0]
    have hχ0' : (OModulePresheaf.ofModules E.f (𝓛₁ ⊗ 𝓛₀.tensorPow 0)).eulerChar 𝒦 *
        (OModulePresheaf.ofModules E.f (𝓛₁ ⊗ 𝓛₀.tensorPow 0)).eulerChar 𝒦 = 1 := by
      rw [← pow_two]; exact hχ0
    rcases mul_self_eq_one_iff.mp hχ0' with h | h
    · left; rw [h]; norm_num
    · right; rw [h]; norm_num
  have hr1 : r = 1 ∨ r = -1 := by
    rcases Polynomial.eq_one_or_eq_neg_one_of_map_eq_C_mul_X_add_C_pow ℓ 2 (by norm_num) P (P.coeff 2) hP2 hP0
      (r : ℚ_[ℓ]) hPmap with h | h
    · left; exact PadicInt.ext (by rw [PadicInt.coe_one]; exact h)
    · right; exact PadicInt.ext (by rw [PadicInt.coe_neg, PadicInt.coe_one]; exact h)
  rcases hr1 with hr1 | hr1
  ·
    rw [hr1, one_smul] at hr
    obtain ⟨hdinv, ⟨εd⟩⟩ := Scheme.Modules.IsInvertible.dual_monoidalV2 h₀
    have hP'inv : Scheme.Modules.IsInvertible (𝓛₁ ⊗ Scheme.Modules.dual 𝓛₀) :=
      Scheme.Modules.IsInvertible.tensor_monoidalV2 h₁ hdinv
    have φ : 𝓛₀ ⊗ (𝓛₁ ⊗ Scheme.Modules.dual 𝓛₀) ≅ 𝓛₁ :=
      β_ _ _ ≪≫ α_ _ _ _ ≪≫ (Iso.refl 𝓛₁ ⊗ᵢ (β_ _ _ ≪≫ εd)) ≪≫ ρ_ 𝓛₁
    obtain ⟨e', he'⟩ := (RiemannForm.existsUnique_isRiemannForm k E.f E.L E.comm E.bundle
      (𝓛₁ ⊗ Scheme.Modules.dual 𝓛₀) hP'inv ℓ hℓ ζ hζ hζℓ).exists
    have hsum := RiemannForm.isRiemannForm_add_of_iso_tensor k E.f E.L E.comm E.bundle 𝓛₀ h₀ ℓ hℓ ζ hζ hζℓ e₀ he₀
      (𝓛₁ ⊗ Scheme.Modules.dual 𝓛₀) hP'inv e' he' 𝓛₁ ⟨φ.symm⟩
    have he'0 : e' = 0 := by
      have h := RiemannForm.isRiemannForm_unique k E.f E.L E.comm E.bundle 𝓛₁ h₁ ℓ hℓ ζ hζ hζℓ (e₀ + e') hsum e₁ he₁
      rw [hr] at h
      ext u v
      have huv := congrArg (fun t : ↥(TateModule ℓ (E.L.AlgPoints E.comm k)) →ₗ[ℤ_[ℓ]]
        ↥(TateModule ℓ (E.L.AlgPoints E.comm k)) →ₗ[ℤ_[ℓ]] ℤ_[ℓ] => t u v) h
      simp only [LinearMap.add_apply] at huv
      rw [LinearMap.zero_apply, LinearMap.zero_apply]
      exact add_eq_left.mp huv
    have hall := (RiemannForm.eq_zero_iff_forall_nonempty_pullback_translation_iso k E.f E.L E.comm E.bundle
      (𝓛₁ ⊗ Scheme.Modules.dual 𝓛₀) hP'inv 2 E.dim_fibre ℓ hℓ ζ hζ hζℓ e' he').mp he'0
    have hPic : Scheme.Modules.IsInvertible (𝓛₁ ⊗ Scheme.Modules.dual 𝓛₀) ∧
        ∀ x : SchemeHomOver (𝟙 (Spec (CommRingCat.of k))) E.f,
          Nonempty ((Scheme.Modules.pullback (E.L.translate x)).obj (𝓛₁ ⊗ Scheme.Modules.dual 𝓛₀) ≅
            𝓛₁ ⊗ Scheme.Modules.dual 𝓛₀) := by
      refine ⟨hP'inv, fun x => ?_⟩
      rw [hbridge.2 x]
      exact hall (RelativeGroupLaw.AlgPoints.ofPoint (RiemannForm.ofUnitPt E.f x))
    obtain ⟨ψ⟩ := Polarisation.nonempty_tensor_pullback_negMor_iso_of_inPicZero k E.f E.L E.comm E.bundle 𝓛₀
      (𝓛₁ ⊗ Scheme.Modules.dual 𝓛₀) h₀ hPic
    have θ : 𝓛₁ ⊗ (Scheme.Modules.pullback (negMor E.f E.L)).obj 𝓛₁ ≅
        𝓛₀ ⊗ (Scheme.Modules.pullback (negMor E.f E.L)).obj 𝓛₀ :=
      (φ.symm ⊗ᵢ (Scheme.Modules.pullback (negMor E.f E.L)).mapIso φ.symm) ≪≫ ψ
    exact (Polarisation.locIsoOnBase_iff_nonempty_iso_of_field E.f _ _).mpr ⟨θ.symm⟩
  ·
    exfalso
    have hsum : RiemannForm.IsRiemannForm E.f E.L E.comm (𝓛₁ ⊗ 𝓛₀) ℓ ζ 0 := by
      have h := RiemannForm.isRiemannForm_add_of_iso_tensor k E.f E.L E.comm E.bundle 𝓛₁ h₁ ℓ hℓ ζ hζ hζℓ e₁ he₁
        𝓛₀ h₀ e₀ he₀ (𝓛₁ ⊗ 𝓛₀) ⟨Iso.refl _⟩
      have hz : e₁ + e₀ = 0 := by
        rw [hr, hr1]
        ext u v
        simp only [LinearMap.add_apply, LinearMap.smul_apply, LinearMap.zero_apply, smul_eq_mul]
        ring
      rwa [hz] at h
    have hall := (RiemannForm.eq_zero_iff_forall_nonempty_pullback_translation_iso k E.f E.L E.comm E.bundle
      (𝓛₁ ⊗ 𝓛₀) (Scheme.Modules.IsInvertible.tensor_monoidalV2 h₁ h₀) 2 E.dim_fibre ℓ hℓ ζ hζ hζℓ 0 hsum).mp rfl
    apply Polarisation.not_forall_nonempty_pullback_translate_tensor_iso_of_kernelTrivial_of_geomFibreH0Finrank_pos
      k E.f E.L E.comm E.bundle 2 E.dim_fibre (by norm_num) 𝓛₀ 𝓛₁ h₀ h₁ hK₀ (hpos₀ k (RingHom.id k))
      (hpos₁ k (RingHom.id k))
    intro x
    rw [hbridge.2 x]
    exact hall (RelativeGroupLaw.AlgPoints.ofPoint (RiemannForm.ofUnitPt E.f x))

end S_CerednikDrinfeld_QM_FakeEllipticCurve_locIsoOnBase_tensor_pullback_negMor_of_kernelTrivial_of_rosatiCompatible_of_isAlgClosed
end P2MW
export P2MW.S_CerednikDrinfeld_QM_FakeEllipticCurve_locIsoOnBase_tensor_pullback_negMor_of_kernelTrivial_of_rosatiCompatible_of_isAlgClosed (solution)
