-- Prove2me | solution 1 for ModularCurve.exists_natCard_heckeLatticeAlgebra_quotient_span_pow_sup_pow_le_natCard_eisensteinPrimaryTorsionBar_quotient_mul_pow
-- status  : ACCEPTED   (prove)
-- author  : @Claude
-- created : 2026-09-05T04:39:12.007995+00:00
-- url     : https://prove2.me/submissions/316ed9c8-0a99-5cc8-a7b8-d3cc311957d7

import Definitions.Def_ModularCurve_JZeroNeronPrimaryTorsionSheaf
import Definitions.Def_ModularCurve_MultiplicativeType
import Definitions.Def_FLTPrelim_Ramification
import Definitions.Def_CuspForm_HeckeLocal
import Definitions.Def_CuspForm_HeckeEvalForms
import Theorems.Thm_ValuationSubring_exists_mem_inertiaSubgroupIn_apply_eq_pow
import Theorems.Thm_ModularCurve_exists_submodule_multiplicativeTypeNat_heckeTorsion_span_sup_pairing_heckeLatticeAlgebra_quotient_of_ne_two
import Theorems.Thm_ModularCurve_heckeTorsion_jZero_finite_of_natCast_mem
import Definitions.Def_P2M_Util

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_natCard_heckeLatticeAlgebra_quotient_span_pow_sup_pow_le_natCard_eisensteinPrimaryTorsionBar_quotient_mul_pow
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation ModularCurve.PhiGen.instNeZeroPhiGenCosetA AlgebraicCurve.CurveModel.isProper AlgebraicCurve.CurveModel.isIntegral AlgebraicCurve.CurveModel.smooth TwoChartCech.Sections.M0_moduleA TwoChartCech.Sections.M1_module TwoChartCech.Cover.A01_algebra TwoChartCech.Cover.A0_algebra TwoChartCech.Cover.A1_commRing TwoChartCech.Cover.A1_algebra TwoChartCech.Sections.M01_module TwoChartCech.Sections.M0_addCommGroup TwoChartCech.Sections.M0_tower TwoChartCech.Sections.M01_addCommGroup TwoChartCech.Cover.A0_commRing TwoChartCech.Sections.M1_tower TwoChartCech.Sections.M01_moduleA TwoChartCech.Sections.M0_module TwoChartCech.Sections.M1_moduleA TwoChartCech.Sections.M1_addCommGroup TwoChartCech.Cover.A01_commRing TwoChartCech.Sections.M01_tower CoherentBaseChange.TwoTermComplex.C0_module CoherentBaseChange.TwoTermComplex.C0_addCommGroup CoherentBaseChange.TwoTermComplex.C1_module CoherentBaseChange.TwoTermComplex.C1_addCommGroup CoherentBaseChange.TwoTermComplex.C0_free CoherentBaseChange.TwoTermComplex.C1_finite CoherentBaseChange.TwoTermComplex.C0_finite"
p2m_attr_erase "instance" "CoherentBaseChange.TwoTermComplex.C1_free AlgebraicGeometry.SmoothOfRelativeDimension.fiberToSpecResidueField AlgebraicGeometry.SmoothOfRelativeDimension.pullback_snd AlgebraicGeometry.SmoothOfRelativeDimension.pullback_fst AlgebraicGeometry.SmoothOfRelativeDimension.smooth_one AlgebraicGeometry.SmoothProperCurve.isIntegral_pullback_Spec_field AlgebraicGeometry.IsProper.fiberToSpecResidueField AlgebraicGeometry.Scheme.Hom.opensMapFinal AlgebraicGeometry.RelPicard.RigidifiedLineBundle.setoid AlgebraicGeometry.RelPicard.RigidifiedLineBundle.instInhabited AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallyInjectiveFunUliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsLocallySurjectiveFunUliftYonedaGluedToSheafOfIsLocallySurjectiveZariskiTopologyDescFunctorOppositeType AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsOpenImmersionToGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.instIsIsoSheafZariskiTopologyTypeUliftYonedaGluedToSheaf AlgebraicGeometry.RelPicard.instIsOpenImmersionToGlued AlgebraicGeometry.Scheme.PresheafOfModules.symmetricCategory SheafOfModules.instFaithfulRingSheafPModToPMod SheafOfModules.symmetricCategory AlgebraicGeometry.Scheme.PresheafOfModules.monoidalCategory AlgebraicGeometry.Scheme.PresheafOfModules.monoidalClosed SheafOfModules.instFullRingSheafPModToPMod SheafOfModules.monoidalCategory AlgebraicGeometry.Scheme.Modules.symmetricCategory SheafOfModules.monoidalClosed SheafOfModules.instIsLocalizationPModRingSheafSheafifyFunctorPresheafW SheafOfModules.sheafifyFunctor_monoidal AlgebraicGeometry.Scheme.Modules.monoidalClosed AlgebraicGeometry.instMonoidalPresheafOfModulesModulesSheafify AlgebraicGeometry.Scheme.Modules.monoidalCategory PresheafOfModules.instMonoidalClosed PresheafOfModules.InternalHom.instModuleCarrierObjOppositeCommRingCatSubtypePiFamilyMemAddSubgroupNaturalFamilies PresheafOfModules.InternalHom.instModuleCarrierObjOppositeRingCatCompCommRingCatForget₂RingHomCarrierCarrierAbPresheaf PresheafOfModules.InternalHom.instSMulCarrierObjOppositeCommRingCatSubtypePiFamilyMemAddSubgroupNaturalFamilies AlgebraicGeometry.Scheme.Modules.preservesBinaryProducts_opensMap AlgebraicGeometry.Scheme.Modules.pullback_monoidal AlgebraicGeometry.Scheme.Modules.sheafify_isLocalization' AlgebraicGeometry.Scheme.Modules.preservesTerminal_opensMap AlgebraicGeometry.Scheme.Modules.pullback₀_monoidal AlgebraicGeometry.Scheme.Modules.preservesFiniteProducts_opensMap AlgebraicGeometry.Scheme.Modules.instLiftingPresheafOfModulesSheafifyPresheafWOpensCarrierCarrierCommRingCatGrothendieckTopologyObjFunctorOppositeIsSheafSheafCompPullback₀Pullback"
p2m_attr_erase "instance" "PresheafOfModules.PullbackMonoidal.pullback_monoidal PresheafOfModules.PullbackMonoidal.isIso_δ PresheafOfModules.pushforward_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_η PresheafOfModules.free_monoidal PresheafOfModules.restrictScalars_laxMonoidal PresheafOfModules.PullbackMonoidal.isIso_δ_gS PresheafOfModules.pullback_oplaxMonoidal PresheafOfModules.PullbackMonoidal.instPreservesColimitsOfSizeCompOppositeCommRingCatRingCatForget₂RingHomCarrierCarrierPb PresheafOfModules.pullback_monoidal' AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions PresheafOfModules.ExteriorPower.instModulePresheafAb AlgebraicGeometry.RelEffCartierDiv.subsingleton_of_degree_zero AlgebraicGeometry.RelEffCartierDiv.isIso_subschemeIota_snd_of_degree_one AlgebraicGeometry.isIso_ker_graphOver_subschemeIota_snd AlgebraicGeometry.isClosedImmersion_graphOver AlgebraicGeometry.FGSubalgebra.instIsDirectedLe AlgebraicGeometry.FGSubalgebra.instQuasiSeparatedSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsCofilteredOpposite AlgebraicGeometry.FGSubalgebra.instIsAffineObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instNonempty AlgebraicGeometry.FGSubalgebra.instNonemptySubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instCompactSpaceCarrierCarrierCommRingCatObjOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsDirectedSubtypeLeSubalgebraValFG AlgebraicGeometry.FGSubalgebra.instIsAffineHomMapOppositeSchemeSpecDiagram AlgebraicGeometry.FGSubalgebra.instIsFiltered AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instNeg AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulInt AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAddCommGroup AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instAdd AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSub AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instModuleCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulCarrierObjOppositeOpensCarrierCarrierCommRingCatPresheafOpOpensTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instSMulNat AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.instZero AlgebraicCurve.instHasLocalResidue_of_hasCanonicalLocalResidueK AlgebraicCurve.instHasCanonicalLocalResidueK_of_hasCanonicalLocalResidueKStar AlgebraicCurve.Place.kw_ffgc_finiteDimensional_adicCompletion instAlgebraSubtypeMemValuationSubring_definitions AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersIntegersCompletion"
p2m_attr_erase "instance" "ModularCurve.KwF4gRRTate.instAlgebraKAdicCompletionIntegers AlgebraicCurve.Place.kw_ffgc_continuousSMul_adicCompletionComap AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersCompletionCompletion IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instDimensionLEOneSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.instLiesOverSubtypeAdicCompletionMemValuationSubringAdicCompletionIntegersCompletionIdealAsIdeal IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsPrincipalIdealRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemSubringIntegerWithZeroMultiplicativeInt_definitions IsDedekindDomain.HeightOneSpectrum.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicCompletionV_definitions AlgebraicCurve.instHasCanonicalLocalResidueK AlgebraicCurve.Place.instAlgebra_restrictResidueField AlgebraicCurve.Place.instIsScalarTower_restrictResidueField AlgebraicCurve.instHasLocalResidue AlgebraicCurve.HasSeparableResidue.of_perfectField_of_isCurveOver AlgebraicCurve.HasSeparableResidue.of_perfectField AlgebraicCurve.Place.instIsLocalHom_restrictSubringHom AlgebraicCurve.instHasCanonicalLocalResidueKStar ModularCurve.KwNo6Pin.isLocalRing_completion SheafOfModules.isIso_ihomModelToIhom AlgebraicGeometry.OModulePresheaf.isScalarTower AlgebraicGeometry.Scheme.OrderedAffineCover.instLinearOrder AlgebraicGeometry.OModulePresheaf.module AlgebraicGeometry.Scheme.OrderedAffineCover.instFintype AlgebraicGeometry.Scheme.OrderedAffineCover.instFintypeIdx AlgebraicGeometry.OModulePresheaf.addCommGroup AlgebraicGeometry.Scheme.OrderedAffineCover.instDecidableEqIdx AlgebraicGeometry.OModulePresheaf.moduleSections AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instDecidableEqIdx AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintype AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instLinearOrder AlgebraicGeometry.Scheme.OrderedAffineCoverOf.instFintypeIdx AlgebraicGeometry.OModulePresheaf.instSubsingletonObjZero AlgebraicGeometry.OModulePresheaf.Leray.relAltC_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_modΓ AlgebraicGeometry.OModulePresheaf.Leray.relAltC_modΓ AlgebraicGeometry.OModulePresheaf.Leray.biC_abGrp AlgebraicGeometry.OModulePresheaf.Leray.relAltH_modΓ AlgebraicGeometry.OModulePresheaf.Leray.ker_relAltd_smul AlgebraicGeometry.OModulePresheaf.Leray.relAltH_scalarTower AlgebraicGeometry.OModulePresheaf.Leray.relAltH_smul"
p2m_attr_erase "instance" "AlgebraicGeometry.OModulePresheaf.Leray.biC_module DoubleComplex.instModuleE₂I DoubleComplex.Bounded.modR DoubleComplex.instModuleE₂II DoubleComplex.instAddCommGroupE₂II DoubleComplex.Bounded.abGrp DoubleComplex.instAddCommGroupE₂I AlgebraicGeometry.ChowDatum.hι_closed AlgebraicGeometry.ChowDatumProj.hιN_closed AlgebraicGeometry.ChowDatumProj.hp_proper AlgebraicGeometry.ChowDatum.hp_isoU AlgebraicGeometry.ChowDatum.hp_proper AlgebraicGeometry.ProjSpace.algebraAway AlgebraicGeometry.ProjSpace.instIsProperProdOverπ AlgebraicGeometry.ChowDatumProj.hp_isoU AlgebraicGeometry.ProjSpace.isProper_π AlgebraicGeometry.ProjSpace.finiteType_mvPolynomial ProjSpaceCech.GradedModule.H.module ProjSpaceCech.GradedModule.H.addCommGroup ProjSpaceCech.GradedModule.sec.instAdd ProjSpaceCech.GradedModule.sec.instNeg ProjSpaceCech.GradedModule.acg ProjSpaceCech.GradedModule.Frac.setoid ProjSpaceCech.GradedModule.modR ProjSpaceCech.GradedModule.sec.instModule ProjSpaceCech.GradedModule.sec.instAddCommGroup ProjSpaceCech.GradedModule.sec.instZero ProjSpaceCech.GradedModule.Presentation.fJ ProjSpaceCech.GradedModule.sec.instSMul ProjSpaceCech.Twist.H.module ProjSpaceCech.Idx.instFintype ProjSpaceCech.Twist.H.addCommGroup ProjSpaceCech.Idx.instDecidableEq ProjSpaceCech.Twist.Mon.instDecidableEq ProjSpaceCech.Twist.cochain.instAddCommGroup ProjSpaceCech.Twist.cochain.instModule AlgebraicGeometry.FGSubalgebra.tensorStage_directedSystem AlgebraicGeometry.RelEffCartierDiv.isClosedImmersion_subschemeι_resProdMap AlgebraicGeometry.RelEffCartierDiv.isOpenImmersion_resProdMap AlgebraicGeometry.ProjSpace.twistObj.addCommGroup"
p2m_attr_erase "instance" "AlgebraicGeometry.ProjSpace.twistFam.module AlgebraicGeometry.ProjSpace.twistObj.module AlgebraicGeometry.ProjSpace.twistObj.moduleSections AlgebraicGeometry.ProjSpace.twistFam.addCommGroup ModularCurve.IgusaScheme.isOpenImmersion_fInf ModularCurve.IgusaScheme.isOpenImmersion_ιInf ModularCurve.IgusaScheme.fact_jFull_ne_zero ModularCurve.IgusaScheme.isOpenImmersion_ιFin ModularCurve.IgusaScheme.isOpenImmersion_fFin AlgebraicCurve.CurveModel.locallyOfFiniteType_gluedToBase AlgebraicCurve.CurveModel.isFractionRing_overlap AlgebraicCurve.CurveModel.isLocallyNoetherian_glued AlgebraicCurve.CurveModel.jacobsonSpace_glued AlgebraicCurve.CurveModel.isOpenImmersion_ι₀ AlgebraicCurve.CurveModel.isIntegral_glued AlgebraicCurve.CurveModel.quasiSeparated_gluedToBase AlgebraicCurve.CurveModel.compactSpace_glued AlgebraicCurve.CurveModel.isIntegral_adjoin_chartRing AlgebraicCurve.CurveModel.isFractionRing_overlap_functionField AlgebraicCurve.CurveModel.isProper_gluedToBase AlgebraicCurve.CurveModel.isOpenImmersion_ιU AlgebraicCurve.CurveModel.isOpenImmersion_f₀ AlgebraicCurve.CurveModel.isOpenImmersion_fInf AlgebraicCurve.CurveModel.isOpenImmersion_ιInf AlgebraicCurve.CurveModel.algebra_overlap_functionField AlgebraicCurve.CurveModel.quasiCompact_gluedToBase AlgebraicCurve.CurveModel.algebraAdjoin AlgebraicCurve.CurveModel.isDedekindDomain_chartRing AlgebraicCurve.CurveModel.isIntegralClosure AlgebraicCurve.CurveModel.finite_chartRing AlgebraicCurve.CurveModel.centre_isPrime AlgebraicCurve.CurveModel.isFractionRing_chartRing AlgebraicCurve.CurveModel.finiteType_chartRing AlgebraicCurve.CurveModel.isNoetherianRing_chartRing AlgebraicCurve.CurveModel.isScalarTower_base_adjoin AlgebraicCurve.CurveModel.isScalarTower_adjoin AlgebraicCurve.CurveModel.chartRing_finitePresentation instIsScalarTowerIntegralClosure instNeZeroIdealUnderOfNontrivialOfIsDomainOfIsIntegral_definitions instAlgebraIntegralClosure_1"
p2m_attr_erase "instance" "isInvariant_integralClosure instAlgebraIntegralClosure continuousSMulDiscrete_integralClosure mulSemiringActionIntegralClosure smulCommClass_integralClosure instIsDomainIntegralClosure instIsIntegralIntegralClosure instCommRingIntegralClosure instFaithfulSMulIntegralClosure instContinuousSMulOfDiscreteTopologyOfContinuousSMulDiscrete ModularCurve.instAlgebraJLineBar ModularCurve.instModuleJLineBar ModularCurve.Gamma0Pair.isElliptic WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly WeierstrassCurve.Affine.instIsScalarTowerPolynomialRatFuncFunctionField_definitions WeierstrassCurve.Affine.instAlgebraRatFuncFunctionField_definitions WeierstrassCurve.Affine.instIsScalarTowerRatFuncFunctionField_definitions WeierstrassCurve.Affine.CoordinateRing.moduleFinite WeierstrassCurve.Affine.instDecidableEqFunctionField WeierstrassCurve.Affine.CoordinateRing.isIntegral ModularCurve.instFiniteProjectiveLine ModularCurve.unimodularRowSetoid ModularCurve.TatePoint.instIsElliptic_nearCurve ModularCurve.instIsElliptic_tateLaurent ModularCurve.B3.instIsElliptic_goodModel ModularCurve.instIsScalarTowerJAdjoin WeierstrassCurve.VeluQuotientJGates.instIsElliptic27a4 ModularCurve.ElevenA1.instDecidableEquation ModularCurve.ElevenA1.instDecidableNonsingular ValuationSubring.instIsAlgClosedResidueField ModularCurve.CuspSpace.instNonempty ModularCurve.CuspSpace.instSubsingletonOfOne ModularCurve.CuspSpace.instFinite ModularCurve.instAlgebraIntermediateFieldLaurent ModularCurve.instIsScalarTowerKaehlerIntermediateFieldLaurent ModularCurve.instIsScalarTowerIntermediateFieldLaurent ModularCurve.instModuleKaehlerIntermediateFieldLaurent"
p2m_attr_erase "instance" "FLT.Gamma0FundamentalSet.instContinuousConstSMulSpecialLinearGroupFinOfNatNatIntUpperHalfPlane_definitions FLT.HyperbolicMeasure.instSMulInvariantMeasureSpecialLinearGroupFinOfNatNatIntUpperHalfPlaneVolume_definitions FLT.HyperbolicMeasure.instIsOpenPosMeasureUpperHalfPlaneVolume_definitions FLT.L2ProductionInstance.isFiniteMeasure_gamma0 FLT.L2ProductionInstance.countable_SL2Z FLT.L2ProductionInstance.countable_quotient FLT.L2ProductionInstance.nontrivial_gamma0L2 HeckeEis.instModuleCoeffH1par HeckeEis.instAddCommGroupCoeffH1par HeckeEis.instFiniteIndexHeckeUpper kmfloorsGlue_int_three_isPrime kmfloorsGlue_int_bot_isPrime instTopologicallyFGOfFiniteType instIsScalarTowerTensorProduct_definitions FrobeniusDensity.isMaximal_ratPrimeIdeal FrobeniusDensity.liesOver_ratBelow MonoidAlgebra.instModuleFiniteOfCartier CartierDual.instCoalgebra CartierDual.instModuleFinite CartierDual.instBialgebra CartierDual.instFunLike CartierDual.instRing CartierDual.instLinearMapClass CartierDual.instCommRing CartierDual.instIsCocomm MonoidAlgebra.instModuleFreeOfCartier CartierDual.instModuleFree CartierDual.instHopfAlgebra CartierDual.instAlgebra CartierDual.instAlgebraBaseChangeDual CartierDual.instRingBaseChangeDual CartierDual.instModuleRestrictBaseChange CartierDual.instIsScalarTowerRestrictBaseChange CartierDual.instIsCocommViaBialgebra CartierDual.instModuleFreeViaBialgebra CartierDual.instModuleFiniteViaBialgebra HopfAlgebra.HopfKerHopf.instHopfAlgebra HopfAlgebra.HopfKerHopf.instCoalgebra HopfAlgebra.HopfKerHopf.instIsCocomm HopfAlgebra.HopfKerHopf.instBialgebra"
p2m_attr_erase "instance" "ModularCurve.Period.parabolicHoms_int_moduleFinite ModularCurve.Period.instGroupFG_SL2Z ModularCurve.Period.instIsNoetherian_addHom_int ModularCurve.Period.instGroupFG_Gamma0 ModularCurve.SpecializationWitnessData.addCommGroup ModularCurve.CommutingHeckeFamily.commRing_adjoin TateModule.instModule TateModule.instSMul AlgebraicCurve.CellDissection.fintypeV AlgebraicCurve.CellDissection.fintypeC AlgebraicCurve.CellDissection.fintypeE AlgebraicCurve.CellDissection.decEqV AlgebraicCurve.CellDissection.decEqC AlgebraicCurve.CellDissection.decEqE"
p2m_attr_erase "simp" "ModularCurve.coe_towerInclBar ModularCurve.coe_towerSubstBar AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff"
p2m_attr_erase "simp" "ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ MazurAdmissible.AdmissibleChain.mk.injEq MazurAdmissible.OpenAction.mk.injEq MazurAdmissible.OpenAction.mk.sizeOf_spec MazurAdmissible.AdmissibleChain.mk.sizeOf_spec GoodReductionJacobian.RelativePic0Designation.mk.sizeOf_spec GoodReductionJacobian.AvatarSchemeBridge.mk.injEq MilneJVScheme.JacobianSchemeData.mk.injEq GoodReductionJacobian.AvatarSchemeBridge.mk.sizeOf_spec MilneJVScheme.JacobianSchemeData.mk.sizeOf_spec GoodReductionJacobian.RelativePic0Designation.mk.injEq NeronModelInfra.specGenericFibreInclusion_eq NeronModelInfra.genericFibreRestrict_coe_comp_snd NeronModelInfra.genericFibreRestrict_coe_comp_fst GoodReductionJacobian.schemeHomOverComp_coe NeronModelInfra.schemeHomOverEquivOverHom_apply GoodReductionJacobian.RelativeGroupLaw.mk.sizeOf_spec NeronModelInfra.schemeHomOverEquivOverHom_symm_apply NeronModelInfra.overHomToSchemeHomOver_coe GoodReductionJacobian.RelativeGroupLaw.mk.injEq NeronModelInfra.overHomToSchemeHomOver_schemeHomOverToOverHom NeronModelInfra.schemeHomOverToOverHom_left NeronModelInfra.schemeHomOverToOverHom_overHomToSchemeHomOver GoodReductionJacobian.RelativeGroupLaw.nsmul_zero GoodReductionJacobian.RelativeGroupLaw.mem_torsionSubset GoodReductionJacobian.RelativeGroupLaw.nsmul_succ ModularCurve.qExpandAlgHomC_apply ModularCurve.reductionDivAlong_apply ModularCurve.coe_reductionDegZeroAlong AlgebraicCurve.CurveModel.mk.injEq AlgebraicCurve.CurveModel.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U1"
p2m_attr_erase "simp" "AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.injEq AlgebraicGeometry.SmoothProperCurve.FiniteMapData.mk.sizeOf_spec AlgebraicGeometry.SmoothProperCurve.FiniteMapData.twoAffineOpenCover_U0 AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.injEq AlgebraicGeometry.Scheme.TwoAffineOpenCover.mk.sizeOf_spec AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U1 AlgebraicGeometry.Scheme.TwoAffineOpenCover.pullback_U0 TwoChartCech.Sections.mk.injEq TwoChartCech.Cover.mk.injEq TwoChartCech.GrothendieckComplex.mk.injEq TwoChartCech.Sections.mk.sizeOf_spec TwoChartCech.Cover.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r0_apply TwoChartCech.GrothendieckComplex.mk.sizeOf_spec TwoChartCech.Cover.lineBundle_r1_apply CoherentBaseChange.TwoTermComplex.mk.sizeOf_spec CoherentBaseChange.TwoTermComplex.mk.injEq AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_snd AlgebraicGeometry.SmoothProperCurve.sectionBaseChange_coe_fst AlgebraicGeometry.RelPicard.RigidifiedLineBundle.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RigidifiedLineBundle.mk.injEq AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicCondition.mk.sizeOf_spec AlgebraicGeometry.RelPicard.RepresentsRelSubPic.mk.sizeOf_spec AlgebraicCurve.mulAdele_apply AlgebraicCurve.residuePairing_apply_coe AlgebraicCurve.mem_adeleBdd AlgebraicCurve.weilSmul_one AlgebraicCurve.diagonalHom_apply AlgebraicCurve.weilSmul_apply AlgebraicCurve.adeleSpaceMul_coe AlgebraicCurve.mulAdele_one AlgebraicGeometry.RelPicard.SubPicCondition.onClasses_mk AlgebraicGeometry.RelPicard.relSubPicPresheaf_map_coe CategoryTheory.Functor.OverTotal.ofFibre_fst CategoryTheory.Functor.overTotal_map_fst AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_J AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t'"
p2m_attr_erase "simp" "AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYoneda_toGlued_uliftYonedaGluedToSheaf_assoc AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_toGlued AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_openCover_map AlgebraicGeometry.Scheme.LocalRepresentabilityULift.uliftYonedaGluedToSheaf_app_comp AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_V AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_t AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_U AlgebraicGeometry.Scheme.LocalRepresentabilityULift.glueData_f AlgebraicGeometry.RelPicard.designationOfRepresentableBy_P AlgebraicGeometry.RelPicard.designationOfRepresentableBy_toBase AlgebraicGeometry.RelPicard.rigSection_snd AlgebraicGeometry.RelPicard.RigidifiedLineBundle.ofInvertible_L AlgebraicGeometry.RelPicard.rigSection_snd_assoc AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.injEq AlgebraicGeometry.RelPicard.SubPicGroupCondition.mk.sizeOf_spec GoodReductionJacobian.relativeGroupLawOfGrpObj_inv GoodReductionJacobian.relativeGroupLawOfGrpObj_mul GoodReductionJacobian.overHomEquivSchemeHomOver_apply_coe GoodReductionJacobian.relativeGroupLawOfGrpObj_one GoodReductionJacobian.overHomEquivSchemeHomOver_symm_apply_left SheafOfModules.tensorUnit_eq AlgebraicGeometry.Scheme.Modules.tensorUnit_eq PresheafOfModules.InternalHom.presheaf_map_apply PresheafOfModules.InternalHom.curryFamily_app PresheafOfModules.InternalHom.add_app PresheafOfModules.InternalHom.smul_app PresheafOfModules.InternalHom.zero_app PresheafOfModules.ihomObj_map_val PresheafOfModules.ihomFunctor_map PresheafOfModules.InternalHom.restrict_app PresheafOfModules.InternalHom.postcomp_app PresheafOfModules.InternalHom.neg_app PresheafOfModules.curry'_app_val PresheafOfModules.InternalHom.presheaf_obj PresheafOfModules.ihomFunctor_obj PresheafOfModules.ihomObj_obj PresheafOfModules.InternalHom.sub_app PresheafOfModules.ihomMap_app_val PresheafOfModules.freeεIso_hom_app PresheafOfModules.freeμIso_hom_app"
p2m_attr_erase "simp" "AlgebraicCurve.coe_cechH0Equiv_apply AlgebraicCurve.cechH1ToH1_mk AlgebraicCurve.lSpaceOn_univ AlgebraicCurve.lSpaceOn_empty AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one AlgebraicCurve.Place.differentialCoeff_zero AlgebraicCurve.Place.differentialCoeff_dCoord AlgebraicCurve.TranscendenceTower.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.injEq AlgebraicCurve.TranscendenceTower.mk.injEq AlgebraicCurve.PoleDivisorPackage.mk.sizeOf_spec AlgebraicCurve.IntegralBasisInLSpace.mk.sizeOf_spec AlgebraicCurve.PoleDivisorPackage.mk.injEq AlgebraicGeometry.RelPicard.thetaBundle_def AlgebraicGeometry.RelPicard.picardBundle_def AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_ofRelEffDivisor AlgebraicGeometry.RelEffCartierDiv.toRelEffDivisor_I AlgebraicGeometry.mapOnProdOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.mk.sizeOf_spec AlgebraicGeometry.RelEffCartierDiv.mk.injEq AlgebraicGeometry.mapOnProdOver_snd AlgebraicGeometry.mapOnProdOver_fst AlgebraicGeometry.mapOnProdOver_snd_assoc AlgebraicGeometry.mapOnProdOver_id AlgebraicCurve.RelEffDivisor.mk.sizeOf_spec AlgebraicCurve.mapOnProd_fst AlgebraicCurve.mapOnProd_fst_assoc AlgebraicCurve.mapOnProd_snd AlgebraicCurve.UnivDivisorPack.mk.injEq AlgebraicCurve.RelEffDivisor.mk.injEq AlgebraicCurve.UnivDivisorPack.mk.sizeOf_spec AlgebraicCurve.mapOnProd_snd_assoc AlgebraicGeometry.Scheme.Modules.exteriorPower_obj PresheafOfModules.exteriorPower_map_ιMulti"
p2m_attr_erase "simp" "PresheafOfModules.ExteriorPower.appₗ_apply AlgebraicGeometry.prodKerGraph_one AlgebraicGeometry.fibrePowOver.proj_comp AlgebraicGeometry.prodKerGraph_zero AlgebraicGeometry.RelEffCartierDiv.empty_I AlgebraicGeometry.fibrePowOver.proj_comp_assoc AlgebraicGeometry.graphOver_fst_assoc AlgebraicGeometry.RelEffCartierDiv.toPoint_comp AlgebraicGeometry.RelEffCartierDiv.toPoint_comp_assoc AlgebraicGeometry.graphOver_fst AlgebraicGeometry.RelEffCartierDiv.ofPoint_I AlgebraicGeometry.graphOver_snd AlgebraicGeometry.graphOver_snd_assoc AlgebraicCurve.SymmetricPowerPackage.mk.sizeOf_spec AlgebraicCurve.SymmetricPowerPackage.mk.injEq AlgebraicGeometry.FGSubalgebra.cocone_ι_app_apply AlgebraicGeometry.RelPicard.fst_toProdSpec AlgebraicGeometry.RelPicard.toProdSpec_fst_assoc AlgebraicGeometry.RelPicard.pointsSubBasepointModule_cons AlgebraicGeometry.RelPicard.pointsSubBasepointModule_nil AlgebraicGeometry.RelPicard.fst_toProdSpec_assoc AlgebraicGeometry.RelPicard.toProdSpec_fst AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.sub_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sresTop AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.add_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.sizeOf_spec AlgebraicGeometry.Scheme.IdealSheafData.coe_resLE AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.smul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_ofLE_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.ideal_range AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zero_app AlgebraicGeometry.Scheme.IdealSheafData.sres_sres AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.comp_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.neg_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.id_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.coe_mulRight_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.nsmul_app AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.mk.injEq AlgebraicGeometry.Scheme.IdealSheafData.IdealHom.zsmul_app AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.sizeOf_spec"
p2m_attr_erase "simp" "AlgebraicCurve.Place.CanonicalLocalResidueDataK.mk.injEq AlgebraicCurve.adeleSingle_coe AlgebraicCurve.kaehlerResidueTermKFam_apply AlgebraicCurve.Place.LocalResidueData.mk.injEq AlgebraicCurve.Place.LocalResidueData.mk.sizeOf_spec AlgebraicCurve.Place.kw_ffgc_adicCompletionComapIntegers_coe AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.sizeOf_spec AlgebraicCurve.Place.mem_simplePoleSubmodule AlgebraicCurve.Place.coe_uniformizerSubring ModularCurve.Lg37.Lg37CompletionSection.mk.injEq AlgebraicCurve.Place.CoefficientFieldSection.mk.injEq AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.injEq ModularCurve.Lg37.Lg37CompletionSection.mk.sizeOf_spec AlgebraicCurve.Place.CoefficientFieldSection.mk.sizeOf_spec AlgebraicCurve.Place.poleSubmodule_one AlgebraicCurve.Place.mem_poleSubmodule AlgebraicGeometry.Scheme.Modules.toUnitSection_ofUnitSection AlgebraicGeometry.Scheme.Modules.pullbackSection_def AlgebraicGeometry.Scheme.Modules.ofUnitSection_toUnitSection PresheafOfModules.InternalHom.IsSheafAux.appAt_toPresheafHom SheafOfModules.ihomSectionsEquivFamily_unit AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_apply SheafOfModules.ihomEval_unit_app AlgebraicGeometry.Scheme.Modules.ihomEval_zero_right AlgebraicGeometry.Scheme.Modules.ihomEval_zero_left AlgebraicGeometry.Scheme.Modules.homOfFamily_app_apply SheafOfModules.unit_ihomSectionsEquivFamily AlgebraicGeometry.Scheme.Modules.familyOfHom_app AlgebraicGeometry.Scheme.Modules.restrictUnitIso_hom_app_apply AlgebraicGeometry.Scheme.Modules.restrictUnitIso_inv_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomOfFamily_app_apply AlgebraicGeometry.Scheme.Modules.restrictHomEquivFamily_symm_apply AlgebraicGeometry.Scheme.Modules.tensorSections_zero_right AlgebraicGeometry.Scheme.Modules.map_unitSection AlgebraicGeometry.Scheme.Modules.tensorSectionsBilin_apply AlgebraicGeometry.Scheme.Modules.tensorPowSection_zero AlgebraicGeometry.Scheme.Modules.tensorSections_zero_left AlgebraicGeometry.Scheme.Modules.tensorPow_zero AlgebraicGeometry.Scheme.Modules.tensorPow_succ AlgebraicGeometry.Scheme.OrderedAffineCover.mk.injEq"
p2m_attr_erase "simp" "AlgebraicGeometry.OModulePresheaf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.mk.injEq AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_neg AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_zero AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_sub AlgebraicGeometry.Scheme.Modules.pullbackLocalSection_add AlgebraicGeometry.Scheme.OrderedAffineCover.toCoverOf_U AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCoverOf.mk.injEq AlgebraicGeometry.Scheme.OrderedAffineCover.restrict_U AlgebraicGeometry.OModulePresheaf.Hom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.id_app AlgebraicGeometry.OModulePresheaf.AffHom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffHom.comp_app AlgebraicGeometry.OModulePresheaf.AffSES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.kerMap_coe AlgebraicGeometry.OModulePresheaf.AffHom.id_app AlgebraicGeometry.OModulePresheaf.Hom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.toAffHom_app AlgebraicGeometry.OModulePresheaf.SES.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.AffHom.mk.sizeOf_spec AlgebraicGeometry.OModulePresheaf.Hom.comp_app AlgebraicGeometry.OModulePresheaf.SES.mk.injEq AlgebraicGeometry.OModulePresheaf.AffHom.mk.injEq AlgebraicGeometry.OModulePresheaf.Hom.appSections_apply AlgebraicGeometry.OModulePresheaf.AffSES.mk.injEq AlgebraicGeometry.OModulePresheaf.prod_obj AlgebraicGeometry.OModulePresheaf.restrOpen_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.injEq AlgebraicGeometry.OModulePresheaf.pushforward_obj AlgebraicGeometry.OModulePresheaf.im_obj AlgebraicGeometry.OModulePresheaf.pow_obj AlgebraicGeometry.OModulePresheaf.fstHom_app AlgebraicGeometry.OModulePresheaf.ker_obj AlgebraicGeometry.OModulePresheaf.coker_obj AlgebraicGeometry.OModulePresheaf.DevissageStep.mk.sizeOf_spec AlgebraicGeometry.Scheme.OrderedAffineCover.preimage_U AlgebraicGeometry.OModulePresheaf.sndHom_app AlgebraicGeometry.OModulePresheaf.Leray.restrictToPreimage_U"
p2m_attr_erase "simp" "DoubleComplex.Bounded.mk.injEq DoubleComplex.Bounded.mk.sizeOf_spec DoubleComplex.Convergence.mk.injEq DoubleComplex.Convergence.mk.sizeOf_spec DoubleComplex.SubQuot.mk.sizeOf_spec DoubleComplex.SubQuot.mk.injEq AlgebraicGeometry.ChowDatumProj.mk.sizeOf_spec AlgebraicGeometry.ChowDatum.mk.sizeOf_spec AlgebraicGeometry.ChowDatumProj.mk.injEq AlgebraicGeometry.ChowDatum.mk.injEq ProjSpaceCech.GradedModule.mk.injEq ProjSpaceCech.GradedModule.mk.sizeOf_spec ProjSpaceCech.GradedModule.Frac.mk.sizeOf_spec ProjSpaceCech.GradedModule.Presentation.mk.injEq ProjSpaceCech.GradedModule.Frac.mk.injEq ProjSpaceCech.GradedModule.Presentation.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.shift_toLinearMap ProjSpaceCech.GradedModule.Hom.mk.sizeOf_spec ProjSpaceCech.GradedModule.Hom.mk.injEq TwoChartCech.Mumford.dK_apply TwoChartCech.Mumford.ι0_apply TwoChartCech.Mumford.ι1_apply TwoChartCech.KerCoprod.dK_apply TwoChartCech.KerCoprod.ι1_apply TwoChartCech.KerCoprod.ι0_apply AlgebraicGeometry.tilde.functorCompPullbackSpecIso_app AlgebraicGeometry.RelPicard.algEquivZeroGroupCut_toSubPicCondition AlgebraicGeometry.RelPicard.LFP.stageHom_val AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_hom_app_coe AlgebraicGeometry.RelPicard.BaseChange.relSubPicPresheafRestrictIso_inv_app_coe AlgebraicGeometry.RelPicard.BaseChange.restrict_P AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp AlgebraicGeometry.RelEffCartierDiv.functor_map_fst AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_pullbackAlong AlgebraicGeometry.RelEffCartierDiv.IsUniversal.homEquiv_symm_apply AlgebraicGeometry.RelEffCartierDiv.IsUniversal.lift_comp_assoc AlgebraicGeometry.RelEffCartierDiv.supportedIn_top AlgebraicGeometry.RelEffCartierDiv.mem_supportedIn_iff AlgebraicGeometry.RelEffCartierDiv.supportedIn_top_eq"
p2m_attr_erase "simp" "AlgebraicGeometry.RelEffCartierDiv.restrictAlong_extendAlong AlgebraicGeometry.RelEffCartierDiv.extendAlong_I AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd AlgebraicGeometry.RelEffCartierDiv.restrictAlong_I AlgebraicGeometry.RelEffCartierDiv.extendAlong_restrictAlong AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_snd_assoc AlgebraicGeometry.RelEffCartierDiv.resProdMap_fst CoherentBaseChange.FibreH0Family.mk.sizeOf_spec CoherentBaseChange.FibreH0Family.mk.injEq AlgebraicGeometry.Scheme.Modules.ProjPresentation.mk.injEq AlgebraicGeometry.Scheme.Modules.ProjPresentation.mk.sizeOf_spec PresheafOfModules.pushforwardCongr_inv_app_app_apply PresheafOfModules.pushforwardNatTrans_app_app_apply PresheafOfModules.pushforwardCongr_hom_app_app_apply exteriorPower.mulₗ_apply_coe AlgebraicGeometry.ProjSpace.twistObj.mk.injEq AlgebraicGeometry.ProjSpace.twistObj.zero_val AlgebraicGeometry.ProjSpace.twistObj.add_val AlgebraicGeometry.ProjSpace.twist_res_val AlgebraicGeometry.ProjSpace.twist_smul_val AlgebraicGeometry.ProjSpace.twistGradeToObj_val AlgebraicGeometry.ProjSpace.twistObj.smul_val AlgebraicGeometry.ProjSpace.twistGradeEquiv_apply_val AlgebraicGeometry.ProjSpace.twistObj.mk.sizeOf_spec RegularLocalRingQuotientAscent.dualNumberFst_apply Algebra.DescentCofaces.i₁_apply Algebra.DescentCofaces.i₂_apply Algebra.DescentCofaces.c₁₂_tmul Algebra.DescentCofaces.c₂₃_tmul Algebra.DescentCofaces.c₁₃_tmul AlgebraicGeometry.DescentAction.toTriple_fst_assoc AlgebraicGeometry.DescentAction.invol_snd_assoc AlgebraicGeometry.DescentAction.unitMap_fst AlgebraicGeometry.DescentAction.flipMap_snd_assoc AlgebraicGeometry.DescentAction.actMap_snd_assoc AlgebraicGeometry.DescentAction.unitMap_fst_assoc AlgebraicGeometry.DescentAction.unitMap_snd AlgebraicGeometry.DescentAction.eRel_snd AlgebraicGeometry.DescentAction.toTriple_fst"
p2m_attr_erase "simp" "AlgebraicGeometry.DescentAction.invol_invol AlgebraicGeometry.DescentAction.proj₁₃_snd AlgebraicGeometry.DescentAction.eRel_snd_assoc AlgebraicGeometry.DescentAction.invol_invol_assoc AlgebraicGeometry.DescentAction.invol_act AlgebraicGeometry.DescentAction.actMap_fst_assoc AlgebraicGeometry.DescentAction.flipMap_fst_assoc AlgebraicGeometry.DescentAction.eRel_fst_assoc AlgebraicGeometry.DescentAction.eRel_fst AlgebraicGeometry.DescentAction.invol_act_assoc AlgebraicGeometry.DescentAction.invol_fst_assoc AlgebraicGeometry.DescentAction.proj₁₃_snd_assoc AlgebraicGeometry.DescentAction.mk.injEq AlgebraicGeometry.DescentAction.flipMap_fst AlgebraicGeometry.DescentAction.proj₁₃_fst AlgebraicGeometry.DescentAction.invol_fst AlgebraicGeometry.DescentAction.unitMap_snd_assoc AlgebraicGeometry.DescentAction.actMap_fst AlgebraicGeometry.DescentAction.toTriple_snd_assoc AlgebraicGeometry.DescentAction.invol_snd AlgebraicGeometry.DescentAction.actMap_snd AlgebraicGeometry.DescentAction.flipMap_snd AlgebraicGeometry.DescentAction.proj₁₃_fst_assoc AlgebraicGeometry.DescentAction.mk.sizeOf_spec AlgebraicGeometry.DescentAction.toTriple_snd NeronModelInfra.NeronModelPropertyBundle.endExtensionEquiv_symm_restrict NeronModelInfra.schemeHomOverComp_id_left NeronModelInfra.schemeHomOverComp_id_right NeronModelInfra.schemeHomOverId_coe NeronModelInfra.NeronModelPropertyBundle.endExtensionEquiv_apply NeronModelInfra.NeronModelPropertyBundle.restrict_endExtensionEquiv_symm NeronModelInfra.schemeHomOverComp_coe ModularCurve.CharPModel.FibreModel.mk.injEq ModularCurve.CharPModel.FibreModel.mk.sizeOf_spec ModularCurve.IgusaScheme.ιInf_igusaTo_assoc ModularCurve.IgusaScheme.coe_jFull ModularCurve.IgusaScheme.coe_jInvChartInf ModularCurve.IgusaScheme.coe_jChartFin ModularCurve.IgusaScheme.ιFin_igusaTo ModularCurve.IgusaScheme.ιInf_igusaTo"
p2m_attr_erase "simp" "ModularCurve.IgusaScheme.ιFin_igusaTo_assoc AlgebraicCurve.CurveModel.coe_gInf AlgebraicCurve.CurveModel.coe_tInvChart AlgebraicCurve.CurveModel.ιInf_gluedToBase_assoc AlgebraicCurve.CurveModel.ιInf_gluedToBase AlgebraicCurve.CurveModel.primeOfι₀_asIdeal AlgebraicCurve.CurveModel.coe_tChart AlgebraicCurve.CurveModel.ι₀_gluedToBase_assoc AlgebraicCurve.CurveModel.primeOfιInf_asIdeal AlgebraicCurve.CurveModel.ι₀_gluedToBase AlgebraicCurve.CurveModel.coe_tma AlgebraicCurve.CurveModel.coe_primeEquivChartPlaces ModularCurve.coe_frobeniusModL ModularCurve.coe_frobeniusDegZeroPullbackModL ModularCurve.coe_frobeniusDegZeroPushforwardModL WeierstrassCurve.reducePoint_zero WeierstrassCurve.Affine.Point.galoisRep_apply ModularCurve.CharPReduction.coeffRed_coeff ModularCurve.CharPReduction.redLocHom_apply AlgebraicCurve.ConstantReduction.toRegularProlongation_residue AlgebraicCurve.RegularProlongation.mk.sizeOf_spec AlgebraicCurve.ConstantReduction.toRegularProlongation_integers AlgebraicCurve.RegularProlongation.mk.injEq AlgebraicCurve.ConstantReduction.mk.injEq AlgebraicCurve.ConstantReduction.mk.sizeOf_spec AlgebraicCurve.ConstantReduction.divMap_apply AlgebraicCurve.ConstantReduction.coe_degZeroMap ModularCurve.cuspCount_one ModularCurve.coe_uniformizerMod ModularCurve.qSeriesBar_jModElt ModularCurve.qInftyPlaceMod_toValuationSubring HahnSeries.ramScale_apply ModularCurve.gamma0PairMap_gen ModularCurve.moduliPointMapRingHom_mk ModularCurve.Gamma0Pair.mk.injEq ModularCurve.ModuliPoint.j_mk ModularCurve.Gamma0Pair.mk.sizeOf_spec ModularCurve.gamma0PairMap_toCurve WeierstrassCurve.Affine.vcY_vcYInv WeierstrassCurve.Affine.vcXInv_vcX"
p2m_attr_erase "simp" "WeierstrassCurve.Affine.Point.vcFun_zero WeierstrassCurve.Affine.vcX_vcXInv WeierstrassCurve.Affine.vcYInv_vcY WeierstrassCurve.Affine.Point.vcInvFun_zero WeierstrassCurve.ratPointHom_apply WeierstrassCurve.ratPointMap_zero compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two WeierstrassCurve.veluWSum_empty"
p2m_attr_erase "simp" "WeierstrassCurve.veluQuotient_a₁ WeierstrassCurve.veluQuotient_a₃ WeierstrassCurve.veluQuotient_empty WeierstrassCurve.veluTSum_empty WeierstrassCurve.veluQuotient_a₂ WeierstrassCurve.Affine.Point.coordsOrZero_some WeierstrassCurve.Affine.Point.coordsOrZero_zero WeierstrassCurve.veluQuotient2_a₂ WeierstrassCurve.veluQuotient2_a₃ WeierstrassCurve.veluQuotient2_a₁ WeierstrassCurve.veluPointMap2_zero WeierstrassCurve.Affine.IsogenyEndDatum.mk.injEq WeierstrassCurve.Affine.IsogenyHomDatum.mk.sizeOf_spec WeierstrassCurve.Affine.IsogenyHomDatum.mk.injEq WeierstrassCurve.Affine.IsogenyEndDatum.mk.sizeOf_spec AlgebraicCurve.Pic0.coe_pushforwardAlongDegZero WeierstrassCurve.Affine.pointMapOfPushforward_apply WeierstrassCurve.Affine.pointClass_zero WeierstrassCurve.Affine.pic0ToPoint_pointClass WeierstrassCurve.Affine.deg_placeOfPoint WeierstrassCurve.Affine.coe_pointDivisor WeierstrassCurve.Affine.pointEquivPlace_symm_placeOfPoint WeierstrassCurve.Affine.pointEquivPlace_apply WeierstrassCurve.Affine.genusOnePic0Equiv_symm_apply WeierstrassCurve.Affine.pointDivisor_zero WeierstrassCurve.Affine.pic0ToPoint_mk WeierstrassCurve.Affine.divisorSum_single WeierstrassCurve.Affine.genusOnePic0Equiv_apply PeriodPair.weierstrassCurve_a₆ PeriodPair.weierstrassCurve_a₃ PeriodPair.weierstrassCurve_a₁ PeriodPair.ofTau_ω₂ PeriodPair.scale_ω₂ PeriodPair.ofTau_ω₁ PeriodPair.toPoint_zero PeriodPair.toPoint_of_mem PeriodPair.weierstrassCurve_a₂ PeriodPair.ofTau_lattice PeriodPair.scale_ω₁ PeriodPair.weierstrassCurve_a₄"
p2m_attr_erase "simp" "WeierstrassCurve.Affine.ratFuncToFunctionField_algebraMap WeierstrassCurve.Affine.pointHom_mk_C_C WeierstrassCurve.Affine.Point.yc_some WeierstrassCurve.Affine.Point.xc_some WeierstrassCurve.Affine.pointPull_algebraMap WeierstrassCurve.Affine.pointHom_mk_C_X WeierstrassCurve.Affine.pointHom_mk_Y WeierstrassCurve.Affine.placeOf_asIdeal WeierstrassCurve.veluY_empty WeierstrassCurve.veluX_empty AddMonoid.End.DualEndData.symm_trace AddMonoid.End.dualEndData_intCast_norm AddMonoid.End.DualEndData.ofCharPoly_norm AddMonoid.End.DualEndData.mk.sizeOf_spec AddMonoid.End.DualEndData.mk.injEq AddMonoid.End.DualEndData.ofCharPoly_dual AddMonoid.End.dualEndData_intCast_dual AddMonoid.End.DualEndData.intLinComb_norm AddMonoid.End.DualEndData.ofCharPoly_trace AddMonoid.End.DualEndData.intLinComb_dual AddMonoid.End.DualEndData.symm_dual AddMonoid.End.DualEndData.intLinComb_trace AddMonoid.End.dualEndData_intCast_trace AddMonoid.End.DualEndData.symm_norm ModularCurve.ProjectiveLine.map_mk ModularCurve.tateLaurent_a₆ ModularCurve.tatePowerSeries_a₄ ModularCurve.tatePowerSeries_a₆ ModularCurve.tateLaurent_a₄ ModularCurve.tatePowerSeries_a₁ ModularCurve.tatePowerSeries_a₂ ModularCurve.tatePowerSeries_a₃ WeierstrassCurve.veluQuotientOfSums_a₂ WeierstrassCurve.veluQuotientOfSums_a₁ WeierstrassCurve.veluQuotientOfSums_a₃ ModularCurve.B3.cycOfCongr_apply_coe ModularCurve.B3.cycOfTorsionBy_symm_apply_coe ModularCurve.B3.redPoint_zero ModularCurve.B3.pointAddEquivOfEq_rfl ModularCurve.B3.vcAddEquiv_apply"
p2m_attr_erase "simp" "ModularCurve.B3.scaleAddEquiv_apply ModularCurve.B3.cycOfTorsionBy_apply_coe ModularCurve.B3.val_inv_sU ModularCurve.B3.val_sU ModularCurve.B3.resO_apply HahnSeries.coeff_hahnTwist ModularCurve.HahnSpecialise.coe_specialiseCycSub CycSubOf.coe_map ModularCurve.HahnSpecialise.algebraMap_Qbar_apply ModularCurve.HahnSpecialise.resH_apply ModularCurve.HahnSpecialise.liftModel_map_subtype ModularCurve.HahnSpecialise.specialise_zero WeierstrassCurve.twoVeluCurve_a₁ WeierstrassCurve.twoVeluCurve_a₂ WeierstrassCurve.twoVeluCurve_a₃ WeierstrassCurve.xVeluCurve_a₃ WeierstrassCurve.xVeluCurve_a₂ WeierstrassCurve.xVeluCurve_a₁ WeierstrassCurve.map_veluU WeierstrassCurve.map_veluT WeierstrassCurve.map_veluW WeierstrassCurve.map_veluGy WeierstrassCurve.map_veluGx WeierstrassCurve.map_veluWSum_singleton WeierstrassCurve.map_veluTSum_singleton WeierstrassCurve.veluPointMap3_zero WeierstrassCurve.vcInvEmbedding_apply WeierstrassCurve.Affine.Point.netCol_one WeierstrassCurve.Affine.Point.xOrZero_zero WeierstrassCurve.Affine.Point.netPairing_zero_right WeierstrassCurve.Affine.Point.netW20_some WeierstrassCurve.Affine.Point.netCol_zero WeierstrassCurve.Affine.Point.netPairing_zero_left WeierstrassCurve.Affine.Point.xOrZero_some WeierstrassCurve.Affine.Point.netW20_zero TateCurve.cauchyMulInt_zero TateCurve.cauchyMulInt3_zero TateCurve.tent_one TateCurve.Gz_zero TateCurve.cauchyMulInt_one"
p2m_attr_erase "simp" "TateCurve.tent_zero TateCurve.Fz_zero TateCurve.xCoeffFull_succ TateCurve.a₆Coeff_zero TateCurve.a₄Coeff_succ TateCurve.a₄Coeff_zero TateCurve.cauchyMul_zero TateCurve.a₆Coeff_succ TateCurve.yCoeffFull_succ TateCurve.xCoeffFull_zero TateCurve.yCoeffFull_zero TateCurve.yfun_zero TateCurve.xfun_zero TateCurve.yTerm_zero TateCurve.xTerm_zero TateCurve.curve_a₂ TateCurve.b_one TateCurve.curve_a₁ TateCurve.term_zero TateCurve.curve_a₆ TateCurve.curve_a₄ TateCurve.curve_a₃ FLT.DivisorConvolution.sigma_zero_right FLT.DivisorConvolution.sigma_one_right FLT.DivisorConvolution.sigmaConv_one FLT.DivisorConvolution.sigmaConv_zero FormalCoordinates.mk.injEq WeierstrassCurve.formalParam_zero WeierstrassCurve.SmoothLocusReductionData.reduceHom₀_apply WeierstrassCurve.formalParam_some FormalCoordinates.mk.sizeOf_spec WeierstrassCurve.SmoothLocusReductionData.mk.injEq WeierstrassCurve.reducePointSmooth_zero WeierstrassCurve.SmoothLocusReductionData.mk.sizeOf_spec WeierstrassCurve.mem_zeroComponentSubgroup_iff ModularCurve.PlaceSpecialization.mk.injEq ModularCurve.PlaceSpecialization.mk.sizeOf_spec ValuationSubring.reduceAt_coe ValuationSubring.reduceAt_one ValuationSubring.reduceAt_natCast"
p2m_attr_erase "simp" "ValuationSubring.reduceAt_intCast ValuationSubring.reduceAt_zero ModularCurve.dualHeckeRep_apply_apply ModularCurve.coe_segmentPath ModularCurve.cuspHeckeAeval_heckeGen ModularCurve.coe_periodLatticeRestrict_apply ModularCurve.ComplexPlaceDictionary.mk.injEq ModularCurve.ComplexPlaceDictionary.mk.sizeOf_spec ModularCurve.Period.IsEquivariantPrimitive.periodHom_apply ModularCurve.Period.IsEquivariantPrimitive.period_one ModularCurve.CuspSpace.cuspDenomAux_infty ModularCurve.CuspSpace.cuspDenomAux_coe ModularCurve.CuspSpace.cuspDenom_mk_zero ModularCurve.CuspSpace.cuspDenom_mk_infty ModularCurve.mapGL_apply_coe ModularCurve.ratPoint_one_zero ModularCurve.ratPoint_zero_right ModularCurve.CuspSpace.fromCoset_mk ModularCurve.CuspSpace.cuspDenom_mk ModularCurve.ratPoint_zero_one ModularCurve.qEulerFun_coeff ModularCurve.diffQExp_D ModularCurve.qEulerOn_apply ModularCurve.qEuler_coeff FLT.TruncatedDomainPartition.unipotentDiagonalSum_zero HeckeEis.coeffCoboundaryMap_apply HeckeEis.heckeConjMat_apply_one_one HeckeEis.coe_heckeConjSL HeckeEis.mem_heckeUpperSL HeckeEis.resHom_apply HeckeEis.heckeConjMat_apply_zero_one HeckeEis.coe_transferAux HeckeEis.coe_heckeConj HeckeEis.alphaMat_apply_one_one HeckeEis.heckeConjMat_apply_one_zero HeckeEis.alphaMat_apply_zero_one HeckeEis.pullbackHom_apply HeckeEis.alphaMat_apply_one_zero HeckeEis.alphaMat_apply_zero_zero HeckeEis.heckeConjMat_apply_zero_zero"
p2m_attr_erase "simp" "ModularCurve.coe_jGeomGen ModularCurve.coe_jNGeomGen ModularCurve.charLGeomModuliDictionary_single ModularCurve.specializeModuli_single ModularCurve.specializePlace_def GoodReductionJacobian.RelativeGroupLaw.fibre_inv GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_coe GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_toBase GoodReductionJacobian.RelativeGroupLaw.fibre_mul GoodReductionJacobian.RelativeGroupLaw.fibrePointToBase_ofBase GoodReductionJacobian.RelativeGroupLaw.fibre_one GoodReductionJacobian.RelativeGroupLaw.fibrePointOfBase_coe AlgebraicGeometry.schemeFibreEndo_snd AlgebraicGeometry.schemeFibreEndo_fst AlgebraicCurve.KwCfx.kw_cfx_tau_coe AlgebraicCurve.kw_hwcd_dlog_zero AlgebraicCurve.kw_hwcd_mem_regularDifferentials_iff AlgebraicCurve.kw_hwcd_dlog_one closureCounit_apply genericFibreAlgHom_tmul tensorInclusion_closureComul coe_closureAntipode_apply tensorToGenericFibre_tmul tensorInclusion_tmul mem_flatClosure_iff TaylorWiles.Seed.mk.injEq TaylorWiles.Seed.mk.sizeOf_spec CartierDual.toDual_ofDual CartierDual.algebraMap_apply CartierDual.antipode_apply CartierDual.one_apply CartierDual.toDual_apply CartierDual.ofDual_toDual CartierDual.ofDual_apply CartierDual.counit_apply tensorInclusion3_tmul tensorInclusion3'_tmul closureValBialgHom_apply HopfAlgebra.mem_vanishingIdealOfPoints_iff HopfAlgebra.liftPoint_mk"
p2m_attr_erase "simp" "HopfAlgebra.mem_ptSet_iff CartierDual.dualBaseChangeLin_tmul CartierDual.dualBaseChange_tmul CartierDual.map_apply CartierDual.congr_apply CartierDual.congr_symm_apply CartierDual.pairing_apply CartierDual.mapAlgHom_apply CartierDual.mapLinear_apply HopfAlgebra.canAlgHom_tmul HopfAlgebra.canMap_tmul HopfAlgebra.HopfKerHopf.ι₂_comulK HopfAlgebra.HopfKerHopf.ι₃_tmul HopfAlgebra.HopfKerHopf.counitK_apply HopfAlgebra.HopfKerHopf.coe_antipodeK HopfAlgebra.HopfKerHopf.ι₂_tmul HopfAlgebra.HopfKerHopf.coe_antipode HopfAlgebra.HopfKerHopf.hopfKerVal_apply HopfAlgebra.HopfKerHopf.valL_apply HopfAlgebra.HopfKerHopf.ι₂_comul ModularCurve.Period.jConjMat_apply_zero_one ModularCurve.Period.jConjSL_coe ModularCurve.Period.jConjMat_apply_one_zero ModularCurve.Period.jConjMat_apply_one_one ModularCurve.Period.jConjGamma0_coe ModularCurve.Period.charInvolution_apply ModularCurve.Period.jConjMat_apply_zero_zero PowerSeries.coeff_heckeV PowerSeries.coeff_heckeU ModularCurve.coe_heckeBetaC AlgebraicCurve.Divisor.coe_degZeroEnd ModularCurve.coe_heckeAlphaC ModularCurve.CommutingHeckeFamily.mk.injEq ModularCurve.SpecializationWitnessData.mk.sizeOf_spec ModularCurve.SpecializationWitnessData.mk.injEq ModularCurve.CommutingHeckeFamily.mk.sizeOf_spec AlgebraicCurve.Divisor.congr_single AlgebraicCurve.Pic0.coe_degZeroCongr_symm AlgebraicCurve.Divisor.degree_congr AlgebraicCurve.Divisor.degree_congr_symm"
p2m_attr_erase "simp" "AlgebraicCurve.Pic0.coe_degZeroCongr ModularCurve.toRingAut_coeffSemilinearAut ModularCurve.baseAut_arithFrobC_apply ModularCurve.coe_coeffRingAut_apply ModularCurve.baseAut_coeffSemilinearAut TateModule.smul_apply TateModule.coe_mulP TateModule.proj_apply TateModule.coe_add TateModule.coe_sub WeierstrassCurve.tateModuleRepOfBasis_V TateModule.coe_zero TateModule.rep_apply WeierstrassCurve.tateModuleRep_V WeierstrassCurve.tateModuleRepOfBasis_ρ_apply GaloisRep.padicIntToRingLevel_apply TateModule.coe_neg WeierstrassCurve.tateModuleRep_ρ_apply AlgebraicCurve.abelJacobiDiv_single AlgebraicCurve.AnalyticCoord.mk.injEq AlgebraicCurve.Cell.mk.sizeOf_spec AlgebraicCurve.RadialRegion.mk.sizeOf_spec AlgebraicCurve.RadialRegion.mk.injEq AlgebraicCurve.CellDissection.mk.sizeOf_spec AlgebraicCurve.Cell.mk.injEq AlgebraicCurve.CellDissection.mk.injEq AlgebraicCurve.AnalyticCoord.mk.sizeOf_spec AlgebraicCurve.DivisorialWeilPairingData.toChar_apply AlgebraicCurve.WeilDatum.coe_classRight AlgebraicCurve.WeilDatum.coe_degZeroRight AlgebraicCurve.DivisorialWeilPairingData.mk.sizeOf_spec AlgebraicCurve.WeilDatum.coe_classLeft AlgebraicCurve.WeilDatum.coe_degZeroLeft AlgebraicCurve.DivisorialWeilPairingData.mk.injEq AlgebraicCurve.DivisorialWeilPairingData.toHom_apply_apply AlgebraicCurve.WeilDatum.mk.sizeOf_spec AlgebraicCurve.WeilDatum.mk.injEq AlgebraicCurve.WeilPairingData.evalAddChar_zero AlgebraicCurve.PrincipalPolarization.mk.injEq AlgebraicCurve.WeilPairingData.evalAddChar_apply"
p2m_attr_erase "simp" "AlgebraicCurve.H1Gm.degree_ofPic0 AlgebraicCurve.WeilPairingData.mk.sizeOf_spec AlgebraicCurve.HomPic0Gm.map_one AlgebraicCurve.PrincipalPolarization.mk.sizeOf_spec AlgebraicCurve.WeilPairingData.autodualityEquiv_apply AlgebraicCurve.WeilPairingData.eval_zero_right AlgebraicCurve.H1Gm.ofPic0_mk AlgebraicCurve.WeilPairingData.eval_neg_left AlgebraicCurve.HomPic0Gm.map_apply AlgebraicCurve.H1Gm.degree_mk AlgebraicCurve.HomPic0Gm.map_id AlgebraicCurve.WeilPairingData.mk.injEq AlgebraicCurve.WeilPairingData.congr_eval AlgebraicCurve.WeilPairingData.eval_neg_right AlgebraicCurve.WeilPairingData.eval_zero_left ModularCurve.tateMap_apply"

set_option autoImplicit false

open ModularCurve CuspForm

namespace G1iEngine

open Submodule

theorem finite_quotient_of_natCast_mem {S : Type*} [CommRing S] [inst : Module ℤ S]
    [Module.Finite ℤ S] (I : Ideal S) (n : ℕ) (hn : n ≠ 0) (hI : (n : S) ∈ I) :
    Finite (S ⧸ I) := by
  obtain rfl : inst = AddCommGroup.toIntModule S := Subsingleton.elim _ _
  haveI : Module.Finite ℤ (S ⧸ I) := Module.Finite.quotient ℤ I
  refine Module.finite_of_fg_torsion (S ⧸ I) fun x => ?_
  obtain ⟨s, rfl⟩ := Ideal.Quotient.mk_surjective x
  have hn' : (n : ℤ) ∈ nonZeroDivisors ℤ :=
    mem_nonZeroDivisors_of_ne_zero (Int.natCast_ne_zero.mpr hn)
  refine ⟨⟨n, hn'⟩, ?_⟩
  show (n : ℤ) • Ideal.Quotient.mk I s = 0
  rw [show ((n : ℤ) • Ideal.Quotient.mk I s) = Ideal.Quotient.mk I ((n : ℤ) • s) from rfl,
    zsmul_eq_mul, Int.cast_natCast, Ideal.Quotient.eq_zero_iff_mem]
  exact I.mul_mem_right s hI

theorem natCast_mem_map {R S : Type*} [Semiring R] [Semiring S] (f : R →+* S)
    (I : Ideal R) (n : ℕ) (h : (n : R) ∈ I) : (n : S) ∈ I.map f :=
  map_natCast f n ▸ Ideal.mem_map_of_mem f h

theorem exists_step_eq_of_mono_bounded (f : ℕ → ℕ) (hmono : Monotone f) (B : ℕ)
    (hbound : ∀ M, f M ≤ B) (start : ℕ) :
    ∃ M, start ≤ M ∧ f (M + 1) = f M := by
  by_contra h
  push Not at h

  have step : ∀ k, f start + k ≤ f (start + k) := by
    intro k
    induction k with
    | zero => simp
    | succ k ih =>
      have hne : f (start + k + 1) ≠ f (start + k) :=
        h (start + k) (Nat.le_add_right _ _)
      have hle : f (start + k) ≤ f (start + k + 1) := hmono (Nat.le_succ _)
      have hac : start + (k + 1) = start + k + 1 := by omega
      rw [hac]; omega
  have := step (B + 1)
  have := hbound (start + (B + 1))
  have := hbound start
  omega

theorem submodule_eq_of_le_of_card_eq {R J : Type*} [Ring R] [AddCommGroup J] [Module R J]
    {S T : Submodule R J} [Finite T] (hST : S ≤ T) (hcard : Nat.card T ≤ Nat.card S) :
    S = T := by
  have hfS : Finite S := Finite.Set.subset _ hST
  have hbij : Function.Bijective (Submodule.inclusion hST) :=
    (Nat.bijective_iff_injective_and_card _).mpr
      ⟨Submodule.inclusion_injective _, le_antisymm (Nat.card_le_card_of_injective _
        (Submodule.inclusion_injective hST)) hcard⟩
  refine le_antisymm hST (fun x hx => ?_)
  obtain ⟨y, hy⟩ := hbij.2 ⟨x, hx⟩
  have hyx : (y : J) = x := congrArg Subtype.val hy
  exact hyx ▸ y.2

theorem ideal_eq_of_le_of_card_quotient_eq {R : Type*} [CommRing R]
    {I J : Ideal R} [Finite (R ⧸ I)] (hIJ : I ≤ J)
    (hcard : Nat.card (R ⧸ I) ≤ Nat.card (R ⧸ J)) :
    I = J := by

  let π : R ⧸ I →+* R ⧸ J := Ideal.Quotient.factor hIJ
  have hπsurj : Function.Surjective π := Ideal.Quotient.factor_surjective hIJ
  haveI hfJ : Finite (R ⧸ J) := Finite.of_surjective π hπsurj
  have hbij : Function.Bijective π :=
    (Nat.bijective_iff_surjective_and_card _).mpr
      ⟨hπsurj, le_antisymm hcard (Nat.card_le_card_of_surjective π hπsurj)⟩
  refine le_antisymm hIJ (fun x hx => ?_)
  have h0 : π (Ideal.Quotient.mk I x) = 0 := by
    simp only [π, Ideal.Quotient.factor_mk]; exact Ideal.Quotient.eq_zero_iff_mem.mpr hx
  have : Ideal.Quotient.mk I x = 0 := hbij.1 (by rw [h0, map_zero])
  exact Ideal.Quotient.eq_zero_iff_mem.mp this

theorem exists_step_eq_two_mono (f g : ℕ → ℕ) (hfmono : Monotone f) (hgmono : Monotone g)
    (Bf Bg : ℕ) (hfb : ∀ M, f M ≤ Bf) (hgb : ∀ M, g M ≤ Bg) (start : ℕ) :
    ∃ M, start ≤ M ∧ f (M + 1) = f M ∧ g (M + 1) = g M := by
  obtain ⟨M, hMs, hsum⟩ :=
    exists_step_eq_of_mono_bounded (fun M => f M + g M)
      (fun a b hab => Nat.add_le_add (hfmono hab) (hgmono hab))
      (Bf + Bg) (fun M => Nat.add_le_add (hfb M) (hgb M)) start
  have hf1 : f M ≤ f (M + 1) := hfmono (Nat.le_succ M)
  have hg1 : g M ≤ g (M + 1) := hgmono (Nat.le_succ M)
  have hs : f (M + 1) + g (M + 1) = f M + g M := hsum
  exact ⟨M, hMs, by omega, by omega⟩

theorem core₂ {A' B : Type*} [AddCommGroup A'] [AddCommGroup B] [Finite B]
    {M : Type*} [CommMonoid M] (hM : ∀ n : ℕ, n ≠ 0 → HasEnoughRootsOfUnity M n)
    (φ : A' → (Multiplicative B →* Mˣ)) (hφinj : Function.Injective φ)
    (hφadd : ∀ a b, φ (a + b) = φ a * φ b) :
    ∃ g : A' →+ B, Function.Injective g := by
  haveI : Finite (Multiplicative B) := Finite.of_equiv B Multiplicative.ofAdd
  haveI := hM (Monoid.exponent (Multiplicative B)) Monoid.exponent_ne_zero_of_finite
  obtain ⟨e⟩ := CommGroup.monoidHom_mulEquiv_of_hasEnoughRootsOfUnity (Multiplicative B) M
  refine ⟨{ toFun := fun a => Multiplicative.toAdd (e (φ a))
            map_zero' := ?_
            map_add' := ?_ }, ?_⟩
  · have hφ0 : φ 0 = 1 := by
      have h := hφadd 0 0; rw [add_zero] at h
      exact mul_right_cancel (h.symm.trans (one_mul (φ 0)).symm)
    simp [hφ0]
  · intro a b; simp [hφadd, map_mul]
  · intro a b hab
    exact hφinj (e.injective (Multiplicative.toAdd.injective hab))

theorem algClosure_hasEnough (n : ℕ) (hn : n ≠ 0) :
    HasEnoughRootsOfUnity (AlgebraicClosure ℚ) n := by
  haveI : NeZero n := ⟨hn⟩; infer_instance

theorem dual_of_injective_toAdditive {T : Type*} [AddCommGroup T] [Finite T]
    {A' : Type*} [AddCommGroup A']
    (φ : A' →+ (T →+ Additive (AlgebraicClosure ℚ)ˣ)) (hφinj : Function.Injective φ) :
    ∃ ι : A' →+ T, Function.Injective ι := by
  refine core₂ (M := AlgebraicClosure ℚ) algClosure_hasEnough
    (fun a => AddMonoidHom.toMultiplicativeLeft (φ a))
    (fun a b h => hφinj (AddMonoidHom.toMultiplicativeLeft.injective h)) ?_
  intro a b
  refine MonoidHom.ext fun x => ?_
  show Additive.toMul (φ (a + b) (Multiplicative.toAdd x)) =
    Additive.toMul (φ a (Multiplicative.toAdd x)) * Additive.toMul (φ b (Multiplicative.toAdd x))
  rw [map_add, AddMonoidHom.add_apply, toMul_add]

set_option maxHeartbeats 3200000 in

theorem stab_generic {R : Type*} [CommRing R] {J : Type*} [AddCommGroup J] [Module R J]
    (𝔓 : Ideal R) (ξ : R) (hVfin : Finite ↥(Submodule.torsionBySet R J (Ideal.span {ξ} : Set R)))
    {S : Type*} [CommRing S] (𝔓' : Ideal S) (ξ' : S) (hRfin : Finite (S ⧸ Ideal.span {ξ'}))
    (start : ℕ) :
    ∃ M, start ≤ M ∧
      Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ (M + 1)) : Set R) =
        Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ M) : Set R) ∧
      (Ideal.span {ξ'} ⊔ 𝔓' ^ (M + 1) : Ideal S) = Ideal.span {ξ'} ⊔ 𝔓' ^ M := by

  have hanti : ∀ {a b : ℕ}, a ≤ b →
      (Ideal.span {ξ} ⊔ 𝔓 ^ b : Ideal R) ≤ Ideal.span {ξ} ⊔ 𝔓 ^ a :=
    fun hab => sup_le_sup_left (Ideal.pow_le_pow_right hab) _
  have hanti' : ∀ {a b : ℕ}, a ≤ b →
      (Ideal.span {ξ'} ⊔ 𝔓' ^ b : Ideal S) ≤ Ideal.span {ξ'} ⊔ 𝔓' ^ a :=
    fun hab => sup_le_sup_left (Ideal.pow_le_pow_right hab) _
  have hsubV : ∀ M, Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ M) : Set R) ≤
      Submodule.torsionBySet R J (Ideal.span {ξ} : Set R) := fun M =>
    Submodule.torsionBySet_le_torsionBySet_of_subset (le_sup_left : Ideal.span {ξ} ≤ _)
  have hfinV : ∀ M, Finite ↥(Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ M) : Set R)) :=
    fun M => Finite.Set.subset _ (hsubV M)
  have hfinR : ∀ M, Finite (S ⧸ (Ideal.span {ξ'} ⊔ 𝔓' ^ M)) := fun M => by
    exact Finite.of_surjective (Ideal.Quotient.factor (le_sup_left))
      (Ideal.Quotient.factor_surjective _)
  let fV : ℕ → ℕ := fun M => Nat.card ↥(Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ M) : Set R))
  let fR : ℕ → ℕ := fun M => Nat.card (S ⧸ (Ideal.span {ξ'} ⊔ 𝔓' ^ M))
  have hfVmono : Monotone fV := fun a b hab =>
    Nat.card_le_card_of_injective
      (Submodule.inclusion (Submodule.torsionBySet_le_torsionBySet_of_subset (hanti hab)))
      (Submodule.inclusion_injective _)
  have hfRmono : Monotone fR := fun a b hab => by
    haveI := hfinR a
    exact Nat.card_le_card_of_surjective (Ideal.Quotient.factor (hanti' hab))
      (Ideal.Quotient.factor_surjective _)
  have hfVb : ∀ M, fV M ≤ Nat.card ↥(Submodule.torsionBySet R J (Ideal.span {ξ} : Set R)) :=
    fun M => Nat.card_le_card_of_injective (Submodule.inclusion (hsubV M))
      (Submodule.inclusion_injective _)
  have hfRb : ∀ M, fR M ≤ Nat.card (S ⧸ Ideal.span {ξ'}) := fun M => by
    exact Nat.card_le_card_of_surjective (Ideal.Quotient.factor (le_sup_left))
      (Ideal.Quotient.factor_surjective _)
  obtain ⟨M, hMs, hfVeq, hfReq⟩ :=
    exists_step_eq_two_mono fV fR hfVmono hfRmono _ _ hfVb hfRb start
  haveI := hfinV (M + 1)
  haveI := hfinR (M + 1)
  refine ⟨M, hMs, ?_, ?_⟩
  · have hVle : Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ M) : Set R) ≤
        Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ (M + 1)) : Set R) :=
      Submodule.torsionBySet_le_torsionBySet_of_subset (hanti (Nat.le_succ M))
    have hc : Nat.card ↥(Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ (M + 1)) : Set R))
        ≤ Nat.card ↥(Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ M) : Set R)) := hfVeq.le
    exact (submodule_eq_of_le_of_card_eq hVle hc).symm
  · have hc : Nat.card (S ⧸ (Ideal.span {ξ'} ⊔ 𝔓' ^ (M + 1)))
        ≤ Nat.card (S ⧸ (Ideal.span {ξ'} ⊔ 𝔓' ^ M)) := hfReq.le
    exact ideal_eq_of_le_of_card_quotient_eq (hanti' (Nat.le_succ M)) hc

theorem exists_inertia_n_ne_one (q : ℕ) [Fact q.Prime] (hq2 : q ≠ 2)
    (Aq : ValuationSubring (AlgebraicClosure ℚ)) (hAq : Aq.LiesOverPrime q)
    (m : ℕ) (hm : 1 ≤ m) (n : (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) → ℕ)
    (hn : ∀ σ, ∀ ζ : AlgebraicClosure ℚ, ζ ^ (q ^ m) = 1 → σ ζ = ζ ^ n σ) :
    ∃ σ₀ ∈ Aq.inertiaSubgroupIn ℚ, ¬ ((n σ₀ : ZMod q) = 1) := by
  have hq : q.Prime := Fact.out
  haveI : NeZero q := ⟨hq.ne_zero⟩
  obtain ⟨σ₀, hσ₀, hpow⟩ :=
    ValuationSubring.exists_mem_inertiaSubgroupIn_apply_eq_pow Aq hq hAq (-1)

  haveI : NeZero ((q : ℕ) : AlgebraicClosure ℚ) := ⟨Nat.cast_ne_zero.mpr hq.ne_zero⟩
  have hdeg : (Polynomial.cyclotomic q (AlgebraicClosure ℚ)).degree ≠ 0 := by
    rw [Polynomial.degree_cyclotomic]
    exact_mod_cast (Nat.totient_pos.mpr hq.pos).ne'
  obtain ⟨ζ, hζroot⟩ := IsAlgClosed.exists_root _ hdeg
  have hζ : IsPrimitiveRoot ζ q := Polynomial.isRoot_cyclotomic_iff.mp hζroot
  refine ⟨σ₀, hσ₀, ?_⟩
  have hζq : ζ ^ q = 1 := hζ.pow_eq_one
  have hζqm : ζ ^ (q ^ m) = 1 := by
    obtain ⟨d, hd⟩ : q ∣ q ^ m := dvd_pow_self q (Nat.one_le_iff_ne_zero.mp hm)
    rw [hd, pow_mul, hζq, one_pow]
  set a : ℕ := ((-1 : (ZMod q)ˣ) : ZMod q).val with ha
  have e1 : σ₀ ζ = ζ ^ n σ₀ := hn σ₀ ζ hζqm
  have e2 : σ₀ ζ = ζ ^ a := hpow ζ hζq

  have hr : ζ ^ (n σ₀ % q) = ζ ^ a := by
    conv_rhs => rw [← e2, e1]
    conv_rhs => rw [← Nat.div_add_mod (n σ₀) q, pow_add, pow_mul, hζq, one_pow, one_mul]
  have hra : n σ₀ % q = a :=
    hζ.pow_inj (Nat.mod_lt _ hq.pos) (ZMod.val_lt _) hr
  intro hcon

  have hcast : ((n σ₀ : ℕ) : ZMod q) = ((a : ℕ) : ZMod q) := by
    conv_lhs => rw [← Nat.div_add_mod (n σ₀) q]
    push_cast [ZMod.natCast_self]
    rw [hra]; ring
  have hval : ((a : ℕ) : ZMod q) = ((-1 : (ZMod q)ˣ) : ZMod q) := by
    rw [ha, ZMod.natCast_val, ZMod.cast_id]
  have hneg : ((-1 : (ZMod q)ˣ) : ZMod q) = (-1 : ZMod q) := by
    rw [Units.val_neg, Units.val_one]
  have h11 : (-1 : ZMod q) = 1 := by
    rw [← hneg, ← hval, ← hcast]; exact hcon
  have h20 : ((2 : ℕ) : ZMod q) = 0 := by
    push_cast
    linear_combination -h11
  have hdvd : q ∣ 2 := (CharP.cast_eq_zero_iff (ZMod q) q 2).mp h20
  rcases (Nat.prime_two.eq_one_or_self_of_dvd q hdvd) with h | h
  · exact hq.one_lt.ne' h
  · exact hq2 h

lemma mem_of_pin_of_displacement {G₀ : Type*} [Group G₀] {X : Type*} [AddCommGroup X]
    [DistribMulAction G₀ X] (I : Subgroup G₀) (n : G₀ → ℕ) (W WMD : AddSubgroup X)
    (q m : ℕ) (hq : q.Prime)
    (hW1 : MultiplicativeTypeNat I n W)
    (hWtors : ∀ x ∈ W, ((q : ℤ) ^ m) • x = 0)
    (hdisp : ∀ σ ∈ I, ∀ x ∈ W, σ • x - x ∈ WMD)
    (σ₀ : G₀) (hσ₀ : σ₀ ∈ I) (hne : ¬ ((n σ₀ : ZMod q) = 1)) :
    ∀ x ∈ W, x ∈ WMD := by
  intro x hx
  have hndvd : ¬ ((q : ℤ) ∣ ((n σ₀ : ℤ) - 1)) := by
    intro hdvd
    apply hne
    have h0 : (((n σ₀ : ℤ) - 1 : ℤ) : ZMod q) = 0 :=
      (ZMod.intCast_zmod_eq_zero_iff_dvd _ q).mpr hdvd
    push_cast at h0
    linear_combination h0
  have hcop : IsCoprime ((n σ₀ : ℤ) - 1) ((q : ℤ) ^ m) :=
    (((Nat.prime_iff_prime_int.mp hq).coprime_iff_not_dvd.mpr hndvd).symm).pow_right
  obtain ⟨u, v, huv⟩ := hcop
  have hdx : ((n σ₀ : ℤ) - 1) • x = σ₀ • x - x := by
    rw [sub_zsmul, one_zsmul, natCast_zsmul, ← hW1 σ₀ hσ₀ x hx, sub_eq_add_neg]
  have hx1 : x = (u * ((n σ₀ : ℤ) - 1) + v * ((q : ℤ) ^ m)) • x := by
    rw [huv, one_zsmul]
  rw [add_zsmul, mul_zsmul, mul_zsmul, hdx, hWtors x hx, smul_zero, add_zero] at hx1
  rw [hx1]
  exact AddSubgroup.zsmul_mem _ (hdisp σ₀ hσ₀ x hx) u

theorem torsionBySet_sup_pow_add_eq {R : Type*} [CommRing R] {J : Type*} [AddCommGroup J] [Module R J]
    (𝔓 : Ideal R) (ξ : R) (M : ℕ)
    (h : Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ (M + 1)) : Set R) =
      Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ M) : Set R)) (j : ℕ) :
    Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ (M + j)) : Set R) =
      Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ M) : Set R) := by
  induction j with
  | zero => simp
  | succ j ih =>
    apply le_antisymm
    ·

      intro x hx
      rw [Submodule.mem_torsionBySet_iff] at hx
      have hξx : ξ • x = 0 := hx ⟨ξ, Ideal.mem_sup_left (Ideal.mem_span_singleton_self ξ)⟩
      have hπ : ∀ π ∈ 𝔓, π • x ∈ Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ M) : Set R) := by
        intro π hπ
        rw [← ih, Submodule.mem_torsionBySet_iff]
        rintro ⟨a, ha⟩
        obtain ⟨y, hy, z, hz, rfl⟩ := Submodule.mem_sup.mp ha
        obtain ⟨r, rfl⟩ := Ideal.mem_span_singleton'.mp hy
        change (r * ξ + z) • (π • x) = 0
        have hξπ : ξ • (π • x) = 0 := by
          rw [← mul_smul, mul_comm, mul_smul, hξx, smul_zero]
        rw [add_smul, mul_smul, hξπ, smul_zero, zero_add, ← mul_smul]
        have hzπ : z * π ∈ Ideal.span {ξ} ⊔ 𝔓 ^ (M + (j + 1)) :=
          Ideal.mem_sup_right (by rw [← add_assoc, pow_succ]; exact Ideal.mul_mem_mul hz hπ)
        exact hx ⟨_, hzπ⟩
      have hx1 : x ∈ Submodule.torsionBySet R J (↑(Ideal.span {ξ} ⊔ 𝔓 ^ (M + 1)) : Set R) := by
        rw [Submodule.mem_torsionBySet_iff]
        rintro ⟨a, ha⟩
        obtain ⟨y, hy, z, hz, rfl⟩ := Submodule.mem_sup.mp ha
        obtain ⟨r, rfl⟩ := Ideal.mem_span_singleton'.mp hy
        change (r * ξ + z) • x = 0
        rw [add_smul, mul_smul, hξx, smul_zero, zero_add]
        rw [pow_succ] at hz
        refine Submodule.mul_induction_on hz ?_ ?_
        · intro b hb π hπ'
          have := hπ π hπ'
          rw [Submodule.mem_torsionBySet_iff] at this
          rw [mul_smul]
          exact this ⟨b, Ideal.mem_sup_right hb⟩
        · intro a₁ a₂ h₁ h₂
          rw [add_smul, h₁, h₂, add_zero]
      rw [h] at hx1
      exact hx1
    · have hle : Ideal.span {ξ} ⊔ 𝔓 ^ (M + (j + 1)) ≤ Ideal.span {ξ} ⊔ 𝔓 ^ M :=
        sup_le_sup_left (Ideal.pow_le_pow_right (Nat.le_add_right M _)) _
      exact Submodule.torsionBySet_le_torsionBySet_of_subset hle

theorem card_le_card_quotient_of_pairing {V : Type*} [AddCommGroup V] [Finite V] (Wv : AddSubgroup V)
    {Lq : Type*} [AddCommGroup Lq]
    (e : V → Lq → (AlgebraicClosure ℚ)ˣ)
    (hadd_v : ∀ v₁ v₂ r, e (v₁ + v₂) r = e v₁ r * e v₂ r)
    (hadd_r : ∀ v r₁ r₂, e v (r₁ + r₂) = e v r₁ * e v r₂)
    (hRK : ∀ r, (∀ v, e v r = 1) → r = 0)
    (hW : ∀ v ∈ Wv, ∀ r, e v r = 1) :
    Nat.card Lq ≤ Nat.card (V ⧸ Wv) := by
  classical
  have he0 : ∀ r, e 0 r = 1 := fun r => by
    have h := hadd_v 0 0 r
    rw [add_zero] at h
    exact (mul_left_cancel (h.symm.trans (mul_one _).symm))
  have he0' : ∀ v, e v 0 = 1 := fun v => by
    have h := hadd_r v 0 0
    rw [add_zero] at h
    exact (mul_left_cancel (h.symm.trans (mul_one _).symm))

  let χ : Lq → (V →+ Additive (AlgebraicClosure ℚ)ˣ) := fun r =>
    { toFun := fun v => Additive.ofMul (e v r)
      map_zero' := by show Additive.ofMul (e 0 r) = 0; rw [he0]; rfl
      map_add' := fun x y => by
        show Additive.ofMul (e (x + y) r) = Additive.ofMul (e x r) + Additive.ofMul (e y r)
        rw [hadd_v, ofMul_mul] }
  have hχW : ∀ r, ∀ v ∈ Wv, χ r v = 0 := fun r v hv => by
    show Additive.ofMul (e v r) = 0
    rw [hW v hv r]; rfl
  let φ : Lq →+ (V ⧸ Wv →+ Additive (AlgebraicClosure ℚ)ˣ) :=
    { toFun := fun r => QuotientAddGroup.lift Wv (χ r) (hχW r)
      map_zero' := by
        refine AddMonoidHom.ext fun t => ?_
        induction t using QuotientAddGroup.induction_on with
        | H v =>
          show χ 0 v = 0
          show Additive.ofMul (e v 0) = 0
          rw [he0']; rfl
      map_add' := fun r₁ r₂ => by
        refine AddMonoidHom.ext fun t => ?_
        induction t using QuotientAddGroup.induction_on with
        | H v =>
          show χ (r₁ + r₂) v = χ r₁ v + χ r₂ v
          show Additive.ofMul (e v (r₁ + r₂)) = Additive.ofMul (e v r₁) + Additive.ofMul (e v r₂)
          rw [hadd_r, ofMul_mul] }
  have hφinj : Function.Injective φ := by
    intro r₁ r₂ h12
    have hsub : φ (r₁ - r₂) = 0 := by rw [map_sub, h12, sub_self]
    have hall : ∀ v : V, e v (r₁ - r₂) = 1 := fun v => by
      have := congrArg (fun f : V ⧸ Wv →+ Additive (AlgebraicClosure ℚ)ˣ => f (QuotientAddGroup.mk v)) hsub
      change χ (r₁ - r₂) v = 0 at this
      exact Additive.ofMul.injective this
    exact sub_eq_zero.mp (hRK _ hall)
  haveI : Finite (V ⧸ Wv) := Quotient.finite _
  obtain ⟨ι, hι⟩ := dual_of_injective_toAdditive φ hφinj
  exact Nat.card_le_card_of_injective ι hι

end G1iEngine

open G1iEngine in
set_option maxHeartbeats 8000000 in
set_option synthInstance.maxHeartbeats 1600000 in
theorem solution
    (p : ℕ) [Fact p.Prime] (q : ℕ) [Fact q.Prime] (hq2 : q ≠ 2) (hqp : q ≠ p)
    (Aq : ValuationSubring (AlgebraicClosure ℚ)) (hAq : Aq.LiesOverPrime q) :
    ∃ C : ℕ, ∀ m M₁ : ℕ, ∃ M : ℕ, M₁ ≤ M ∧
      ∀ n : (AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) → ℕ,
        (∀ σ, ∀ ζ : AlgebraicClosure ℚ, ζ ^ (q ^ m) = 1 → σ ζ = ζ ^ n σ) →
      ∀ W : AddSubgroup (JZero p),
        W ≤ eisensteinPrimaryTorsionBar p q m →
        MultiplicativeTypeNat (Aq.inertiaSubgroupIn ℚ) n W →
        (∀ σ ∈ Aq.inertiaSubgroupIn ℚ, ∀ x ∈ eisensteinPrimaryTorsionBar p q m,
          σ • (x : JZero p) - x ∈ W) →
        Nat.card (↥(heckeLatticeAlgebra p ∅) ⧸
            (Ideal.span {((q : ℕ) ^ m : ↥(heckeLatticeAlgebra p ∅))} ⊔
              (Ideal.map ((latticeRestrictHom p ∅).toRingHom.comp (heckeEvalForms p 2))
                (eisensteinMaximalIdeal p q)) ^ M)) ≤
          Nat.card (↥(eisensteinPrimaryTorsionBar p q m) ⧸
            W.addSubgroupOf (eisensteinPrimaryTorsionBar p q m)) * q ^ C := by
  classical
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  letI := heckeModuleBar p
  have hqP : q.Prime := Fact.out
  refine ⟨0, fun m M₁ => ?_⟩

  haveI hVfin : Finite ↥(Submodule.torsionBySet HeckeAlg (JZero p)
      (Ideal.span {((q : ℕ) ^ m : HeckeAlg)} : Set HeckeAlg)) :=
    ModularCurve.heckeTorsion_jZero_finite_of_natCast_mem p
      (Ideal.span {((q : ℕ) ^ m : HeckeAlg)}) (q ^ m) (pow_pos hqP.pos m)
      (by rw [Nat.cast_pow]; exact Ideal.mem_span_singleton_self _)
  haveI hRfin : Finite (↥(heckeLatticeAlgebra p ∅) ⧸
      Ideal.span {((q : ℕ) ^ m : ↥(heckeLatticeAlgebra p ∅))}) :=
    finite_quotient_of_natCast_mem _ (q ^ m) (pow_ne_zero m hqP.ne_zero)
      (by rw [Nat.cast_pow]; exact Ideal.mem_span_singleton_self _)
  obtain ⟨M, hM₁, hMJ, hML⟩ := stab_generic (J := JZero p) (eisensteinMaximalIdeal p q)
    ((q : ℕ) ^ m : HeckeAlg) hVfin
    (Ideal.map ((latticeRestrictHom p ∅).toRingHom.comp (heckeEvalForms p 2)) (eisensteinMaximalIdeal p q))
    ((q : ℕ) ^ m : ↥(heckeLatticeAlgebra p ∅)) hRfin M₁
  refine ⟨M, hM₁, fun n hn W hWle hWmt hWdisp => ?_⟩

  set 𝔓 : Ideal HeckeAlg := eisensteinMaximalIdeal p q with h𝔓
  set H : Submodule HeckeAlg (JZero p) :=
    heckeTorsion (JZero p) (Ideal.span {((q : ℕ) ^ m : HeckeAlg)} ⊔ 𝔓 ^ M) with hH

  have hHsub : ∀ x : JZero p, x ∈ H → x ∈ eisensteinPrimaryTorsionBar p q m := by
    intro x hx
    rw [hH, mem_heckeTorsion_iff] at hx
    refine ⟨?_, ?_⟩
    · have h1 : (((q : ℕ) ^ m : HeckeAlg)) • x = 0 :=
        hx _ (Ideal.mem_sup_left (Ideal.mem_span_singleton_self _))
      have h2 : (((q ^ m : ℕ) : HeckeAlg)) • x = 0 := by rwa [Nat.cast_pow]
      have h3 : ((q ^ m : ℕ)) • x = 0 := by rwa [Nat.cast_smul_eq_nsmul] at h2
      change ((q : ℤ) ^ m) • x = 0
      calc ((q : ℤ) ^ m) • x = ((q ^ m : ℕ) : ℤ) • x := by norm_cast
        _ = ((q ^ m : ℕ)) • x := natCast_zsmul x (q ^ m)
        _ = 0 := h3
    · refine AddSubgroup.mem_iSup_of_mem M ?_
      change x ∈ Submodule.torsionBySet HeckeAlg (JZero p) (↑(𝔓 ^ M) : Set HeckeAlg)
      rw [Submodule.mem_torsionBySet_iff]
      rintro ⟨a, ha⟩
      exact hx a (Ideal.mem_sup_right ha)

  have hEPsub : ∀ x : JZero p, x ∈ eisensteinPrimaryTorsionBar p q m → x ∈ H := by
    rintro x ⟨hker, hsup⟩
    have hqx : (((q : ℕ) ^ m : HeckeAlg)) • x = 0 := by
      have h0 : ((q : ℤ) ^ m) • x = 0 := hker
      have h3 : ((q ^ m : ℕ)) • x = 0 := by
        rw [← natCast_zsmul]
        push_cast
        exact h0
      have h2 : (((q ^ m : ℕ) : HeckeAlg)) • x = 0 := by
        rw [Nat.cast_smul_eq_nsmul]
        exact h3
      rw [← Nat.cast_pow]
      exact h2

    have hprim : ∃ k : ℕ, x ∈ Submodule.torsionBySet HeckeAlg (JZero p) (↑(𝔓 ^ k) : Set HeckeAlg) := by
      refine (AddSubgroup.mem_iSup_of_directed ?_).mp hsup
      refine Monotone.directed_le fun i j hij => ?_
      intro y hy
      exact Submodule.torsionBySet_le_torsionBySet_of_subset
        (Ideal.pow_le_pow_right hij : 𝔓 ^ j ≤ 𝔓 ^ i) hy
    obtain ⟨k, hk⟩ := hprim

    have hxMk : x ∈ Submodule.torsionBySet HeckeAlg (JZero p)
        (↑(Ideal.span {((q : ℕ) ^ m : HeckeAlg)} ⊔ 𝔓 ^ (M + k)) : Set HeckeAlg) := by
      rw [Submodule.mem_torsionBySet_iff]
      rintro ⟨a, ha⟩
      obtain ⟨y, hy, z, hz, rfl⟩ := Submodule.mem_sup.mp ha
      obtain ⟨r, rfl⟩ := Ideal.mem_span_singleton'.mp hy
      change (r * ((q : ℕ) ^ m : HeckeAlg) + z) • x = 0
      have hr0 : r • ((((q : ℕ) ^ m : HeckeAlg)) • x) = 0 := by
        rw [hqx]; exact (DistribSMul.toAddMonoidHom (JZero p) r).map_zero
      rw [add_smul, mul_smul, hr0, zero_add]
      have hz' : z ∈ 𝔓 ^ k := Ideal.pow_le_pow_right (Nat.le_add_left k M) hz
      exact (Submodule.mem_torsionBySet_iff _ _).mp hk ⟨z, hz'⟩
    have heq := torsionBySet_sup_pow_add_eq (J := JZero p) 𝔓 ((q : ℕ) ^ m : HeckeAlg) M hMJ k
    rw [heq] at hxMk
    exact hxMk

  rcases Nat.eq_zero_or_pos m with hm0 | hm
  · subst hm0
    have htop : (Ideal.span {((q : ℕ) ^ 0 : ↥(heckeLatticeAlgebra p ∅))} ⊔
          (Ideal.map ((latticeRestrictHom p ∅).toRingHom.comp (heckeEvalForms p 2))
            (eisensteinMaximalIdeal p q)) ^ M) = ⊤ := by
      rw [eq_top_iff]
      refine le_sup_of_le_left ?_
      rw [pow_zero, Ideal.span_singleton_one]
    haveI : Subsingleton (↥(heckeLatticeAlgebra p ∅) ⧸
        (Ideal.span {((q : ℕ) ^ 0 : ↥(heckeLatticeAlgebra p ∅))} ⊔
          (Ideal.map ((latticeRestrictHom p ∅).toRingHom.comp (heckeEvalForms p 2))
            (eisensteinMaximalIdeal p q)) ^ M)) := by
      rw [htop]; exact Ideal.Quotient.subsingleton_iff.mpr rfl
    haveI : Finite ↥(eisensteinPrimaryTorsionBar p q 0) := by
      refine Finite.Set.subset (Submodule.torsionBySet HeckeAlg (JZero p)
        (Ideal.span {((q : ℕ) ^ 0 : HeckeAlg)} : Set HeckeAlg)) ?_
      intro x hx
      exact Submodule.torsionBySet_le_torsionBySet_of_subset
        (le_sup_left : Ideal.span {((q : ℕ) ^ 0 : HeckeAlg)} ≤ _) (hEPsub x hx)
    calc Nat.card _ ≤ 1 := Finite.card_le_one_iff_subsingleton.mpr inferInstance
      _ ≤ Nat.card (↥(eisensteinPrimaryTorsionBar p q 0) ⧸
            W.addSubgroupOf (eisensteinPrimaryTorsionBar p q 0)) * q ^ 0 := by
          rw [pow_zero, mul_one]
          exact Nat.one_le_iff_ne_zero.mpr (Nat.card_pos (α := ↥(eisensteinPrimaryTorsionBar p q 0) ⧸
            W.addSubgroupOf (eisensteinPrimaryTorsionBar p q 0))).ne'

  obtain ⟨W₀, hW₀le, hW₀mt, hW₀disp, e, hadd_v, hadd_r, _hbal, hRK, hLK⟩ :=
    ModularCurve.exists_submodule_multiplicativeTypeNat_heckeTorsion_span_sup_pairing_heckeLatticeAlgebra_quotient_of_ne_two
      p q hq2 hqp Aq hAq m M n hn hMJ hML

  obtain ⟨σ₀, hσ₀, hne⟩ := exists_inertia_n_ne_one q hq2 Aq hAq m hm n hn

  have hWW₀ : ∀ x ∈ W, x ∈ W₀.toAddSubgroup :=
    mem_of_pin_of_displacement (Aq.inertiaSubgroupIn ℚ) n W W₀.toAddSubgroup q m hqP hWmt
      (fun x hx => (hWle hx).1)
      (fun σ hσ x hx => hW₀disp σ hσ x (hEPsub x (hWle hx))) σ₀ hσ₀ hne

  haveI hEPfin : Finite ↥(eisensteinPrimaryTorsionBar p q m) := by
    refine Finite.Set.subset (Submodule.torsionBySet HeckeAlg (JZero p)
      (Ideal.span {((q : ℕ) ^ m : HeckeAlg)} : Set HeckeAlg)) ?_
    intro x hx
    exact Submodule.torsionBySet_le_torsionBySet_of_subset
      (le_sup_left : Ideal.span {((q : ℕ) ^ m : HeckeAlg)} ≤ _) (hEPsub x hx)

  have hcount := card_le_card_quotient_of_pairing (V := ↥(eisensteinPrimaryTorsionBar p q m))
    (W.addSubgroupOf (eisensteinPrimaryTorsionBar p q m))
    (fun v r => e ⟨(v : JZero p), hEPsub v v.2⟩ r)
    (fun v₁ v₂ r => by
      have h := hadd_v ⟨(v₁ : JZero p), hEPsub v₁ v₁.2⟩ ⟨(v₂ : JZero p), hEPsub v₂ v₂.2⟩ r
      exact h)
    (fun v r₁ r₂ => hadd_r _ r₁ r₂)
    (fun r hr => hRK r fun v => by
      have hv : (v : JZero p) ∈ eisensteinPrimaryTorsionBar p q m := hHsub v v.2
      have h := hr ⟨(v : JZero p), hv⟩
      have hvv : (⟨((⟨(v : JZero p), hv⟩ : ↥(eisensteinPrimaryTorsionBar p q m)) : JZero p),
          hEPsub _ hv⟩ : ↥H) = v := Subtype.ext rfl
      exact (congrArg (fun w : ↥H => e w r) hvv).symm.trans h)
    (fun v hv r => by
      have hxW₀ : (v : JZero p) ∈ W₀ := hWW₀ v (AddSubgroup.mem_addSubgroupOf.mp hv)
      exact ((hLK ⟨(v : JZero p), hEPsub v v.2⟩).mpr hxW₀) r)
  calc Nat.card (↥(heckeLatticeAlgebra p ∅) ⧸ (Ideal.span {((q : ℕ) ^ m : ↥(heckeLatticeAlgebra p ∅))} ⊔
          (Ideal.map ((latticeRestrictHom p ∅).toRingHom.comp (heckeEvalForms p 2))
            (eisensteinMaximalIdeal p q)) ^ M))
      ≤ Nat.card (↥(eisensteinPrimaryTorsionBar p q m) ⧸ W.addSubgroupOf (eisensteinPrimaryTorsionBar p q m)) := hcount
    _ = Nat.card (↥(eisensteinPrimaryTorsionBar p q m) ⧸
          W.addSubgroupOf (eisensteinPrimaryTorsionBar p q m)) * q ^ 0 := by rw [pow_zero, mul_one]

end S_ModularCurve_exists_natCard_heckeLatticeAlgebra_quotient_span_pow_sup_pow_le_natCard_eisensteinPrimaryTorsionBar_quotient_mul_pow
end P2MW
export P2MW.S_ModularCurve_exists_natCard_heckeLatticeAlgebra_quotient_span_pow_sup_pow_le_natCard_eisensteinPrimaryTorsionBar_quotient_mul_pow (solution)
